const canvas=document.getElementById('world');const ctx=canvas.getContext('2d');
const state={started:false,x:620,y:420,money:10000,energy:100,minutes:480,quest:0,dialogue:null,inventory:[],saved:false};
const npcs=[
 {x:390,y:300,name:'Marta',role:'Vecina',color:'#d86b5b',text:'Hola. Si querés conocer Villa Pelón, hablá con la gente y mirá con atención.'},
 {x:790,y:300,name:'Raúl',role:'Trabajador rural',color:'#5d87bd',text:'En la chacra siempre hay algo para hacer. Volvé después y te puedo ofrecer trabajo.'},
 {x:300,y:540,name:'Lucía',role:'Docente',color:'#b66a9b',text:'La escuela conserva recuerdos del pueblo. Las fotografías pueden contar mucho.'},
 {x:930,y:520,name:'Pedro',role:'Comerciante',color:'#c58b52',text:'Un pueblo chico funciona gracias a quienes trabajan todos los días.'},
 {x:650,y:205,name:'Nico',role:'Joven del pueblo',color:'#6a9b62',text:'La plaza es un buen lugar para empezar a conocer Villa Pelón.'}
];
const buildings=[{x:140,y:170,w:190,h:100,label:'ESCUELA'},{x:700,y:170,w:190,h:100,label:'ALMACÉN'},{x:490,y:620,w:190,h:95,label:'RADIO'}];
const clue={x:1060,y:250};
function resize(){const d=devicePixelRatio||1;canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
const key={};addEventListener('keydown',e=>{key[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e'||e.key===' ')interact()});addEventListener('keyup',e=>key[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();key[k]=true};b.onpointerup=b.onpointercancel=()=>key[k]=false});
document.getElementById('startBtn').onclick=()=>{state.started=true;document.getElementById('start').classList.add('hidden');document.getElementById('game').classList.remove('hidden');load();};
document.getElementById('interact').onclick=interact;document.getElementById('dialogueNext').onclick=closeDialogue;document.getElementById('save').onclick=save;
function update(){if(!state.started||state.dialogue)return;let dx=(key.d||key.arrowright||key.right?1:0)-(key.a||key.arrowleft||key.left?1:0),dy=(key.s||key.arrowdown||key.down?1:0)-(key.w||key.arrowup||key.up?1:0);if(dx||dy){let l=Math.hypot(dx,dy);state.x+=dx/l*3;state.y+=dy/l*3;state.energy=Math.max(0,state.energy-.02);state.minutes+=.12}state.x=Math.max(35,Math.min(innerWidth-35,state.x));state.y=Math.max(80,Math.min(innerHeight-35,state.y));ui()}
function nearby(){for(const n of npcs)if(Math.hypot(state.x-n.x,state.y-n.y)<58)return n;if(Math.hypot(state.x-clue.x,state.y-clue.y)<65)return clue;return null}
function interact(){if(!state.started)return;if(state.dialogue){closeDialogue();return}const n=nearby();if(!n)return;if(n===clue){if(state.quest<2){state.quest=2;state.money+=2500;state.inventory.push('Pista histórica');openDialogue('ARCHIVO DE MEMORIA','Encontraste una pista. La historia real se incorporará con fuentes verificadas. Recibís $2.500.');}else openDialogue('ARCHIVO','Esta pista ya fue descubierta.');return}if(state.quest===0)state.quest=1;openDialogue(n.name,n.text)}
function openDialogue(s,t){state.dialogue=true;document.getElementById('dialogue').classList.remove('hidden');document.getElementById('speaker').textContent=s;document.getElementById('dialogueText').textContent=t}
function closeDialogue(){state.dialogue=false;document.getElementById('dialogue').classList.add('hidden')}
function save(){localStorage.setItem('villa_pelon_v2',JSON.stringify(state));state.saved=true;document.getElementById('questText').textContent='Partida guardada ✓';setTimeout(ui,1300)}
function load(){try{const s=JSON.parse(localStorage.getItem('villa_pelon_v2'));if(s)Object.assign(state,s);state.started=true}catch(e){}}
function ui(){const h=Math.floor(state.minutes/60)%24,m=Math.floor(state.minutes%60);document.getElementById('clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');document.getElementById('money').textContent=Math.round(state.money);document.getElementById('energy').textContent=Math.round(state.energy);document.getElementById('questText').textContent=state.quest===0?'Conocé a un vecino.':state.quest===1?'Buscá la primera pista histórica.':'Primer descubrimiento completado.'}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#91aa68';ctx.fillRect(0,0,w,h);ctx.fillStyle='#c8ae79';ctx.fillRect(0,h*.47,w,h*.13);ctx.fillStyle='#d7bd83';ctx.fillRect(w*.45,58,w*.1,h-58);ctx.fillStyle='#4f7748';for(let x=25;x<w;x+=55)for(let y=95;y<h;y+=65){ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fill()}buildings.forEach(b=>{ctx.fillStyle='#d6bf96';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#704b39';ctx.fillRect(b.x+b.w*.43,b.y+b.h*.55,b.w*.14,b.h*.45);ctx.fillStyle='#79a7b8';ctx.fillRect(b.x+22,b.y+32,38,25);ctx.fillRect(b.x+b.w-60,b.y+32,38,25);ctx.fillStyle='#172019';ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillText(b.label,b.x+b.w/2,b.y-8)});ctx.fillStyle='#73964f';ctx.fillRect(w*.73,h*.67,w*.22,h*.22);for(let i=0;i<5;i++){ctx.fillStyle='#426b3b';ctx.fillRect(w*.75+i*50,h*.7,6,145)}npcs.forEach(n=>{ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(n.x,n.y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#172019';ctx.font='12px system-ui';ctx.fillText(n.name,n.x,n.y-22)});ctx.fillStyle='#e6b84d';ctx.beginPath();ctx.arc(clue.x,clue.y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='14px system-ui';ctx.fillText('?',clue.x-4,clue.y+5);ctx.fillStyle='#315a9b';ctx.beginPath();ctx.arc(state.x,state.y,17,0,Math.PI*2);ctx.fill();const n=nearby();if(n){ctx.fillStyle='#172019dd';ctx.roundRect(state.x-62,state.y-55,124,27,8);ctx.fill();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText('E · INTERACTUAR',state.x,state.y-37)}}
function loop(){update();draw();requestAnimationFrame(loop)}loop();
