/* Villa Pelón V4 — MEMORIA HISTÓRICA DOCUMENTADA.
   Regla: hechos reales y fuentes separados de la ficción jugable. */
(()=>{
'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
V.history=[
 {id:'origen',title:'El Chañar y los primeros registros',type:'documentado',text:'La historia institucional municipal señala referencias a un posible mangrullo y posta, además de documentación de mensuras de Encina, Moreno y Cía. de 1881-1882.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'tratayen',title:'La colonia Tratayen',type:'documentado',text:'La identidad histórica municipal menciona una mensura del ingeniero Tressens hacia 1913 y una colonia que habría alcanzado unas 20 manzanas. La misma fuente plantea que una gran crecida del río Neuquén pudo haber afectado su continuidad.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'1966',title:'El campo antes del pueblo',type:'documentado',text:'En 1966 un grupo de vecinos de Cinco Saltos adquirió El Chañar. La historia institucional municipal describe esa etapa como un antecedente de la transformación posterior del territorio.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'riego',title:'El agua transforma el paisaje',type:'documentado',text:'En 1968 se inició la sistematización de las tierras y en 1969 comenzaron los primeros cultivos y plantaciones mediante bombeo desde el río Neuquén. La Municipalidad señala que la primera bocatoma, en 1971, permitió regar la primera etapa de 3.068 hectáreas.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'fundacion',title:'21 de mayo de 1973',type:'documentado',text:'La localidad fue creada por Decreto Provincial N.º 1339 el 21 de mayo de 1973. El aniversario de esa fecha forma parte de la memoria institucional de San Patricio del Chañar.',source:'Legislatura de Neuquén — Proyecto sobre aniversarios / documentación histórica',url:'https://www.legislaturaneuquen.gob.ar/SVRFILES/hln/documentos/VerTaqui/XLVII/ApendiceReunion8/Proyecto11627.pdf'},
 {id:'primeras_autoridades',title:'La primera Comisión de Fomento',type:'documentado',text:'Las primeras autoridades de la Comisión de Fomento fueron puestas en funciones el 8 de abril de 1974, fecha vinculada a la inauguración de obras e instituciones iniciales.',source:'Neuquén Informa — Reseña histórica',url:'https://www.neuqueninforma.gob.ar/noticias/2014/05/22/48785-jorge-sapag-asistira-al-41-aniversario-de-san-patricio-del-chanar'},
 {id:'produccion',title:'De monte a zona productiva',type:'documentado',text:'El riego y la producción agrícola fueron fundamentales para transformar el paisaje. La historia institucional municipal describe los trabajos de sistematización y las primeras cosechas.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'escuela273',title:'La Escuela N.º 273',type:'documentado',text:'La cronología histórica local registra el inicio de la Escuela N.º 273 el 1 de marzo de 1975, convirtiéndose en una de las instituciones educativas tempranas de la localidad.',source:'Más Neuquén — Cronología de San Patricio del Chañar',url:'https://masneuquen.com/efemerides-cronologia-de-san-patricio-del-chanar/'},
 {id:'club',title:'El Club Atlético San Patricio',type:'documentado',text:'La cronología histórica local registra la creación del Club Atlético San Patricio en 1976 como espacio de contención y encuentro para los jóvenes.',source:'Más Neuquén — Cronología de San Patricio del Chañar',url:'https://masneuquen.com/efemerides-cronologia-de-san-patricio-del-chanar/'},
 {id:'pelon',title:'La Fiesta Provincial del Pelón',type:'documentado',text:'La Fiesta Provincial del Pelón comenzó en 1985 y homenajea a uno de los frutos emblemáticos de la ciudad y al trabajo rural.',source:'Municipalidad de San Patricio del Chañar — ¿Qué hacer?',url:'https://sanpatricio.gob.ar/quehacer'},
 {id:'vinos',title:'La identidad vitivinícola',type:'documentado',text:'La Municipalidad presenta a San Patricio del Chañar como un polo vitivinícola y destaca sus viñedos, bodegas y circuitos agroturísticos como parte de la identidad productiva.',source:'Municipalidad de San Patricio del Chañar — ¿Qué hacer?',url:'https://sanpatricio.gob.ar/quehacer'},
 {id:'territorio',title:'Rutas y territorio productivo',type:'documentado',text:'Las rutas provinciales 7 y 8 forman parte de la conexión territorial y productiva de la localidad.',source:'Municipalidad de San Patricio del Chañar — Ubicación',url:'https://www.sanpatricio.gob.ar/llegar'}
];
})();