/* Villa Pelón V6.39 — MEMORIA HISTÓRICA DOCUMENTADA
   Hechos y fuentes separados de la ficción jugable.
   El territorio real aparece como referencia documental, no como identidad del pueblo jugable.
*/
(()=>{
'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const records=[
 {id:'origen',title:'El Chañar y los primeros registros',type:'documentado',text:'La historia institucional municipal señala referencias a un posible mangrullo y posta, además de documentación de mensuras de Encina, Moreno y Cía. de 1881-1882.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'tratayen',title:'La colonia Tratayen',type:'documentado',text:'La identidad histórica municipal menciona una mensura del ingeniero Tressens hacia 1913 y una colonia que habría alcanzado unas 20 manzanas. La misma fuente plantea que una gran crecida del río Neuquén pudo haber afectado su continuidad.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'1966',title:'El campo antes del pueblo',type:'documentado',text:'En 1966 un grupo de vecinos de Cinco Saltos adquirió El Chañar. La historia institucional municipal describe esa etapa como un antecedente de la transformación posterior del territorio.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'riego',title:'El agua transforma el paisaje',type:'documentado',text:'En 1968 se inició la sistematización de las tierras y en 1969 comenzaron los primeros cultivos y plantaciones mediante bombeo desde el río Neuquén. La Municipalidad señala que la primera bocatoma, en 1971, permitió regar la primera etapa de 3.068 hectáreas.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'fundacion',title:'21 de mayo de 1973',type:'documentado',text:'La localidad fue creada por Decreto Provincial N.º 1339 el 21 de mayo de 1973. Esta fecha pertenece a la historia real que inspira la capa documental del juego.',source:'Legislatura de Neuquén — documentación histórica',url:'https://www.legislaturaneuquen.gob.ar/SVRFILES/hln/documentos/VerTaqui/XLVII/ApendiceReunion8/Proyecto11627.pdf'},
 {id:'primeras_autoridades',title:'La primera Comisión de Fomento',type:'documentado',text:'Las primeras autoridades de la Comisión de Fomento fueron puestas en funciones el 8 de abril de 1974, fecha vinculada a la inauguración de obras e instituciones iniciales.',source:'Neuquén Informa — Reseña histórica',url:'https://www.neuqueninforma.gob.ar/noticias/2014/05/22/48785-jorge-sapag-asistira-al-41-aniversario-de-san-patricio-del-chanar'},
 {id:'produccion',title:'De monte a zona productiva',type:'documentado',text:'El riego y la producción agrícola fueron fundamentales para transformar el paisaje. La historia institucional municipal describe los trabajos de sistematización y las primeras cosechas.',source:'Municipalidad de San Patricio del Chañar — Nuestra Identidad',url:'https://www.sanpatricio.gob.ar/identidad'},
 {id:'escuela273',title:'La Escuela N.º 273',type:'documentado',text:'La cronología histórica local registra el inicio de la Escuela N.º 273 el 1 de marzo de 1975, convirtiéndose en una de las instituciones educativas tempranas de la localidad.',source:'Más Neuquén — Cronología',url:'https://masneuquen.com/efemerides-cronologia-de-san-patricio-del-chanar/'},
 {id:'club',title:'El Club Atlético San Patricio',type:'documentado',text:'La cronología histórica local registra la creación del Club Atlético San Patricio en 1976 como espacio de contención y encuentro para los jóvenes.',source:'Más Neuquén — Cronología',url:'https://masneuquen.com/efemerides-cronologia-de-san-patricio-del-chanar/'},
 {id:'pelon',title:'La Fiesta Provincial del Pelón',type:'documentado',text:'La Fiesta Provincial del Pelón comenzó en 1985 y homenajea a uno de los frutos emblemáticos de la ciudad y al trabajo rural.',source:'Municipalidad de San Patricio del Chañar — ¿Qué hacer?',url:'https://sanpatricio.gob.ar/quehacer'},
 {id:'vinos',title:'La identidad vitivinícola',type:'documentado',text:'La Municipalidad presenta al territorio de referencia como un polo vitivinícola y destaca viñedos, bodegas y circuitos agroturísticos como parte de su identidad productiva.',source:'Municipalidad de San Patricio del Chañar — ¿Qué hacer?',url:'https://sanpatricio.gob.ar/quehacer'},
 {id:'territorio',title:'Rutas y territorio productivo',type:'documentado',text:'Las rutas provinciales 7 y 8 forman parte de la conexión territorial y productiva del área que inspira la ambientación.',source:'Municipalidad de San Patricio del Chañar — Ubicación',url:'https://www.sanpatricio.gob.ar/llegar'}
];
V.history=records;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function inspect(id){const h=records.find(x=>x.id===id);if(!h)return false;const existing=document.getElementById('historyMemoryPanel');existing?.remove();const p=document.createElement('div');p.id='historyMemoryPanel';p.style.cssText='position:fixed;inset:8%;z-index:4000;background:#211a15;color:#ead8c0;border:3px solid #b99655;border-radius:12px;padding:24px;overflow:auto;box-shadow:0 20px 70px #000;font-family:system-ui,sans-serif';p.innerHTML='<h2 style="color:#f0d27d;margin-top:0">'+esc(h.title)+'</h2><p style="line-height:1.65;font-size:16px">'+esc(h.text)+'</p><p style="font-size:12px;color:#bdb09a;border-top:1px solid #5b4b37;padding-top:12px">FUENTE: '+esc(h.source)+'</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button id="historyClose" style="padding:9px 14px">CERRAR</button><a href="'+esc(h.url)+'" target="_blank" rel="noopener" style="padding:9px 14px;color:#211a15;background:#e1c16d;text-decoration:none">VER FUENTE</a></div>';document.body.appendChild(p);document.getElementById('historyClose').onclick=()=>p.remove();if(V.state){V.state.dialogue=true;V.state.flags=V.state.flags||{};V.state.flags['history_'+id]=true}if(V.rpgProgression?.api?.discover)V.rpgProgression.api.discover(id);return true}
V.history.inspect=inspect;
})();
