/* Villa Pelón V2 — HISTORIA VIVA
   Conversaciones de pueblo, misiones progresivas, aventuras y secundarias.
   La ficción jugable está separada de los datos históricos documentados. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const S=()=>V.state;
const story={main:0,side:{},flags:{},rel:{},active:null,missions:[
{id:'bienvenida',title:'UN DÍA CUALQUIERA',text:'Hablá con Marta y conocé cómo se mueve el pueblo.',target:'marta',reward:180},
{id:'mandado',title:'EL MANDADO',text:'Marta necesita que acerques un paquete a la casa de Raúl.',target:'raul',reward:260},
{id:'plaza',title:'DOS MINUTOS EN LA PLAZA',text:'Pasá por la plaza y charlá con Lucía.',target:'lucia',reward:220},
{id:'changa',title:'UNA CHANGA',text:'Dale una mano a Raúl con unos cajones en la chacra.',target:'job',reward:650},
{id:'agua',title:'DONDE PASA EL AGUA',text:'Buscá a Pedro y preguntale por el canal de riego.',target:'pedro',reward:300},
{id:'memoria',title:'UNA HISTORIA QUE QUEDÓ',text:'Encontrá una memoria del pueblo y escuchala con calma.',target:'history',reward:350},
{id:'radio',title:'LA VOZ DEL PUEBLO',text:'Visitá la radio y hablá con Nico.',target:'nico',reward:450},
{id:'fiesta',title:'SE VIENE LA FIESTA',text:'Ayudá a Inés a preparar algo para los vecinos.',target:'ines',reward:520},
{id:'camino',title:'POR EL CAMINO RURAL',text:'Acompañá a Tomás hasta el puesto y volvé antes de que anochezca.',target:'tomas',reward:700},
{id:'pueblo',title:'YA SOS PARTE',text:'Elegí qué hacer con tu vida en Villa Pelón: trabajo, vecinos, campo o aventuras.',target:'free',reward:1000}
],sides:[
{id:'pan',npc:'marta',title:'PAN RECIÉN HECHO',text:'Marta necesita que acerques pan a una vecina mayor.',need:'Compra: pan',reward:320,unlock:1},
{id:'herramienta',npc:'raul',title:'LA HERRAMIENTA PERDIDA',text:'Raúl perdió una llave inglesa cerca del galpón.',reward:480,unlock:2},
{id:'gallinas',npc:'ines',title:'SE ESCAPARON LAS GALLINAS',text:'Tres gallinas se fueron para el lado de la plaza. Ayudá a encontrarlas.',reward:390,unlock:3},
{id:'radio_recuerdo',npc:'nico',title:'UN MENSAJE PARA LA RADIO',text:'Nico quiere una historia corta de un vecino para el programa.',reward:420,unlock:5},
{id:'mate',npc:'lucia',title:'MATE DE POR MEDIO',text:'Conseguí yerba y compartí un rato con Lucía en la plaza.',need:'Yerba',reward:280,unlock:2},
{id:'caballo',npc:'pedro',title:'EL CABALLO INQUIETO',text:'Un caballo anda demasiado cerca del alambrado. Ayudá a Pedro a llevarlo de vuelta.',reward:560,unlock:4}
]};V.story=story;
function rel(id,n=1){story.rel[id]=(story.rel[id]||0)+n}function flag(k,v=true){story.flags[k]=v}
function saveStory(){try{localStorage.setItem('villa_pelon_v2_story',JSON.stringify({main:story.main,side:story.side,flags:story.flags,rel:story.rel}))}catch(_){} }
function loadStory(){try{const x=JSON.parse(localStorage.getItem('villa_pelon_v2_story'));if(x){story.main=Math.min(Number(x.main)||0,story.missions.length-1);story.side=x.side||{};story.flags=x.flags||{};story.rel=x.rel||{}}}catch(_){} }
loadStory();
function say(name,lines,choices){
 let box=document.getElementById('v2dialog');if(!box){box=document.createElement('div');box.id='v2dialog';box.className='v2-dialog hidden';box.innerHTML='<div class="v2-dialog-inner"><div class="v2-speaker"></div><div class="v2-text"></div><div class="v2-choices"></div></div>';document.body.appendChild(box)}
 box.classList.remove('hidden');const sp=box.querySelector('.v2-speaker'),tx=box.querySelector('.v2-text'),ch=box.querySelector('.v2-choices');sp.textContent=name;tx.textContent=lines[0]||'';ch.innerHTML='';let i=0;
 const close=()=>{box.classList.add('hidden');story.active=null;if(typeof window.__v2StoryRefresh==='function')window.__v2StoryRefresh()};
 if(choices&&choices.length){choices.forEach(c=>{const b=document.createElement('button');b.textContent=c.label;b.onclick=()=>{if(c.action)c.action();if(c.lines)say(name,c.lines,c.after);else if(c.close!==false)close()};ch.appendChild(b)})}else{const b=document.createElement('button');b.textContent='Seguir';b.onclick=()=>{i++;if(i<lines.length)tx.textContent=lines[i];else close()};ch.appendChild(b)}story.active={close};
}
function rewardMain(){const m=story.missions[story.main];S().money+=m.reward;flag('main_'+m.id);story.main=Math.min(story.main+1,story.missions.length-1);saveStory();say('VILLA PELÓN',[`Listo. Sumaste $${m.reward}.`,`En un pueblo chico una cosa suele llevar a otra. Ahora fijate qué aparece.`])}
function completeSide(q){story.side[q.id]='done';S().money+=q.reward;flag('side_'+q.id);saveStory();say('VILLA PELÓN',[`Ayudaste con ${q.title.toLowerCase()}.`,`Te dieron $${q.reward}. Y ahora hay una persona que te conoce un poco mejor.`])}
function activeSide(id){return story.sides.find(q=>q.npc===id&&story.main>=q.unlock&&!story.side[q.id])}
function mainDialog(n){const id=n.id,m=story.missions[story.main];if(!m||m.target!==id)return false;
 if(m.id==='bienvenida')say('Marta',['Buen día. ¿Recién llegás?','Acá pasa eso: uno sale a comprar pan y termina enterándose de media vida del pueblo.','Si necesitás algo, preguntá. En los pueblos chicos preguntar no cuesta nada.'],[{label:'¿Y qué hay para hacer?',action:()=>{rel(id,2);rewardMain()}},{label:'Voy a dar una vuelta.',action:()=>{rel(id,1);rewardMain()}}]);
 else if(m.id==='mandado')say('Marta',['¿Podés acercarle este paquete a Raúl? Vive cerca de la chacra.','No es nada raro, son unas cosas que dejó encargadas.'],[{label:'Sí, se lo llevo.',action:()=>{flag('package');rewardMain()}}]);
 else if(m.id==='plaza')say('Lucía',['¿Viste cómo cambia la plaza según la hora?','A la mañana pasan chicos, después aparecen los grandes y a la tardecita queda gente charlando.','No parece que pase mucho, pero siempre pasa algo.'],[{label:'Me gusta esa calma.',action:()=>{rel(id,2);rewardMain()}},{label:'¿Qué recordás de acá?',action:()=>{rel(id,1);rewardMain()}}]);
 else if(m.id==='agua')say('Pedro',['El agua parece una cosa simple hasta que falta.','Acá muchas cosas cambiaron cuando el riego empezó a transformar estas tierras.','Si querés entender el pueblo, mirá por dónde corre el agua.'],[{label:'Quiero saber más.',action:()=>{flag('water_memory');rewardMain()}},{label:'Después vuelvo.',close:false}]);
 else if(m.id==='radio')say('Nico',['Ponete cómodo. La radio de pueblo tiene algo de eso: alguien llama por una cosa y termina contando otra.','Si alguna vez tenés una historia, una foto vieja o un dato, traelo.'],[{label:'Me gustaría colaborar.',action:()=>{rel(id,2);rewardMain()}},{label:'Solo vine a escuchar.',action:rewardMain}]);
 else if(m.id==='fiesta')say('Inés',['Estamos preparando algo sencillo para los vecinos.','No hace falta que sepas hacer de todo. Elegí una tarea y la hacemos.'],[{label:'Ayudo con las mesas.',action:()=>{flag('fiesta_help');rewardMain()}},{label:'Ayudo con la comida.',action:()=>{flag('fiesta_food');rewardMain()}}]);
 else if(m.id==='camino')say('Tomás',['Voy hasta el puesto. Si querés, vení conmigo.','No hay apuro. Por el camino se aprende más mirando que corriendo.'],[{label:'Te acompaño.',action:()=>{rel(id,2);rewardMain()}},{label:'Voy después.',close:false}]);
 else if(m.id==='pueblo')say('Tomás',['Ya conocés bastante del pueblo.','Ahora no necesitás que nadie te diga qué hacer. Podés trabajar, hablar, explorar, ayudar o simplemente salir a caminar.'],[{label:'Quiero seguir explorando.',action:()=>{rel(id,1);rewardMain()}}]);
 return true}
function sideDialog(n,q){if(q.id==='pan'){if(!S().inventory.includes('Compra: pan'))say('Marta',['Si vas para el almacén, ¿me traés pan? Después lo llevo a doña Elvira.','No es urgente. Cuando puedas.'],[{label:'Dale, voy.',action:()=>flag('pan_started'),close:false}]);else completeSide(q);return true}
 if(q.id==='herramienta'){if(!story.flags.tool_found)say('Raúl',['Estoy buscando una llave inglesa. Creo que la dejé cerca del galpón.','Si la ves, dejámela ahí mismo.'],[{label:'La busco.',action:()=>flag('tool_search'),close:false}]);else completeSide(q);return true}
 if(q.id==='gallinas'){say('Inés',['No sé cómo hicieron, pero se me escaparon las gallinas.','Una estaba cerca de la plaza. Otra puede haber cruzado hacia las casas.','Si encontrás las tres, avisame.'],[{label:'Voy a buscarlas.',action:()=>{flag('chicken_search');S().money+=0},close:false}]);return true}
 if(q.id==='radio_recuerdo'){say('Nico',['Hoy quiero contar algo que no salga en ningún diario.','Una historia sencilla de alguien del pueblo. ¿Conocés alguna?'],[{label:'Sí, tengo una.',action:()=>completeSide(q)},{label:'Ahora no.',close:false}]);return true}
 if(q.id==='mate'){if(!S().inventory.includes('Yerba'))say('Lucía',['Si pasás por el almacén, traé yerba.','Después nos sentamos un rato en la plaza. No hace falta hablar de nada importante.'],[{label:'Bueno.',action:()=>flag('mate_started'),close:false}]);else completeSide(q);return true}
 if(q.id==='caballo'){say('Pedro',['Ese caballo está medio inquieto hoy.','Vamos despacio y lo llevamos para el corral.'],[{label:'Vamos.',action:()=>{flag('horse_done');completeSide(q)}}]);return true}return false}
function ambientDialog(n){const h=Math.floor((S().minutes||480)/60)%24,r=story.rel[n.id]||0;const sets={marta:h<12?['¿Ya arrancaste el día?','A esta hora el almacén es tranquilo. Después se llena.']:['Qué día largo. A la tarde uno ya piensa en sentarse a tomar mate.'],raul:['Hoy la tierra está pidiendo agua.','Mañana hay que mirar cómo quedó la chacra.'],lucia:['¿Escuchaste la radio hoy?','Siempre termina apareciendo alguna historia.'],pedro:['Ese viento no me gusta para los árboles.','Igual mañana vemos. El campo tiene sus tiempos.'],nico:['Tenemos mensajes de todos lados.','Una radio de pueblo nunca se queda sin cosas para contar.'],ines:['Vine por una compra y me quedé charlando.','Acá uno se cruza con todo el mundo.'],tomas:['¿Viste los cerros con esta luz?','Hay días en que parecen estar más cerca.']};let lines=sets[n.id]||['Qué lindo día para caminar.'];if(r>=3)lines.push('Ya nos hemos cruzado varias veces. Cuando necesites algo, avisame.');say(n.name,lines)}
function historyDialog(){const hs=V.history||[];const h=hs.find(x=>!story.flags['hist_'+x.id])||hs[0];if(!h)return;say('MEMORIA · '+h.title,[h.text,'Esto está presentado como dato documentado. Las historias y personajes inventados del juego se mantienen separados.'],[{label:'Guardar esta memoria.',action:()=>{flag('hist_'+h.id);S().history=S().history||[];if(!S().history.includes(h.id))S().history.push(h.id);if(story.missions[story.main].target==='history')rewardMain()}}])}
function jobDialog(){const m=story.missions[story.main];if(m&&m.id==='changa'){if((S().energy||0)<20){say('CHANGA RURAL',['Estás cansado. Andá a descansar y volvé cuando tengas un poco más de energía.']);return}S().energy-=20;S().money+=650;S().inventory=S().inventory||[];if(!S().inventory.includes('Cajón de cosecha'))S().inventory.push('Cajón de cosecha');rewardMain()}else say('CHACRA',['Hay cajones para mover, herramientas para acomodar y siempre alguna tarea que aparece.','Si volvés otro día, puede haber trabajo distinto.'])}
function buildingDialog(b){if(b.type==='shop')say('ALMACÉN EL ENCUENTRO',['Pasá tranquilo.','Pan, yerba, azúcar y algunas cosas para la casa.','¿Qué necesitás?'],[{label:'Comprar pan ($120)',action:()=>{if(S().money>=120){S().money-=120;S().inventory=S().inventory||[];if(!S().inventory.includes('Compra: pan'))S().inventory.push('Compra: pan');say('ALMACÉN',['Listo. Pan recién hecho.'])}else say('ALMACÉN',['Te faltan unos pesos.'])}},{label:'Comprar yerba ($180)',action:()=>{if(S().money>=180){S().money-=180;S().inventory=S().inventory||[];if(!S().inventory.includes('Yerba'))S().inventory.push('Yerba');say('ALMACÉN',['Listo. Yerba para el mate.'])}else say('ALMACÉN',['Con eso no alcanza.'])}},{label:'Solo charlar.',action:()=>say('Marta',['Quedate un rato si querés. Acá las compras son la excusa.'])}]);
 else if(b.type==='radio')say('RADIO OASIS',['La puerta está entreabierta. Adentro se escucha una voz hablando del tiempo.','Hay papeles, una taza de mate y una foto vieja del pueblo.']);else if(b.type==='school')say('ESCUELA',['A esta hora está tranquila.','Hay dibujos, cuadernos y recuerdos de distintas generaciones.']);else if(b.type==='rural')say('GALPÓN RURAL',['Huele a madera, tierra y herramientas.','Hay cajones, una pala y cosas preparadas para mañana.']);else if(b.type==='home')say('CASA',['Una casa sencilla. Se escucha una radio de fondo.','Algunas historias se conocen desde la vereda.']);else say(b.label||'PUEBLO',['Un lugar más del pueblo. Si volvés en otro momento, puede haber algo distinto.'])}
function nearest(){const st=S();let best=null,bd=145;const all=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[]),V.storyJob||null].filter(Boolean);(V.historySpots||[]).forEach(o=>{});all.forEach(o=>{const x=o.x+(o.w?o.w/2:0),y=o.y+(o.h?o.h/2:0),d=Math.hypot(st.x-x,st.y-y);if(d<bd){bd=d;best=o}});return best}
function interact(){const st=S();if(!st?.started)return;if(story.active){story.active.close();return}const n=nearest();if(!n)return;if(n._history){historyDialog();return}if(n._job){jobDialog();return}if(n.id){const q=activeSide(n.id);if(q&&sideDialog(n,q))return;if(mainDialog(n))return;ambientDialog(n);return}if(n.w)buildingDialog(n)}
function refresh(){const st=S();if(!st?.started)return;const m=story.missions[story.main];const qt=document.getElementById('questTitle'),qx=document.getElementById('questText');if(qt&&qx){qt.textContent='MISIÓN · '+m.title;qx.textContent=m.text}let hint=document.getElementById('storyHint');if(!hint){hint=document.createElement('div');hint.id='storyHint';document.getElementById('game')?.appendChild(hint)}const n=nearest();hint.textContent=n?(n.id?`E · hablar con ${n.name}`:n._history?'E · leer memoria':n._job?'E · hacer la changa':`E · ${n.label||'interactuar'}`):'WASD / flechas · caminar  •  E · conversar';}
window.__v2StoryRefresh=refresh;
function prepareWorld(){V.storyJob={x:2530,y:820,_job:true};V.historySpots=(V.history||[]).map((h,i)=>({x:[2220,2700,3320,3650,1850,3000,900,3900][i%8],y:[500,1320,1130,480,1180,1550,1280,900][i%8],_history:true,id:h.id}));}
prepareWorld();
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if((k==='e'||e.key===' ')&&S()?.started){e.preventDefault();e.stopImmediatePropagation();interact()}},true);
document.addEventListener('pointerdown',e=>{if(e.target?.id==='interact'&&S()?.started){e.preventDefault();e.stopImmediatePropagation();interact()}},true);
setInterval(()=>{saveStory();refresh()},2500);requestAnimationFrame(function loop(){refresh();requestAnimationFrame(loop)});
})();
