/* Villa Pelón V3 — capa de experiencia: mochila, mapa, teléfono y pueblo más vivo. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const S=()=>V.state||{};
const canvas=document.getElementById('world');
const ctx=canvas?.getContext('2d');
const ui={};
const extra={
  people:[
    {x:620,y:620,name:'Doña Elvira',role:'vecina',dx:0.18,dy:0.05},{x:940,y:1180,name:'Sergio',role:'repartidor',dx:-.14,dy:.09},
    {x:1680,y:1160,name:'Mabel',role:'productora',dx:.08,dy:-.13},{x:1960,y:520,name:'Cacho',role:'camionero',dx:-.1,dy:.04},
    {x:2920,y:1260,name:'Ariel',role:'jornalero',dx:.07,dy:.1},{x:3650,y:1520,name:'Norma',role:'vecina',dx:-.06,dy:-.08}
  ],
  vehicles:[
    {x:430,y:810,axis:'x',speed:48,type:'auto'},{x:1700,y:810,axis:'x',speed:-62,type:'camioneta'},
    {x:2860,y:790,axis:'x',speed:72,type:'tractor'},{x:3300,y:900,axis:'y',speed:-52,type:'camion'}
  ],
  animals:[
    {x:1880,y:1180,type:'caballo',dx:.04,dy:.03},{x:2050,y:1240,type:'vaca',dx:-.03,dy:.02},
    {x:1170,y:720,type:'gallina',dx:.08,dy:-.04},{x:1280,y:760,type:'gallina',dx:-.06,dy:.05},{x:1390,y:700,type:'gallina',dx:.05,dy:.06}
  ],
  spots:[
    ['Plaza central',1120,760,'plaza'],['Escuela 273',575,485,'school'],['Almacén',1955,545,'shop'],['Radio Oasis',1265,1500,'radio'],
    ['Galpón rural',2555,1045,'rural'],['Bodega',3380,855,'rural'],['Puesto del pueblo',515,1660,'rural'],['Camino de chacras',3000,1500,'rural'],['Dique / naturaleza',3750,2050,'nature']
  ]
};
function css(){if(document.getElementById('v3style'))return;const s=document.createElement('style');s.id='v3style';s.textContent=`
.v3-panel{position:fixed;inset:7%;z-index:40;background:rgba(28,20,15,.97);border:2px solid #c6a45b;box-shadow:0 20px 70px #000b;color:#f5ead0;border-radius:18px;padding:24px;display:none;font-family:system-ui,sans-serif}.v3-panel.open{display:block}.v3-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.v3-head h2{margin:0;font-size:28px}.v3-close{background:#6d4930;color:#fff;border:1px solid #c6a45b;border-radius:8px;padding:8px 12px}.v3-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px;height:calc(100% - 60px)}.v3-card{background:#38271d;border:1px solid #74583e;border-radius:12px;padding:14px;overflow:auto}.v3-map{position:relative;background:#b8a271;min-height:390px;border-radius:10px;overflow:hidden;border:2px solid #6b5237}.v3-map .road{position:absolute;background:#d5c18f}.v3-pin{position:absolute;transform:translate(-50%,-50%);background:#2d2119;color:#ffe7a0;border:2px solid #e3bf63;border-radius:999px;padding:4px 7px;font-size:11px;white-space:nowrap}.v3-item{display:flex;justify-content:space-between;gap:10px;padding:10px;border-bottom:1px solid #5b4532}.v3-phone{background:linear-gradient(150deg,#171513,#34271e);max-width:330px;margin:auto;border:5px solid #111;border-radius:28px;padding:18px;min-height:480px;box-shadow:0 12px 40px #0009}.v3-apps{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:20px}.v3-app{padding:18px 8px;border:1px solid #80633f;background:#453124;color:#ffe9bd;border-radius:12px}.v3-toast{position:fixed;left:50%;bottom:90px;transform:translateX(-50%);z-index:60;background:#2a1d16;color:#ffe9bd;border:1px solid #c6a45b;padding:10px 16px;border-radius:20px;opacity:0;pointer-events:none;transition:.25s}.v3-toast.show{opacity:1}.v3-buttons{display:flex;gap:8px;flex-wrap:wrap}.v3-buttons button{background:#6d4930;color:#fff1cf;border:1px solid #a9814b;border-radius:8px;padding:9px 12px}.v3-hint{font-size:12px;opacity:.75}.v3-badge{display:inline-block;background:#9d783e;padding:3px 7px;border-radius:10px;font-size:11px}@media(max-width:700px){.v3-panel{inset:2%;padding:14px}.v3-grid{grid-template-columns:1fr;height:calc(100% - 55px)}.v3-card:nth-child(2){display:none}.v3-head h2{font-size:21px}}
`;document.head.appendChild(s)}
function panel(id,title){const p=document.createElement('section');p.id=id;p.className='v3-panel';p.innerHTML=`<div class="v3-head"><h2>${title}</h2><button class="v3-close">CERRAR</button></div><div class="v3-content"></div>`;p.querySelector('.v3-close').onclick=()=>p.classList.remove('open');document.body.appendChild(p);return p}
function toast(t){let e=document.querySelector('.v3-toast');if(!e){e=document.createElement('div');e.className='v3-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function inventory(){const p=ui.bag;p.querySelector('.v3-content').innerHTML='';const box=document.createElement('div');box.className='v3-grid';const a=document.createElement('div');a.className='v3-card';const inv=S().inventory||[];a.innerHTML=`<h3>Lo que llevás</h3><p>Capacidad: <b>${inv.length}</b> objetos</p>`;if(!inv.length)a.innerHTML+='<p>La mochila está vacía.</p>';inv.forEach((x,i)=>{const d=document.createElement('div');d.className='v3-item';d.innerHTML=`<span>🎒 ${x}</span><span class="v3-badge">${i+1}</span>`;a.appendChild(d)});const b=document.createElement('div');b.className='v3-card';b.innerHTML='<h3>Vida diaria</h3><p>La mochila no es solo inventario: acá guardás cosas que vas encontrando, comprando o usando en el pueblo.</p><p class="v3-hint">Tecla I para abrir/cerrar.</p>';box.append(a,b);p.querySelector('.v3-content').appendChild(box)}
function map(){const p=ui.map,panel=p.querySelector('.v3-content');panel.innerHTML='<div class="v3-grid"><div class="v3-card"><div class="v3-map"><div class="road" style="left:0;right:0;top:47%;height:9%"></div><div class="road" style="top:0;bottom:0;left:35%;width:7%"></div><div class="road" style="left:30%;right:0;top:69%;height:5%;transform:rotate(-8deg)"></div></div></div><div class="v3-card"><h3>Destinos</h3></div></div>';const m=panel.querySelector('.v3-map'),list=panel.querySelector('.v3-card:nth-child(2)');extra.spots.forEach((q,i)=>{const [name,x,y,type]=q;const pin=document.createElement('div');pin.className='v3-pin';pin.style.left=(x/4200*100)+'%';pin.style.top=(y/2700*100)+'%';pin.textContent='● '+name;m.appendChild(pin);const d=document.createElement('div');d.className='v3-item';d.innerHTML=`<span>${name}</span><span class="v3-badge">${type}</span>`;list.appendChild(d)});const me=document.createElement('div');me.className='v3-pin';me.style.left=(S().x/4200*100)+'%';me.style.top=(S().y/2700*100)+'%';me.textContent='TÚ';m.appendChild(me)}
function phone(){const p=ui.phone,c=p.querySelector('.v3-content');c.innerHTML=`<div class="v3-phone"><div class="v3-hint">VILLA PELÓN · ${String(Math.floor((S().minutes||480)/60)%24).padStart(2,'0')}:${String(Math.floor((S().minutes||480)%60)).padStart(2,'0')}</div><h2>📱 Teléfono</h2><p>Un teléfono sencillo para estar conectado con el pueblo.</p><div class="v3-apps"><button class="v3-app" id="contacts">👥 Contactos</button><button class="v3-app" id="notes">📝 Notas</button><button class="v3-app" id="radioapp">📻 Radio</button><button class="v3-app" id="weatherapp">☁️ Clima</button></div><div id="phoneinfo" class="v3-card" style="margin-top:15px">Elegí una aplicación.</div></div>`;c.querySelector('#contacts').onclick=()=>phoneInfo('Contactos','Marta · Raúl · Lucía · Pedro · Nico · Inés · Tomás');c.querySelector('#notes').onclick=()=>phoneInfo('Notas',`Misión: ${document.getElementById('questText')?.textContent||'Explorá el pueblo.'}`);c.querySelector('#radioapp').onclick=()=>phoneInfo('Radio Oasis','La voz del pueblo está al aire. Volvé a la radio para hablar con Nico.');c.querySelector('#weatherapp').onclick=()=>phoneInfo('Clima',document.getElementById('weather')?.textContent||'Despejado')}
function phoneInfo(a,b){const x=document.getElementById('phoneinfo');if(x)x.innerHTML=`<h3>${a}</h3><p>${b}</p>`}
function toggle(p){p.classList.toggle('open');if(p.classList.contains('open')){if(p===ui.bag)inventory();if(p===ui.map)map();if(p===ui.phone)phone()}}
function makeButtons(){css();ui.bag=panel('v3bag','🎒 MOCHILA');ui.map=panel('v3map','🗺️ MAPA DEL PUEBLO');ui.phone=panel('v3phone','📱 TELÉFONO');const bar=document.createElement('div');bar.id='v3bar';bar.style.cssText='position:fixed;right:18px;bottom:18px;z-index:25;display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end';[['🎒','Mochila',ui.bag],['🗺️','Mapa',ui.map],['📱','Teléfono',ui.phone]].forEach(([ico,t,p])=>{const b=document.createElement('button');b.textContent=`${ico} ${t}`;b.style.cssText='background:#3b281d;color:#ffe9bd;border:1px solid #a9814b;border-radius:10px;padding:9px 11px;box-shadow:0 3px 12px #0007';b.onclick=()=>toggle(p);bar.appendChild(b)});document.body.appendChild(bar);document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button'))return;const k=e.key.toLowerCase();if(k==='i')toggle(ui.bag);if(k==='m')toggle(ui.map);if(k==='p')toggle(ui.phone);if(k==='escape'){[ui.bag,ui.map,ui.phone].forEach(x=>x.classList.remove('open'))}})}
function worldEntities(dt){const st=S();if(!canvas||!ctx||!st.started)return;extra.people.forEach(n=>{n.x+=n.dx*dt*18;n.y+=n.dy*dt*18;if(n.x<300||n.x>3900)n.dx*=-1;if(n.y<350||n.y>2250)n.dy*=-1});extra.vehicles.forEach(v=>{v.x+=v.axis==='x'?v.speed*dt:0;v.y+=v.axis==='y'?v.speed*dt:0;if(v.x>4200)v.x=-100;if(v.x<-150)v.x=4200;if(v.y>2700)v.y=-100;if(v.y<-150)v.y=2700});extra.animals.forEach(a=>{a.x+=a.dx*dt*20;a.y+=a.dy*dt*20;if(a.x<200||a.x>4000)a.dx*=-1;if(a.y<350||a.y>2200)a.dy*=-1});
  // Render in the same approximate camera used by game.js.
  const zoom=.82,cx=st.x,cy=st.y,ox=innerWidth/2-cx*zoom,oy=innerHeight/2-cy*zoom;
  ctx.save();ctx.translate(ox,oy);ctx.scale(zoom,zoom);
  extra.vehicles.forEach(v=>{ctx.fillStyle=v.type==='tractor'?'#6d7d35':v.type==='camion'?'#6b6f72':v.type==='camioneta'?'#7b5940':'#536b72';ctx.fillRect(v.x-28,v.y-12,56,24);ctx.fillStyle='#202020';ctx.fillRect(v.x-19,v.y+9,13,6);ctx.fillRect(v.x+8,v.y+9,13,6);if(v.type==='tractor'){ctx.fillStyle='#34411e';ctx.fillRect(v.x-38,v.y-8,12,16)}});
  extra.people.forEach(n=>{ctx.fillStyle='#35251d';ctx.beginPath();ctx.ellipse(n.x,n.y+13,13,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b87452';ctx.beginPath();ctx.arc(n.x,n.y-3,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6b4c38';ctx.fillRect(n.x-7,n.y+5,14,20);ctx.fillStyle='#ffe4ad';ctx.font='11px sans-serif';ctx.fillText(n.name,n.x-25,n.y-18)});
  extra.animals.forEach(a=>{ctx.fillStyle=a.type==='caballo'?'#76523a':a.type==='vaca'?'#e2d7bd':'#b86e4f';ctx.beginPath();ctx.ellipse(a.x,a.y, a.type==='gallina'?9:18, a.type==='gallina'?6:10,0,0,Math.PI*2);ctx.fill();if(a.type!=='gallina'){ctx.fillRect(a.x+12,a.y-7,7,9)}else{ctx.fillStyle='#8c4a32';ctx.fillRect(a.x+7,a.y-3,5,4)}});ctx.restore()}
function loop(t){const dt=Math.min(.05,((loop.last||t)-t)*-0.001||0);loop.last=t;worldEntities(dt);requestAnimationFrame(loop)}
makeButtons();requestAnimationFrame(loop);
})();
