/* Villa Pelón V3 — interfaz integrada: mochila, mapa, teléfono y estado del pueblo. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const S=()=>V.state||{};const ui={};
function css(){if(document.getElementById('v3style'))return;const s=document.createElement('style');s.id='v3style';s.textContent=`
.v3-panel{position:fixed;inset:7%;z-index:40;background:rgba(28,20,15,.97);border:2px solid #c6a45b;box-shadow:0 20px 70px #000b;color:#f5ead0;border-radius:18px;padding:24px;display:none;font-family:system-ui,sans-serif}.v3-panel.open{display:block}.v3-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.v3-head h2{margin:0;font-size:28px}.v3-close{background:#6d4930;color:#fff;border:1px solid #c6a45b;border-radius:8px;padding:8px 12px}.v3-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px;height:calc(100% - 60px)}.v3-card{background:#38271d;border:1px solid #74583e;border-radius:12px;padding:14px;overflow:auto}.v3-map{position:relative;background:#b8a271;min-height:390px;border-radius:10px;overflow:hidden;border:2px solid #6b5237}.v3-map .road{position:absolute;background:#d5c18f}.v3-route{position:absolute;height:5px;background:#806a48;transform-origin:left center;border-radius:4px;opacity:.75}.v3-pin{position:absolute;transform:translate(-50%,-50%);background:#2d2119;color:#ffe7a0;border:2px solid #e3bf63;border-radius:999px;padding:4px 7px;font-size:11px;white-space:nowrap}.v3-item{display:flex;justify-content:space-between;gap:10px;padding:10px;border-bottom:1px solid #5b4532}.v3-phone{background:linear-gradient(150deg,#171513,#34271e);max-width:330px;margin:auto;border:5px solid #111;border-radius:28px;padding:18px;min-height:480px;box-shadow:0 12px 40px #0009}.v3-apps{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:20px}.v3-app{padding:18px 8px;border:1px solid #80633f;background:#453124;color:#ffe9bd;border-radius:12px}.v3-buttons button{background:#6d4930;color:#fff1cf;border:1px solid #a9814b;border-radius:8px;padding:9px 12px}.v3-hint{font-size:12px;opacity:.75}.v3-badge{display:inline-block;background:#9d783e;padding:3px 7px;border-radius:10px;font-size:11px}@media(max-width:700px){.v3-panel{inset:2%;padding:14px}.v3-grid{grid-template-columns:1fr;height:calc(100% - 55px)}.v3-card:nth-child(2){display:none}.v3-head h2{font-size:21px}}
`;document.head.appendChild(s)}
function panel(id,title){const p=document.createElement('section');p.id=id;p.className='v3-panel';p.innerHTML=`<div class="v3-head"><h2>${title}</h2><button class="v3-close">CERRAR</button></div><div class="v3-content"></div>`;p.querySelector('.v3-close').onclick=()=>p.classList.remove('open');document.body.appendChild(p);return p}
function inventory(){const p=ui.bag,c=p.querySelector('.v3-content'),inv=S().inventory||[];c.innerHTML=`<div class="v3-grid"><div class="v3-card"><h3>Lo que llevás</h3><p>Objetos: <b>${inv.length}</b></p>${inv.length?inv.map((x,i)=>`<div class="v3-item"><span>🎒 ${x}</span><span class="v3-badge">${i+1}</span></div>`).join(''):'<p>La mochila está vacía.</p>'}</div><div class="v3-card"><h3>Uso</h3><p>Acá se guardan compras, herramientas y objetos de misión.</p><p class="v3-hint">Tecla I para abrir/cerrar.</p></div></div>`}
function map(){const p=ui.map,c=p.querySelector('.v3-content'),spots=[['Plaza central',1120,760,'plaza'],['Escuela 273',575,485,'escuela'],['Almacén',1955,545,'comercio'],['Radio Oasis',1265,1500,'radio'],['Galpón rural',2555,1045,'rural'],['Bodega',3380,855,'bodega'],['Puesto del pueblo',515,1660,'rural'],['Camino de chacras',3000,1500,'chacras'],['Dique / naturaleza',3750,2050,'naturaleza']];c.innerHTML='<div class="v3-grid"><div class="v3-card"><div class="v3-map"></div></div><div class="v3-card"><h3>Destinos</h3></div></div>';const m=c.querySelector('.v3-map'),list=c.querySelector('.v3-card:nth-child(2)');const addRoute=(r)=>{for(let i=1;i<r.length;i++){const a=r[i-1],b=r[i],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),el=document.createElement('div');el.className='v3-route';el.style.left=a.x/4200*100+'%';el.style.top=a.y/2700*100+'%';el.style.width=len/4200*100+'%';el.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;m.appendChild(el)}};Object.values(V.v3Routes||{}).forEach(addRoute);spots.forEach(q=>{const [name,x,y,type]=q,pin=document.createElement('div');pin.className='v3-pin';pin.style.left=x/4200*100+'%';pin.style.top=y/2700*100+'%';pin.textContent='● '+name;m.appendChild(pin);const d=document.createElement('div');d.className='v3-item';d.innerHTML=`<span>${name}</span><span class="v3-badge">${type}</span>`;list.appendChild(d)});const me=document.createElement('div');me.className='v3-pin';me.style.left=S().x/4200*100+'%';me.style.top=S().y/2700*100+'%';me.textContent='TÚ';m.appendChild(me)}
function phone(){const p=ui.phone,c=p.querySelector('.v3-content'),st=S(),L=V.life||{};c.innerHTML=`<div class="v3-phone"><div class="v3-hint">VILLA PELÓN · ${String(Math.floor((st.minutes||480)/60)%24).padStart(2,'0')}:${String(Math.floor((st.minutes||480)%60)).padStart(2,'0')}</div><h2>📱 Teléfono</h2><p>Estado del pueblo: <b>${L.eventText||'tranquilo'}</b></p><div class="v3-apps"><button class="v3-app" id="contacts">👥 Contactos</button><button class="v3-app" id="notes">📝 Misión</button><button class="v3-app" id="radioapp">📻 Radio</button><button class="v3-app" id="weatherapp">☁️ Clima</button></div><div id="phoneinfo" class="v3-card" style="margin-top:15px">Elegí una aplicación.</div></div>`;c.querySelector('#contacts').onclick=()=>info('Contactos',(V.npcs||[]).map(n=>n.name).join(' · '));c.querySelector('#notes').onclick=()=>info('Misión',document.getElementById('questText')?.textContent||'Explorá el pueblo.');c.querySelector('#radioapp').onclick=()=>info('Radio Oasis','La radio acompaña la vida cotidiana del pueblo.');c.querySelector('#weatherapp').onclick=()=>info('Clima',`${L.weather||'despejado'} · ${L.temperature||19}°C`)}
function info(a,b){const x=document.getElementById('phoneinfo');if(x)x.innerHTML=`<h3>${a}</h3><p>${b}</p>`}
function toggle(p){p.classList.toggle('open');if(p.classList.contains('open')){if(p===ui.bag)inventory();if(p===ui.map)map();if(p===ui.phone)phone()}}
function boot(){css();ui.bag=panel('v3bag','🎒 MOCHILA');ui.map=panel('v3map','🗺️ MAPA DEL PUEBLO');ui.phone=panel('v3phone','📱 TELÉFONO');const bar=document.createElement('div');bar.id='v3bar';bar.style.cssText='position:fixed;right:18px;bottom:18px;z-index:25;display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end';[['🎒','Mochila',ui.bag],['🗺️','Mapa',ui.map],['📱','Teléfono',ui.phone]].forEach(([i,t,p])=>{const b=document.createElement('button');b.textContent=`${i} ${t}`;b.style.cssText='background:#3b281d;color:#ffe9bd;border:1px solid #a9814b;border-radius:10px;padding:9px 11px;box-shadow:0 3px 12px #0007';b.onclick=()=>toggle(p);bar.appendChild(b)});document.body.appendChild(bar);document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button'))return;const k=e.key.toLowerCase();if(k==='i')toggle(ui.bag);if(k==='m')toggle(ui.map);if(k==='p')toggle(ui.phone);if(k==='escape')[ui.bag,ui.map,ui.phone].forEach(x=>x.classList.remove('open'))})}
boot();
})();
