/* Villa Pelón V4 — SISTEMA DE PERSONAS
   Una sola representación visual humana para NPCs, vecinos y trabajadores.
   Identidad determinista + cuerpo completo + animación + ropa por oficio.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const C=V.v4Characters=V.v4Characters||{};C.version=4;
const profiles=V.characterProfiles;
function make(n={},i=0){return profiles?.make?profiles.make(n,i):Object.assign({id:n.id||`person_${i}`,name:n.name||'Vecino',age:n.age||35,height:n.height||1,build:n.build||.5,skin:n.skin||'#d9a17b',hair:n.hair||'#3b2b24',shirt:n.shirt||n.color||'#52705e',pants:n.pants||'#45413c',shoes:n.shoes||'#292723',hairStyle:n.hairStyle||'short',clothing:n.clothing||'shirt',appearanceSeed:i},n)}
function shadow(c,x,y,s=1){c.fillStyle='rgba(25,19,15,.30)';c.beginPath();c.ellipse(x,y+38*s,17*s,5*s,0,0,Math.PI*2);c.fill()}
function limb(c,x1,y1,x2,y2,w,color){c.strokeStyle='#302722';c.lineWidth=w+3;c.lineCap='round';c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.strokeStyle=color;c.lineWidth=w;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()}
function hair(c,n){const col=n.hair||'#40312a';c.fillStyle=col;c.strokeStyle='#30251f';c.lineWidth=1.5;c.beginPath();const s=n.hairStyle;if(s==='long'){c.arc(0,-29,15,Math.PI,Math.PI*2);c.lineTo(15,2);c.quadraticCurveTo(9,7,6,1);c.lineTo(-7,5);c.quadraticCurveTo(-14,7,-15,0)}else if(s==='curly'){c.arc(-9,-28,8,0,Math.PI*2);c.arc(0,-32,9,0,Math.PI*2);c.arc(9,-28,8,0,Math.PI*2);c.lineTo(13,-16);c.lineTo(-13,-16)}else if(s==='ponytail'){c.arc(0,-29,15,Math.PI,Math.PI*2);c.lineTo(13,-17);c.lineTo(-13,-17);c.fill();c.beginPath();c.arc(15,-23,7,0,Math.PI*2);c.fill();c.stroke();return}else if(s==='wavy'){c.arc(0,-29,15,Math.PI,Math.PI*2);c.lineTo(15,-15);c.quadraticCurveTo(9,-8,5,-17);c.quadraticCurveTo(0,-10,-5,-17);c.quadraticCurveTo(-9,-8,-15,-15)}else{c.arc(0,-29,15,Math.PI,Math.PI*2);c.lineTo(14,-18);c.quadraticCurveTo(5,-22,0,-18);c.quadraticCurveTo(-6,-22,-14,-18)}c.closePath();c.fill();c.stroke()}
function draw(c,n){if(!n||n.x==null||n.y==null)return;const s=n.height||1,b=Math.max(.34,Math.min(.82,n.build||.5));c.save();c.translate(n.x,n.y);c.scale(s,s);const skin=n.skin||'#d7a07b',shirt=n.player?'#315d9d':n.shirt||'#68765e',pants=n.pants||'#4b4b45',shoes=n.shoes||'#292723',phase=n.moving?Math.sin(performance.now()/115+(n.appearanceSeed||0)):0,role=String(n.role||n.kind||'').toLowerCase();
shadow(c,0,0,1);const gap=5+3*b,lx=-gap+phase*3,rx=gap-phase*3;
/* cuerpo completo: dos piernas independientes, rodillas, tobillos y pies */limb(c,lx,8,lx+phase*2,27,7,pants);limb(c,lx+phase*2,27,lx-phase*1.5,43,6,pants);limb(c,rx,8,rx-phase*2,27,7,pants);limb(c,rx-phase*2,27,rx+phase*1.5,43,6,pants);c.fillStyle=skin;c.fillRect(lx-2,41,4,5);c.fillRect(rx-2,41,4,5);limb(c,lx-1,45,lx-11,46,5,shoes);limb(c,rx+1,45,rx+11,46,5,shoes);
/* cadera, torso y cuello */const bw=15+16*b;c.fillStyle=pants;c.strokeStyle='#2d2723';c.lineWidth=2;c.beginPath();c.roundRect(-9-5*b,1,18+10*b,11,4);c.fill();c.stroke();c.fillStyle=shirt;c.beginPath();c.roundRect(-bw/2,-19,bw,30,6);c.fill();c.stroke();c.fillStyle=skin;c.fillRect(-4,-22,8,7);
/* ropa según oficio */if(n.clothing==='jacket'||/camion|chofer|repart|rural|jornal|product/.test(role)){c.fillStyle='rgba(20,25,27,.25)';c.fillRect(-bw/2+3,-16,bw-6,22);c.strokeStyle='rgba(30,27,24,.65)';c.beginPath();c.moveTo(0,-16);c.lineTo(0,9);c.stroke()}if(n.clothing==='dress'){c.fillStyle=shirt;c.beginPath();c.moveTo(-bw/2,-18);c.lineTo(bw/2,-18);c.lineTo(bw/2+8,12);c.lineTo(-bw/2-8,12);c.closePath();c.fill()}if(n.clothing==='school'||/escuela|estudiante|niñ/.test(role)){c.fillStyle='#e6dfc7';c.fillRect(-bw/2+3,-13,bw-6,5);c.fillStyle='#315d9d';c.fillRect(-3,-13,6,23)}if(n.clothing==='apron'||/panader/.test(role)){c.fillStyle='#eee2c8';c.fillRect(-bw/2+3,-15,bw-6,25);c.strokeStyle='#b9a98a';c.strokeRect(-bw/2+3,-15,bw-6,25)}
/* brazos, codos y manos */limb(c,-bw/2+3,-12,-bw/2-7+phase*3,10,7,shirt);limb(c,bw/2-3,-12,bw/2+7-phase*3,10,7,shirt);c.fillStyle=skin;c.strokeStyle='#352820';c.lineWidth=1.4;c.beginPath();c.arc(-bw/2-7+phase*3,10,4.3,0,Math.PI*2);c.arc(bw/2+7-phase*3,10,4.3,0,Math.PI*2);c.fill();c.stroke();
if(n.bag){c.fillStyle='#5b4a3c';c.fillRect(bw/2-2,-7,8,14)}if(n.tool||/rural|jornal|product|repart/.test(role)){c.strokeStyle='#624b35';c.lineWidth=3;c.beginPath();c.moveTo(bw/2+7,4);c.lineTo(bw/2+12,-12);c.stroke();c.fillStyle='#7d6847';c.fillRect(bw/2+8,-14,9,4)}
/* cabeza, orejas, cabello y rostro */const age=n.age||35,head=age<16?11:age>60?14:13;c.fillStyle=skin;c.strokeStyle='#352720';c.lineWidth=1.8;c.beginPath();c.ellipse(0,-30,head,head*1.08,0,0,Math.PI*2);c.fill();c.stroke();c.beginPath();c.arc(-head,-29,3.2,0,Math.PI*2);c.arc(head,-29,3.2,0,Math.PI*2);c.fill();c.stroke();hair(c,n);c.strokeStyle='#382b25';c.lineWidth=1.6;c.beginPath();c.moveTo(-8,-34);c.lineTo(-3,-35);c.moveTo(3,-35);c.lineTo(8,-34);c.stroke();c.fillStyle='#fffaf0';c.beginPath();c.ellipse(-5,-29,3.2,2.4,0,0,Math.PI*2);c.ellipse(5,-29,3.2,2.4,0,0,Math.PI*2);c.fill();c.fillStyle='#171515';c.beginPath();c.arc(-5,-29,1.25,0,Math.PI*2);c.arc(5,-29,1.25,0,Math.PI*2);c.fill();c.strokeStyle='#925c49';c.lineWidth=1;c.beginPath();c.moveTo(0,-28);c.lineTo(-1,-22);c.lineTo(2,-22);c.stroke();c.strokeStyle=n.expression==='happy'?'#9b4e4b':'#713e3b';c.beginPath();c.arc(0,-21,4,.15,Math.PI-.15);c.stroke();if(n.facialHair&&age>18){c.fillStyle=n.hair||'#40312a';c.beginPath();c.arc(0,-20,5,0,Math.PI);c.fill()}if(n.hat||/rural|jornal/.test(role)){c.fillStyle=n.hair||'#40312a';c.beginPath();c.arc(0,-34,14,Math.PI,Math.PI*2);c.fill();c.fillRect(-16,-34,31,4)}if(n.player){c.fillStyle='#f2d98d';c.font='bold 9px system-ui';c.textAlign='center';c.fillText('TÚ',0,57)}else if(n.showName){c.fillStyle='rgba(245,231,190,.9)';c.font='9px system-ui';c.textAlign='center';c.fillText(n.name||'Vecino',0,58)}c.restore()}
function collect(){const out=[],seen=new Set();const add=(n,i)=>{if(!n||n.x==null||seen.has(n))return;seen.add(n);out.push(make(n,i))};(V.npcs||[]).forEach((n,i)=>add(n,i));(V.life?.ambient||[]).forEach((n,i)=>add(Object.assign({id:`ambient_${i}`,name:['Claudia','Sergio','Rosa','Miguel','Laura','Jorge'][i]||'Vecino',role:'vecino',showName:false},n),100+i));(V.life?.workers||[]).forEach((n,i)=>add(Object.assign({id:`worker_${i}`,name:['Carlos','Daniel','Rubén'][i]||'Trabajador',role:'rural',showName:false},n),200+i));return out}
function drawAmbient(c){const all=collect();for(const n of all)if(!V.npcs?.includes(n)){/* perfiles derivados */}for(const n of all){const isCore=(V.npcs||[]).some(x=>x&&x.id===n.id);if(!isCore)draw(c,n)}}
C.make=make;C.draw=draw;C.collect=collect;C.drawAmbient=drawAmbient;C.profiles={version:4,body:'human-full',identity:'deterministic',hair:'8 styles',clothing:'role-based',animation:'walk-cycle'};
/* No instala wrappers sobre el motor: game.js conserva el control del render. */
V.v4?.register?.('characters',C);
})();