/* Villa Pelón V4 — SISTEMA HUMANO ÚNICO
   Todos los habitantes y el jugador pasan por este renderizador.
   No hay personaje por puntos, cuadrado o clon genérico.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const C=V.v4Characters=V.v4Characters||{};C.version=4;
const defaults={height:1,build:.5,skin:'#d7a07b',hair:'#40312a',shirt:'#68765e',pants:'#4b4b45',shoes:'#292723',hairStyle:'short',age:35};
const palette=[['#d9a17b','#3b2b24','#315d9d','#343d49'],['#c98e68','#5b3927','#8a5b38','#51453b'],['#e0b18b','#252321','#9b4f43','#3f4541'],['#b97855','#3a261e','#6d7650','#41372f'],['#d3a07d','#72513b','#b17b3e','#4a4742'],['#e5b995','#191817','#5c6e82','#4b3e38']];
function make(n,i=0){const p=palette[Math.abs(i)%palette.length];return Object.assign({},defaults,n,{skin:n.skin||p[0],hair:n.hair||p[1],shirt:n.shirt||n.color||p[2],pants:n.pants||p[3],height:n.height||(.88+(Math.abs(i)%5)*.08),build:n.build??(.38+(Math.abs(i)%4)*.09),age:n.age||(24+(Math.abs(i)*7)%48),hairStyle:n.hairStyle||['short','long','crop','cap','curly'][Math.abs(i)%5]})}
function collect(){const out=[],seen=new Set();const add=(n,i)=>{if(!n||n.x==null||seen.has(n))return;seen.add(n);out.push(make(n,i))};(V.npcs||[]).forEach((n,i)=>add(n,i));(V.v3Citizens||[]).forEach((n,i)=>add(n,i+20));(V.life?.workers||[]).forEach((n,i)=>add(n,i+40));(V.life?.ambient||[]).forEach((n,i)=>add(n,i+60));return out}
function hair(ctx,style,color){ctx.fillStyle=color;ctx.beginPath();if(style==='long'){ctx.arc(0,-22,14,Math.PI,Math.PI*2);ctx.lineTo(14,4);ctx.lineTo(8,8);ctx.lineTo(-9,7);ctx.lineTo(-14,3)}else if(style==='curly'){ctx.arc(-7,-22,7,0,Math.PI*2);ctx.arc(0,-25,8,0,Math.PI*2);ctx.arc(8,-22,7,0,Math.PI*2);ctx.lineTo(12,-13);ctx.lineTo(-12,-13)}else if(style==='cap'){ctx.arc(0,-21,13,Math.PI,Math.PI*2);ctx.fillRect(-15,-21,30,4);ctx.fill();return}else{ctx.arc(0,-22,14,Math.PI,Math.PI*2);ctx.lineTo(13,-13);ctx.lineTo(-12,-12)}ctx.closePath();ctx.fill()}
function draw(ctx,n){const scale=n.height||1,b=Math.max(.3,Math.min(.75,n.build||.5)),x=n.x,y=n.y;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const skin=n.skin,hairColor=n.hair,shirt=n.player?'#315d9d':n.shirt,pants=n.pants,shoes=n.shoes;const walk=n.moving||n.player&&!!(V.engine?.input?.up||V.engine?.input?.down||V.engine?.input?.left||V.engine?.input?.right);const swing=walk?Math.sin(performance.now()/110+(x||0))*.28:0;ctx.fillStyle='rgba(25,19,15,.30)';ctx.beginPath();ctx.ellipse(0,35,18+9*b,7,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=pants;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-5*b,4);ctx.lineTo(-7*b+Math.sin(swing)*5,25);ctx.moveTo(5*b,4);ctx.lineTo(7*b-Math.sin(swing)*5,25);ctx.stroke();ctx.strokeStyle=shoes;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-7*b+Math.sin(swing)*5,26);ctx.lineTo(-13+Math.sin(swing)*5,28);ctx.moveTo(7*b-Math.sin(swing)*5,26);ctx.lineTo(13-Math.sin(swing)*5,28);ctx.stroke();const bw=10+13*b;ctx.fillStyle=shirt;ctx.strokeStyle='#29231f';ctx.lineWidth=2.3;ctx.beginPath();ctx.roundRect(-bw/2,-17,bw,27,5);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(-bw/2+3,-13,bw*.22,18);ctx.strokeStyle=shirt;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-bw/2+2,-12);ctx.lineTo(-bw/2-7+Math.sin(swing)*3,7);ctx.moveTo(bw/2-2,-12);ctx.lineTo(bw/2+7-Math.sin(swing)*3,7);ctx.stroke();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(-bw/2-7+Math.sin(swing)*3,9,4,0,Math.PI*2);ctx.arc(bw/2+7-Math.sin(swing)*3,9,4,0,Math.PI*2);ctx.fill();ctx.fillRect(-4,-20,8,6);const age=n.age||35,head=age<16?11:age>60?14:13;ctx.strokeStyle='#352720';ctx.lineWidth=1.8;ctx.beginPath();ctx.ellipse(0,-28,head,head*1.08,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(-head,-27,3.2,0,Math.PI*2);ctx.arc(head,-27,3.2,0,Math.PI*2);ctx.fill();hair(ctx,n.hairStyle,hairColor);ctx.strokeStyle='#392b25';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-8,-31);ctx.lineTo(-3,-32);ctx.moveTo(3,-32);ctx.lineTo(8,-31);ctx.stroke();ctx.fillStyle='#171515';ctx.beginPath();ctx.arc(-5,-29,1.8,0,Math.PI*2);ctx.arc(5,-29,1.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#995f4a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,-29);ctx.lineTo(-1,-23);ctx.lineTo(2,-23);ctx.stroke();ctx.strokeStyle='#733d3b';ctx.beginPath();ctx.arc(0,-20,4,.15,Math.PI-.15);ctx.stroke();const role=(n.role||'').toLowerCase();if(/rural|repart|camion|jornal|product/.test(role)){ctx.fillStyle='#4a3b2c';ctx.fillRect(-4,-9,8,8)}if(/escuela|estudiante|niñ/.test(role)){ctx.fillStyle='#d8c59a';ctx.fillRect(-bw/2-1,-10,3,9);ctx.fillRect(bw/2-2,-10,3,9)}if(/radio/.test(role)){ctx.fillStyle='#252321';ctx.fillRect(-4,-10,8,4)}ctx.restore()}
function install(){if(!V.engine||C.installed)return false;C.installed=true;const e=V.engine,base=e.render;e.render=()=>{base();for(const n of collect())draw(e.ctx,n);if(V.state)draw(e.ctx,make({x:V.state.x,y:V.state.y,player:true,name:'TÚ',height:1,build:.48,shirt:'#315d9d',hair:'#332b28'},99))};return true}
C.make=make;C.draw=draw;C.collect=collect;C.install=install;C.profiles={version:4,heights:'individuales',builds:'individuales',ages:'infancia-adultez-vejez',faces:'ojos-cejas-nariz-boca',hair:'5 estilos',clothing:'por personaje/profesion',animation:'brazos-piernas-caminata'};const wait=()=>install()||requestAnimationFrame(wait);wait();
})();