/* Villa Pelón V4 — JUGABILIDAD
   Sistemas jugables: mapa, mochila, misiones, diálogos, curiosidades,
   relaciones, economía, actividades y mundo vivo. Este módulo agrega
   gameplay sobre el motor V4; no crea un segundo game loop.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const KEY='villa_pelon_v4_gameplay';
const state=()=>V.state||{};
const G=V.v4Gameplay={version:4,open:null};
const qs=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ensureState(){const s=state();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.relationships=s.relationships||{};s.flags=s.flags||{};s.money=Number.isFinite(s.money)?s.money:10000;s.energy=Number.isFinite(s.energy)?s.energy:100;s.mission=Number.isFinite(s.mission)?s.mission:0;return s}
const missions=[
{id:'arrival',title:'Conocé el pueblo',desc:'Recorré la avenida y conocé a una persona del pueblo.',reward:150,need:1},
{id:'mandados',title:'Un mandado sencillo',desc:'Conseguí pan en el almacén y entregalo a Raúl.',reward:300,need:1},
{id:'plaza',title:'La vida de la plaza',desc:'Visitá la plaza y quedate unos minutos observando.',reward:180,need:1},
{id:'changa',title:'Una changa',desc:'Hacé una tarea rural en el galpón.',reward:650,need:1},
{id:'memory',title:'Una memoria del lugar',desc:'Descubrí una curiosidad histórica documentada.',reward:350,need:1},
{id:'radio',title:'La voz del pueblo',desc:'Visitá la radio y conversá con Nico.',reward:450,need:1},
{id:'free',title:'Ahora elegís vos',desc:'El pueblo queda abierto: trabajá, comprá, conversá, explorá y descubrí.',reward:1000,need:1}
];
const curiosities=[
{id:'agua',title:'El agua cambió el paisaje',text:'Los trabajos de riego comenzaron a transformar estas tierras desde fines de la década de 1960. En 1971 comenzó la primera bocatoma.',source:'Memoria histórica del juego',historyId:'riego'},
{id:'pelon',title:'¿Por qué Pelón?',text:'El pelón es uno de los frutos asociados a la identidad productiva de San Patricio del Chañar. La fiesta provincial comenzó en 1985.',source:'Memoria histórica del juego',historyId:'pelon'},
{id:'vino',title:'Viñedos en el desierto',text:'El riego permitió desarrollar una importante actividad agrícola y vitivinícola en un paisaje naturalmente árido.',source:'Memoria histórica del juego',historyId:'vinos'},
{id:'tratayen',title:'Una colonia anterior',text:'La documentación institucional menciona la colonia Tratayen y una mensura de comienzos del siglo XX.',source:'Memoria histórica del juego',historyId:'tratayen'},
{id:'rutas',title:'El pueblo y sus caminos',text:'Las rutas provinciales 7 y 8 forman parte de la conexión territorial y productiva de la zona.',source:'Memoria histórica del juego',historyId:'territorio'}
];
const events=[
{t:0,msg:'Un vecino pasa en bicicleta y saluda.'},{t:8,msg:'Se escucha movimiento cerca del almacén.'},{t:15,msg:'Un vehículo rural cruza la avenida.'},{t:25,msg:'Dos vecinos se quedan conversando en la vereda.'},{t:35,msg:'Un perro cruza la calle y sigue su camino.'},{t:45,msg:'La actividad de la chacra empieza a aumentar.'},{t:55,msg:'La radio prepara una nueva salida al aire.'}
];
function css(){if(qs('#v4GameplayStyle'))return;const st=document.createElement('style');st.id='v4GameplayStyle';st.textContent=`
.v4g-tools{position:absolute;z-index:12;right:16px;top:128px;display:flex;gap:7px}.v4g-tools button{padding:9px 12px;border-radius:8px;background:rgba(35,31,23,.9);color:#f4dfae;border:1px solid rgba(224,190,111,.4);box-shadow:0 5px 18px rgba(0,0,0,.28)}.v4g-tools button:hover{background:#4b3a25}.v4g-panel{position:fixed;z-index:50;inset:7%;background:rgba(29,25,19,.985);border:1px solid #d1ae67;border-radius:15px;box-shadow:0 30px 100px #000;overflow:auto;color:#f4ead4}.v4g-head{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid rgba(220,187,111,.25);position:sticky;top:0;background:#29231b;z-index:2}.v4g-head strong{color:#e6c675;letter-spacing:1.5px}.v4g-close{background:#5a4430;color:#fff;padding:7px 11px;border-radius:7px}.v4g-body{padding:18px}.v4g-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.v4g-card{padding:13px;background:#393026;border:1px solid rgba(222,191,119,.18);border-radius:10px}.v4g-card h3{margin:0 0 6px;color:#e4c16d;font-size:14px}.v4g-card p{margin:0;color:#d9cfbd;font-size:12px;line-height:1.45}.v4g-action{margin-top:10px;padding:8px 10px;border-radius:7px;background:#b98538;color:#241a11}.v4g-map{width:100%;height:min(65vh,620px);display:block;background:#8f805e;border-radius:10px}.v4g-log{position:fixed;z-index:25;right:16px;bottom:16px;width:min(330px,calc(100vw - 32px));display:flex;flex-direction:column;gap:6px;pointer-events:none}.v4g-toast{padding:10px 13px;border-radius:9px;background:rgba(30,26,20,.94);border:1px solid rgba(225,193,115,.35);color:#eee2c5;font-size:12px;box-shadow:0 7px 22px #0006}.v4g-toast b{color:#e5c36e}.v4g-live{position:absolute;z-index:11;left:16px;bottom:82px;padding:8px 12px;border-radius:8px;background:rgba(29,26,20,.8);border:1px solid rgba(222,188,107,.25);color:#d9cfb9;font-size:11px}.v4g-live b{color:#e4c16d}@media(max-width:800px){.v4g-tools{top:120px;right:8px}.v4g-tools button{font-size:10px;padding:8px}.v4g-panel{inset:3%}.v4g-live{bottom:145px;left:8px;font-size:9px}.v4g-grid{grid-template-columns:1fr 1fr}}`;
document.head.appendChild(st)}
function ui(){if(qs('#v4gTools'))return;const game=qs('#game');if(!game)return;const tools=document.createElement('div');tools.id='v4gTools';tools.className='v4g-tools';tools.innerHTML='<button id="v4gMap">MAPA</button><button id="v4gBag">MOCHILA</button><button id="v4gQuest">MISIÓN</button><button id="v4gCur">CURIOSIDADES</button>';game.appendChild(tools);const log=document.createElement('div');log.id='v4gLog';log.className='v4g-log';game.appendChild(log);const live=document.createElement('div');live.id='v4gLive';live.className='v4g-live';game.appendChild(live);qs('#v4gMap').onclick=()=>map();qs('#v4gBag').onclick=()=>bag();qs('#v4gQuest').onclick=()=>quest();qs('#v4gCur').onclick=()=>curiosity();}
function toast(msg){const box=qs('#v4gLog');if(!box)return;const d=document.createElement('div');d.className='v4g-toast';d.innerHTML=msg;box.appendChild(d);setTimeout(()=>d.remove(),4200)}
function panel(title,html){close();const p=document.createElement('div');p.id='v4gPanel';p.className='v4g-panel';p.innerHTML='<div class="v4g-head"><strong>'+esc(title)+'</strong><button class="v4g-close">CERRAR</button></div><div class="v4g-body">'+html+'</div>';document.body.appendChild(p);p.querySelector('.v4g-close').onclick=close;G.open=p;return p}
function close(){const p=qs('#v4gPanel');if(p)p.remove();G.open=null}
function map(){ensureState();const p=panel('MAPA · VILLA PELÓN','<canvas id="v4gMapCanvas" class="v4g-map"></canvas><p>Tu posición, vecinos, edificios, lugares históricos y zonas de actividad aparecen en el mapa.</p>');const c=qs('#v4gMapCanvas'),ctx=c.getContext('2d');const d=Math.min(devicePixelRatio||1,2);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.scale(d,d);drawMap(ctx,c.clientWidth,c.clientHeight)}
function drawMap(ctx,w,h){const world=V.world||{w:4200,h:2700};const sx=w/world.w,sy=h/world.h;ctx.fillStyle='#a7956d';ctx.fillRect(0,0,w,h);ctx.fillStyle='#77805e';ctx.fillRect(0,0,w,Math.max(60,h*.18));ctx.fillStyle='#c7b181';ctx.fillRect(0,700*sy,w,230*sy);ctx.fillRect(1180*sx,0,220*sx,h);ctx.fillStyle='#ded2aa';ctx.fillRect(0,782*sy,w,66*sy);ctx.fillRect(1256*sx,0,68*sx,h);ctx.strokeStyle='#8a7557';ctx.lineWidth=2;ctx.setLineDash([12,9]);ctx.beginPath();ctx.moveTo(0,815*sy);ctx.lineTo(w,815*sy);ctx.moveTo(1290*sx,0);ctx.lineTo(1290*sx,h);ctx.stroke();ctx.setLineDash([]);
(V.buildings||[]).forEach(b=>{ctx.fillStyle=b.type==='shop'?'#9a6941':b.type==='school'?'#b8aa7d':b.type==='radio'?'#a96d60':b.type==='rural'?'#896444':'#ad9274';ctx.fillRect(b.x*sx,b.y*sy,b.w*sx,b.h*sy)});
(V.historySpots||[]).forEach(o=>{ctx.fillStyle='#d9b84f';ctx.beginPath();ctx.arc(o.x*sx,o.y*sy,7,0,Math.PI*2);ctx.fill()});
(V.npcs||[]).forEach(n=>{ctx.fillStyle='#e6d8ad';ctx.beginPath();ctx.arc(n.x*sx,n.y*sy,4,0,Math.PI*2);ctx.fill()});
const s=state();ctx.fillStyle='#fff0a0';ctx.beginPath();ctx.arc(s.x*sx,s.y*sy,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#241c13';ctx.stroke();ctx.fillStyle='#211a13';ctx.font='bold 11px system-ui';ctx.fillText('VOS',s.x*sx+9,s.y*sy+4);ctx.fillStyle='#e8d39a';ctx.font='bold 12px system-ui';ctx.fillText('AVENIDA PRINCIPAL',10,700*sy-6);ctx.fillText('CALLE CENTRAL',1260*sx,18)}
function bag(){const s=ensureState(),items=s.inventory;const cards=items.length?items.map((x,i)=>'<div class="v4g-card"><h3>'+esc(x)+'</h3><p>Objeto guardado en tu mochila.</p></div>').join(''):'<div class="v4g-card"><h3>Mochila vacía</h3><p>Comprá, encontrá o recibí objetos durante tus recorridos.</p></div>';panel('MOCHILA', '<div class="v4g-grid">'+cards+'</div><p style="margin-top:15px">Dinero: <b>$'+Math.round(s.money)+'</b> · Energía: <b>'+Math.round(s.energy)+'</b></p>')}
function quest(){const s=ensureState(),m=missions[Math.min(s.mission,missions.length-1)];const done=s.flags['mission_'+m.id];panel('MISIÓN ACTUAL','<div class="v4g-card"><h3>'+esc(m.title)+'</h3><p>'+esc(m.desc)+'</p><p style="margin-top:9px">Recompensa: <b>$'+m.reward+'</b></p><p style="margin-top:9px">Estado: <b>'+(done?'COMPLETADA':'EN CURSO')+'</b></p></div><div class="v4g-grid" style="margin-top:12px">'+missions.map((q,i)=>'<div class="v4g-card"><h3>'+(i===s.mission?'▶ ':'')+esc(q.title)+'</h3><p>'+esc(q.desc)+'</p></div>').join('')+'</div>')}
function curiosity(){const s=ensureState();const cards=curiosities.map(c=>{const seen=!!s.flags['cur_'+c.id];return '<div class="v4g-card"><h3>'+esc(c.title)+(seen?' ✓':'')+'</h3><p>'+esc(c.text)+'</p><p style="margin-top:7px;font-size:10px">'+esc(c.source)+'</p><button class="v4g-action" data-cur="'+c.id+'">'+(seen?'LEÍDA':'DESCUBRIR')+'</button></div>'}).join('');const p=panel('CURIOSIDADES · MEMORIA VIVA','<div class="v4g-grid">'+cards+'</div>');p.querySelectorAll('[data-cur]').forEach(b=>b.onclick=()=>discover(b.dataset.cur));}
function discover(id){const c=curiosities.find(x=>x.id===id);if(!c)return;const s=ensureState();s.flags['cur_'+id]=true;if(c.historyId){s.history=s.history||[];if(!s.history.includes(c.historyId))s.history.push(c.historyId)}persist();toast('<b>CURIOSIDAD:</b> '+esc(c.title));panel('CURIOSIDAD · '+c.title,'<div class="v4g-card"><p>'+esc(c.text)+'</p><p style="margin-top:10px">'+esc(c.source)+'</p></div>');}
function dialogue(n){const s=ensureState();const lines=(n.lines&&n.lines.length?n.lines:['Buen día. ¿Cómo andás?']);let i=0;const p=panel(n.name||n.label||'VECINO','<div id="v4gDialogueText" style="font-size:17px;line-height:1.6;min-height:70px">'+esc(lines[0])+'</div><div id="v4gChoices" class="v4g-grid" style="margin-top:14px"></div><button id="v4gNext" class="v4g-action">SEGUIR</button>');const next=()=>{i++;if(i<lines.length)qs('#v4gDialogueText').textContent=lines[i];else{close();s.dialogue=false;persist()}};p.querySelector('#v4gNext').onclick=next;s.dialogue=true;const choices=[['¿Qué hay para hacer?',()=>toast('Podés caminar, comprar, trabajar, conocer gente y buscar historias.')],['¿Cómo es vivir acá?',()=>toast('En los pueblos las distancias son cortas y las historias largas.')]];const ch=p.querySelector('#v4gChoices');choices.forEach(([label,fn])=>{const b=document.createElement('button');b.className='v4g-action';b.textContent=label;b.onclick=()=>{fn();rel(n.id,1)};ch.appendChild(b)});rel(n.id,1);checkMission('arrival');}
function rel(id,n){const s=ensureState();if(!id)return;s.relationships[id]=(s.relationships[id]||0)+n;persist()}
function checkMission(kind){const s=ensureState(),m=missions[Math.min(s.mission,missions.length-1)];if(!m||s.flags['mission_'+m.id])return false;let ok=false;if(m.id==='arrival'&&kind==='arrival')ok=true;if(m.id==='mandados'&&kind==='bread')ok=true;if(m.id==='plaza'&&kind==='plaza')ok=true;if(m.id==='changa'&&kind==='job')ok=true;if(m.id==='memory'&&kind==='memory')ok=true;if(m.id==='radio'&&kind==='radio')ok=true;if(m.id==='free')ok=true;if(!ok)return false;s.flags['mission_'+m.id]=true;s.money+=m.reward;s.mission=Math.min(s.mission+1,missions.length-1);persist();toast('<b>MISIÓN COMPLETADA:</b> '+esc(m.title)+' · +$'+m.reward);return true}
function shop(){const s=ensureState();const p=panel('ALMACÉN EL ENCUENTRO','<div class="v4g-grid"><div class="v4g-card"><h3>Pan · $120</h3><p>Pan para llevar o compartir.</p><button class="v4g-action" id="buyBread">COMPRAR</button></div><div class="v4g-card"><h3>Yerba · $180</h3><p>Para un mate tranquilo en la plaza.</p><button class="v4g-action" id="buyYerba">COMPRAR</button></div><div class="v4g-card"><h3>Azúcar · $90</h3><p>Un básico de almacén.</p><button class="v4g-action" id="buySugar">COMPRAR</button></div></div>');[['#buyBread','Pan'],['#buyYerba','Yerba'],['#buySugar','Azúcar']].forEach(([sel,item])=>p.querySelector(sel).onclick=()=>buy(item,item==='Pan'?120:item==='Yerba'?180:90));}
function buy(item,cost){const s=ensureState();if(s.money<cost){toast('<b>ALMACÉN:</b> No te alcanza.');return}s.money-=cost;if(!s.inventory.includes(item))s.inventory.push(item);persist();toast('<b>MOCHILA:</b> '+item+' guardado.');checkMission(item==='Pan'?'bread':'none');bag()}
function job(){const s=ensureState();if(s.energy<20){toast('<b>CHACRA:</b> Estás cansado. Descansá.');return}s.energy-=20;s.money+=650;if(!s.inventory.includes('Cajón de cosecha'))s.inventory.push('Cajón de cosecha');persist();toast('<b>CHANGA:</b> Terminaste una tarea rural · +$650');checkMission('job')}
function activate(n){if(!n)return false;if(n.id&&V.npcs?.includes(n)){dialogue(n);return true}if(n.type==='shop'){shop();return true}if(n.type==='home'){const s=ensureState();s.energy=Math.min(100,s.energy+35);s.minutes+=30;persist();toast('<b>CASA:</b> Descansaste y recuperaste energía.');return true}if(n.type==='radio'){dialogue({id:'radio',name:n.label||'RADIO OASIS',lines:['La radio está al aire. Siempre hay una historia dando vueltas.','Podés traer fotos, recuerdos y noticias del pueblo.']});checkMission('radio');return true}if(n.type==='rural'){job();return true}if(n.type==='school'){dialogue({id:'school',name:n.label||'ESCUELA',lines:['Acá quedan recuerdos de distintas generaciones.','Una escuela también es parte de la memoria de un pueblo.']});return true}if(n.id&&V.historySpots?.includes(n)){const h=(V.history||[]).find(x=>x.id===n.id);if(h){discover(h.id);checkMission('memory')}return true}return false}
function nearest(){const s=state();let best=null,bd=155;const arr=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[]),V.storyJob].filter(Boolean);for(const o of arr){const x=o.x+(o.w?o.w/2:0),y=o.y+(o.h?o.h/2:0),d=Math.hypot(s.x-x,s.y-y);if(d<bd){bd=d;best=o}}return best}
function capture(e){const k=e.key?.toLowerCase();if(!state().started)return;if(k==='escape'){if(G.open){close();e.preventDefault();e.stopImmediatePropagation();return}if(state().dialogue){state().dialogue=false;return}}if(k==='m'){map();e.preventDefault();e.stopImmediatePropagation();return}if(k==='i'||k==='b'){bag();e.preventDefault();e.stopImmediatePropagation();return}if(k==='j'||k==='q'){quest();e.preventDefault();e.stopImmediatePropagation();return}if(k==='h'){curiosity();e.preventDefault();e.stopImmediatePropagation();return}if(k==='e'||k===' '){if(G.open){const n=qs('#v4gNext');if(n)n.click();e.preventDefault();e.stopImmediatePropagation();return}const n=nearest();if(activate(n)){e.preventDefault();e.stopImmediatePropagation()}}}
function persist(){const s=ensureState();try{localStorage.setItem(KEY,JSON.stringify({version:4,mission:s.mission,flags:s.flags,inventory:s.inventory,relationships:s.relationships}))}catch(_){}if(V.story?.saveV4)V.story.saveV4();if(typeof V.v4World?.sync==='function')V.v4World.sync()}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x){const s=ensureState();s.mission=Number(x.mission)||0;s.flags=x.flags||{};s.inventory=Array.isArray(x.inventory)?x.inventory:[];s.relationships=x.relationships||{}}}catch(_){} }
let lastEvent=-1;
function live(){const s=state();if(!s.started)return;const minute=Math.floor(s.minutes%60),idx=Math.floor(minute/7);if(idx!==lastEvent&&events[idx]){lastEvent=idx;toast('<b>MUNDO VIVO:</b> '+events[idx].msg)}const l=qs('#v4gLive');if(l){const h=Math.floor(s.minutes/60)%24;l.innerHTML='<b>MUNDO VIVO</b> · '+(h<6?'Pueblo en calma':h<10?'La mañana empieza':h<14?'Movimiento en calles y comercios':h<19?'Tarde de trabajo y encuentros':'Baja el ritmo del pueblo')}}
function install(){css();ui();load();document.addEventListener('keydown',capture,true);const oldStart=qs('#startBtn');if(oldStart)oldStart.addEventListener('click',()=>setTimeout(()=>{ui();toast('<b>V4:</b> Mapa, mochila, misiones, diálogos y curiosidades disponibles. Teclas: M · I/B · J/Q · H · E.');},100));setInterval(live,1000);G.activate=activate;G.nearest=nearest;G.persist=persist;G.missions=missions;G.curiosities=curiosities;}
install();
})();
