/* Villa Pelón V4 — SISTEMA PRINCIPAL DE JUGABILIDAD
   Concepto: videojuego educativo de aventura sobre la historia de San Patricio del Chañar.
   Bucle: explorar -> hablar -> descubrir -> cumplir misión -> aprender -> desbloquear.
   Único dueño de misiones, diálogo, inventario, curiosidades, mapa y progreso.
   No crea un segundo RAF ni reemplaza el motor de movimiento. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const G=V.v4Playability={version:4,authority:true,open:null};
const KEY='villa_pelon_v4_player';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state=()=>V.state||(V.state={});
const chapters=[
 {id:'origen',title:'CAPÍTULO 1 · EL TERRITORIO'},
 {id:'riego',title:'CAPÍTULO 2 · EL AGUA'},
 {id:'comunidad',title:'CAPÍTULO 3 · LA COMUNIDAD'},
 {id:'produccion',title:'CAPÍTULO 4 · LA PRODUCCIÓN'},
 {id:'memoria',title:'CAPÍTULO 5 · LA MEMORIA'},
 {id:'presente',title:'CAPÍTULO 6 · EL PUEBLO ACTUAL'}
];
const missions=[
 {id:'llegada',chapter:0,title:'Conocé a alguien',objective:'Hablá con un vecino del pueblo.',hint:'Buscá una persona y acercate hasta interactuar.',reward:150},
 {id:'mandado',chapter:1,title:'El primer mandado',objective:'Comprá pan en el almacén.',hint:'Encontrá el comercio del pueblo y abrí su menú.',reward:250},
 {id:'entrega',chapter:1,title:'Lleváselo a Raúl',objective:'Entregale el pan a Raúl.',hint:'Con el pan en la mochila, buscá a Raúl.',reward:300},
 {id:'plaza',chapter:2,title:'La vida de la plaza',objective:'Visitá la plaza y conversá con un vecino.',hint:'Recorré el centro: la plaza es un punto de encuentro.',reward:180},
 {id:'changa',chapter:3,title:'Una changa rural',objective:'Realizá una tarea en la zona rural.',hint:'Acercate al galpón o puesto de trabajo rural.',reward:650},
 {id:'memoria',chapter:4,title:'Una memoria del lugar',objective:'Descubrí una memoria histórica.',hint:'Buscá un punto de memoria marcado en el mundo.',reward:350},
 {id:'radio',chapter:4,title:'La voz del pueblo',objective:'Visitá la radio y hablá con Nico.',hint:'La radio guarda historias y memoria oral.',reward:450},
 {id:'libre',chapter:5,title:'Ahora elegís vos',objective:'El pueblo queda abierto: explorá, trabajá, comprá, conversá y descubrí.',hint:'Completaste la campaña inicial. Las actividades siguen disponibles.',reward:1000}
];
const dialogues={
 default:{name:'Vecino',lines:['Buen día. ¿Cómo andás?','En un pueblo chico siempre hay una historia detrás de una cosa sencilla.']},
 raul:{name:'Raúl',lines:['Buen día. ¿Venís por el pan?','Gracias. Después contame qué encontraste mientras recorrías el pueblo.']},
 nico:{name:'Nico',lines:['Pasá. Acá la radio también guarda memoria.','Si encontrás una foto, un recuerdo o un dato documentado, traelo.']},
 plaza:{name:'Vecina de la plaza',lines:['Esta plaza cambia según la hora.','La vida cotidiana también forma parte de la historia de un pueblo.']},
 shop:{name:'Almacén El Encuentro',lines:['Pasá tranquilo.','Muchas historias empiezan con un mandado.']},
 rural:{name:'Trabajador rural',lines:['Hay trabajo para hacer.','El paisaje y la producción están muy ligados a la vida cotidiana.']}
};
const curiosities=[
 {id:'agua',title:'El agua y la transformación del paisaje',text:'El riego es una clave para entender cómo un paisaje naturalmente árido pudo transformarse en un territorio productivo.',chapter:1,source:'Contenido educativo: completar con fuentes históricas verificadas.'},
 {id:'pelon',title:'El pelón y la identidad productiva',text:'El pelón forma parte de la identidad frutícola asociada a San Patricio del Chañar.',chapter:3,source:'Contenido educativo: completar con fuente documental específica.'},
 {id:'vinos',title:'Viñedos en el desierto',text:'La agricultura bajo riego y la vitivinicultura son parte fundamental de la transformación productiva del valle.',chapter:3,source:'Contenido educativo: completar con fuentes verificadas.'},
 {id:'tratayen',title:'Tratayen y el territorio anterior',text:'La historia territorial de la zona no comienza con el pueblo moderno. Documentos y cartografía permiten investigar etapas anteriores.',chapter:0,source:'Contenido educativo: completar con documentación archivística.'},
 {id:'caminos',title:'Los caminos conectan historias',text:'Los caminos vinculan viviendas, chacras, instituciones y zonas productivas, y permiten reconstruir el crecimiento territorial.',chapter:0,source:'Contenido educativo: completar con mapas históricos.'}
];
function ensure(){const s=state();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.relationships=s.relationships||{};s.flags=s.flags||{};s.history=Array.isArray(s.history)?s.history:[];s.money=Number.isFinite(s.money)?s.money:10000;s.energy=Number.isFinite(s.energy)?s.energy:100;s.mission=Math.max(0,Math.min(missions.length-1,Number.isFinite(s.mission)?s.mission:0));s.v4Version=4;return s}
function save(){const s=ensure();try{localStorage.setItem(KEY,JSON.stringify({inventory:s.inventory,relationships:s.relationships,flags:s.flags,history:s.history,money:s.money,energy:s.energy,mission:s.mission,version:4}))}catch(_){} }
function load(){const s=ensure();try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d&&typeof d==='object'){Object.assign(s,d);s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.relationships=s.relationships||{};s.flags=s.flags||{};s.history=Array.isArray(s.history)?s.history:[];s.v4Version=4}}catch(_){}return s}
function has(item){return ensure().inventory.some(x=>String(x).toLowerCase()===item.toLowerCase()||String(x).toLowerCase().includes(item.toLowerCase()))}
function add(item){if(!has(item))ensure().inventory.push(item)}
function remove(item){const s=ensure(),i=s.inventory.findIndex(x=>String(x).toLowerCase()===item.toLowerCase()||String(x).toLowerCase().includes(item.toLowerCase()));if(i>=0){s.inventory.splice(i,1);return true}return false}
function mission(){return missions[ensure().mission]}
function done(id){return !!ensure().flags['m_done_'+id]}
function complete(id){const s=ensure(),m=missions.find(x=>x.id===id);if(!m||done(id)||s.mission!==missions.indexOf(m))return false;s.flags['m_done_'+id]=true;s.money+=m.reward;s.mission=Math.min(missions.length-1,s.mission+1);save();toast('MISIÓN COMPLETADA · '+m.title+' · +$'+m.reward);refreshMission();return true}
function css(){if(document.getElementById('v4PlayabilityCSS'))return;const st=document.createElement('style');st.id='v4PlayabilityCSS';st.textContent=`#v4pTools{position:absolute;z-index:80;top:126px;right:14px;display:flex;gap:6px;flex-wrap:wrap;max-width:520px;justify-content:flex-end}#v4pTools button{background:rgba(28,24,18,.94);border:1px solid #b99655;color:#f1d99d;border-radius:7px;padding:8px 10px;font:700 11px system-ui;cursor:pointer}.v4p-panel{position:fixed;z-index:1000;inset:4%;overflow:auto;background:#211c16;color:#eee3cf;border:1px solid #c7a45d;border-radius:14px;box-shadow:0 30px 100px #000}.v4p-head{position:sticky;top:0;z-index:2;background:#30271e;border-bottom:1px solid #715c38;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}.v4p-head strong{color:#ebce81;letter-spacing:1px}.v4p-body{padding:18px}.v4p-close,.v4p-action{background:#936a35;color:#fff;border:0;border-radius:7px;padding:8px 12px;font-weight:700;cursor:pointer}.v4p-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.v4p-card{background:#393026;border:1px solid #5e4e36;border-radius:9px;padding:13px}.v4p-card h3{color:#e6c676;margin:0 0 7px;font-size:14px}.v4p-card p{font-size:12px;line-height:1.5;color:#d9cfbd;margin:5px 0}.v4p-dialog{font-size:18px;line-height:1.65;min-height:95px;padding:12px 0}.v4p-speaker{color:#e9cb78;font-weight:800;letter-spacing:1px}.v4p-choice{margin:5px 5px 0 0}.v4p-map{display:block;width:100%;height:min(70vh,680px);background:#a3946e;border-radius:9px}.v4p-toast{position:fixed;z-index:1100;right:15px;bottom:18px;max-width:380px;background:rgba(28,24,18,.97);border:1px solid #806b45;border-radius:8px;padding:11px 14px;color:#eee2c9;box-shadow:0 10px 30px #000}.v4p-live{position:absolute;z-index:79;left:15px;bottom:80px;padding:7px 10px;background:rgba(28,24,18,.82);border:1px solid #65543a;border-radius:7px;color:#d8cfbd;font-size:11px}.v4p-progress{height:9px;background:#18140f;border-radius:8px;overflow:hidden;margin:10px 0}.v4p-progress i{display:block;height:100%;background:#c49a4c}.v4p-source{font-size:10px!important;color:#aaa08e!important;border-top:1px solid #5e4e36;padding-top:7px;margin-top:10px!important}@media(max-width:700px){#v4pTools{top:118px;right:7px;max-width:330px}.v4p-panel{inset:2%}.v4p-live{bottom:145px}.v4p-grid{grid-template-columns:1fr}.v4p-dialog{font-size:16px}}`;document.head.appendChild(st)}
function ui(){if(document.getElementById('v4pTools'))return;const g=document.getElementById('game');if(!g)return;const b=document.createElement('div');b.id='v4pTools';b.innerHTML='<button data-v4="map">MAPA</button><button data-v4="bag">MOCHILA</button><button data-v4="missions">MISIONES</button><button data-v4="memory">MEMORIA</button>';g.appendChild(b);b.querySelector('[data-v4="map"]').onclick=map;b.querySelector('[data-v4="bag"]').onclick=bag;b.querySelector('[data-v4="missions"]').onclick=missionsUI;b.querySelector('[data-v4="memory"]').onclick=memoryUI;const l=document.createElement('div');l.id='v4pLive';l.className='v4p-live';g.appendChild(l);refreshMission()}
function panel(title,html){close();const p=document.createElement('div');p.id='v4pPanel';p.className='v4p-panel';p.innerHTML='<div class="v4p-head"><strong>'+esc(title)+'</strong><button class="v4p-close">CERRAR</button></div><div class="v4p-body">'+html+'</div>';document.body.appendChild(p);p.querySelector('.v4p-close').onclick=close;G.open=p;return p}
function close(){document.getElementById('v4pPanel')?.remove();G.open=null;ensure().dialogue=false}
function toast(text){const d=document.createElement('div');d.className='v4p-toast';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),3200)}
function refreshMission(){const s=ensure(),m=mission(),q=document.getElementById('questTitle'),t=document.getElementById('questText');if(q)q.textContent=m.id==='libre'?'MUNDO ABIERTO':'MISIÓN · '+m.title;if(t)t.textContent=m.objective;const l=document.getElementById('v4pLive');if(l)l.innerHTML='MISIÓN · <b>'+esc(m.title)+'</b>'}
function map(){const p=panel('MAPA · VILLA PELÓN','<canvas id="v4pMap" class="v4p-map"></canvas><p>El mapa marca lugares de misión, memoria, edificios, vecinos y tu posición.</p>');const c=document.getElementById('v4pMap'),d=Math.min(devicePixelRatio||1,2);c.width=c.clientWidth*d;c.height=c.clientHeight*d;const x=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight;x.scale(d,d);const world=V.world||{w:4200,h:2700},sx=w/world.w,sy=h/world.h;x.fillStyle='#a79670';x.fillRect(0,0,w,h);x.fillStyle='#77805d';x.fillRect(0,0,w,h*.18);x.fillStyle='#c8b17d';x.fillRect(0,700*sy,w,230*sy);x.fillRect(1180*sx,0,220*sx,h);x.fillStyle='#ded1a8';x.fillRect(0,782*sy,w,66*sy);x.fillRect(1256*sx,0,68*sx,h);x.strokeStyle='#806d51';x.setLineDash([10,8]);x.beginPath();x.moveTo(0,815*sy);x.lineTo(w,815*sy);x.moveTo(1290*sx,0);x.lineTo(1290*sx,h);x.stroke();x.setLineDash([]);(V.buildings||[]).forEach(b=>{x.fillStyle=b.type==='shop'?'#996940':b.type==='school'?'#b7aa7f':b.type==='radio'?'#a86b60':b.type==='rural'?'#896345':'#ae9273';x.fillRect(b.x*sx,b.y*sy,b.w*sx,b.h*sy)});(V.historySpots||[]).forEach(o=>{x.fillStyle='#e0bc4d';x.beginPath();x.arc(o.x*sx,o.y*sy,7,0,Math.PI*2);x.fill()});(V.npcs||[]).forEach(n=>{x.fillStyle='#eee0b0';x.beginPath();x.arc(n.x*sx,n.y*sy,4,0,Math.PI*2);x.fill()});const s=ensure();x.fillStyle='#fff09b';x.beginPath();x.arc(s.x*sx,s.y*sy,7,0,Math.PI*2);x.fill();x.strokeStyle='#211a13';x.stroke();x.fillStyle='#211a13';x.font='bold 11px system-ui';x.fillText('VOS',s.x*sx+9,s.y*sy+4);x.fillText('AV. PRINCIPAL',8,700*sy-6);x.fillText('CALLE CENTRAL',1180*sx,18)}
function bag(){const s=ensure(),items=s.inventory;const html=items.length?items.map(i=>'<div class="v4p-card"><h3>'+esc(i)+'</h3><p>Objeto disponible para misiones o actividades.</p></div>').join(''):'<div class="v4p-card"><h3>MOCHILA VACÍA</h3><p>Comprá, encontrá o recibí objetos durante tus misiones.</p></div>';panel('MOCHILA','<div class="v4p-grid">'+html+'</div><p><b>Dinero:</b> $'+Math.round(s.money)+' · <b>Energía:</b> '+Math.round(s.energy)+'</p>')}
function missionsUI(){const s=ensure(),idx=s.mission,progress=Math.round(idx/(missions.length-1)*100);const cards=missions.map((m,i)=>'<div class="v4p-card"><h3>'+(i<idx?'✓ ':i===idx?'▶ ':'○ ')+esc(m.title)+'</h3><p>'+esc(m.objective)+'</p><p><b>Recompensa:</b> $'+m.reward+'</p></div>').join('');panel('CAMPAÑA HISTÓRICA · MISIONES','<p>La exploración se convierte en aprendizaje.</p><div class="v4p-progress"><i style="width:'+progress+'%"></i></div><p>'+idx+' / '+(missions.length-1)+' etapas completadas.</p><div class="v4p-card"><h3>ACTUAL · '+esc(mission().title)+'</h3><p>'+esc(mission().objective)+'</p><p><b>Pista:</b> '+esc(mission().hint)+'</p></div><div class="v4p-grid" style="margin-top:12px">'+cards+'</div>')}
function memoryUI(){const s=ensure(),cards=curiosities.map(c=>{const seen=!!s.flags['cur_'+c.id];return '<div class="v4p-card"><h3>'+esc(c.title)+(seen?' ✓':'')+'</h3><p>'+esc(c.text)+'</p><p class="v4p-source">'+esc(c.source)+'</p><button class="v4p-action" data-cur="'+c.id+'">'+(seen?'VOLVER A LEER':'DESCUBRIR')+'</button></div>'}).join('');const p=panel('MEMORIA VIVA · CURIOSIDADES','<div class="v4p-grid">'+cards+'</div>');p.querySelectorAll('[data-cur]').forEach(b=>b.onclick=()=>discover(b.dataset.cur))}
function discover(id){const c=curiosities.find(x=>x.id===id);if(!c)return;const s=ensure();s.flags['cur_'+id]=true;if(!s.history.includes(c.id))s.history.push(c.id);save();if(mission().id==='memoria')complete('memoria');panel('MEMORIA · '+c.title,'<div class="v4p-card"><h3>'+esc(c.title)+'</h3><p>'+esc(c.text)+'</p><p class="v4p-source">'+esc(c.source)+'</p></div><button class="v4p-action" id="v4MemoryBack">VOLVER A MEMORIA</button>');document.getElementById('v4MemoryBack').onclick=memoryUI}
function npcKind(n){const z=(String(n.id||'')+' '+String(n.name||'')+' '+String(n.label||'')).toLowerCase();if(/raul|raúl/.test(z))return'raul';if(/nico/.test(z))return'nico';if(/marta/.test(z))return'shop';if(/lucia|lucía/.test(z))return'plaza';return'default'}
function isShop(b){const z=(String(b?.id||'')+' '+String(b?.name||'')+' '+String(b?.label||'')+' '+String(b?.type||'')).toLowerCase();return /almacen|almacén|shop|comercio|panader/.test(z)}
function isRadio(b){const z=(String(b?.id||'')+' '+String(b?.name||'')+' '+String(b?.label||'')+' '+String(b?.type||'')).toLowerCase();return /radio|oasis/.test(z)}
function isRural(b){const z=(String(b?.id||'')+' '+String(b?.name||'')+' '+String(b?.label||'')+' '+String(b?.type||'')).toLowerCase();return /rural|galpon|galpón|chacra|campo|puesto/.test(z)}
function dialogue(n,kind,onComplete){const d=dialogues[kind||npcKind(n)]||dialogues.default;const p=panel('CONVERSACIÓN · '+d.name,'<div class="v4p-speaker">'+esc(d.name)+'</div><div id="v4pDialog" class="v4p-dialog">'+esc(d.lines[0])+'</div><div id="v4pChoices"></div><button id="v4pNext" class="v4p-action">SEGUIR</button>');ensure().dialogue=true;let i=0;const text=document.getElementById('v4pDialog');document.getElementById('v4pNext').onclick=()=>{i++;if(i<d.lines.length)text.textContent=d.lines[i];else{close();if(typeof onComplete==='function')onComplete()}};const choices=document.getElementById('v4pChoices');[['¿Qué puedo conocer?',()=>toast('Recorré el pueblo: el mapa y las misiones te van guiando.')],['¿Por qué importa la memoria?',()=>toast('Cada lugar, objeto y testimonio ayuda a reconstruir la historia.')]].forEach(([label,fn])=>{const b=document.createElement('button');b.className='v4p-action v4p-choice';b.textContent=label;b.onclick=fn;choices.appendChild(b)});const s=ensure();s.relationships[n.id||n.name]=(s.relationships[n.id||n.name]||0)+1;save()}
function shop(){const p=panel('ALMACÉN · EL ENCUENTRO','<div class="v4p-card"><h3>Productos</h3><p>Pan para el mandado · $120</p><button class="v4p-action" id="buyBread">COMPRAR PAN</button><p style="margin-top:12px">Yerba · $900</p><button class="v4p-action" id="buyYerba">COMPRAR YERBA</button></div>');document.getElementById('buyBread').onclick=()=>{const s=ensure();if(s.money<120){toast('No te alcanza para el pan.');return}s.money-=120;add('Pan');save();toast('PAN GUARDADO EN LA MOCHILA');if(mission().id==='mandado')complete('mandado');bag()};document.getElementById('buyYerba').onclick=()=>{const s=ensure();if(s.money<900){toast('No te alcanza para la yerba.');return}s.money-=900;add('Yerba');save();toast('YERBA GUARDADA EN LA MOCHILA')};}
function deliver(){if(!has('pan')){toast('Raúl espera el pan. Primero compralo en el almacén.');return}if(remove('pan')){save();complete('entrega');toast('ENTREGA REALIZADA A RAÚL')}}
function rural(){const s=ensure();if(s.energy<20){toast('Estás cansado. Descansá antes de trabajar.');return}s.energy-=20;s.money+=650;add('Cajón de cosecha');save();if(mission().id==='changa')complete('changa');toast('TAREA RURAL · +$650 · -20 ENERGÍA')}
function historySpot(o){const id=String(o.id||'');let cid=id==='origen'?'tratayen':id==='riego'?'agua':id==='vinos'?'vinos':id;const c=curiosities.find(x=>x.id===cid);if(c)discover(c.id);else memoryUI();return true}
function near(){const s=ensure();let best=null,bd=155;const arr=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[])];if(V.storyJob)arr.push(V.storyJob);arr.forEach(o=>{if(!Number.isFinite(o.x)||!Number.isFinite(o.y))return;const x=o.x+(o.w?o.w/2:0),y=o.y+(o.h?o.h/2:0),d=Math.hypot(s.x-x,s.y-y);if(d<bd){bd=d;best=o}});return best}
function plazaNear(){const s=ensure();return s.x>850&&s.x<1550&&s.y>520&&s.y<760}
function interact(){const s=ensure();if(!s.started)return true;if(s.dialogue){const next=document.getElementById('v4pNext');if(next){next.click();return true}return true}if(mission().id==='plaza'&&plazaNear()){const n=(V.npcs||[]).find(x=>Math.hypot(s.x-x.x,s.y-x.y)<220);if(n){dialogue(n,'plaza',()=>complete('plaza'));return true}toast('Estás en la plaza. Buscá a alguien para conversar.');return true}const o=near();if(!o){toast('No hay nada para interactuar cerca.');return true}if(V.historySpots?.includes(o))return historySpot(o);if(isShop(o))return shop();if(isRadio(o)){const n=(V.npcs||[]).find(x=>npcKind(x)==='nico'&&Math.hypot(o.x-x.x,o.y-x.y)<500);if(n&&mission().id==='radio')dialogue(n,'nico',()=>complete('radio'));else dialogue({name:'Radio Oasis'},'nico');return true}if(isRural(o)||o===V.storyJob)return rural();if(npcKind(o)==='raul')return dialogue(o,'raul',()=>{if(mission().id==='entrega')deliver()});if(npcKind(o)==='nico')return dialogue(o,'nico');if(o.id||o.name||o.label)return dialogue(o,'default',()=>{if(mission().id==='llegada')complete('llegada')});return true}
function installKeys(){if(G.keys)return;G.keys=true;document.addEventListener('keydown',e=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='escape'){if(G.open){e.preventDefault();e.stopImmediatePropagation();close()}return}if(G.open){if((k==='e'||k===' ')&&document.getElementById('v4pNext')){e.preventDefault();e.stopImmediatePropagation();document.getElementById('v4pNext').click()}return}if(k==='m'||k==='i'||k==='b'||k==='q'||k==='j'||k==='h'){e.preventDefault();e.stopImmediatePropagation();if(k==='m')map();else if(k==='i'||k==='b')bag();else if(k==='q'||k==='j')missionsUI();else memoryUI();return}if(k==='e'||k===' '){e.preventDefault();e.stopImmediatePropagation();interact()}},true)}
function boot(){load();css();ui();installKeys();V.story=V.story||{};V.story.version=4;V.story.missions=missions;V.story.interact=interact;V.story.saveV4=save;V.story.refresh=refreshMission;G.missions=missions;G.curiosities=curiosities;G.interact=interact;G.save=save;G.load=load;refreshMission()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();