/* Villa Pelón V4 — CAPA DE JUGABILIDAD REAL
   Unifica acceso a mapa, mochila, misiones, diálogos y curiosidades.
   No crea un segundo motor ni un segundo RAF. Intercepta controles antes
   de los sistemas heredados para que V4 sea la experiencia visible.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const G=V.v4Playability={version:4,open:null};
const KEY='villa_pelon_v4_playability';
const S=()=>V.state||{};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const missions=[
 ['Llegada','Hablá con un vecino.','Conversá con cualquier persona del pueblo.',150],
 ['Mandado','Comprá pan','Entrá al almacén y comprá pan.',250],
 ['Entrega','Ayudá a Raúl','Llevále el pan a Raúl.',300],
 ['Plaza','La vida del pueblo','Visitá la plaza y conversá con alguien.',180],
 ['Changa','Trabajo rural','Realizá una tarea en el galpón rural.',650],
 ['Memoria','Una historia del lugar','Descubrí una curiosidad histórica.',350],
 ['Radio','La voz del pueblo','Visitá Radio Oasis y hablá con Nico.',450],
 ['Mundo abierto','Ahora elegís vos','Explorá, trabajá, comprá, conversá y descubrí.',1000]
];
const curiosidades=[
 ['agua','El agua y el desierto','El riego transformó profundamente el paisaje productivo del valle.'],
 ['pelon','El pelón','El pelón forma parte de la identidad frutícola y productiva asociada a San Patricio del Chañar.'],
 ['vino','Viñedos en el desierto','El riego hizo posible desarrollar agricultura intensiva y vitivinicultura en un paisaje naturalmente árido.'],
 ['tratayen','Tratayen','La historia territorial de la zona es anterior al pueblo moderno y aparece en documentación y cartografía histórica.'],
 ['caminos','Los caminos del valle','Los caminos conectan viviendas, chacras, servicios y zonas productivas; también son parte de la vida cotidiana.']
];
function ensure(){const x=S();x.inventory=Array.isArray(x.inventory)?x.inventory:[];x.relationships=x.relationships||{};x.flags=x.flags||{};x.history=Array.isArray(x.history)?x.history:[];x.money=Number.isFinite(x.money)?x.money:10000;x.energy=Number.isFinite(x.energy)?x.energy:100;x.mission=Math.max(0,Math.min(missions.length-1,Number(x.mission)||0));return x}
function save(){const x=ensure();try{localStorage.setItem(KEY,JSON.stringify({inventory:x.inventory,relationships:x.relationships,flags:x.flags,history:x.history,money:x.money,energy:x.energy,mission:x.mission}))}catch(_){} }
function load(){const x=ensure();try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d&&typeof d==='object'){Object.assign(x,d);x.inventory=Array.isArray(x.inventory)?x.inventory:[];x.relationships=x.relationships||{};x.flags=x.flags||{};x.history=Array.isArray(x.history)?x.history:[]}}catch(_){} }
function css(){if(document.getElementById('v4PlayabilityCSS'))return;const z=document.createElement('style');z.id='v4PlayabilityCSS';z.textContent=`
.v4pbar{position:absolute;z-index:40;top:126px;right:14px;display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end;max-width:460px}.v4pbar button{background:rgba(31,27,21,.95);border:1px solid #a58752;border-radius:7px;color:#f1dba5;padding:8px 10px;font:700 11px system-ui;cursor:pointer}.v4pbar button:hover{background:#59462c}.v4ppanel{position:fixed;z-index:200;inset:4%;overflow:auto;background:#211c16;color:#eee3cf;border:1px solid #c7a45d;border-radius:14px;box-shadow:0 35px 100px #000}.v4phead{position:sticky;top:0;z-index:2;background:#30271e;border-bottom:1px solid #715c38;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}.v4phead b{color:#ebce81;letter-spacing:1px}.v4pbody{padding:18px}.v4pclose,.v4pbtn{background:#936a35;color:#fff;border:0;border-radius:7px;padding:8px 12px;font-weight:700;cursor:pointer}.v4pgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.v4pcard{background:#393026;border:1px solid #5e4e36;border-radius:9px;padding:13px}.v4pcard h3{color:#e6c676;margin:0 0 7px;font-size:14px}.v4pcard p{font-size:12px;line-height:1.5;color:#d9cfbd;margin:5px 0}.v4pmap{width:100%;height:min(70vh,680px);display:block;background:#a3946e;border-radius:9px}.v4pdial{font-size:18px;line-height:1.6;min-height:100px;padding:14px 0}.v4pname{color:#e9cb78;font-weight:800;letter-spacing:1px}.v4ptoast{position:fixed;z-index:220;right:15px;bottom:18px;max-width:370px;background:rgba(28,24,18,.96);border:1px solid #806b45;border-radius:8px;padding:11px 14px;color:#eee2c9;box-shadow:0 10px 30px #000}.v4plive{position:absolute;z-index:39;left:15px;bottom:80px;padding:7px 10px;background:rgba(28,24,18,.8);border:1px solid #65543a;border-radius:7px;color:#d8cfbd;font-size:11px}@media(max-width:700px){.v4pbar{top:118px;right:7px;max-width:300px}.v4pbar button{font-size:10px;padding:7px 8px}.v4ppanel{inset:2%}.v4plive{bottom:145px}}
`;document.head.appendChild(z)}
function bar(){if(document.getElementById('v4PlayBar'))return;const g=document.getElementById('game');if(!g)return;const b=document.createElement('div');b.id='v4PlayBar';b.className='v4pbar';b.innerHTML='<button data-p="map">MAPA</button><button data-p="bag">MOCHILA</button><button data-p="mis">MISIONES</button><button data-p="cur">CURIOSIDADES</button>';g.appendChild(b);b.querySelector('[data-p="map"]').onclick=map;b.querySelector('[data-p="bag"]').onclick=bag;b.querySelector('[data-p="mis"]').onclick=missionsUI;b.querySelector('[data-p="cur"]').onclick=curUI;const l=document.createElement('div');l.id='v4PlayLive';l.className='v4plive';g.appendChild(l);live()}
function live(){const l=document.getElementById('v4PlayLive'),x=ensure();if(l)l.innerHTML='MUNDO VIVO · <b>'+(['Mañana tranquila','Movimiento en comercios','Actividad escolar','Trabajo en chacras','Radio al aire','Tarde en la plaza','El pueblo baja el ritmo'][Math.floor(((x.minutes||480)/60)%24/4)])+'</b>'}
function toast(t){const d=document.createElement('div');d.className='v4ptoast';d.innerHTML=t;document.body.appendChild(d);setTimeout(()=>d.remove(),3500)}
function close(){document.getElementById('v4PlayPanel')?.remove();G.open=null;ensure().dialogue=false}
function panel(title,body){close();const p=document.createElement('div');p.id='v4PlayPanel';p.className='v4ppanel';p.innerHTML='<div class="v4phead"><b>'+esc(title)+'</b><button class="v4pclose">CERRAR</button></div><div class="v4pbody">'+body+'</div>';document.body.appendChild(p);p.querySelector('.v4pclose').onclick=close;G.open=p;return p}
function map(){const p=panel('MAPA · VILLA PELÓN','<canvas id="v4PlayMap" class="v4pmap"></canvas><p>● vos &nbsp; ● vecinos &nbsp; ■ edificios &nbsp; ◆ lugares de memoria</p>');const c=document.getElementById('v4PlayMap'),d=Math.min(devicePixelRatio||1,2);c.width=c.clientWidth*d;c.height=c.clientHeight*d;const x=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,world=V.world||{w:4200,h:2700},sx=w/world.w,sy=h/world.h;x.scale(d,d);x.fillStyle='#aa9a70';x.fillRect(0,0,w,h);x.fillStyle='#71805e';x.fillRect(0,0,w,h*.18);x.fillStyle='#c8b17d';x.fillRect(0,700*sy,w,230*sy);x.fillRect(1180*sx,0,220*sx,h);x.fillStyle='#dfd2a6';x.fillRect(0,782*sy,w,66*sy);x.fillRect(1256*sx,0,68*sx,h);x.strokeStyle='#79684e';x.lineWidth=2;x.setLineDash([12,9]);x.beginPath();x.moveTo(0,815*sy);x.lineTo(w,815*sy);x.moveTo(1290*sx,0);x.lineTo(1290*sx,h);x.stroke();x.setLineDash([]);(V.buildings||[]).forEach(b=>{x.fillStyle=b.type==='shop'?'#9c6e42':b.type==='school'?'#b6aa83':b.type==='radio'?'#a66d60':b.type==='rural'?'#8d6648':'#b39474';x.fillRect(b.x*sx,b.y*sy,b.w*sx,b.h*sy)});(V.historySpots||[]).forEach(o=>{x.fillStyle='#dfbd52';x.beginPath();x.arc(o.x*sx,o.y*sy,6,0,7);x.fill()});(V.npcs||[]).forEach(n=>{x.fillStyle='#eee0b0';x.beginPath();x.arc(n.x*sx,n.y*sy,4,0,7);x.fill()});const st=ensure();x.fillStyle='#fff09c';x.beginPath();x.arc(st.x*sx,st.y*sy,7,0,7);x.fill();x.strokeStyle='#201a13';x.stroke();x.fillStyle='#211a14';x.font='bold 11px system-ui';x.fillText('VOS',st.x*sx+9,st.y*sy+4);x.fillText('AV. PRINCIPAL',8,700*sy-6);x.fillText('CALLE CENTRAL',1185*sx,17)}
function bag(){const x=ensure(),items=x.inventory;const body=items.length?items.map(i=>'<div class="v4pcard"><h3>'+esc(i)+'</h3><p>Objeto guardado en tu mochila. Puede intervenir en encargos o actividades.</p></div>').join(''):'<div class="v4pcard"><h3>MOCHILA VACÍA</h3><p>Comprá, encontrá o recibí objetos para verla crecer.</p></div>';panel('MOCHILA','<div class="v4pgrid">'+body+'</div><p><b>Dinero:</b> $'+Math.round(x.money)+' · <b>Energía:</b> '+Math.round(x.energy)+'</p>')}
function missionsUI(){const x=ensure(),i=x.mission;panel('MISIONES','<div class="v4pcard"><h3>ACTUAL · '+esc(missions[i][0])+'</h3><p><b>Objetivo:</b> '+esc(missions[i][2])+'</p><p><b>Recompensa:</b> $'+missions[i][3]+'</p></div><div class="v4pgrid" style="margin-top:12px">'+missions.map((m,j)=>'<div class="v4pcard"><h3>'+(j<i?'✓ ':j===i?'▶ ':'○ ')+esc(m[1])+'</h3><p>'+esc(m[2])+'</p></div>').join('')+'</div>')}
function curUI(){const x=ensure(),body=curiosidades.map(q=>'<div class="v4pcard"><h3>'+esc(q[1])+(x.flags['cur_'+q[0]]?' ✓':'')+'</h3><p>'+esc(q[2])+'</p><button class="v4pbtn" data-cur="'+q[0]+'">DESCUBRIR</button></div>').join('');const p=panel('CURIOSIDADES · MEMORIA VIVA','<div class="v4pgrid">'+body+'</div>');p.querySelectorAll('[data-cur]').forEach(b=>b.onclick=()=>discover(b.dataset.cur))}
function discover(id){const q=curiosidades.find(a=>a[0]===id);if(!q)return;const x=ensure();x.flags['cur_'+id]=true;if(!x.history.includes(id))x.history.push(id);save();toast('<b>CURIOSIDAD DESCUBIERTA:</b> '+esc(q[1]));curUI();if(missions[x.mission][0]==='Memoria')complete()}
function dialogue(n){const x=ensure(),name=n.name||n.label||'VECINO',lines=n.lines?.length?n.lines:['Buen día. ¿Cómo andás?'];let i=0;const p=panel('CONVERSACIÓN','<div class="v4pname">'+esc(name)+'</div><div id="v4PlayText" class="v4pdial">'+esc(lines[0])+'</div><button id="v4PlayNext" class="v4pbtn">SEGUIR</button><div class="v4pgrid" style="margin-top:14px"><button id="v4Ask" class="v4pbtn">¿QUÉ HAY PARA HACER?</button><button id="v4Ask2" class="v4pbtn">¿CÓMO ES VIVIR ACÁ?</button></div>');x.dialogue=true;x.relationships[n.id]=(x.relationships[n.id]||0)+1;save();if(missions[x.mission][0]==='Llegada')complete();p.querySelector('#v4Ask').onclick=()=>toast('Podés caminar, comprar, trabajar, explorar y conocer gente.');p.querySelector('#v4Ask2').onclick=()=>toast('Volvé a distintas horas: las personas cambian de actividad durante el día.');p.querySelector('#v4PlayNext').onclick=()=>{i++;if(i<lines.length)p.querySelector('#v4PlayText').textContent=lines[i];else close()}}
function complete(){const x=ensure(),m=missions[x.mission];if(!m||x.flags['mission_done_'+x.mission])return;x.flags['mission_done_'+x.mission]=true;x.money+=m[3];x.mission=Math.min(missions.length-1,x.mission+1);save();toast('<b>MISIÓN COMPLETADA:</b> '+esc(m[1])+' · +$'+m[3])}
function buy(){const x=ensure();if(x.money<120){toast('No tenés suficiente dinero.');return}x.money-=120;if(!x.inventory.includes('Pan'))x.inventory.push('Pan');x.flags.bread=true;save();toast('<b>COMPRA:</b> Pan guardado en la mochila.');if(missions[x.mission][0]==='Comprá pan')complete()}
function store(){const p=panel('ALMACÉN EL ENCUENTRO','<div class="v4pcard"><h3>COMPRAS</h3><p>Pan, yerba y productos para la vida cotidiana.</p><button id="v4Buy" class="v4pbtn">COMPRAR PAN · $120</button> <button id="v4Yerba" class="v4pbtn">COMPRAR YERBA · $180</button></div>');p.querySelector('#v4Buy').onclick=buy;p.querySelector('#v4Yerba').onclick=()=>{const x=ensure();if(x.money<180){toast('No te alcanza.');return}x.money-=180;if(!x.inventory.includes('Yerba'))x.inventory.push('Yerba');save();toast('Yerba guardada en la mochila.')}}
function work(){const x=ensure();if(x.energy<20){dialogue({label:'CHACRA',lines:['Estás cansado. Descansá y volvé más tarde.']});return}x.energy-=20;x.money+=650;if(!x.inventory.includes('Cajón de cosecha'))x.inventory.push('Cajón de cosecha');save();toast('<b>TRABAJO:</b> +$650 · -20 energía');if(missions[x.mission][0]==='Trabajo rural')complete()}
function interact(){const x=ensure();if(!x.started)return true;if(G.open)return true;const n=V.engine?.nearest?.()||near();if(!n)return true;if(V.npcs?.includes(n)){dialogue(n);return true}if(n.type==='shop'){store();return true}if(n.id==='job'){work();return true}if(n.type==='rural'){work();return true}if(n.type==='home'){x.energy=Math.min(100,x.energy+35);x.minutes+=30;save();toast('Descansaste. Energía recuperada.');return true}if(n.type==='radio'){dialogue({label:n.label,lines:['La radio conecta a los vecinos. Siempre aparece una historia nueva.']});if(missions[x.mission][0]==='La voz del pueblo')complete();return true}if(n.type==='school'){dialogue({label:n.label,lines:['La escuela guarda dibujos, cuadernos y recuerdos de muchas generaciones.']});return true}return true}
function near(){const x=ensure(),arr=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[]),V.storyJob].filter(Boolean);let b=null,d0=170;arr.forEach(o=>{const d=Math.hypot(x.x-(o.x+(o.w||0)/2),x.y-(o.y+(o.h||0)/2));if(d<d0){d0=d;b=o}});return b}
function keyboard(){document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='m'){e.preventDefault();e.stopImmediatePropagation();map()}else if(k==='i'||k==='b'){e.preventDefault();e.stopImmediatePropagation();bag()}else if(k==='q'||k==='j'){e.preventDefault();e.stopImmediatePropagation();missionsUI()}else if(k==='h'){e.preventDefault();e.stopImmediatePropagation();curUI()}else if(k==='escape'&&G.open){e.preventDefault();e.stopImmediatePropagation();close()}else if((k==='e'||k===' ')&&!G.open){e.preventDefault();e.stopImmediatePropagation();interact()}},{capture:true});const b=document.getElementById('interact');if(b)b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(G.open)close();else interact()},{capture:true})}
function boot(){load();css();bar();keyboard();G.interact=interact;G.map=map;G.bag=bag;G.missions=missionsUI;G.curiosities=curUI;setInterval(()=>{if(ensure().started)live()},10000)}
boot();
})();