/* Villa Pelón V4 — MENU / SETTINGS / AUDIO / LANGUAGE
   UI shell only: no second game loop. Procedural music uses Web Audio after user gesture.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const KEY='villa_pelon_v4_settings';
const defaults={language:'es',music:true,volume:.28,controls:'joystick',quality:'high'};
let settings={...defaults};
try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(settings))}catch(_){};document.documentElement.dataset.lang=settings.language;document.documentElement.dataset.controls=settings.controls};
let audio=null;
function audioStart(){if(!settings.music)return;if(audio?.ctx){if(audio.ctx.state==='suspended')audio.ctx.resume();return}try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),master=ctx.createGain();master.gain.value=settings.volume;master.connect(ctx.destination);const notes=[196,220,261.63,293.66,329.63,293.66,261.63,220];let step=0;const play=()=>{if(!settings.music)return;const o=ctx.createOscillator(),g=ctx.createGain(),f=notes[step++%notes.length];o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(.12,ctx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.5);o.connect(g);g.connect(master);o.start();o.stop(ctx.currentTime+1.55)};play();audio={ctx,master,timer:setInterval(play,1500)}}catch(_){}
}
function audioStop(){if(!audio)return;clearInterval(audio.timer);try{audio.master.gain.setTargetAtTime(0,audio.ctx.currentTime,.05)}catch(_){}audio=null}
function audioApply(){if(!settings.music){audioStop();return}if(audio?.master)audio.master.gain.value=settings.volume}
function t(key){const d={es:{play:'JUGAR',menu:'MENÚ',settings:'CONFIGURACIÓN',language:'IDIOMA',music:'MÚSICA',controls:'CONTROLES',joystick:'JOYSTICK',arrows:'FLECHAS',volume:'VOLUMEN',quality:'GRÁFICOS',high:'ALTO',low:'AHORRO',back:'VOLVER',resume:'CONTINUAR',newgame:'NUEVA PARTIDA',on:'ACTIVADA',off:'DESACTIVADA',spanish:'ESPAÑOL',english:'ENGLISH',portuguese:'PORTUGUÊS'},en:{play:'PLAY',menu:'MENU',settings:'SETTINGS',language:'LANGUAGE',music:'MUSIC',controls:'CONTROLS',joystick:'JOYSTICK',arrows:'ARROWS',volume:'VOLUME',quality:'GRAPHICS',high:'HIGH',low:'BATTERY',back:'BACK',resume:'RESUME',newgame:'NEW GAME',on:'ON',off:'OFF',spanish:'ESPAÑOL',english:'ENGLISH',portuguese:'PORTUGUÊS'},pt:{play:'JOGAR',menu:'MENU',settings:'CONFIGURAÇÕES',language:'IDIOMA',music:'MÚSICA',controls:'CONTROLES',joystick:'JOYSTICK',arrows:'SETAS',volume:'VOLUME',quality:'GRÁFICOS',high:'ALTO',low:'ECONOMIA',back:'VOLTAR',resume:'CONTINUAR',newgame:'NOVO JOGO',on:'ATIVADA',off:'DESATIVADA',spanish:'ESPAÑOL',english:'ENGLISH',portuguese:'PORTUGUÊS'}};return (d[settings.language]||d.es)[key]||key}
function css(){if(document.getElementById('v4UIAudioCSS'))return;const s=document.createElement('style');s.id='v4UIAudioCSS';s.textContent=`#v4MainMenu{position:absolute;z-index:120;right:14px;top:14px;display:flex;gap:7px;flex-direction:column}#v4MainMenu button{min-width:92px;min-height:44px;padding:9px 12px;background:#2d241b;color:#f0d28b;border:2px solid #8b6b3e;box-shadow:3px 3px 0 #15100c;font:800 11px monospace}#v4Pause{position:fixed;inset:0;z-index:1500;background:rgba(19,14,10,.78);display:none;align-items:center;justify-content:center;padding:18px}.v4MenuCard{width:min(94vw,520px);max-height:90vh;overflow:auto;background:#2a211a;border:4px solid #9c7943;box-shadow:8px 8px 0 #120d09;padding:20px;color:#eee0bf;font-family:monospace}.v4MenuCard h2{color:#edcc7e;margin:0 0 18px;font-size:22px;letter-spacing:2px}.v4MenuRow{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid #58462f}.v4MenuRow button,.v4MenuCard>button{background:#b98b43;color:#21180f;border:2px solid #6b4b25;padding:10px 13px;min-height:44px;font-weight:900;font-family:monospace}.v4Range{width:180px;accent-color:#c79b50}.v4Lang{display:flex;gap:6px;flex-wrap:wrap}.v4Lang button.active{outline:3px solid #eed28b}.v4Controls{display:flex;gap:6px}.v4Controls button.active{background:#e0b75f}@media(max-width:700px){#v4MainMenu{top:62px;right:7px;flex-direction:row}#v4MainMenu button{min-width:52px;font-size:9px;padding:7px}.v4MenuCard{padding:15px}.v4MenuRow{grid-template-columns:1fr}.v4Range{width:100%}}`;
document.head.appendChild(s)}
function applyControls(){document.body.classList.toggle('v4-arrows',settings.controls==='arrows');document.body.classList.toggle('v4-joystick',settings.controls==='joystick');document.body.classList.toggle('v4-lowquality',settings.quality==='low');document.documentElement.lang=settings.language==='pt'?'pt':settings.language;save()}
function settingsPanel(){const p=document.getElementById('v4Pause');if(!p)return;p.querySelector('.v4MenuCard').innerHTML=`<h2>${t('settings')}</h2><div class="v4MenuRow"><span>${t('language')}</span><div class="v4Lang"><button data-l="es" class="${settings.language==='es'?'active':''}">${t('spanish')}</button><button data-l="en" class="${settings.language==='en'?'active':''}">${t('english')}</button><button data-l="pt" class="${settings.language==='pt'?'active':''}">${t('portuguese')}</button></div></div><div class="v4MenuRow"><span>${t('music')} · <b>${settings.music?t('on'):t('off')}</b></span><button id="v4Music">${settings.music?t('off'):t('on')}</button></div><div class="v4MenuRow"><span>${t('volume')}</span><input id="v4Vol" class="v4Range" type="range" min="0" max="100" value="${Math.round(settings.volume*100)}"></div><div class="v4MenuRow"><span>${t('controls')}</span><div class="v4Controls"><button data-c="joystick" class="${settings.controls==='joystick'?'active':''}">${t('joystick')}</button><button data-c="arrows" class="${settings.controls==='arrows'?'active':''}">${t('arrows')}</button></div></div><div class="v4MenuRow"><span>${t('quality')}</span><div class="v4Controls"><button data-q="high" class="${settings.quality==='high'?'active':''}">${t('high')}</button><button data-q="low" class="${settings.quality==='low'?'active':''}">${t('low')}</button></div></div><button id="v4Back">${t('back')}</button>`;
p.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{settings.language=b.dataset.l;save();settingsPanel()});p.querySelector('#v4Music').onclick=()=>{settings.music=!settings.music;save();audioApply();settingsPanel()};p.querySelector('#v4Vol').oninput=e=>{settings.volume=Number(e.target.value)/100;save();audioApply()};p.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{settings.controls=b.dataset.c;applyControls();settingsPanel()});p.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{settings.quality=b.dataset.q;applyControls();settingsPanel()});p.querySelector('#v4Back').onclick=menuPanel}
function menuPanel(){const p=document.getElementById('v4Pause');if(!p)return;p.style.display='flex';p.querySelector('.v4MenuCard').innerHTML=`<h2>VILLA PELÓN</h2><button id="v4Resume">${t('resume')}</button><button id="v4Settings" style="margin-left:7px">${t('settings')}</button><button id="v4New" style="margin-left:7px">${t('newgame')}</button>`;p.querySelector('#v4Resume').onclick=()=>p.style.display='none';p.querySelector('#v4Settings').onclick=settingsPanel;p.querySelector('#v4New').onclick=()=>{try{localStorage.removeItem('villa_pelon_v4_save');localStorage.removeItem('villa_pelon_v4_player');localStorage.removeItem('villa_pelon_v4_world')}catch(_){}location.reload()}}
function boot(){css();save();applyControls();const game=document.getElementById('game');if(!game)return;const pause=document.createElement('div');pause.id='v4Pause';pause.innerHTML='<div class="v4MenuCard"></div>';document.body.appendChild(pause);const top=document.createElement('div');top.id='v4MainMenu';top.innerHTML='<button id="v4MenuBtn">MENU</button><button id="v4SettingsBtn">⚙</button>';game.appendChild(top);document.getElementById('v4MenuBtn').onclick=menuPanel;document.getElementById('v4SettingsBtn').onclick=settingsPanel;document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(pause.style.display==='flex')pause.style.display='none';else menuPanel()}});document.getElementById('startBtn')?.addEventListener('pointerdown',audioStart,{passive:true});document.getElementById('startBtn')?.addEventListener('click',audioStart);document.getElementById('v4MenuBtn').addEventListener('pointerdown',audioStart,{passive:true});document.getElementById('v4SettingsBtn').addEventListener('pointerdown',audioStart,{passive:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
V.ui={version:4,settings,audioStart,openMenu:menuPanel};
})();
