/* Villa Pelón V6.39 — PRESENTACIÓN DE INTERACCIÓN
   El núcleo V6.37 es la única autoridad de input e interacción.
   Este módulo solo aporta presentación contextual para NPC y refresco UI.
   No RAF, no intervalos, no listeners duplicados, no puente hacia V4.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const B=V.v5Interaction=V.v5Interaction||{version:3,ready:false,authority:'v6_game_core'};
const state=()=>V.state||{};const dlg=()=>document.getElementById('dialogue');
function findNpc(){const s=state();let best=null,bd=155;for(const n of V.npcs||[]){const d=Math.hypot(s.x-n.x,s.y-n.y);if(d<bd){bd=d;best=n}}return best}
function point(n){const c=V.camera||state(),z=Number(c.zoom)||.82;return{x:innerWidth/2+(n.x-c.x)*z,y:innerHeight/2+(n.y-c.y)*z-58*z}}
function style(){if(document.getElementById('v5BridgeCSS'))return;const s=document.createElement('style');s.id='v5BridgeCSS';s.textContent=`#dialogue.v5-bubble{position:fixed;z-index:1800;width:min(292px,calc(100vw - 22px));padding:0;background:#fff;color:#171717;border:3px solid #171717;border-radius:7px;box-shadow:5px 5px 0 rgba(0,0,0,.28);transform:translate(-50%,-100%);overflow:visible;pointer-events:auto;font-family:monospace}#dialogue.v5-bubble:after{content:"";position:absolute;left:50%;bottom:-13px;width:18px;height:18px;background:#fff;border-right:3px solid #171717;border-bottom:3px solid #171717;transform:translateX(-50%) rotate(45deg)}#dialogue.v5-bubble #speaker{padding:7px 10px 2px;font:900 11px monospace;color:#171717;text-transform:uppercase}#dialogue.v5-bubble #dialogueText{padding:2px 11px 9px;font:500 14px/1.35 system-ui,sans-serif;min-height:0}#dialogue.v5-bubble #dialogueNext{display:block;margin:0 8px 8px auto;padding:4px 8px;background:#f4f4f4;color:#111;border:2px solid #222;border-radius:3px;font:900 10px monospace;cursor:pointer}#v5-interact-prompt{position:fixed;z-index:1790;transform:translate(-50%,-100%);padding:3px 7px;background:#fff;color:#111;border:2px solid #111;border-radius:4px;box-shadow:3px 3px 0 rgba(0,0,0,.2);font:900 10px monospace;pointer-events:none;white-space:nowrap}@media(max-width:600px){#dialogue.v5-bubble{width:min(250px,calc(100vw - 18px))}#dialogue.v5-bubble #dialogueText{font-size:13px}}`;document.head.appendChild(s)}
function showNpc(n){const b=dlg();if(!b||!n)return false;const lines=Array.isArray(n.lines)&&n.lines.length?n.lines:['Buen día. ¿Cómo andás?'];b.classList.remove('hidden');b.classList.add('v5-bubble');b.dataset.lines=JSON.stringify(lines);b.dataset.index='0';b.dataset.npc=n.id||n.name;const sp=document.getElementById('speaker'),tx=document.getElementById('dialogueText'),src=document.getElementById('sourceLink');if(sp)sp.textContent=n.name||'Vecino';if(tx)tx.textContent=lines[0];if(src)src.classList.add('hidden');state().dialogue=true;position();return true}
function position(){const b=dlg(),id=b?.dataset?.npc;if(!b||b.classList.contains('hidden'))return;const n=(V.npcs||[]).find(x=>String(x.id)===String(id))||findNpc();if(!n)return;const p=point(n),w=Math.min(292,innerWidth-22),x=Math.max(w/2+8,Math.min(innerWidth-w/2-8,p.x)),y=Math.max(86,Math.min(innerHeight-22,p.y));b.style.left=x+'px';b.style.top=y+'px'}
function close(){const b=dlg();if(b)b.classList.remove('v5-bubble');state().dialogue=false;const p=document.getElementById('v5-interact-prompt');if(p)p.style.display='none'}
function next(){const b=dlg();if(!b||!state().dialogue)return;let lines=[];try{lines=JSON.parse(b.dataset.lines||'[]')}catch(_){}const i=Number(b.dataset.index||0)+1;if(i<lines.length){b.dataset.index=i;const t=document.getElementById('dialogueText');if(t)t.textContent=lines[i];position()}else{close();b.classList.add('hidden')}}
function refresh(){const p=document.getElementById('v5-interact-prompt');if(!p){const g=document.getElementById('game');if(!g)return;const n=document.createElement('div');n.id='v5-interact-prompt';g.appendChild(n)}const el=document.getElementById('v5-interact-prompt');if(state().dialogue){el.style.display='none';return}const n=findNpc();if(!n){el.style.display='none';return}const q=point(n);el.textContent='E  HABLAR · '+n.name;el.style.left=Math.max(70,Math.min(innerWidth-70,q.x))+'px';el.style.top=Math.max(42,Math.min(innerHeight-16,q.y))+'px';el.style.display='block'}
function init(){style();const nextBtn=document.getElementById('dialogueNext');if(nextBtn)nextBtn.onclick=e=>{e.preventDefault();next()};addEventListener('resize',position,{passive:true});B.showNpc=showNpc;B.next=next;B.close=close;B.refresh=refresh;B.ready=true;refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
