/* Villa Pelón V6.31 — POBLACIÓN + RUTINAS + LUGARES VIVOS
   Autoridad única de población. Los habitantes tienen estados explícitos,
   permanencia contextual, llegadas seguras y actividades visibles.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const D=V.worldLifeDeep=V.worldLifeDeep||{};Object.assign(D,{version:11,enabled:true,events:D.events||[],services:D.services||{},economy:D.economy||{},ticks:D.ticks||0,population:D.population||[],workersAtField:D.workersAtField||[],occupancy:D.occupancy||{}});
const hour=()=>((V.state?.minutes??480)/60)%24,day=()=>V.state?.day||1,minute=()=>Number(V.state?.minutes??480)%1440,now=()=>performance.now();const parcels=()=>V.agriculturalCycle?.parcels||[];
const home=p=>p.home&&Number.isFinite(p.home.x)&&Number.isFinite(p.home.y)?p.home:{x:Number.isFinite(p.homeX)?p.homeX:1200,y:Number.isFinite(p.homeY)?p.homeY:620};
function allPeople(){const seen=new Set(),out=[];for(const p of [...(V.life?.ambient||[]),...(V.life?.workers||[]),...(V.npcs||[])]){if(!p||!p.id||seen.has(p.id))continue;seen.add(p.id);out.push(p)}D.population=out;return out}
function movers(){return allPeople().filter(p=>p&&!p._v65Hidden)}
function roleKey(p){const r=String(p.role||'vecino').toLowerCase();if(r.includes('estud'))return'estudiante';if(r.includes('trab')||r==='rural'||r.includes('tractor'))return'trabajador';if(r.includes('repart'))return'repartidor';return r.includes('vecina')?'vecina':'vecino'}
const routes={estudiante:[['06:30','casa'],['07:30','escuela'],['13:30','plaza'],['17:30','casa'],['19:00','plaza'],['21:00','casa']],vecina:[['07:00','casa'],['08:00','almacen'],['10:00','plaza'],['12:00','casa'],['16:00','almacen'],['18:00','plaza'],['21:00','casa']],vecino:[['07:00','casa'],['09:00','almacen'],['12:00','casa'],['16:00','plaza'],['18:00','plaza'],['21:00','casa']],trabajador:[['06:00','casa'],['07:00','chacra'],['12:30','casa'],['15:00','chacra'],['19:00','plaza'],['21:30','casa']],repartidor:[['07:00','casa'],['08:00','almacen'],['10:00','radio'],['12:00','plaza'],['14:00','almacen'],['18:00','radio'],['21:00','casa']]};
function workerParcel(p){const ps=parcels();if(!ps.length)return null;const explicit=ps.find(q=>q.worker&&String(q.worker).toLowerCase()===String(p.name||'').toLowerCase());return explicit||ps[(Number(String(p.id).replace(/\D/g,''))||0)%ps.length]}
function buildingForPlace(place){const bs=V.buildingSystem?.buildings||[];const wanted={almacen:['shop','comercio'],escuela:['school','escuela'],radio:['radio'],chacra:['rural','galpon']};const keys=wanted[place]||[];return bs.find(b=>keys.some(k=>String(b.type||'').toLowerCase().includes(k)||String(b.function||'').toLowerCase().includes(k)))||null}
function plazaTarget(){const nodes=V.urbanFabric?.publicNodes;if(Array.isArray(nodes)&&nodes.length)return nodes[Math.abs((Number(day())||1)-1)%nodes.length];const xs=V.streetSystem?.intersections||[];for(const p of xs){const a=V.streetSystem?.roadById?.[p.a],b=V.streetSystem?.roadById?.[p.b];if(a&&(a.kind==='urban'||a.kind==='urban-edge')&&b&&(b.kind==='urban'||b.kind==='urban-edge'))return{x:p.x,y:p.y,place:'plaza'}}return{x:1200,y:760,place:'plaza'}}
function scheduleFor(p){const m=minute(),list=routes[roleKey(p)]||routes.vecino;let place='casa';for(const r of list)if(m>=Number(r[0].split(':')[0])*60+Number(r[0].split(':')[1]))place=r[1];const parcel=place==='chacra'?workerParcel(p):null;if(parcel)return{place,parcel,target:{x:parcel.x+parcel.w*.12,y:parcel.y+parcel.h*.5,place:'chacra'}};if(place==='casa')return{place,target:{...home(p),place}};if(place==='plaza')return{place,target:plazaTarget()};const b=buildingForPlace(place);if(b)return{place,target:{x:b.door.x,y:b.door.y,place,building:b.id}};return{place,target:{...home(p),place:'casa'}}}
function setState(p,state,reason){p.lifeState=state;p.lifeStateReason=reason||p.lifeStateReason||'';p.lifeStateSince=now();}
function moveTo(p,t,dt){const nav=V.territorialNavigation;if(nav?.move){const moved=nav.move(p,t,dt,Number(p.age)<18?42:58);p.lifeMoving=!!moved;if(moved){setState(p,'walking','hacia '+(t.place||'destino'));return true}return false}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);if(d<=24){p.lifeMoving=false;return false}const step=Math.min(d,(Number(p.age)<18?42:58)*dt);p.x+=dx/d*step;p.y+=dy/d*step;p.lifeMoving=true;return true}
function isOpen(b){const h=((hour()%24)+24)%24,a=b.openingHours||[0,24];return a[0]<=a[1]?h>=a[0]&&h<a[1]:h>=a[0]||h<a[1]}
function arriveOrWork(p,s){const target=s.target,d=Math.hypot(target.x-p.x,target.y-p.y);if(d>42){if(p.lifeState!=='walking')setState(p,'walking','en ruta');p.lifeInside=false;p.lifeBuildingId=null;return false}if(s.place==='casa'){setState(p,'home','en casa');p.lifeInside=false;p.lifeBuildingId=null;p.lifeRoom='casa';p.lifeAt='casa';return true}if(s.place==='plaza'){setState(p,'social','en espacio publico');p.lifeInside=false;p.lifeBuildingId=null;p.lifeRoom='plaza';p.lifeAt='plaza';return true}const b=s.target?.building?V.buildingSystem?.byId?.get(s.target.building):buildingForPlace(s.place);if(!b||!isOpen(b)){setState(p,'waiting','lugar cerrado');p.lifeInside=false;p.lifeBuildingId=null;p.lifeRoom=null;p.lifeAt=s.place;return false}p.lifeInside=true;p.lifeBuildingId=b.id;const rooms=b.interior?.rooms||['interior'];const slot=Math.floor((Number(String(p.id).replace(/\D/g,''))||0)+Math.floor(D.ticks/90));p.lifeRoom=rooms[Math.abs(slot)%rooms.length];p.lifeActivity=b.activity;p.lifeAt=s.place;setState(p,s.place==='chacra'?'working':'inside',b.label);return true}
function dwell(p,s,dt){if(p.lifeDestinationKey!==s.place+(s.target?.building||s.parcel?.id||'')||p.lifeTargetChanged){p.lifeDestinationKey=s.place+(s.target?.building||s.parcel?.id||'');p.lifeDwellUntil=0;p.lifeTargetChanged=false}
 const state=p.lifeState;const base=state==='home'?55:state==='social'?70:state==='working'?95:state==='inside'?75:state==='waiting'?18:0;const until=p.lifeDwellUntil||0;if(until<=now()&&state!=='walking'){const jitter=((Number(String(p.id).replace(/\D/g,''))||1)%17)*2;p.lifeDwellUntil=now()+(base+jitter)*1000}if(state!=='walking'&&p.lifeDwellUntil>now()){p.lifeMoving=false;p.moving=false;p.lifeDwellProgress=Math.max(0,1-(p.lifeDwellUntil-now())/((base+1)*1000));if(state==='social'){p.lifeActivity='conversando';}else if(state==='working'){p.lifeActivity='trabajando';}else if(state==='home'){p.lifeActivity='vida doméstica';}return true}return false}
function routines(dt){D.occupancy={};const working=[];for(const p of movers()){if(!(p.home||p.homeX||p.homeY))p.home={x:p.x,y:p.y};const s=scheduleFor(p);const newKey=s.place+(s.target?.building||s.parcel?.id||'');if(p.lifeDestinationKey&&p.lifeDestinationKey!==newKey){p.lifeTargetChanged=true;setState(p,'walking','nuevo horario')}p.lifeTarget=s.place;p.lifeDestination=s;p.lifeScheduleRole=roleKey(p);p.lifeParcelId=s.parcel?.id||null;
 if(p.lifeState!=='walking'&&!dwell(p,s,dt)){moveTo(p,s.target,dt)}else if(p.lifeState==='walking')moveTo(p,s.target,dt);
 const arrived=arriveOrWork(p,s);if(arrived)dwell(p,s,dt);const atField=!!s.parcel&&Math.hypot(p.x-s.target.x,p.y-s.target.y)<42&&p.lifeState==='working';if(atField)working.push({person:p,parcel:s.parcel});
 p.needs=p.needs||{social:45,rest:25,work:0,food:25};p.needs.social=Math.min(100,p.needs.social+dt*(p.lifeAt==='plaza'?-0.8:.11));p.needs.rest=Math.min(100,p.needs.rest+dt*(p.lifeAt==='casa'?-0.7:.09));p.needs.food=Math.min(100,p.needs.food+dt*.035);p.needs.work=atField?Math.min(100,(p.needs.work||0)+dt*.65):Math.max(0,(p.needs.work||0)-dt*.18);p.lifeMood=p.needs.social<20?'necesita compañía':p.needs.food>75?'tiene hambre':p.needs.rest>82?'cansado':p.needs.work>80?'agotado':p.lifeState==='working'?'trabajando':p.lifeState==='social'?'de paseo':p.lifeState==='home'?'en casa':p.lifeState==='inside'?'ocupado':'en camino';}
 D.workersAtField=working;for(const p of parcels())p.workerActivity=working.filter(w=>w.parcel.id===p.id).length;V.buildingSystem?.syncPopulation?.()}
function social(dt){const ps=allPeople().filter(p=>!p._v65Hidden&&p.lifeState==='social');for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j];if(Math.hypot(a.x-b.x,a.y-b.y)<90){a.social=a.social||{};b.social=b.social||{};a.social[b.id]=(a.social[b.id]||0)+dt*.1;b.social[a.id]=(b.social[a.id]||0)+dt*.1;if(!a.talking&&Math.random()<dt*.055){a.talking=b.talking=true;D.events.push({x:(a.x+b.x)/2,y:(a.y+b.y)/2,text:a.name+' conversa con '+b.name,ttl:6,type:'social'})}}else{if(Math.random()<dt*.02){a.talking=false;b.talking=false}}}}
function services(){const h=hour();D.services={almacen:h>=8&&h<20,escuela:h>=7&&h<18,radio:h>=10&&h<22,galpon:h>=7&&h<19,plaza:true,transporte:h>=6&&h<23}}
function economy(){const h=hour(),workers=D.workersAtField?.length||0;D.economy={clientes:h>=8&&h<20?Math.round(5+allPeople().length*.3):0,trabajadores:workers,produccion:workers?Math.round(workers*12):0,radioAudiencia:h>=10&&h<22?Math.round(allPeople().length*.7):0,comercio:D.services.almacen?'activo':'cerrado'}}
const pool=[{name:'feria',text:'Feria y movimiento en la plaza',days:[5,6],a:16,b:20},{name:'club',text:'Entrenamiento en el club',days:[2,4],a:18,b:21},{name:'radio',text:'Vecinos visitan la radio',days:[1,3,5],a:10,b:13},{name:'cosecha',text:'Jornada de cosecha en las chacras',days:[1,2,3,4,5,6],a:8,b:12}];
function eventTarget(name){if(name==='club'){const b=V.buildingSystem?.buildings?.find(x=>x.type==='sports');return b?{x:b.door.x,y:b.door.y}:null}if(name==='radio'){const b=buildingForPlace('radio');return b?{x:b.door.x,y:b.door.y}:null}if(name==='cosecha'){const p=parcels()[0];return p?{x:p.x+p.w*.5,y:p.y+p.h*.5}:null}return plazaTarget()}
function events(dt){const h=hour(),d=((day()-1)%7)+1;D.events=D.events.filter(e=>(e.ttl-=dt)>0);pool.forEach(e=>{if(e.days.includes(d)&&h>=e.a&&h<e.b&&!D.events.some(x=>x.name===e.name)){const t=eventTarget(e.name);D.events.push({...e,...(t||{}),ttl:Math.min(18,(e.b-h)*60),type:'scheduled'})}})}
function weather(){const w=V.life?.weather||'despejado';D.environment={weather:w,temperature:V.life?.temperature??19,night:hour()<7||hour()>=21,activity:w==='lluvia'?.7:w==='viento'?.85:1}}
function save(){try{localStorage.setItem('villa_pelon_life_deep',JSON.stringify({version:11,people:allPeople().map(p=>({id:p.id,social:p.social,needs:p.needs,lifeParcelId:p.lifeParcelId,home:p.home,lifeBuildingId:p.lifeBuildingId,lifeInside:p.lifeInside,lifeRoom:p.lifeRoom,lifeTarget:p.lifeTarget,lifeState:p.lifeState,lifeStateSince:p.lifeStateSince,lifeActivity:p.lifeActivity}))}))}catch(_){} }
function load(){try{const s=JSON.parse(localStorage.getItem('villa_pelon_life_deep')||'null');allPeople().forEach(p=>{const q=s?.people?.find(x=>x.id===p.id);if(q){p.social=q.social||{};p.needs=q.needs||p.needs;p.lifeParcelId=q.lifeParcelId||null;p.home=q.home||p.home;p.lifeBuildingId=q.lifeBuildingId||null;p.lifeInside=!!q.lifeInside;p.lifeRoom=q.lifeRoom||null;p.lifeTarget=q.lifeTarget||null;p.lifeState=q.lifeState||'idle';p.lifeStateSince=q.lifeStateSince||now();p.lifeActivity=q.lifeActivity||null}})}catch(_){} }
function hookLife(){if(D._lifeHook||!V.life?.update)return;const old=V.life.update;V.life.update=function(dt,minutes){const result=old.apply(this,arguments);if(V.state?.started){routines(dt);social(dt);services();economy();events(dt);weather();D.ticks++;if(D.ticks%120===0)save()}return result};D._lifeHook=true;D._baseLifeUpdate=old;load()}
hookLife();
V.population={state:D,people:allPeople,find:id=>allPeople().find(p=>p.id===id),movers,workerParcel,workers:()=>D.workersAtField||[],schedule:scheduleFor,getServices:()=>D.services,getEconomy:()=>D.economy,getEvents:()=>D.events,getOccupancy:()=>D.occupancy};
V.worldLifeAPI={state:D,people:allPeople,find:V.population.find,target:scheduleFor,getServices:()=>D.services,getEconomy:()=>D.economy,getEvents:()=>D.events,getOccupancy:()=>D.occupancy};
D.features=['unified-population','all-npc-movers','schedule-driven-movement','physical-territorial-navigation','place-aware-schedules','building-door-arrival','virtual-interiors','room-activity','live-building-occupancy','field-work','social-proximity','relationships','needs','scheduled-events','derived-public-destinations','weather-effects','persistent-memory','life-update-authority','explicit-npc-state-machine','contextual-dwell','arrival-states','activity-state-sync'];
})();
