/* Villa Pelón V6.17 — POBLACIÓN + RUTINAS + LUGARES FUNCIONALES
   Los NPC autónomos ahora tienen destino de lugar, acceso, actividad interior
   y estado de ocupación. game.js conserva la autoridad de los NPC principales.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const D=V.worldLifeDeep=V.worldLifeDeep||{version:7,enabled:true,events:[],services:{},economy:{},ticks:0,population:[],workersAtField:[],occupancy:{}};D.version=8;
const hour=()=>((V.state?.minutes??480)/60)%24;const day=()=>V.state?.day||1;const minuteOfDay=()=>Number(V.state?.minutes??480)%1440;
const home=p=>p.home&&Number.isFinite(p.home.x)&&Number.isFinite(p.home.y)?p.home:{x:Number.isFinite(p.homeX)?p.homeX:1200,y:Number.isFinite(p.homeY)?p.homeY:620};
const parcels=()=>V.agriculturalCycle?.parcels||[];
function allPeople(){const seen=new Set(),out=[];for(const p of [...(V.life?.ambient||[]),...(V.life?.workers||[]),...(V.npcs||[])]){if(!p||!p.id||seen.has(p.id))continue;seen.add(p.id);out.push(p)}D.population=out;return out}
function movers(){const seen=new Set(),out=[];for(const p of [...(V.life?.ambient||[]),...(V.life?.workers||[])]){if(!p||!p.id||seen.has(p.id))continue;seen.add(p.id);out.push(p)}return out}
function roleKey(p){const r=String(p.role||'vecino').toLowerCase();if(r.includes('estud'))return'estudiante';if(r.includes('trab')||r==='rural'||r.includes('tractor'))return'trabajador';if(r.includes('repart'))return'repartidor';return r.includes('vecina')?'vecina':'vecino'}
const routes={estudiante:[['06:30','casa'],['07:30','escuela'],['13:30','plaza'],['17:30','casa'],['19:00','plaza'],['21:00','casa']],vecina:[['07:00','casa'],['08:00','almacen'],['10:00','plaza'],['12:00','casa'],['16:00','almacen'],['18:00','plaza'],['21:00','casa']],vecino:[['07:00','casa'],['09:00','almacen'],['12:00','casa'],['16:00','plaza'],['18:00','plaza'],['21:00','casa']],trabajador:[['06:00','casa'],['07:00','chacra'],['12:30','casa'],['15:00','chacra'],['19:00','plaza'],['21:30','casa']],repartidor:[['07:00','casa'],['08:00','almacen'],['10:00','radio'],['12:00','plaza'],['14:00','almacen'],['18:00','radio'],['21:00','casa']]};
const fixed={casa:{ambient_0:[820,680],ambient_1:[1480,700],ambient_2:[900,940],ambient_3:[1650,1235],ambient_4:[720,680],ambient_5:[1760,1235],worker_0:[3750,2200],worker_1:[4120,2200],worker_2:[4860,2200]},almacen:{ambient_0:[1910,690],ambient_1:[1910,690],ambient_4:[1910,690],worker_0:[1910,690],worker_1:[1910,690]},plaza:{ambient_0:[1050,760],ambient_1:[1180,760],ambient_2:[1280,760],ambient_3:[1400,760],ambient_4:[1000,820],ambient_5:[1500,820]},escuela:{ambient_2:[575,635],ambient_3:[575,635]},radio:{ambient_5:[1360,1540]}};
function workerParcel(p){const ps=parcels();if(!ps.length)return null;const explicit=ps.find(q=>q.worker&&String(q.worker).toLowerCase()===String(p.name||'').toLowerCase());if(explicit)return explicit;const idx=Math.max(0,Number(String(p.id).replace(/\D/g,''))||0)%ps.length;return ps[idx]}
function buildingForPlace(place){const bs=V.buildingSystem?.buildings||[];const wanted={almacen:['shop','comercio'],escuela:['school','escuela'],radio:['radio'],chacra:['rural','galpon'],casa:['home','vivienda'],panaderia:['bakery','panaderia']};const keys=wanted[place]||[];return bs.find(b=>keys.some(k=>String(b.type||'').toLowerCase().includes(k)||String(b.function||'').toLowerCase().includes(k)))||null}
function scheduleFor(p){const m=minuteOfDay(),key=roleKey(p),list=routes[key]||routes.vecino;let place='casa';for(const r of list)if(m>=Number(r[0].split(':')[0])*60+Number(r[0].split(':')[1]))place=r[1];const parcel=place==='chacra'?workerParcel(p):null;if(parcel)return{place,parcel,target:{x:parcel.x+parcel.w*.12,y:parcel.y+parcel.h*.5,place:'chacra'}};const q=fixed[place]?.[p.id];if(q)return{place,target:{x:q[0],y:q[1],place}};const b=buildingForPlace(place);if(b)return{place,target:{x:b.door.x,y:b.door.y,place,building:b.id}};return{place,target:home(p)}}
function moveTo(p,t,dt){const nav=V.territorialNavigation;if(nav?.move){const moved=nav.move(p,t,dt,Number(p.age)<18?42:58);p.lifeMoving=!!moved;if(moved)p.lifeAt='en camino';else if(Math.hypot(t.x-p.x,t.y-p.y)<34)p.lifeAt=t.place||'destino';return moved}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);if(d<=24){p.lifeMoving=false;p.lifeAt=t.place;return false}const speed=Number(p.age)<18?42:58,step=Math.min(d,speed*dt);p.x+=dx/d*step;p.y+=dy/d*step;p.lifeMoving=true;p.lifeAt='en camino';return true}
function occupy(p,t){const b=t.target?.building?V.buildingSystem?.byId?.get(t.target.building):buildingForPlace(t.place);const at=b&&Math.hypot(p.x-b.door.x,p.y-b.door.y)<42;if(at&&V.buildingSystem?.isOpen?.(b)){p.lifeInside=true;p.lifeBuildingId=b.id;p.lifeRoom=(b.interior?.rooms||['interior'])[Math.floor((D.ticks/90+p.id.length)%Math.max(1,(b.interior?.rooms||[]).length))]||'interior';p.lifeAt='interior';return true}p.lifeInside=false;p.lifeBuildingId=null;p.lifeRoom=null;return false}
function routines(dt){const active=movers(),working=[];D.occupancy={};for(const p of active){if(!(p.home||p.homeX||p.homeY))p.home={x:p.x,y:p.y};const t=scheduleFor(p);p.lifeTarget=t.place;p.lifeDestination=t;p.lifeScheduleRole=roleKey(p);p.lifeParcelId=t.parcel?.id||null;moveTo(p,t.target,dt);occupy(p,t);if(p.lifeInside&&p.lifeBuildingId){D.occupancy[p.lifeBuildingId]=(D.occupancy[p.lifeBuildingId]||0)+1}p.needs=p.needs||{social:45,rest:25,work:0,food:25};p.needs.social=Math.min(100,p.needs.social+dt*(p.lifeAt==='plaza'?-0.8:0.11));p.needs.rest=Math.min(100,p.needs.rest+dt*(p.lifeAt==='casa'||p.lifeInside&&p.lifeTarget==='casa'?-0.7:0.09));p.needs.food=Math.min(100,p.needs.food+dt*.035);const atField=!!t.parcel&&Math.hypot(p.x-t.target.x,p.y-t.target.y)<38;p.needs.work=atField?Math.min(100,(p.needs.work||0)+dt*.65):Math.max(0,(p.needs.work||0)-dt*.18);p.lifeMood=p.needs.social<20?'necesita compañía':p.needs.food>75?'tiene hambre':p.needs.rest>82?'cansado':p.needs.work>80?'agotado':p.lifeInside?'en su lugar':'bien';if(atField)working.push({person:p,parcel:t.parcel})}D.workersAtField=working;for(const p of parcels())p.workerActivity=working.filter(w=>w.parcel.id===p.id).length}
function social(dt){const ps=allPeople().filter(p=>!p._v65Hidden);for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<90){a.social=a.social||{};b.social=b.social||{};a.social[b.id]=(a.social[b.id]||0)+dt*.1;b.social[a.id]=(b.social[a.id]||0)+dt*.1;a.socialTarget=b.name;b.socialTarget=a.name;if(!a.talking&&Math.random()<dt*.055){a.talking=b.talking=true;D.events.push({x:(a.x+b.x)/2,y:(a.y+b.y)/2,text:a.name+' conversa con '+b.name,ttl:6,type:'social',name:'talk_'+a.id+'_'+b.id})}}}for(const p of ps)if(p.talking&&!ps.some(q=>q!==p&&q.id===p.socialTarget))p.talking=false}
function services(){const h=hour();D.services={almacen:h>=8&&h<20,escuela:h>=7&&h<18,radio:h>=10&&h<22,galpon:h>=7&&h<19,plaza:true,transporte:h>=6&&h<23}}
function economy(){const h=hour(),workers=D.workersAtField?.length||0;D.economy={clientes:h>=8&&h<20?Math.round(5+allPeople().length*.3):0,trabajadores:workers,produccion:workers?Math.round(workers*12):0,radioAudiencia:h>=10&&h<22?Math.round(allPeople().length*.7):0,comercio:D.services.almacen?'activo':'cerrado'}}
const pool=[{name:'feria',text:'Feria y movimiento en la plaza',days:[5,6],a:16,b:20,x:1200,y:760},{name:'club',text:'Entrenamiento en el club',days:[2,4],a:18,b:21,x:2860,y:1570},{name:'radio',text:'Vecinos visitan la radio',days:[1,3,5],a:10,b:13,x:1360,y:1540},{name:'cosecha',text:'Jornada de cosecha en las chacras',days:[1,2,3,4,5,6],a:8,b:12,x:5000,y:3500}];
function events(dt){const h=hour(),d=((day()-1)%7)+1;D.events=D.events.filter(e=>(e.ttl-=dt)>0);pool.forEach(e=>{if(e.days.includes(d)&&h>=e.a&&h<e.b&&!D.events.some(x=>x.name===e.name))D.events.push({...e,ttl:Math.min(18,(e.b-h)*60),type:'scheduled'})})}
function weather(){const w=V.life?.weather||'despejado';D.environment={weather:w,temperature:V.life?.temperature??19,night:hour()<7||hour()>=21,activity:w==='lluvia'?.7:w==='viento'?.85:1};if(w==='lluvia')movers().forEach(p=>p.lifeMood='buscando refugio')}
function save(){try{localStorage.setItem('villa_pelon_life_deep',JSON.stringify({version:8,people:allPeople().map(p=>({id:p.id,social:p.social,needs:p.needs,lifeParcelId:p.lifeParcelId,home:p.home,lifeBuildingId:p.lifeBuildingId,lifeRoom:p.lifeRoom}))}))}catch(_){} }
function load(){try{const s=JSON.parse(localStorage.getItem('villa_pelon_life_deep')||'null');allPeople().forEach(p=>{const q=s?.people?.find(x=>x.id===p.id);if(q){p.social=q.social||{};p.needs=q.needs||p.needs;p.lifeParcelId=q.lifeParcelId||null;p.home=q.home||p.home;p.lifeBuildingId=q.lifeBuildingId||null;p.lifeRoom=q.lifeRoom||null}})}catch(_){} }
function hookLife(){if(D._lifeHook||!V.life?.update)return;const old=V.life.update;V.life.update=function(dt,minutes){const result=old.apply(this,arguments);if(V.state?.started){routines(dt);social(dt);services();economy();events(dt);weather();D.ticks++;if(D.ticks%120===0)save()}return result};D._lifeHook=true;D._baseLifeUpdate=old;load()}
hookLife();
V.population={state:D,people:allPeople,find:id=>allPeople().find(p=>p.id===id),movers,schedule:scheduleFor,workerParcel,workers:()=>D.workersAtField||[],getServices:()=>D.services,getEconomy:()=>D.economy,getEvents:()=>D.events,getOccupancy:()=>D.occupancy};
V.worldLifeAPI={state:D,people:allPeople,find:V.population.find,target:scheduleFor,getServices:()=>D.services,getEconomy:()=>D.economy,getEvents:()=>D.events,getOccupancy:()=>D.occupancy};
D.features=['unified-population','simulation-movers','main-npc-readonly-social-layer','individual-routines','worker-parcel-assignment','physical-territorial-navigation','waypoint-movement','field-work','schedule-driven-movement','place-aware-schedules','building-door-arrival','virtual-interiors','room-activity','building-occupancy','social-proximity','relationships','needs','scheduled-events','weather-effects','persistent-memory','life-update-authority'];
})();
