/* Villa Pelón V68 — interfaz de juego: menú, mapa, mochila e introducción interactiva. */
(()=>{'use strict';const V=window.VillaPelon||(window.VillaPelon={});const S={inventory:[],menu:false};V.ui67=S;
function install(){if(document.getElementById('vp68'))return;const css=document.createElement('style');css.textContent=`#vp68{position:fixed;inset:0;background:rgba(12,18,14,.96);z-index:80;color:#eee5c9;font:16px monospace;padding:20px;box-sizing:border-box;display:none;overflow:auto}#vp68.open{display:block}#vp68 .panel{max-width:820px;margin:auto}#vp68 h1,#vp68 h2{letter-spacing:2px}#vp68 button{padding:11px 14px;margin:5px;background:#405b43;color:#fff;border:1px solid #a99b72;font:inherit}#vp68 .cards{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}#vp68 .card{border:1px solid #6d795f;padding:12px;flex:1;min-width:180px;background:rgba(255,255,255,.04)}#vp68mapCanvas{width:100%;max-width:760px;height:auto;image-rendering:pixelated;background:#a99b72;border:2px solid #7f7658}#vp68intro{position:fixed;inset:0;z-index:90;background:#101711;display:flex;align-items:center;justify-content:center;color:#efe5c8;font:18px monospace;text-align:center;padding:24px}#vp68intro.hidden{display:none}#vp68intro .inner{max-width:680px}#vp68intro h1{font-size:clamp(24px,6vw,48px);letter-spacing:3px}#vp68intro p{line-height:1.6}#vp68intro button{padding:14px 22px;background:#405b43;color:#fff;border:1px solid #b5a36d;font:inherit}`;document.head.appendChild(css);
const d=document.createElement('div');d.id='vp68';d.innerHTML='<div class="panel"><h1>VILLA PELÓN</h1><div class="cards"><button id="vp68map">MAPA</button><button id="vp68bag">MOCHILA</button><button id="vp68save">GUARDAR</button><button id="vp68close">VOLVER</button></div><div id="vp68content"></div></div>';document.body.appendChild(d);
const b=document.createElement('button');b.id='vp68menu';b.textContent='MENÚ';b.style='position:fixed;right:12px;top:52px;z-index:30;padding:8px;background:#405b43;color:white;border:1px solid #a99b72;font:14px monospace';document.body.appendChild(b);
const content=()=>document.getElementById('vp68content');
function open(){d.classList.add('open');S.menu=true}function close(){d.classList.remove('open');S.menu=false}b.onclick=open;document.getElementById('vp68close').onclick=close;document.getElementById('vp68save').onclick=()=>V.saveGame?.();
function map(){const s=V.gameState||{};const z=V.territory?.zones||{pueblo:{x:120,y:180,w:1680,h:650},rural:{x:1800,y:830,w:1080,h:1000},river:{x:2880,y:120,w:320,h:1710}};content().innerHTML='<h2>MAPA DEL TERRITORIO</h2><canvas id="vp68mapCanvas" width="800" height="500"></canvas><p>Tu posición: '+Math.round(s.x||0)+' / '+Math.round(s.y||0)+' · '+(V.territorialCore?.zone()||'transición')+'</p>';const c=document.getElementById('vp68mapCanvas'),x=c.getContext('2d');x.fillStyle='#a99b72';x.fillRect(0,0,800,500);const sx=.25,sy=.25;function zone(r,col){x.fillStyle=col;x.fillRect(r.x*sx,r.y*sy,r.w*sx,r.h*sy)}zone(z.pueblo,'#8fa77a');zone(z.rural,'#7f965d');zone(z.river,'#638f91');x.strokeStyle='#e8ddba';x.lineWidth=3;x.strokeRect(120*sx,180*sy,1680*sx,650*sy);x.strokeRect(1800*sx,830*sy,1080*sx,1000*sy);x.fillStyle='#f3ebd1';x.font='bold 16px monospace';x.fillText('PUEBLO',190,70);x.fillText('RURAL / CHACRAS',490,235);x.fillText('RÍO',730,70);x.fillStyle='#b94138';x.beginPath();x.arc((s.x||960)*sx,(s.y||650)*sy,7,0,Math.PI*2);x.fill();}
function bag(){const s=V.gameState||{};const inv=s.inventory||[];content().innerHTML='<h2>MOCHILA</h2>'+(inv.length?inv.map((i,n)=>'<div class="card">'+(n+1)+'. '+i+'</div>').join(''):'<p>Está vacía. Las pistas, compras y objetos encontrados aparecerán acá.</p>')}
document.getElementById('vp68map').onclick=map;document.getElementById('vp68bag').onclick=bag;
let introDone=false;function cinematic(){if(introDone||!document.getElementById('start'))return;const i=document.createElement('div');i.id='vp68intro';i.innerHTML='<div class="inner"><div>VILLA PELÓN · PRÓLOGO</div><h1>DONDE EL AGUA CAMBIÓ LA TIERRA</h1><p id="vp68scene">Antes de las calles hubo cauces. Antes de las chacras, tierra y viento.</p><button id="vp68next">SEGUIR</button></div>';document.body.appendChild(i);let n=0;const scenes=['Antes de las calles hubo cauces. Antes de las chacras, tierra y viento.','Después llegaron caminos, familias, trabajo y memoria.','Ahora el territorio está vivo. Caminá, escuchá y preguntá.','Tu primera tarea es sencilla: conocé a un vecino.'];document.getElementById('vp68next').onclick=()=>{n++;if(n<scenes.length)document.getElementById('vp68scene').textContent=scenes[n];else{i.classList.add('hidden');introDone=true;document.getElementById('startBtn')?.click()}}}document.getElementById('startBtn')?.addEventListener('click',()=>{if(!introDone){/* el primer click abre el prólogo; el siguiente inicia */}},true);}
cinematic();window.addEventListener('keydown',e=>{if(e.key==='Escape')S.menu?close():open();if(e.key.toLowerCase()==='m')open();});
setInterval(()=>{const s=V.gameState;if(s){S.inventory=s.inventory||[]}},400);
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install()})();