/* Villa Pelón V6.18 — LUGARES FUNCIONALES + OCUPACIÓN + ACTIVIDAD
   Registro único de edificios. Los lugares ahora pueden recibir población autónoma,
   asignar habitaciones/actividades y reflejar vida interior sin crear otro loop.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const B=V.buildingSystem=V.buildingSystem||{};B.version=4;B.ready=false;B.patched=false;B.inside=null;B.notice='';B.objectIndex=0;B.occupancy={};B.activities={};
const META={home:{label:'Vivienda',fn:'vivienda',hours:[0,24],roof:'gable',body:'rgba(139,104,76,.30)',activity:'vida doméstica',rooms:['cocina','estar','dormitorio']},school:{label:'Escuela',fn:'educación',hours:[7,18],roof:'flat',body:'rgba(116,128,111,.34)',activity:'clases y encuentros',rooms:['aula','patio','dirección']},shop:{label:'Comercio',fn:'comercio',hours:[8,20],roof:'flat',body:'rgba(157,112,67,.34)',activity:'compras y conversación',rooms:['salón','depósito','mostrador']},bakery:{label:'Panadería',fn:'panadería',hours:[6,20],roof:'gable',body:'rgba(174,126,70,.36)',activity:'producción y venta',rooms:['mostrador','horno','depósito']},radio:{label:'Radio',fn:'radio',hours:[9,22],roof:'flat',body:'rgba(103,117,102,.34)',activity:'emisión y producción',rooms:['estudio','control','archivo']},rural:{label:'Galpón rural',fn:'producción',hours:[6,20],roof:'gable',body:'rgba(116,100,66,.30)',activity:'trabajo rural',rooms:['galpón','herramientas','cosecha']},sports:{label:'Deportes',fn:'deporte',hours:[8,22],roof:'flat',body:'rgba(94,111,96,.32)',activity:'actividad comunitaria',rooms:['salón','vestuario','depósito']},public:{label:'Salón vecinal',fn:'comunidad',hours:[8,23],roof:'gable',body:'rgba(126,104,82,.32)',activity:'reuniones',rooms:['salón','cocina','archivo']}};
const OBJECTS={home:[['mesa','Mesa familiar','sentarse y tomar mate'],['mate','Mate','Un momento de calma'],['cocina','Cocina','preparar comida'],['radio','Radio doméstica','escuchar noticias']],school:[['pizarron','Pizarrón','clases del día'],['banco','Banco escolar','esperar o conversar'],['archivo','Archivo','papeles de la comunidad']],shop:[['mostrador','Mostrador','comprar productos'],['estante','Estantería','mirar mercadería'],['caja','Caja','actividad comercial']],bakery:[['horno','Horno','producción de pan'],['mostrador','Mostrador','pan fresco'],['harina','Sacos de harina','materia prima']],radio:[['microfono','Micrófono','voz del pueblo'],['consola','Consola','control de emisión'],['archivo','Archivo sonoro','historias registradas']],rural:[['herramientas','Herramientas','oficio rural'],['cajones','Cajones','cosecha'],['tractor','Maquinaria','trabajo productivo']],sports:[['banco','Banco','descanso'],['pelota','Pelota','actividad comunitaria'],['vestuario','Vestuario','prepararse']],public:[['mesa','Mesa comunitaria','reunión'],['silla','Sillas','encuentro'],['archivo','Archivo vecinal','memoria']]};
const ACT={casa:['cocina','estar','dormitorio'],almacen:['mostrador','salón','depósito'],escuela:['aula','patio','dirección'],radio:['estudio','control','archivo'],chacra:['galpón','herramientas','cosecha'],plaza:['patio','salón']};
function enrich(b,i){const m=META[b.type]||META.home;const side=i%2?'bottom':'top';const door=b.door||{x:b.x+b.w*.5,y:side==='bottom'?b.y+b.h+18:b.y-18};Object.assign(b,{id:b.id||`building_${i}_${b.type}`,label:b.label||m.label,function:b.function||m.fn,category:b.category||b.type,openingHours:b.openingHours||m.hours.slice(),activity:b.activity||m.activity,occupants:b.occupants||[],setback:b.setback||Math.max(18,Math.min(52,Math.round(Math.min(b.w,b.h)*.12))),door,accessPoints:b.accessPoints||[door],collision:b.collision!==false,interactable:b.interactable!==false,interior:Object.assign({w:720,h:430,rooms:m.rooms.slice(),lighting:'warm',objects:(OBJECTS[b.type]||OBJECTS.home).slice()},b.interior||{}),visual:Object.assign({roof:m.roof,body:m.body,windows:Math.max(2,Math.floor(b.w/105)),yard:b.type==='home'||b.type==='rural'},b.visual||{})});return b}
function registry(){const src=Array.isArray(V.buildings)?V.buildings:[];src.forEach(enrich);B.buildings=src;B.byId=new Map(src.map(b=>[b.id,b]));return src}
function hour(){return Number(V.state?.minutes??480)/60}function isOpen(b){const h=((hour()%24)+24)%24,a=b.openingHours||[0,24];return a[0]<=a[1]?h>=a[0]&&h<a[1]:h>=a[0]||h<a[1]}
function nearest(max=110){const p=V.state;if(!p)return null;let best=null,bd=max;for(const b of B.buildings||[]){const d=Math.hypot(p.x-b.door.x,p.y-b.door.y);if(b.interactable&&d<bd){bd=d;best=b}}return best}
function clearOccupancy(){B.occupancy={};B.activities={};for(const b of B.buildings||[])b.occupants=[]}
function activityFor(p){const place=p.lifeTarget||p.lifeAt||'casa',pool=ACT[place]||ACT.casa;return pool[Math.abs(Number(String(p.id).replace(/\D/g,''))||0)%pool.length]}
function syncPopulation(){clearOccupancy();const people=V.population?.movers?.()||[];for(const p of people){if(!p.lifeBuildingId||!p.lifeInside)continue;const b=B.byId.get(p.lifeBuildingId);if(!b)continue;p.lifeRoom=p.lifeRoom||activityFor(p);p.lifeActivity=p.lifeActivity||b.activity;b.occupants.push(p.id);B.occupancy[b.id]=(B.occupancy[b.id]||0)+1;B.activities[b.id]=B.activities[b.id]||{};B.activities[b.id][p.lifeRoom]=(B.activities[b.id][p.lifeRoom]||0)+1}}
function enter(b){if(!b)return;if(!isOpen(b)&&b.type!=='home'){B.notice=`${b.label} está cerrado ahora.`;return}B.inside=b;B.objectIndex=0;B.notice='';if(V.state){V.state._buildingInterior=true;V.state.dialogue=true}}
function exit(){B.inside=null;B.notice='';if(V.state){V.state._buildingInterior=false;V.state.dialogue=false}}
function toggle(){if(B.inside)return exit();const b=nearest();if(b)enter(b)}
function currentObject(){const a=B.inside?.interior?.objects||[];return a.length?a[B.objectIndex%a.length]:null}
function interactObject(){const o=currentObject();if(!o)return;B.notice=`${o[1]} · ${o[2]}`;B.objectIndex++}
function capture(e){if(!V.state?.started)return;const k=e.key.toLowerCase();if(B.inside){if(k==='e'||k==='escape'){e.preventDefault();e.stopImmediatePropagation();exit();return}if(k==='f'){e.preventDefault();e.stopImmediatePropagation();interactObject();return}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){e.preventDefault();e.stopImmediatePropagation();return}}else if(k==='e'){const b=nearest();if(!b)return;e.preventDefault();e.stopImmediatePropagation();toggle()}}
function facade(c){for(const b of B.buildings||[]){const v=b.visual||{};c.fillStyle='rgba(39,31,25,.17)';c.fillRect(b.x+8,b.y+b.h+7,Math.max(1,b.w-16),8);c.fillStyle=v.body;c.fillRect(b.x+3,b.y+3,Math.max(1,b.w-6),Math.max(1,b.h-6));c.strokeStyle='rgba(60,45,34,.42)';c.lineWidth=2;c.strokeRect(b.x+3,b.y+3,Math.max(1,b.w-6),Math.max(1,b.h-6));if(v.roof==='gable'){c.fillStyle='rgba(75,57,43,.34)';c.beginPath();c.moveTo(b.x-5,b.y+11);c.lineTo(b.x+b.w*.5,b.y-17);c.lineTo(b.x+b.w+5,b.y+11);c.closePath();c.fill()}const n=Math.max(2,v.windows||2);for(let i=0;i<n;i++){const wx=b.x+28+i*((b.w-56)/Math.max(1,n-1)),wy=b.y+b.h*.4;c.fillStyle='rgba(61,73,66,.66)';c.fillRect(wx-7,wy-8,14,15);if(isOpen(b)){c.fillStyle='rgba(220,190,115,.32)';c.fillRect(wx-5,wy-6,4,11)}}const d=b.door,dx=d.x-8,dy=d.y>b.y+b.h?b.y+b.h-1:b.y+1;c.fillStyle='rgba(67,48,36,.9)';c.fillRect(dx,dy,16,20);if((B.occupancy[b.id]||0)>0){c.fillStyle='rgba(220,190,115,.55)';c.fillRect(dx+11,dy+10,2,2)}}}
function drawInterior(c,vw,vh){const b=B.inside,W=vw||c.canvas.width,H=vh||c.canvas.height;c.fillStyle='rgba(19,17,15,.96)';c.fillRect(0,0,W,H);const w=Math.min(820,W-42),h=Math.min(510,H-60),x=(W-w)/2,y=(H-h)/2;c.fillStyle='rgba(145,111,76,.97)';c.fillRect(x,y,w,h);c.strokeStyle='rgba(231,197,127,.8)';c.lineWidth=4;c.strokeRect(x,y,w,h);c.fillStyle='#f3dfaa';c.font='bold 18px monospace';c.fillText(b.label,x+34,y+40);c.font='10px monospace';c.fillText(`${b.function.toUpperCase()} · ${isOpen(b)?'ACTIVO':'CERRADO'}`,x+34,y+58);const rooms=b.interior.rooms||[],cols=Math.min(3,rooms.length||1),rw=(w-70-(cols-1)*12)/cols;rooms.forEach((r,i)=>{const col=i%cols,row=Math.floor(i/cols),rx=x+28+col*(rw+12),ry=y+84+row*118;c.fillStyle='rgba(247,221,162,.18)';c.fillRect(rx,ry,rw,92);c.strokeStyle='rgba(84,63,47,.35)';c.strokeRect(rx,ry,rw,92);c.fillStyle='rgba(59,46,38,.82)';c.font='bold 11px monospace';c.fillText(String(r).toUpperCase(),rx+12,ry+22);const count=B.activities[b.id]?.[r]||0;if(count){c.fillStyle='rgba(221,190,116,.5)';c.fillRect(rx+12,ry+36,Math.min(rw-24,28+count*22),10);c.fillStyle='#f2dca7';c.font='9px monospace';c.fillText(`${count} activo${count===1?'':'s'}`,rx+12,ry+64)}});const o=currentObject();c.fillStyle='rgba(51,39,32,.9)';c.fillRect(x+28,y+h-72,w-56,42);c.fillStyle='#f2dca7';c.font='bold 11px monospace';c.fillText(o?`F · ${o[1]}`:'Sin objetos interactivos',x+44,y+h-45);c.font='10px monospace';c.fillText(`E / ESC · salir   PERSONAS: ${B.occupancy[b.id]||0}`,x+w-210,y+h-45)}
function overlay(c,vw,vh){if(B.inside){drawInterior(c,vw,vh);return}if(B.notice){c.fillStyle='rgba(35,27,21,.86)';c.fillRect(vw/2-210,70,420,34);c.fillStyle='#f0dfb0';c.font='bold 11px monospace';c.textAlign='center';c.fillText(B.notice,vw/2,92);c.textAlign='left'}}
function patch(){if(!V.life)return;if(!B.worldPatched&&V.life.drawWorld){const old=V.life.drawWorld;V.life.drawWorld=function(c){old.call(this,c);if(!B.inside)facade(c)};B.worldPatched=true}if(!B.overlayPatched&&V.life.drawOverlay){const old=V.life.drawOverlay;V.life.drawOverlay=function(c,vw,vh){old.call(this,c,vw,vh);overlay(c,vw,vh)};B.overlayPatched=true}registry();syncPopulation();B.patched=B.worldPatched;B.ready=B.worldPatched&&B.overlayPatched}
registry();patch();setTimeout(patch,250);setTimeout(patch,900);setTimeout(patch,1800);window.addEventListener('keydown',capture,true);B.nearest=nearest;B.enter=enter;B.exit=exit;B.isOpen=isOpen;B.toggle=toggle;B.interactObject=interactObject;B.syncPopulation=syncPopulation;B.getOccupancy=()=>B.occupancy;B.getActivities=()=>B.activities;B.check=()=>({ok:B.ready,version:B.version,buildings:B.buildings?.length||0,withDoors:(B.buildings||[]).filter(b=>b.door).length,withInteriors:(B.buildings||[]).filter(b=>b.interior).length,interactiveObjects:(B.buildings||[]).reduce((n,b)=>n+(b.interior?.objects?.length||0),0),openNow:(B.buildings||[]).filter(isOpen).length,inside:B.inside?.id||null,occupancy:B.occupancy,activities:B.activities});
})();
