/* Villa Pelón V6.34 — PROPS CONTEXTUALES + ESCENAS HABITADAS
   Capa visual derivada del territorio real del juego.
   Los detalles respetan función, circulación y escala; no crea loop, física ni autoridad paralela.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),P=V.contextualProps=V.contextualProps||{};
Object.assign(P,{version:2,ready:false,patched:false,features:['contextual-props','deterministic-detail','building-frontage','rural-work-props','residential-microdetail','street-life-props','domestic-scenes','productive-scenes','depth-clusters']});
const hash=s=>{let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)/4294967295};
const R=(c,x,y,w,h,fill,stroke)=>{c.save();c.fillStyle=fill;c.fillRect(Math.round(x),Math.round(y),Math.max(1,Math.round(w)),Math.max(1,Math.round(h)));if(stroke){c.strokeStyle=stroke;c.strokeRect(Math.round(x)+.5,Math.round(y)+.5,Math.max(1,Math.round(w)-1),Math.max(1,Math.round(h)-1))}c.restore()};
function planter(c,x,y,s=1){R(c,x,y,16*s,8*s,'rgba(111,76,53,.92)','rgba(48,39,31,.7)');R(c,x+3*s,y-7*s,10*s,8*s,'rgba(78,105,62,.9)');R(c,x+7*s,y-11*s,4*s,5*s,'rgba(98,126,70,.85)')}
function bin(c,x,y){R(c,x,y,10,13,'rgba(66,70,63,.9)','rgba(31,28,24,.7)');R(c,x-1,y-2,12,3,'rgba(46,49,45,.95)')}
function crate(c,x,y,s=1){R(c,x,y,18*s,13*s,'rgba(151,106,58,.95)','rgba(67,48,32,.9)');c.save();c.strokeStyle='rgba(225,182,107,.45)';c.lineWidth=2;c.beginPath();c.moveTo(x+3*s,y+3*s);c.lineTo(x+15*s,y+10*s);c.moveTo(x+15*s,y+3*s);c.lineTo(x+3*s,y+10*s);c.stroke();c.restore()}
function bench(c,x,y){R(c,x,y,34,5,'rgba(117,81,55,.95)');R(c,x+3,y+5,4,10,'rgba(75,58,44,.9)');R(c,x+27,y+5,4,10,'rgba(75,58,44,.9)')}
function tree(c,x,y,s=1){c.save();c.fillStyle='rgba(78,57,40,.95)';c.fillRect(Math.round(x-3*s),Math.round(y),Math.max(4,Math.round(6*s)),Math.round(20*s));c.fillStyle='rgba(66,93,58,.92)';c.beginPath();c.arc(Math.round(x),Math.round(y-5*s),Math.round(12*s),0,Math.PI*2);c.arc(Math.round(x-8*s),Math.round(y+1*s),Math.round(8*s),0,Math.PI*2);c.arc(Math.round(x+8*s),Math.round(y+1*s),Math.round(8*s),0,Math.PI*2);c.fill();c.restore()}
function poplar(c,x,y,s=1){c.save();c.fillStyle='rgba(76,59,43,.9)';c.fillRect(x-2*s,y,4*s,25*s);c.fillStyle='rgba(66,91,57,.88)';c.beginPath();c.ellipse(x,y-5*s,7*s,18*s,0,0,Math.PI*2);c.fill();c.restore()}
function tool(c,x,y,s=1){c.save();c.strokeStyle='rgba(78,55,38,.95)';c.lineWidth=Math.max(2,2*s);c.beginPath();c.moveTo(x,y+15*s);c.lineTo(x+8*s,y);c.stroke();c.fillStyle='rgba(110,109,94,.9)';c.fillRect(x+5*s,y-2*s,10*s,4*s);c.restore()}
function bicycle(c,x,y,s=1){c.save();c.strokeStyle='rgba(48,51,48,.9)';c.lineWidth=1.5;c.beginPath();c.arc(x,y,5*s,0,Math.PI*2);c.arc(x+16*s,y,5*s,0,Math.PI*2);c.moveTo(x,y);c.lineTo(x+8*s,y-7*s);c.lineTo(x+16*s,y);c.moveTo(x+8*s,y-7*s);c.lineTo(x+12*s,y+1*s);c.stroke();c.restore()}
function laundry(c,x,y,s=1){c.save();c.strokeStyle='rgba(70,57,46,.7)';c.lineWidth=1;c.beginPath();c.moveTo(x,y);c.lineTo(x+38*s,y);c.stroke();for(let i=0;i<4;i++){const xx=x+4+i*10;c.fillStyle=['rgba(203,184,151,.9)','rgba(113,134,141,.85)','rgba(183,124,91,.82)','rgba(221,205,166,.9)'][i];c.fillRect(xx,y+1,7,10*s)}c.restore()}
function table(c,x,y,s=1){R(c,x,y,28*s,5*s,'rgba(113,78,53,.9)');R(c,x+3*s,y+5*s,3*s,9*s,'rgba(71,55,43,.85)');R(c,x+22*s,y+5*s,3*s,9*s,'rgba(71,55,43,.85)')}
function barrel(c,x,y,s=1){c.save();c.fillStyle='rgba(113,76,48,.94)';c.fillRect(x,y,12*s,14*s);c.strokeStyle='rgba(57,43,33,.75)';c.strokeRect(x,y,12*s,14*s);c.fillStyle='rgba(194,146,78,.5)';c.fillRect(x+2*s,y+4*s,8*s,2*s);c.fillRect(x+2*s,y+10*s,8*s,2*s);c.restore()}
function roadProps(c,r,index){if(!r)return;const urban=r.kind==='urban'||r.kind==='urban-edge',productive=r.kind==='productive'||r.kind==='rural'||r.kind==='service';const seed=hash(r.id);if(r.orientation==='horizontal'){const count=Math.max(2,Math.floor(r.w/500));for(let i=0;i<count;i++){const q=hash(r.id+i),x=r.x+(i+.24+q*.45)*(r.w/count),side=r.y-(V.streetSystem.sidewalkWidth||28)-18-(hash('s'+r.id+i)*18);if(urban&&hash('p'+r.id+i)>.25)planter(c,x,side,1);if(urban&&hash('b'+r.id+i)>.62)bench(c,x+25,side+2);if(urban&&hash('bike'+r.id+i)>.82)bicycle(c,x+18,side+13,.8);if(productive&&hash('t'+r.id+i)>.34)tool(c,x,side+4,.9);if(productive&&hash('bar'+r.id+i)>.72)barrel(c,x+24,side+5,.75)}}else{const count=Math.max(2,Math.floor(r.h/500));for(let i=0;i<count;i++){const q=hash(r.id+i),y=r.y+(i+.24+q*.45)*(r.h/count),side=r.x-(V.streetSystem.sidewalkWidth||28)-18-(hash('s'+r.id+i)*18);if(urban&&hash('p'+r.id+i)>.28)planter(c,side,y,1);if(urban&&hash('bike'+r.id+i)>.84)bicycle(c,side+13,y+18,.8);if(productive&&hash('t'+r.id+i)>.34)tool(c,side,y,.9)}}return seed}
function buildingProps(c,b,i){if(!b||!Number.isFinite(Number(b.x)))return;const seed=hash(b.id||i),door=b.door||{x:b.x+b.w/2,y:b.y+b.h+24},style=String(b.visual?.style||b.type||'home').toLowerCase(),frontY=door.y+4,side=seed>.5?1:-1;
 if(style.includes('home')||style.includes('vivienda')){if(seed>.15)planter(c,door.x+side*28,frontY,seed>.72?1.2:.9);if(seed>.4)tree(c,b.x+b.w*(.16+hash('tree'+b.id)*.55),b.y+b.h+30,seed>.76?1.05:.8);if(seed>.56)bin(c,b.x+b.w*.78,frontY+3);if(seed>.68)bicycle(c,door.x-side*25,frontY+12,.75);if(seed>.77)laundry(c,b.x+b.w*.15,b.y+b.h+18,.9);if(seed>.86)table(c,b.x+b.w*.56,b.y+b.h+28,.8)}
 else if(style.includes('shop')||style.includes('comercio')||style.includes('bakery')){crate(c,door.x+side*28,frontY,seed>.65?1.1:.85);if(style.includes('bakery')){crate(c,door.x-side*25,frontY+1,.8);barrel(c,door.x+side*44,frontY+1,.75)}else{bin(c,door.x-side*34,frontY+2);if(seed>.7)planter(c,door.x+side*40,frontY,1)}}
 else if(style.includes('rural')){crate(c,door.x+side*28,frontY,1.1);crate(c,door.x+side*5,frontY+2,.8);tool(c,door.x-side*28,frontY+2,1);barrel(c,door.x+side*48,frontY+1,.9)}
 else if(style.includes('sports')||style.includes('public')){bench(c,door.x-17,frontY+3);if(seed>.45)bin(c,door.x+side*36,frontY+2);if(seed>.72)tree(c,door.x+side*48,frontY+8,.8)}
 else if(style.includes('radio')){bin(c,door.x+side*30,frontY+2);if(seed>.45)barrel(c,door.x-side*25,frontY+2,.7)}}
function parcelProps(c,p,i){if(!p)return;const seed=hash(p.id||'parcel'+i),x=p.x+p.w*(.14+seed*.66),y=p.y+p.h*(.72+hash('py'+p.id)*.16);crate(c,x,y,.85);if(seed>.28)tool(c,x+27,y+1,.8);if(seed>.55)tree(c,p.x+p.w*.88,p.y+p.h*.72,.9);if(seed>.7)poplar(c,p.x+p.w*.08,p.y+p.h*.45,1.05)}
function depthClusters(c){const S=V.streetSystem,B=V.buildingSystem;if(!S||!B)return;const roads=S.roads||[],buildings=B.buildings||[];for(let i=0;i<Math.min(buildings.length,80);i++){const b=buildings[i],s=hash('depth'+b.id);if(s>.55){const x=b.x-12-(s*18),y=b.y+b.h+25+(hash('d2'+b.id)*18);if(s>.78)poplar(c,x,y,.72);else planter(c,x,y,.8)}}}
function draw(c){const S=V.streetSystem,B=V.buildingSystem,A=V.agriculturalCycle;if(!S||!B)return;for(let i=0;i<(S.roads||[]).length;i++)roadProps(c,S.roads[i],i);for(let i=0;i<(B.buildings||[]).length;i++)buildingProps(c,B.buildings[i],i);for(let i=0;i<(A?.parcels||[]).length;i++)parcelProps(c,A.parcels[i],i);depthClusters(c)}
function patch(){if(P.patched)return;if(!V.life?.drawWorld)return;const old=V.life.drawWorld;V.life.drawWorld=function(c){old.call(this,c);draw(c)};P.patched=true;P.ready=true;P.check=()=>({ok:P.ready,version:P.version,roads:V.streetSystem?.roads?.length||0,buildings:V.buildingSystem?.buildings?.length||0,parcels:V.agriculturalCycle?.parcels?.length||0,features:P.features});}
patch();setTimeout(patch,300);setTimeout(patch,1000);
})();
