/* Villa Pelón V6.2 — GLOBOS ESTABLES
   Posicionamiento sincronizado con el motor. Sin RAF ni intervalos propios.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const D=V.v6Dialogue=V.v6Dialogue||{version:2,enabled:true};let lastKey='';
function css(){if(document.getElementById('v6DialogueStableCSS'))return;const s=document.createElement('style');s.id='v6DialogueStableCSS';s.textContent=`#dialogue.v5-bubble,#dialogue.v6-stable{position:fixed!important;z-index:1100!important;box-sizing:border-box;width:min(276px,calc(100vw - 24px));max-height:min(230px,42vh);overflow:hidden!important;border:3px solid #1c1c1c!important;border-radius:0!important;box-shadow:4px 4px 0 rgba(0,0,0,.25)!important;transform:translate(-50%,0)!important;transition:none!important;animation:none!important;opacity:1!important;visibility:visible!important}#dialogue.v6-above{transform:translate(-50%,-100%)!important}#dialogue.v5-bubble #dialogueText,#dialogue.v6-stable #dialogueText{max-height:120px;overflow:hidden!important}#dialogue.v5-bubble::after,#dialogue.v5-bubble::before{display:none!important}#v5-interact-prompt{transition:none!important;animation:none!important}@media(max-width:600px){#dialogue.v5-bubble,#dialogue.v6-stable{width:min(248px,calc(100vw - 16px));max-height:200px}#dialogue.v5-bubble #dialogueText,#dialogue.v6-stable #dialogueText{font-size:12px;line-height:1.3;max-height:100px}}`;document.head.appendChild(s)}
function speaker(){const name=document.getElementById('speaker')?.textContent?.trim();return(V.npcs||[]).find(n=>String(n.name||'').trim()===name)||null}
function place(){const b=document.getElementById('dialogue');if(!b||b.classList.contains('hidden')){lastKey='';return}const n=speaker();if(!n)return;const c=V.camera||{x:V.state?.x||0,y:V.state?.y||0,zoom:.82},z=Number(c.zoom)||.82,sx=innerWidth*.5+(n.x-c.x)*z,sy=innerHeight*.5+(n.y-c.y)*z-54*z,bw=Math.min(276,innerWidth-24),margin=8;let x=Math.max(margin+bw/2,Math.min(innerWidth-margin-bw/2,sx)),y=sy;const top=92,bottom=innerHeight-14,h=Math.min(230,Math.max(96,b.offsetHeight||140));let above=true;if(y-h<top){above=false;y=sy+48*z}if(!above)y=Math.max(top,Math.min(bottom-h+8,y));else y=Math.max(top+h,Math.min(bottom,y));const key=[Math.round(x),Math.round(y),above?'a':'b'].join(':');if(key!==lastKey){b.style.left=x+'px';b.style.top=y+'px';b.classList.toggle('v6-above',above);b.classList.add('v6-stable');lastKey=key}}
function prompt(){let p=document.getElementById('v5-interact-prompt');if(!p){p=document.createElement('div');p.id='v5-interact-prompt';document.getElementById('game')?.appendChild(p)}const st=V.state||{};if(st.dialogue){p.style.display='none';return}const n=V.engine?.nearest?.()||null;if(!n){p.style.display='none';return}const c=V.camera||{x:st.x||0,y:st.y||0,zoom:.82},z=Number(c.zoom)||.82,x=innerWidth*.5+(n.x+(n.w?n.w/2:0)-c.x)*z,y=innerHeight*.5+(n.y+(n.h?n.h/2:0)-c.y)*z-34*z;p.style.left=Math.max(65,Math.min(innerWidth-65,x))+'px';p.style.top=Math.max(42,Math.min(innerHeight-18,y))+'px';p.textContent=n.name?'E  HABLAR · '+n.name:'E  INTERACTUAR';p.style.display='block'}
function update(){place();prompt()}
function hook(){if(!V.engine||D.hooked)return false;const old=V.engine.update;if(typeof old!=='function')return false;V.engine.update=function(dt){const r=old.apply(this,arguments);if(V.state?.started)update();return r};D.hooked=true;return true}
function init(){css();update();if(!hook())setTimeout(init,100);D.ready=true;addEventListener('resize',update)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
