/* Villa Pelón V6.39 — CORE REPAIR
   Núcleo único: loop, input, movimiento físico, cámara y render.
   Esta versión vuelve al core dueño del desplazamiento real del jugador.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),canvas=document.getElementById('world');
if(!canvas)throw new Error('V6.39: canvas #world no encontrado');
const ctx=canvas.getContext('2d',{alpha:false});
const world=V.world||{w:8400,h:5600,version:9};world.w=8400;world.h=5600;world.version=9;V.world=world;
const state=V.state||{started:false,x:1280,y:820,speed:235,money:10000,energy:100,minutes:480,day:1,mission:0,inventory:[],dialogue:false,saved:false,walk:0,history:[],relationships:{},version:9,facing:'down',moving:false};
V.state=state;state.baseSpeed=235;state.version=9;state.motion=state.motion||{vx:0,vy:0,phase:0};
const input=V.input||{up:false,down:false,left:false,right:false};V.input=input;
const camera=V.camera||{x:state.x,y:state.y,zoom:.82};V.camera=camera;
let vw=innerWidth,vh=innerHeight,last=performance.now(),near=null,raf=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const river={x:7000,y:0,w:1200,h:5600},bridges=[{y:815,h:90},{y:1395,h:90}];
function resize(){vw=innerWidth;vh=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(vw*d));canvas.height=Math.max(1,Math.floor(vh*d));canvas.style.width=vw+'px';canvas.style.height=vh+'px';ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
function clearInput(){input.up=input.down=input.left=input.right=false}addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput()});
function bind(){addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))input.up=true;else if(['arrowdown','s'].includes(k))input.down=true;else if(['arrowleft','a'].includes(k))input.left=true;else if(['arrowright','d'].includes(k))input.right=true;else if(k==='e'||k===' '){e.preventDefault();interact()}if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k))e.preventDefault()});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))input.up=false;if(['arrowdown','s'].includes(k))input.down=false;if(['arrowleft','a'].includes(k))input.left=false;if(['arrowright','d'].includes(k))input.right=false});document.querySelectorAll('#touch [data-key]').forEach(b=>{const k=b.dataset.key;if(b.__v639)return;b.__v639=true;const down=e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId)}catch(_){}input[k]=true},up=e=>{e.preventDefault();input[k]=false};b.addEventListener('pointerdown',down,{passive:false});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>b.addEventListener(ev,up,{passive:false}))});const ib=document.getElementById('interact');if(ib&&!ib.__v639){ib.__v639=true;ib.addEventListener('click',e=>{e.preventDefault();interact()})}}bind();
const startBtn=document.getElementById('startBtn');if(startBtn)startBtn.onclick=()=>{state.started=true;document.getElementById('start')?.classList.add('hidden');document.getElementById('game')?.classList.remove('hidden');load();last=performance.now();ui();startLoop()};const saveBtn=document.getElementById('save');if(saveBtn&&!saveBtn.__v639){saveBtn.__v639=true;saveBtn.onclick=save}const dialogueNext=document.getElementById('dialogueNext');if(dialogueNext&&!dialogueNext.__v639){dialogueNext.__v639=true;dialogueNext.onclick=nextDialogue}
function bridgeAt(x,y){return bridges.some(b=>x>=river.x-24&&x<=river.x+river.w+24&&Math.abs(y-b.y-b.h/2)<=b.h/2+12)}
function fallbackBlocked(x,y){if(x<60||y<180||x>world.w-60||y>world.h-60)return true;if(x>=river.x&&x<=river.x+river.w&&!bridgeAt(x,y))return true;return (V.buildings||[]).some(b=>b.collision!==false&&x>b.x-14&&x<b.x+b.w+14&&y>b.y-14&&y<b.y+b.h+14)}
function blocked(a,b){const nav=V.territorialNavigation;if(nav&&typeof nav.segmentClear==='function'){try{return !nav.segmentClear(a,b,{radius:12})}catch(_){}}return fallbackBlocked(b.x,b.y)}
function moveReal(dx,dy,dt){const old={x:state.x,y:state.y},full={x:state.x+dx*dt,y:state.y+dy*dt};if(!blocked(old,full)){state.x=full.x;state.y=full.y;return true}let moved=false;const x={x:full.x,y:state.y},y={x:state.x,y:full.y};if(!blocked(old,x)){state.x=x.x;moved=true}if(!blocked({x:state.x,y:state.y},y)){state.y=y.y;moved=true}return moved}
function update(dt){if(!state.started)return;dt=Math.min(Math.max(Number(dt)||0,.001),.05);if(state.dialogue)return;let ix=(input.right?1:0)-(input.left?1:0),iy=(input.down?1:0)-(input.up?1:0),has=!!(ix||iy),len=Math.hypot(ix,iy)||1;if(has){ix/=len;iy/=len}const m=state.motion,target=has?state.baseSpeed*(state.energy<10?.58:1):0,acc=has?12:18;m.vx+=(ix*target-m.vx)*Math.min(1,dt*acc);m.vy+=(iy*target-m.vy)*Math.min(1,dt*acc);if(!has){m.vx*=Math.max(0,1-dt*14);m.vy*=Math.max(0,1-dt*14)}const sp=Math.hypot(m.vx,m.vy);if(sp<1){m.vx=m.vy=0}const moved=moveReal(m.vx,m.vy,dt);state.speed=sp;state.moving=moved&&sp>5;if(has)state.facing=Math.abs(ix)>Math.abs(iy)?(ix>0?'right':'left'):(iy>0?'down':'up');if(state.moving){state.walk+=dt*(7+Math.min(sp,260)/30);state.energy=Math.max(0,state.energy-dt*.42);state.minutes+=dt*2.7}else{state.energy=Math.min(100,state.energy+dt*.02);state.minutes+=dt*.04}while(state.minutes>=1440){state.minutes-=1440;state.day++;state.energy=100;V.life?.nextWeather?.()}camera.x+=(state.x-camera.x)*Math.min(1,dt*9);camera.y+=(state.y-camera.y)*Math.min(1,dt*9);const hw=vw/(2*Math.max(camera.zoom,.01)),hh=vh/(2*Math.max(camera.zoom,.01));camera.x=clamp(camera.x,hw,world.w-hw);camera.y=clamp(camera.y,hh,world.h-hh);try{V.life?.update?.(dt,state.minutes)}catch(e){console.warn('V6.39 life update',e)}near=nearest();ui()}
function nearest(){let best=null,bd=150;const arr=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[]),V.storyJob].filter(Boolean);for(const o of arr){if(o.hidden===true)continue;const x=o.x+(o.w?o.w/2:0),y=o.y+(o.h?o.h/2:0),d=Math.hypot(state.x-x,state.y-y);if(d<bd){bd=d;best=o}}return best}
function openDialogue(s,lines,source){const b=document.getElementById('dialogue');if(!b)return false;state.dialogue=true;b.classList.remove('hidden');b.dataset.lines=JSON.stringify(lines||['']);b.dataset.index='0';const sp=document.getElementById('speaker'),tx=document.getElementById('dialogueText'),a=document.getElementById('sourceLink');if(sp)sp.textContent=s||'';if(tx)tx.textContent=(lines&&lines[0])||'';if(a){if(source){a.href=source;a.classList.remove('hidden')}else a.classList.add('hidden')}return true}
function nextDialogue(){const b=document.getElementById('dialogue');if(!state.dialogue||!b)return;let lines=[];try{lines=JSON.parse(b.dataset.lines||'[]')}catch(_){}const i=Number(b.dataset.index||0)+1;if(i<lines.length){b.dataset.index=i;const tx=document.getElementById('dialogueText');if(tx)tx.textContent=lines[i]}else{state.dialogue=false;b.classList.add('hidden')}}
function interact(){if(!state.started)return;if(state.dialogue){nextDialogue();return}const n=near||nearest();if(!n)return;if(n.id&&V.npcs?.includes(n)){V.dialogue?.start?.(n)||openDialogue(n.name,n.lines);return}if(n.type==='job'&&V.ruralEconomy?.startHarvest){V.ruralEconomy.startHarvest();return}if(n.id&&V.history?.inspect){try{V.history.inspect(n.id);return}catch(_){} }if(n.type&&V.buildingSystem?.enter){try{if(V.buildingSystem.enter(n))return}catch(_){} }openDialogue(n.label||'VILLA PELÓN',{home:['Descansaste un rato.'],shop:['El almacén sigue abierto.'],school:['La escuela guarda historias.'],radio:['La radio acompaña al pueblo.'],rural:['La actividad rural continúa.'],sports:['La gente se encuentra y hace actividad.']}[n.type]||['Acá pasa algo todos los días.'])}
function save(){const payload={...state,version:9,dialogue:false,saved:false};try{localStorage.setItem('villa_pelon_v6_state',JSON.stringify(payload));localStorage.setItem('villa_pelon_v4_save',JSON.stringify(payload));state.saved=true;ui();setTimeout(()=>{state.saved=false;ui()},1200)}catch(e){console.warn('save',e)}}
function load(){try{const raw=localStorage.getItem('villa_pelon_v6_state')||localStorage.getItem('villa_pelon_v4_save');if(raw){const s=JSON.parse(raw);for(const k of ['x','y','money','energy','minutes','day','mission','inventory','history','relationships'])if(s[k]!==undefined)state[k]=s[k]}}catch(_){}state.x=clamp(Number(state.x)||1280,60,world.w-60);state.y=clamp(Number(state.y)||820,180,world.h-60);state.version=9;state.dialogue=false}
function ui(){const h=Math.floor(state.minutes/60)%24,m=Math.floor(state.minutes%60),set=(id,val)=>{const e=document.getElementById(id);if(e)e.textContent=val};set('clock',String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'));set('day',state.day);set('money',Math.round(state.money));set('energy',Math.round(state.energy));set('weather',V.life?.weather||'Despejado');const q=document.getElementById('questText');if(q)q.textContent=state.mission?'Continuá tu historia.':'Explorá el pueblo.'}
function render(){ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(Math.floor(vw/2-camera.x*camera.zoom),Math.floor(vh/2-camera.y*camera.zoom));ctx.scale(camera.zoom,camera.zoom);if(typeof V.renderWorld==='function')V.renderWorld(ctx);else if(V.life?.drawWorld)V.life.drawWorld(ctx);ctx.restore();if(typeof V.renderOverlay==='function')V.renderOverlay(ctx);}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;update(dt);render();raf=requestAnimationFrame(frame)}function startLoop(){if(raf)return;last=performance.now();raf=requestAnimationFrame(frame)}
V.engine=V.engine||{};V.engine.version='6.39';V.engine.update=update;V.engine.interact=interact;V.engine.save=save;V.engine.load=load;V.engine.start=startLoop;V.engine.render=render;V.coreIntegrity={version:'6.39',singleLoop:true,realPlayerMovement:true};startLoop();
})();