/* Villa Pelón V6.23 — GAMEPLAY CORE
   Núcleo activo único: estado, input, movimiento, cámara, loop y render base.
   La red vial, navegación, población y edificios pertenecen a sus autoridades V6.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const canvas=document.getElementById('world');
if(!canvas) throw new Error('V6.23: canvas #world no encontrado');
const ctx=canvas.getContext('2d',{alpha:false});
const world={w:8400,h:5600,version:8};
const state={started:false,x:1280,y:820,speed:235,money:10000,energy:100,minutes:480,day:1,mission:0,inventory:[],dialogue:false,saved:false,walk:0,history:[],relationships:{},version:8,facing:'down',moving:false};
V.world=world;V.state=state;
const buildings=[
{x:360,y:360,w:430,h:250,label:'ESCUELA 273',type:'school'},{x:1740,y:420,w:430,h:250,label:'ALMACÉN EL ENCUENTRO',type:'shop'},
{x:1050,y:1380,w:430,h:240,label:'RADIO OASIS 92.5',type:'radio'},{x:680,y:470,w:250,h:180,label:'CASA',type:'home'},
{x:1480,y:1010,w:300,h:200,label:'CASA',type:'home'},{x:2360,y:930,w:390,h:230,label:'GALPÓN RURAL',type:'rural'},
{x:3150,y:420,w:460,h:270,label:'BODEGA PATAGÓNICA',type:'rural'},{x:2860,y:1570,w:340,h:210,label:'VESTUARIOS',type:'sports'},
{x:350,y:1560,w:330,h:200,label:'PUESTO DEL PUEBLO',type:'rural'}];
V.buildings=V.buildings||[];for(const b of buildings)if(!V.buildings.some(x=>x.x===b.x&&x.y===b.y&&x.label===b.label))V.buildings.push(b);
V.historySpots=V.historySpots||[{x:2220,y:500,id:'origen'},{x:2700,y:1320,id:'riego'},{x:3320,y:1130,id:'vinos'}];
V.storyJob=V.storyJob||{x:2530,y:820,id:'job',type:'job',label:'CHANGA RURAL'};
V.npcs=V.npcs||[
{id:'marta',x:780,y:690,name:'Marta',color:'#a95745',hair:'#4a3028',shirt:'#a95745',pants:'#4b3d38',height:.96,build:.48,age:48,home:{x:820,y:540},work:{x:1910,y:650},role:'comercio',lines:['Buen día. Soy Marta. En un pueblo chico siempre hay alguien para ayudar.','El almacén es donde muchas veces empiezan las conversaciones.']},
{id:'raul',x:2030,y:930,name:'Raúl',color:'#557ca8',hair:'#302a27',shirt:'#557ca8',pants:'#3e4649',height:1.12,build:.68,age:42,home:{x:1560,y:980},work:{x:2540,y:1420},role:'rural',lines:['Trabajo en una chacra. Acá el calendario de la tierra manda.','Si buscás una changa, preguntá en el galpón.']},
{id:'lucia',x:1230,y:530,name:'Lucía',color:'#a55e8f',hair:'#5a342b',shirt:'#a55e8f',pants:'#50465b',height:.98,build:.42,age:29,home:{x:820,y:540},work:{x:1250,y:350},role:'escuela',lines:['La escuela guarda recuerdos de muchas familias.','Hay historias que se entienden mejor caminando el pueblo.']},
{id:'pedro',x:2320,y:1330,name:'Pedro',color:'#bd8249',hair:'#463127',shirt:'#bd8249',pants:'#554631',height:1.16,build:.74,age:56,home:{x:1560,y:980},work:{x:2480,y:1510},role:'rural',lines:['En la chacra siempre aparece algo para hacer.','Cargar, regar, podar: cada tarea tiene su momento.']},
{id:'nico',x:1330,y:1540,name:'Nico',color:'#5d8d59',hair:'#252321',shirt:'#5d8d59',pants:'#3f4740',height:1.04,build:.44,age:23,home:{x:1560,y:980},work:{x:1360,y:1540},role:'radio',lines:['La radio conecta a los vecinos.','A veces una noticia cambia el día de todo el pueblo.']},
{id:'ines',x:1540,y:650,name:'Inés',color:'#8c6aa0',hair:'#70432f',shirt:'#8c6aa0',pants:'#554758',height:1.01,build:.5,age:37,home:{x:820,y:540},work:{x:1120,y:720},role:'comercio',lines:['Vengo a hacer las compras antes de que cierre el almacén.','En el pueblo las novedades viajan rápido.']},
{id:'tomas',x:1020,y:930,name:'Tomás',color:'#6d8d57',hair:'#463329',shirt:'#6d8d57',pants:'#4b463b',height:.92,build:.4,age:15,home:{x:820,y:540},work:{x:980,y:900},role:'plaza',lines:['A veces salgo a caminar sin rumbo.','La plaza cambia mucho según la hora del día.']}];
V.v4World=V.v4World||{};V.v4World.version=8;
const input=V.input||{up:false,down:false,left:false,right:false};V.input=input;
const camera=V.camera||{x:state.x,y:state.y,zoom:.82};V.camera=camera;
let vw=innerWidth,vh=innerHeight,last=performance.now(),near=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const river={x:7000,y:0,w:1200,h:5600},bridges=[{y:815,h:90},{y:1395,h:90}];
function resize(){vw=innerWidth;vh=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(vw*d));canvas.height=Math.max(1,Math.floor(vh*d));canvas.style.width=vw+'px';canvas.style.height=vh+'px';ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
function bind(){addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k)){input.up=true;e.preventDefault()}else if(['arrowdown','s'].includes(k)){input.down=true;e.preventDefault()}else if(['arrowleft','a'].includes(k)){input.left=true;e.preventDefault()}else if(['arrowright','d'].includes(k)){input.right=true;e.preventDefault()}else if(k==='e'||k===' '){e.preventDefault();interact()}});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))input.up=false;if(['arrowdown','s'].includes(k))input.down=false;if(['arrowleft','a'].includes(k))input.left=false;if(['arrowright','d'].includes(k))input.right=false});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key,on=e=>{e.preventDefault();input[k]=true},off=e=>{if(e)e.preventDefault();input[k]=false};b.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave','pointerout'].forEach(ev=>b.addEventListener(ev,off))});const ib=document.getElementById('interact');if(ib)ib.addEventListener('click',e=>{e.preventDefault();interact()})}bind();
const startBtn=document.getElementById('startBtn');if(startBtn)startBtn.onclick=()=>{state.started=true;document.getElementById('start')?.classList.add('hidden');document.getElementById('game')?.classList.remove('hidden');load();last=performance.now();ui()};const saveBtn=document.getElementById('save');if(saveBtn)saveBtn.onclick=save;const dialogueNext=document.getElementById('dialogueNext');if(dialogueNext)dialogueNext.onclick=nextDialogue;
function road(x,y){return !!V.streetSystem?.onRoad?.(x,y)}
function bridgeAt(x,y){return bridges.some(b=>x>=river.x-24&&x<=river.x+river.w+24&&Math.abs(y-b.y-b.h/2)<=b.h/2+12)}
function riverBlocked(x,y){return x>=river.x&&x<=river.x+river.w&&y>=river.y&&y<=river.y+river.h&&!bridgeAt(x,y)}
function fallbackBlocked(x,y){if(x<60||y<180||x>world.w-60||y>world.h-60||riverBlocked(x,y))return true;return V.buildings.some(b=>b.collision!==false&&x>b.x-12&&x<b.x+b.w+12&&y>b.y-12&&y<b.y+b.h+12)}
function movePlayer(dx,dy,dt){const nav=V.territorialNavigation;if(nav?.move){const ghost={x:state.x,y:state.y,radius:12};const target={x:state.x+dx*state.speed*dt,y:state.y+dy*state.speed*dt};if(nav.segmentClear?.(ghost,target,ghost)){state.x=clamp(target.x,60,world.w-60);state.y=clamp(target.y,180,world.h-60);return}return}const nx=state.x+dx*state.speed*dt,ny=state.y+dy*state.speed*dt;if(!fallbackBlocked(nx,state.y))state.x=nx;if(!fallbackBlocked(state.x,ny))state.y=ny;state.x=clamp(state.x,60,world.w-60);state.y=clamp(state.y,180,world.h-60)}
function advance(dt,moving){state.minutes+=dt*(moving?2.7:.04);while(state.minutes>=1440){state.minutes-=1440;state.day++;state.energy=100;if(V.life?.nextWeather)V.life.nextWeather()}}
function update(dt){if(!state.started||state.dialogue)return;let dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0);const moving=!!(dx||dy);state.moving=moving;if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;state.facing=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');const boost=state.energy<10?.55:1;movePlayer(dx*boost,dy*boost,dt);state.energy=Math.max(0,state.energy-dt*.42);state.walk+=dt*10}else state.energy=Math.min(100,state.energy+dt*.02);advance(dt,moving);V.life?.update?.(dt,state.minutes);camera.x+=(state.x-camera.x)*Math.min(1,dt*8);camera.y+=(state.y-camera.y)*Math.min(1,dt*8);const hw=vw/(2*Math.max(camera.zoom,.01)),hh=vh/(2*Math.max(camera.zoom,.01));camera.x=clamp(camera.x,hw,world.w-hw);camera.y=clamp(camera.y,hh,world.h-hh);near=nearest();ui()}
function nearest(){let best=null,bd=150;const arr=[...(V.npcs||[]),...(V.buildings||[]),...(V.historySpots||[]),V.storyJob].filter(Boolean);for(const o of arr){if(o.hidden===true)continue;const x=o.x+(o.w?o.w/2:0),y=o.y+(o.h?o.h/2:0),d=Math.hypot(state.x-x,state.y-y);if(d<bd){bd=d;best=o}}return best}
function openDialogue(s,lines,source){const b=document.getElementById('dialogue');if(!b)return false;state.dialogue=true;b.classList.remove('hidden');b.dataset.lines=JSON.stringify(lines||['']);b.dataset.index='0';const sp=document.getElementById('speaker'),tx=document.getElementById('dialogueText'),a=document.getElementById('sourceLink');if(sp)sp.textContent=s||'';if(tx)tx.textContent=(lines&&lines[0])||'';if(a){if(source){a.href=source;a.classList.remove('hidden')}else a.classList.add('hidden')}return true}
function nextDialogue(){const b=document.getElementById('dialogue');if(!state.dialogue||!b)return;let lines=[];try{lines=JSON.parse(b.dataset.lines||'[]')}catch(_){}const i=Number(b.dataset.index||0)+1;if(i<lines.length){b.dataset.index=i;const tx=document.getElementById('dialogueText');if(tx)tx.textContent=lines[i]}else{state.dialogue=false;b.classList.add('hidden')}}
function interact(){if(!state.started)return;if(state.dialogue){nextDialogue();return}const n=near||nearest();if(!n)return;if(n.id&&V.npcs?.includes(n)){if(V.dialogue?.start)V.dialogue.start(n);else openDialogue(n.name,n.lines);return}if(n.type==='job'&&V.ruralEconomy?.startHarvest){V.ruralEconomy.startHarvest();return}if(n.id&&V.history?.inspect){try{V.history.inspect(n.id);return}catch(_){} }if(n.type&&V.buildingSystem?.enter){try{if(V.buildingSystem.enter(n))return}catch(_){} }const lines={home:['Descansaste un rato. El pueblo siguió con su actividad.'],shop:['Pan, yerba, azúcar y comestibles.'],school:['Un lugar de estudio, encuentros y memoria.'],radio:['La radio acompaña la vida cotidiana del pueblo.'],rural:['Trabajo, producción y movimiento forman parte de la vida del pueblo.'],sports:['Trabajo, producción y movimiento forman parte de la vida del pueblo.']};if(lines[n.type]){if(n.type==='home'){state.energy=clamp(state.energy+35,0,100);state.minutes+=30}openDialogue(n.label||'VILLA PELÓN',lines[n.type])}}
function save(){const payload={...state,version:8,dialogue:false,saved:false};try{localStorage.setItem('villa_pelon_v6_state',JSON.stringify(payload));localStorage.setItem('villa_pelon_v4_save',JSON.stringify(payload));localStorage.setItem('villa_pelon_v4_world',JSON.stringify({version:8,citizens:V.npcs||[],traffic:V.life?.traffic||[],animals:V.life?.animals||[]}));state.saved=true;ui();setTimeout(()=>{state.saved=false;ui()},1200)}catch(_){}V.story?.save?.()}
function load(){try{const raw=localStorage.getItem('villa_pelon_v6_state')||localStorage.getItem('villa_pelon_v4_save');if(raw){const s=JSON.parse(raw);if(s&&typeof s==='object'){for(const k of ['x','y','money','energy','minutes','day','mission','inventory','history','relationships'])if(s[k]!==undefined)state[k]=s[k]}}}catch(_){}state.version=8;state.dialogue=false;state.x=clamp(Number(state.x)||1280,60,world.w-60);state.y=clamp(Number(state.y)||820,180,world.h-60);try{const w=JSON.parse(localStorage.getItem('villa_pelon_v4_world')||'null');if(w?.citizens&&Array.isArray(w.citizens)&&V.npcs)V.npcs.splice(0,V.npcs.length,...w.citizens)}catch(_){}V.story?.load?.()}
function ui(){const h=Math.floor(state.minutes/60)%24,m=Math.floor(state.minutes%60),set=(id,val)=>{const e=document.getElementById(id);if(e)e.textContent=val};set('clock',String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'));set('day',state.day);set('money',Math.round(state.money));set('energy',Math.round(state.energy));set('weather',V.life?.weather||'Despejado');const q=document.getElementById('questText');if(q)q.textContent=state.mission?'Continuá tu historia.':'Explorá el pueblo.'}
function terrain(){ctx.fillStyle='#a8956b';ctx.fillRect(0,0,world.w,world.h);for(let i=0;i<900;i++){const x=(i*211+77)%world.w,y=(i*137+51)%world.h;ctx.fillStyle=i%4?'rgba(77,68,48,.11)':'rgba(230,212,165,.14)';ctx.fillRect(x,y,2+(i%5)*2,2+(i%5)*2)}ctx.fillStyle='#77775e';ctx.beginPath();ctx.moveTo(0,360);for(let x=0;x<=world.w;x+=180)ctx.lineTo(x,250+Math.sin(x*.006)*65);ctx.lineTo(world.w,0);ctx.lineTo(0,0);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(96,119,67,.12)';ctx.fillRect(3000,2800,3900,2700)}
function drawRoads(){const roads=V.streetSystem?.roads||[];for(const r of roads){ctx.fillStyle=r.kind==='regional'?'#a9936c':r.kind==='rural'?'#b79c70':'#c9b27f';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='rgba(244,232,195,.72)';if(r.w>=r.h)ctx.fillRect(r.x,r.y+r.h*.34,r.w,r.h*.32);else ctx.fillRect(r.x+r.w*.34,r.y,r.w*.32,r.h);ctx.strokeStyle='rgba(92,74,53,.7)';ctx.lineWidth=3;ctx.setLineDash([30,24]);ctx.beginPath();if(r.w>=r.h){ctx.moveTo(r.x,r.y+r.h/2);ctx.lineTo(r.x+r.w,r.y+r.h/2)}else{ctx.moveTo(r.x+r.w/2,r.y);ctx.lineTo(r.x+r.w/2,r.y+r.h)}ctx.stroke();ctx.setLineDash([])}}
function drawRiver(){ctx.fillStyle='#6f9299';ctx.fillRect(river.x,river.y,river.w,river.h);ctx.fillStyle='rgba(225,239,231,.16)';for(let y=80;y<5600;y+=120){ctx.fillRect(river.x+80,y,420,5);ctx.fillRect(river.x+650,y+42,360,4)}for(const b of bridges){ctx.fillStyle='#7a5b43';ctx.fillRect(river.x-70,b.y,river.w+140,b.h);ctx.fillStyle='#c5a477';ctx.fillRect(river.x-70,b.y+8,river.w+140,b.h-16)}}
function buildingDraw(b){if(riverBlocked(b.x+b.w/2,b.y+b.h/2))return;ctx.fillStyle='rgba(32,24,17,.25)';ctx.fillRect(b.x+15,b.y+b.h,b.w-30,18);const wall={school:'#d7c79f',shop:'#d1aa70',radio:'#bd816d',rural:'#a57a53',home:'#c9a985',sports:'#a5a06f'}[b.type]||'#c4a37d';ctx.fillStyle='#684b37';ctx.beginPath();ctx.moveTo(b.x-22,b.y);ctx.lineTo(b.x+b.w/2,b.y-68);ctx.lineTo(b.x+b.w+22,b.y);ctx.closePath();ctx.fill();ctx.fillStyle=wall;ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#594334';ctx.lineWidth=3;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#7898a0';ctx.fillRect(b.x+25,b.y+35,58,42);ctx.fillRect(b.x+b.w-83,b.y+35,58,42);ctx.fillStyle='#60412f';ctx.fillRect(b.x+b.w*.44,b.y+b.h*.54,b.w*.12,b.h*.46);ctx.fillStyle='#f1dfae';ctx.font='bold 18px monospace';ctx.textAlign='center';ctx.fillText(b.label,b.x+b.w/2,b.y-78);ctx.textAlign='left'}
function markers(){for(const h of V.historySpots||[]){if(state.history.includes(h.id))continue;ctx.fillStyle='#e0b84e';ctx.beginPath();ctx.arc(h.x,h.y,20+Math.sin(performance.now()/300)*3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4b3c27';ctx.font='bold 19px monospace';ctx.textAlign='center';ctx.fillText('?',h.x,h.y+7);ctx.textAlign='left'}}
function render(){ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(vw/2,vh/2);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);terrain();drawRiver();drawRoads();for(const b of V.buildings||[])buildingDraw(b);if(V.life?.drawWorld)V.life.drawWorld(ctx);if(V.v4Characters?.draw){for(const n of V.npcs||[])if(n.hidden!==true)V.v4Characters.draw(ctx,n)}markers();ctx.restore();if(V.life?.drawOverlay)V.life.drawOverlay(ctx,vw,vh)}
V.engine={version:8,canvas,ctx,input,camera,world,state,update,render,interact,nearest,openDialogue,nextDialogue,save,load,road};V.v4?.register?.('engine',V.engine);
function loop(now){const dt=Math.min((now-last)/1000,.05);last=now;if(V.v4){V.v4.frame++;V.v4.dt=dt;V.v4.fps=1/Math.max(dt,.001)}update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
