/* Villa Pelón V6.2 — PUENTE DE INTERACCIONES
   Conecta las construcciones V6, puntos históricos y changas con el interactuar real.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const B=V.v6Interaction=V.v6Interaction||{version:1,enabled:true};
function install(){if(!V.engine||B.patched)return false;const old=V.engine.interact;if(typeof old!=='function')return false;V.engine.interact=function(){if(V.state?.dialogue)return old.apply(this,arguments);const n=V.engine.nearest?.()||null;if(n){if(n.type==='bakery'){open(n.label||'PANADERÍA',['Hay pan recién hecho. En el pueblo, un mandado sencillo también puede convertirse en una historia.']);return}if(n.type==='public'){open(n.label||'SALÓN VECINAL',['Acá se reúnen vecinos, se organizan actividades y se cruzan historias del barrio.']);return}if(n.type==='job'){open('CHANGA RURAL',['Hay trabajo para hacer. Preguntá por la tarea y ganá unas monedas.']);return}if(n.id&&V.historySpots?.includes(n)){const lines={origen:['Este lugar guarda una pista sobre los primeros tiempos del territorio.','La historia no está solamente en los libros: también queda en el paisaje.'],riego:['El agua cambió la vida productiva de la zona.','Seguí la pista de los canales y mirá cómo se transformó el paisaje.'],vinos:['La producción vitivinícola terminó formando parte de la identidad del Chañar.','Todavía quedan huellas de ese proceso en las chacras y bodegas.']};open('MEMORIA DEL LUGAR',lines[n.id]||['Encontraste una memoria del territorio.']);return}}return old.apply(this,arguments)};B.patched=true;B.ready=true;return true}
function open(s,lines){if(typeof V.engine.openDialogue==='function')return V.engine.openDialogue(s,lines);const b=document.getElementById('dialogue');if(!b)return;V.state.dialogue=true;b.classList.remove('hidden');b.dataset.lines=JSON.stringify(lines);b.dataset.index='0';document.getElementById('speaker').textContent=s;document.getElementById('dialogueText').textContent=lines[0]||''}
function boot(){if(!install())setTimeout(boot,100)}boot();
})();
