/* Villa Pelón V6.4 — INTERIORES FUNCIONALES
   Interiores ligeros y reversibles para edificios interactuables.
   No reemplaza el motor: crea una capa de entrada/salida sobre el mundo.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const I=V.v6Interiors=V.v6Interiors||{version:1,open:null};
const defs={shop:{title:'Almacén',color:'#9b7047',props:['mostrador','estantes','bolsas','caja']},bakery:{title:'Panadería',color:'#b88958',props:['horno','mostrador','canastos','pan']},school:{title:'Escuela',color:'#9b9270',props:['pizarrón','bancos','mapa','libros']},radio:{title:'Radio del pueblo',color:'#a66d62',props:['micrófono','consola','grabador','papeles']},public:{title:'Salón comunitario',color:'#85795d',props:['mesas','sillas','cartelera','termo']},rural:{title:'Galpón rural',color:'#806044',props:['herramientas','cajones','bolsas','banco']},winery:{title:'Bodega',color:'#785b49',props:['toneles','cajones','botellas','mesa']}};
function building(){const p=V.state||{};let best=null,bd=145;for(const b of(V.buildings||[])){const cx=b.x+b.w/2,cy=b.y+b.h/2,d=Math.hypot(p.x-cx,p.y-cy);if(d<bd){bd=d;best=b}}return best}
function close(){document.getElementById('v6Interior')?.remove();I.open=null;V.state._v6Inside=false}
function open(b){const d=defs[b.type]||{title:b.name||'Edificio',color:'#76634f',props:['muebles','objetos','papeles']};close();const p=document.createElement('div');p.id='v6Interior';p.style.cssText='position:fixed;inset:7%;z-index:1250;background:#211b16;color:#f0e2c7;border:4px solid #15120f;box-shadow:10px 10px 0 rgba(0,0,0,.35);font-family:monospace;overflow:hidden';p.innerHTML='<div style="height:42px;padding:12px 16px;background:#30261d;border-bottom:2px solid #8e7144;display:flex;justify-content:space-between;align-items:center"><b>'+d.title.toUpperCase()+'</b><button id="v6Exit" style="background:#b78c4f;color:#211a14;border:2px solid #15120f;padding:6px 10px;font:900 11px monospace">SALIR</button></div><div style="height:calc(100% - 42px);display:flex;align-items:center;justify-content:center;background:#a99973"><div id="v6Room" style="position:relative;width:min(760px,88vw);height:min(480px,65vh);background:'+d.color+';border:5px solid #3a2d22;box-shadow:inset 0 0 0 8px rgba(255,255,255,.08)"></div></div>';document.body.appendChild(p);document.getElementById('v6Exit').onclick=close;const room=document.getElementById('v6Room');d.props.forEach((q,i)=>{const o=document.createElement('div');o.textContent=q.toUpperCase();o.style.cssText='position:absolute;left:'+(12+(i*21)%78)+'%;top:'+(18+(i*27)%65)+'%;padding:10px;background:#d8c59b;border:3px solid #392b21;color:#392b21;font:bold 10px monospace;box-shadow:4px 4px 0 rgba(0,0,0,.18)';room.appendChild(o)});I.open=b.id||b.type;V.state._v6Inside=true}
function patch(){if(I.patched||!V.engine?.interact)return;const old=V.engine.interact;V.engine.interact=function(){const b=building();if(b&&b.interactable!==false){open(b);return true}return old.apply(this,arguments)};I.patched=true;I.ready=true;I.openBuilding=open;I.close=close}
patch();setTimeout(patch,250);setTimeout(patch,800);
})();
