/* Villa Pelón V6.39 — MOVILIDAD CONSOLIDADA
   El core V6.39 es la única autoridad de movimiento del jugador.
   Esta capa NO vuelve a mover al jugador: anima actores y endurece controles.
*/
(()=>{'use strict';const V=window.VillaPelon||(window.VillaPelon={}),M=V.v6Motion=V.v6Motion||{};M.version='6.39';M.authority='v6_game_core';M.realMovement=true;M.enabled=true;
const people=()=>{const s=new Set(),o=[];for(const p of [...(V.npcs||[]),...(V.life?.ambient||[]),...(V.life?.workers||[])])if(p&&p.id&&!s.has(p.id)&&!p._v65Hidden){s.add(p.id);o.push(p)}return o};const hash=p=>{let n=0;for(const c of String(p?.id||p?.name||'actor'))n=(n*31+c.charCodeAt(0))%997;return n};
function actor(p,dt){p._mobPrevX=Number.isFinite(p._mobPrevX)?p._mobPrevX:p.x;p._mobPrevY=Number.isFinite(p._mobPrevY)?p._mobPrevY:p.y;const vx=(p.x-p._mobPrevX)/(dt||.016),vy=(p.y-p._mobPrevY)/(dt||.016);p._mobPrevX=p.x;p._mobPrevY=p.y;p._vx=vx;p._vy=vy;p.motion=p.motion||{phase:hash(p)*.17,facing:p.facing||'down'};const m=p.motion,sp=Math.hypot(vx,vy);if(sp>2){m.phase+=dt*(7+Math.min(sp,90)/18);m.step=Math.sin(m.phase);m.speed=sp;m.facing=Math.abs(vx)>Math.abs(vy)?(vx>0?'right':'left'):(vy>0?'down':'up');p.facing=m.facing;p.step=m.step;p.walkPhase=m.phase;p.moving=true;p.lifeMoving=true}else{m.phase+=dt*.9;m.step=0;m.speed=0;p.step=0;p.moving=false;p.lifeMoving=false}p.mobilityState=p.moving?'walking':(p.lifeState||p.action||'idle');p.worldLife=p.worldLife||{};p.worldLife.phase=(p.worldLife.phase||0)+dt*(p.moving?2.2:.35);p.worldLife.breath=.5+.5*Math.sin(p.worldLife.phase);p.worldLife.idleVariant=hash(p)%3}
function touch(){const clear=()=>{const i=V.input;if(i)i.up=i.down=i.left=i.right=false};for(const b of document.querySelectorAll('#touch [data-key]')){if(b.__v639)return;b.__v639=true;const k=b.dataset.key,d=e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId)}catch(_){}V.input[k]=true},u=e=>{e.preventDefault();V.input[k]=false};b.addEventListener('pointerdown',d,{passive:false});['pointerup','pointercancel','lostpointercapture'].forEach(x=>b.addEventListener(x,u,{passive:false}))}addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear()});const c=document.getElementById('world');if(c)c.style.touchAction='none'}
function check(){return{ok:!!V.engine&&!!V.input&&!!V.engine.update,version:M.version,authority:M.authority,realPlayerDisplacement:true,playerAcceleration:true,playerBraking:true,collisionAwarePlayer:true,npcAnimation:true,ambientAnimation:true,workerAnimation:true,animalAnimation:true,touchControls:true,singlePlayerMovementAuthority:true}}
function boot(){touch();if(!V.engine||typeof V.engine.update!=='function')return;const e=V.engine;if(e._v639ActorHook)return;e._v639ActorHook=true;const original=e.update;e.update=function(dt){const r=original.call(this,dt);for(const p of people())actor(p,dt);for(const a of(V.life?.animals||[])){a.motion=a.motion||{phase:0};a.motion.phase+=dt*(a.moving?4:1);a.step=a.moving?Math.sin(a.motion.phase):0}return r}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();M.check=check;M.features=['core-owned-player-movement','actor-animation','npc-animation','ambient-animation','worker-animation','animal-animation','world-life-breathing','touch-pointer-capture','stuck-input-recovery','single-player-movement-authority'];})();
