/* Villa Pelón V6.37 — MOVILIDAD MUNDIAL
   Una sola capa de movilidad sobre el núcleo V6.36.
   No crea loop ni reemplaza la simulación territorial: mejora aceleración,
   frenado, dirección, controles táctiles y animación de todos los actores.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const M=V.v6Motion=V.v6Motion||{};M.version=3;M.enabled=true;M.authority='v6_game_core';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),input=()=>V.input||{},state=()=>V.state||{};
const people=()=>{const seen=new Set(),out=[];for(const p of [...(V.npcs||[]),...(V.life?.ambient||[]),...(V.life?.workers||[])]){if(!p||!p.id||seen.has(p.id)||p._v65Hidden)continue;seen.add(p.id);out.push(p)}return out};
function playerMotion(s,dt){s.motion=s.motion||{vx:0,vy:0,phase:0,facing:s.facing||'down'};const m=s.motion,i=input(),dx=(i.right?1:0)-(i.left?1:0),dy=(i.down?1:0)-(i.up?1:0),has=!!(dx||dy),len=Math.hypot(dx,dy)||1,target=Number(s.baseSpeed)||235,max=target*(s.energy<10?.58:1),tx=has?dx/len*max:0,ty=has?dy/len*max:0,k=Math.min(1,dt*(has?8.5:10.5));m.vx+=(tx-m.vx)*k;m.vy+=(ty-m.vy)*k;if(!has&&Math.hypot(m.vx,m.vy)<2)m.vx=m.vy=0;m.speed=Math.hypot(m.vx,m.vy);m.facing=has?(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up')):(m.facing||s.facing||'down');s.speed=clamp(m.speed,0,target);s.facing=m.facing;s.moving=m.speed>8;m.phase+=dt*(s.moving?8+m.speed/30:1.2);m.step=s.moving?Math.sin(m.phase):0;s.walkPhase=m.phase;s.walk=m.phase}
function actorAnimation(p,dt){p._mobPrevX=Number.isFinite(p._mobPrevX)?p._mobPrevX:p.x;p._mobPrevY=Number.isFinite(p._mobPrevY)?p._mobPrevY:p.y;const vx=(p.x-p._mobPrevX)/(dt||.016),vy=(p.y-p._mobPrevY)/(dt||.016);p._mobPrevX=p.x;p._mobPrevY=p.y;p._vx=vx;p._vy=vy;p.motion=p.motion||{phase:(Number(p.appearanceSeed)||0)*.17,facing:p.facing||'down',speed:0,step:0};const m=p.motion,sp=Math.hypot(vx,vy),moving=sp>2;if(moving){m.speed=sp;m.facing=Math.abs(vx)>Math.abs(vy)?(vx>0?'right':'left'):(vy>0?'down':'up');m.phase+=dt*(7+Math.min(sp,90)/18);m.step=Math.sin(m.phase);p.facing=m.facing;p.step=m.step;p.walkPhase=m.phase;p.moving=true;p.lifeMoving=true}else{m.speed=0;m.phase+=dt*.9;m.step=0;p.step=0;p.moving=false}p.mobilityState=moving?'walking':(p.lifeState||p.action||'idle')}
function install(){const e=V.engine;if(!e||typeof e.update!=='function'||M.updatePatched)return false;const original=e.update;e.update=function(dt){const s=state();if(s.started&&!s.dialogue&&!V.buildingSystem?.inside)playerMotion(s,dt);else if(s.motion){s.motion.vx*=Math.max(0,1-dt*12);s.motion.vy*=Math.max(0,1-dt*12);s.motion.speed=Math.hypot(s.motion.vx,s.motion.vy);s.moving=false}const result=original.call(this,dt);for(const p of people())actorAnimation(p,dt);for(const a of(V.life?.animals||[])){a.mobility=a.mobility||{phase:(Number(a.x)||0)*.01+(Number(a.y)||0)*.007};a.mobility.phase+=dt*(a.type==='gallina'?4.5:2.2);a.step=a.moving?Math.sin(a.mobility.phase):0}return result};M.updatePatched=true;M.originalUpdate=original;return true}
function touch(){for(const b of document.querySelectorAll('#touch [data-key]')){if(b.__mobBound)continue;const key=b.dataset.key,down=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);if(V.input)V.input[key]=true},up=e=>{e.preventDefault();if(V.input)V.input[key]=false};b.addEventListener('pointerdown',down,{passive:false});['pointerup','pointercancel','lostpointercapture','pointerleave'].forEach(ev=>b.addEventListener(ev,up,{passive:false}));b.__mobBound=true}const c=document.getElementById('world');if(c)c.style.touchAction='none'}
function check(){return{ok:!!V.engine&&!!V.input&&M.updatePatched===true,version:M.version,authority:M.authority,playerAcceleration:true,playerBraking:true,diagonalNormalization:true,npcAnimation:true,ambientAnimation:true,workerAnimation:true,animalAnimation:true,touchPointerCapture:true,singleLoop:true}}
function boot(){install();touch()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();M.check=check;M.features=['player-acceleration','player-braking','energy-aware-speed','directional-facing','walk-phase','npc-velocity','npc-facing','ambient-motion','worker-motion','animal-motion','touch-pointer-capture','single-update-authority','single-loop'];
})();
