/* Villa Pelón V6.19 — POBLACIÓN VISIBLE + ACTIVIDAD LEGIBLE */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),P=V.populationVisuals=V.populationVisuals||{version:1,ready:false},life=V.life,chars=V.v4Characters;if(!life||!chars)return;const originalAmbient=chars.drawAmbient;
function drawWithExteriorPopulation(c){const oldA=life.ambient,oldW=life.workers;try{life.ambient=(oldA||[]).filter(p=>!p?.lifeInside);life.workers=(oldW||[]).filter(p=>!p?.lifeInside);originalAmbient.call(chars,c)}finally{life.ambient=oldA;life.workers=oldW}}
function labelFor(p){if(p.lifeInside)return null;if(p.lifeTarget==='chacra'||p.lifeActivity==='trabajo rural')return'TRABAJO';if(p.lifeTarget==='escuela')return'ESTUDIO';if(p.lifeTarget==='almacen')return'COMPRAS';if(p.lifeTarget==='plaza')return p.talking?'CONVERSA':'PASEO';if(p.lifeTarget==='radio')return'RADIO';if(p.lifeMood==='tiene hambre')return'HAMBRE';if(p.lifeMood==='cansado')return'DESCANSO';return null}
function tag(c,x,y,text){if(!text)return;c.save();c.font='bold 8px monospace';const w=c.measureText(text).width+10;c.fillStyle='rgba(31,24,20,.86)';c.fillRect(x-w/2,y-73,w,15);c.strokeStyle='rgba(221,190,116,.55)';c.strokeRect(x-w/2,y-73,w,15);c.fillStyle='rgba(246,225,171,.96)';c.textAlign='center';c.textBaseline='middle';c.fillText(text,x,y-65);c.restore()}
function drawActivity(c){for(const p of[...(life.ambient||[]),...(life.workers||[])]){if(p.lifeInside||p._v65Hidden||p.x==null)continue;tag(c,p.x,p.y,labelFor(p));if(p.talking){c.save();c.fillStyle='rgba(244,224,169,.88)';c.font='bold 11px monospace';c.textAlign='center';c.fillText('•••',p.x,p.y-78);c.restore()}}}
function patch(){if(P.patched)return;if(typeof originalAmbient==='function')chars.drawAmbient=drawWithExteriorPopulation;if(life.drawWorld&&!P.worldPatched){const old=life.drawWorld;life.drawWorld=function(c){old.call(this,c);drawActivity(c)};P.worldPatched=true}P.patched=typeof chars.drawAmbient==='function'&&P.worldPatched;P.ready=P.patched}
patch();setTimeout(patch,300);setTimeout(patch,1000);P.check=()=>({ok:P.ready,version:P.version,inside:[...(life.ambient||[]),...(life.workers||[])].filter(p=>p.lifeInside).length,activeLabels:[...(life.ambient||[]),...(life.workers||[])].filter(p=>labelFor(p)).length});
})();
