/* Villa Pelón V6.9.6 — CICLO RURAL JUGABLE
   Extiende la jugabilidad existente: chacra -> tarea -> cosecha -> cajón -> venta.
   No crea RAF, física, movimiento ni una economía paralela. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const R=V.ruralEconomy=V.ruralEconomy||{version:1,enabled:true,patched:false};
const KEY='villa_pelon_v4_player';
function state(){return V.state||(V.state={})}
function save(){if(typeof V.v4Playability?.save==='function'){V.v4Playability.save();return}try{const s=state();localStorage.setItem(KEY,JSON.stringify({inventory:s.inventory||[],money:Number(s.money)||0,energy:Number(s.energy)||0,mission:Number(s.mission)||0,flags:s.flags||{},version:4}))}catch(_){} }
function toast(text){if(typeof V.v4Playability?.toast==='function'){V.v4Playability.toast(text);return}const d=document.createElement('div');d.className='v4p-toast';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function has(item){return Array.isArray(state().inventory)&&state().inventory.some(x=>String(x).toLowerCase()===item.toLowerCase()||String(x).toLowerCase().includes(item.toLowerCase()))}
function add(item){const s=state();s.inventory=Array.isArray(s.inventory)?s.inventory:[];if(!has(item))s.inventory.push(item)}
function remove(item){const s=state();const a=Array.isArray(s.inventory)?s.inventory:[];const i=a.findIndex(x=>String(x).toLowerCase()===item.toLowerCase()||String(x).toLowerCase().includes(item.toLowerCase()));if(i<0)return false;a.splice(i,1);return true}
function complete(id){if(typeof V.v4Playability?.complete==='function')return V.v4Playability.complete(id);return false}
function isWorkTarget(t){if(!t)return false;return t===V.storyJob||/galpón rural|galpon rural|chacra|puesto del pueblo/i.test(String(t.label||t.name||''))}
function isSaleTarget(t){if(!t)return false;return /puesto del pueblo/i.test(String(t.label||t.name||''))}
function target(){return typeof V.worldInteractionAPI?.nearest==='function'?V.worldInteractionAPI.nearest():typeof V.engine?.nearest==='function'?V.engine.nearest():null}
function panel(title,html){document.getElementById('v4pPanel')?.remove();if(V.v4Playability)V.v4Playability.open=null;const p=document.body.appendChild(document.createElement('div'));p.id='v4pPanel';p.className='v4p-panel';p.innerHTML='<div class="v4p-head"><strong>'+title+'</strong><button class="v4p-close">CERRAR</button></div><div class="v4p-body">'+html+'</div>';p.querySelector('.v4p-close').onclick=()=>{p.remove();if(V.v4Playability)V.v4Playability.open=null};if(V.v4Playability)V.v4Playability.open=p;return p}
function work(){const s=state();if(!s.started)return false;const p=panel('CHACRA · TRABAJO RURAL','<div class="v4p-card"><h3>COSECHA DE FRUTA</h3><p>La tarea se realiza en la zona productiva. Requiere energía y deja un cajón de cosecha para transportar.</p><p><b>Energía:</b> 20 · <b>Tiempo:</b> 30 minutos</p><button class="v4p-action" id="ruralHarvest">COSECHAR</button></div><div class="v4p-card" style="margin-top:10px"><h3>CIRCUITO PRODUCTIVO</h3><p>Chacra → cosecha → cajón → traslado → puesto → venta.</p></div>');p.querySelector('#ruralHarvest').onclick=()=>{const s=state();if(Number(s.energy)<20){toast('Estás cansado. Descansá antes de cosechar.');return}if(has('Cajón de cosecha')){toast('Ya llevás un cajón. Primero llevalo al puesto.');return}s.energy-=20;s.minutes=(Number(s.minutes)||0)+30;add('Cajón de cosecha');s.flags=s.flags||{};s.flags.rural_last_action='cosecha';s.flags.rural_crates=Number(s.flags.rural_crates||0)+1;save();if(s.mission===4)complete('changa');toast('COSECHA REALIZADA · CAJÓN EN LA MOCHILA');p.remove();if(V.v4Playability)V.v4Playability.open=null};return true}
function sale(){const s=state();if(!s.started)return false;const price=420;const p=panel('PUESTO DEL PUEBLO · ACOPIO','<div class="v4p-card"><h3>RECIBO DE COSECHA</h3><p>El puesto recibe producción de la zona rural y la incorpora al circuito local.</p><p class="v4p-price">VALOR DEL CAJÓN · $'+price+'</p><button class="v4p-action" id="ruralSell">VENDER CAJÓN</button></div><p class="v4p-shop-note">El pago actualiza dinero, inventario y guardado.</p>');p.querySelector('#ruralSell').onclick=()=>{if(!has('Cajón de cosecha')){toast('No llevás ningún cajón para vender.');return}if(!remove('Cajón de cosecha'))return;s.money=(Number(s.money)||0)+price;s.flags=s.flags||{};s.flags.rural_last_sale=Date.now();s.flags.rural_total_sales=Number(s.flags.rural_total_sales||0)+1;save();toast('CAJÓN VENDIDO · +$'+price);p.remove();if(V.v4Playability)V.v4Playability.open=null};return true}
function patch(){const G=V.v4Playability;if(!G||R.patched||typeof G.interact!=='function')return false;const original=G.interact;G.interact=function(){const t=target();if(isSaleTarget(t))return sale();if(isWorkTarget(t))return work();return original.apply(this,arguments)};R.patched=true;R.hook='V.v4Playability.interact';return true}
function keyboard(){if(R.keyboard)return true;window.addEventListener('keydown',e=>{if(!state().started||state().dialogue)return;const k=String(e.key||'').toLowerCase();if(k!=='e'&&k!==' ')return;const p=document.getElementById('v4pPanel');if(p)return;const t=target();if(!isSaleTarget(t)&&!isWorkTarget(t))return;e.preventDefault();e.stopImmediatePropagation();if(isSaleTarget(t))sale();else work()},true);R.keyboard=true;return true}
function style(){if(document.getElementById('v6RuralEconomyCSS'))return;const st=document.createElement('style');st.id='v6RuralEconomyCSS';st.textContent='.v4p-price{font-size:18px!important;font-weight:800;color:#f0d487!important}.v4p-shop-note{font-size:11px;color:#aaa08e;margin-top:14px;padding-top:10px;border-top:1px solid #5e4e36}';document.head.appendChild(st)}
style();patch();keyboard();setTimeout(patch,250);setTimeout(patch,800);R.features=['rural-workspot','harvest-task','energy-cost','time-cost','crate-inventory','rural-sale','local-circuit','save-sync','mission-sync'];
})();
