/* Villa Pelón V6.33 — INTEGRIDAD, AUDITORÍA Y AUTOREPARACIÓN */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),I=V.systemIntegrity=V.systemIntegrity||{};Object.assign(I,{version:6.33,checks:[],repairs:0,ready:false,fatal:[]});const checks=[];
const critical=(name,fn)=>{try{const ok=!!fn();checks.push({name,status:ok?'ok':'fatal'});if(!ok)I.fatal.push(name)}catch(e){checks.push({name,status:'fatal',error:String(e?.message||e)});I.fatal.push(name)}};
const repair=(name,fn)=>{try{const changed=!!fn();checks.push({name,status:changed?'repaired':'ok'});if(changed)I.repairs++}catch(e){checks.push({name,status:'error',error:String(e?.message||e)});I.fatal.push(name)}};
const finite=(v,d)=>Number.isFinite(Number(v))?Number(v):d;
function run(){checks.length=0;I.fatal=[];I.repairs=0;
 critical('boot-state',()=>V.state&&typeof V.state==='object');critical('boot-life',()=>V.life&&typeof V.life.update==='function'&&typeof V.life.drawWorld==='function');critical('boot-street-authority',()=>V.streetSystem&&Array.isArray(V.streetSystem.roads)&&V.streetSystem.roads.length>=8&&V.streetSystem.singleAuthority===true);critical('boot-building-authority',()=>V.buildingSystem&&Array.isArray(V.buildingSystem.buildings));critical('boot-population-authority',()=>V.population&&typeof V.population.movers==='function'&&typeof V.population.schedule==='function');critical('boot-navigation-authority',()=>V.territorialNavigation&&V.territorialNavigation.version>=10&&typeof V.territorialNavigation.move==='function'&&typeof V.territorialNavigation.graph==='function');critical('boot-game-canvas',()=>document.getElementById('world'));
 repair('state-contract',()=>{const s=V.state;if(!s)return false;let r=false;const old=[s.x,s.y,s.money,s.energy,s.minutes,s.day];s.x=finite(s.x,1280);s.y=finite(s.y,820);s.money=Math.max(0,finite(s.money,10000));s.energy=Math.max(0,Math.min(100,finite(s.energy,100)));s.minutes=Math.max(0,finite(s.minutes,480));s.day=Math.max(1,Math.floor(finite(s.day,1)));if(!Array.isArray(s.inventory)){s.inventory=[];r=true}if(!Array.isArray(s.history)){s.history=[];r=true}if(!s.relationships||typeof s.relationships!=='object'){s.relationships={};r=true}return r||old.some((v,i)=>v!==[s.x,s.y,s.money,s.energy,s.minutes,s.day][i])});
 repair('world-bounds',()=>{const w=V.world,s=V.state;if(!w||!s||!Number.isFinite(w.w)||!Number.isFinite(w.h))return false;const x=Math.max(60,Math.min(w.w-60,s.x)),y=Math.max(180,Math.min(w.h-60,s.y));const r=x!==s.x||y!==s.y;s.x=x;s.y=y;return r});
 repair('street-index',()=>{const S=V.streetSystem;if(!S||!Array.isArray(S.roads))return false;let r=false;S.singleAuthority=true;for(let i=0;i<S.roads.length;i++){const road=S.roads[i];if(!road.id){road.id='road_'+String(i+1).padStart(2,'0');r=true}if(!road.kind){road.kind='urban';r=true}}const expected=Object.fromEntries(S.roads.map(x=>[x.id,x]));if(!S.roadById||Object.keys(S.roadById).length!==S.roads.length||S.roads.some(x=>S.roadById[x.id]!==x)){S.roadById=expected;r=true}return r});
 critical('street-visual-contract',()=>V.streetSystem&&V.streetSystem.version>=6.27&&typeof V.streetSystem.renderOverlay==='function'&&V.streetSystem.singleAuthority===true);critical('street-grammar',()=>Array.isArray(V.streetSystem?.intersections)&&V.streetSystem.territorialGrammar&&Array.isArray(V.streetSystem.urbanRoads));
 repair('building-contract',()=>{const B=V.buildingSystem;if(!B||!Array.isArray(B.buildings))return false;let r=false;for(const b of B.buildings){b.x=finite(b.x,0);b.y=finite(b.y,0);b.w=Math.max(1,finite(b.w,100));b.h=Math.max(1,finite(b.h,80));if(!b.door||!Number.isFinite(Number(b.door.x))||!Number.isFinite(Number(b.door.y))){b.door={x:b.x+b.w/2,y:b.y+b.h+24};r=true}if(!Array.isArray(b.accessPoints)){b.accessPoints=[{x:b.door.x,y:b.door.y}];r=true}if(!b.interior)b.interior={rooms:['principal']};if(!Array.isArray(b.interior.rooms)||!b.interior.rooms.length)b.interior.rooms=['principal'];if(!b.visual||!b.visual.style){b.visual=Object.assign({style:b.type==='home'?'home':b.type},b.visual||{});r=true}}const expected=Object.fromEntries(B.buildings.filter(x=>x.id).map(x=>[x.id,x]));if(!(B.byId instanceof Map)||B.byId.size!==Object.keys(expected).length||Object.keys(expected).some(k=>B.byId.get(k)!==expected[k])){B.byId=new Map(Object.entries(expected));r=true}return r});
 critical('building-architecture-render',()=>V.buildingSystem&&V.buildingSystem.version>=5&&V.buildingSystem.ready===true&&typeof V.buildingSystem.getOccupancy==='function');critical('urban-fabric-render',()=>V.urbanFabric&&V.urbanFabric.version>=3&&V.urbanFabric.patched===true);critical('urban-fabric-authority',()=>Array.isArray(V.urbanFabric?.features)&&V.urbanFabric.features.includes('public-destination-api'));
 repair('population-contract',()=>{if(!Array.isArray(V.npcs))return false;let r=false;for(const n of V.npcs){n.x=finite(n.x,1280);n.y=finite(n.y,820);if(!n.home||!Number.isFinite(Number(n.home.x))||!Number.isFinite(Number(n.home.y))){n.home={x:n.x,y:n.y};r=true}}return r});
 critical('population-unified-movers',()=>Array.isArray(V.population?.movers?.())&&V.population.movers().every(p=>V.npcs?.includes(p)||V.life?.ambient?.includes(p)||V.life?.workers?.includes(p)));
 repair('agriculture-contract',()=>{const A=V.agriculturalCycle;if(!A||!Array.isArray(A.parcels))return false;let r=false;for(const p of A.parcels){p.x=finite(p.x,0);p.y=finite(p.y,0);p.w=Math.max(1,finite(p.w,100));p.h=Math.max(1,finite(p.h,100));p.growth=Math.max(0,Math.min(1,finite(p.growth,0)));p.moisture=Math.max(0,Math.min(1,finite(p.moisture,0)))}return r});
 critical('navigation-graph',()=>{const N=V.territorialNavigation,g=N?.graph?.(),c=N?.check?.();return !!g&&Object.keys(g.map||{}).length>0&&Object.values(g.adj||{}).some(a=>Array.isArray(a)&&a.length>0)&&!!c?.ok&&c.version>=10});critical('navigation-physical-contract',()=>{const N=V.territorialNavigation;return typeof N.isWalkable==='function'&&typeof N.route==='function'&&typeof N.nextWaypoint==='function'&&typeof N.invalidate==='function'&&typeof N.move==='function'});critical('navigation-resilience',()=>{const f=V.territorialNavigation?.features||[];return f.includes('stuck-recovery')&&f.includes('route-retry')&&f.includes('pedestrian-separation')});
 critical('npc-state-machine',()=>{const f=V.worldLifeDeep?.features||[];return f.includes('explicit-npc-state-machine')&&f.includes('contextual-dwell')&&f.includes('arrival-states')&&f.includes('activity-state-sync')&&V.worldLifeDeep?.version>=11});critical('npc-state-contract',()=>V.population?.movers?.().every(p=>p.lifeState&&Number.isFinite(Number(p.lifeStateSince))));critical('npc-destination-contract',()=>V.population?.movers?.().every(p=>p.lifeDestination&&p.lifeDestination.target&&Number.isFinite(Number(p.lifeDestination.target.x))&&Number.isFinite(Number(p.lifeDestination.target.y))));
 critical('activity-visual-contract',()=>V.activityWorld&&V.activityWorld.version>=2&&V.activityWorld.ready===true&&V.activityWorld.patched===true&&Array.isArray(V.activityWorld.features)&&V.activityWorld.features.includes('state-driven-activity'));critical('contextual-props-contract',()=>V.contextualProps&&V.contextualProps.version>=1&&V.contextualProps.ready===true&&V.contextualProps.patched===true&&Array.isArray(V.contextualProps.features)&&V.contextualProps.features.includes('contextual-props'));
 critical('controls-dom',()=>{const t=document.getElementById('touch');return !!t&&!!document.getElementById('interact')});critical('interaction-dom',()=>!!document.getElementById('dialogue')&&!!document.getElementById('dialogueNext'));critical('unique-script-loads',()=>{const scripts=[...document.scripts].map(s=>s.src).filter(Boolean);return new Set(scripts).size===scripts.length});
 repair('navigation-contract',()=>{const N=V.territorialNavigation;if(!N)return false;let r=false;if(typeof N.clear!=='function'){N.clear=N.invalidate||(()=>{});r=true}return r});I.checks=checks.map(x=>({...x}));I.ready=I.fatal.length===0;I.lastRun=Date.now();I.version=6.33;V.systemIntegrity=I;return I}
V.runSystemAudit=run;function boot(){try{run()}catch(e){I.ready=false;I.fatal=['audit-runtime'];I.error=String(e?.message||e)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0);setTimeout(boot,1200);
})();
