/* Villa Pelón V6.9.0 — CICLO COMERCIAL FUNCIONAL
   Extiende la autoridad de V4 Playability sin crear otra economía/inventario.
   Añade una tienda contextual reutilizable: precio, dinero, compra, inventario,
   guardado y avance de misión quedan conectados al estado existente.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const S=V.shopFlow=V.shopFlow||{version:1,enabled:true,patched:false};
const KEY='villa_pelon_v4_player';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function state(){return V.state||(V.state={})}
function save(){if(typeof V.v4Playability?.save==='function'){V.v4Playability.save();return}try{const s=state();localStorage.setItem(KEY,JSON.stringify({inventory:s.inventory||[],money:Number(s.money)||0,energy:Number(s.energy)||0,mission:Number(s.mission)||0,flags:s.flags||{},version:4}))}catch(_){} }
function has(item){return Array.isArray(state().inventory)&&state().inventory.some(x=>String(x).toLowerCase()===item.toLowerCase()||String(x).toLowerCase().includes(item.toLowerCase()))}
function refresh(){if(typeof V.v4Playability?.refreshMission==='function')V.v4Playability.refreshMission();const money=document.getElementById('money');if(money)money.textContent=Math.round(Number(state().money)||0)}
function toast(text){if(typeof V.v4Playability?.toast==='function'){V.v4Playability.toast(text);return}const d=document.createElement('div');d.className='v4p-toast';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function buy(item,price){const s=state();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.money=Number.isFinite(s.money)?s.money:0;if(has(item)){toast('Ya tenés '+item.toLowerCase()+' en la mochila.');return false}if(s.money<price){toast('No alcanza el dinero · necesitás $'+price);return false}s.money-=price;s.inventory.push(item);s.flags=s.flags||{};s.flags.shop_last_purchase=item;save();refresh();toast('COMPRA REALIZADA · '+item+' · -$'+price);if(item==='Pan'&&s.mission===1&&typeof V.v4Playability?.complete==='function')V.v4Playability.complete('mandado');return true}
function open(shop){const label=shop?.label||shop?.name||'ALMACÉN';if(!state().started)return false;const panel=document.getElementById('v4pPanel');if(panel){panel.remove();V.v4Playability.open=null}if(!V.v4Playability)return false;const html='<div class="v4p-shop-balance"><b>DINERO DISPONIBLE</b><span>$'+Math.round(Number(state().money)||0)+'</span></div><div class="v4p-grid"><div class="v4p-card v4p-shop-item"><h3>PAN</h3><p>Un mandado cotidiano. Sirve para la misión actual y para llevarle a Raúl.</p><p class="v4p-price">$120</p><button class="v4p-action" data-buy="Pan" data-price="120">COMPRAR PAN</button></div><div class="v4p-card v4p-shop-item"><h3>YERBA</h3><p>Un objeto cotidiano para seguir ampliando las actividades del pueblo.</p><p class="v4p-price">$900</p><button class="v4p-action" data-buy="Yerba" data-price="900">COMPRAR YERBA</button></div></div><p class="v4p-shop-note">Cada compra actualiza dinero, mochila, misión y guardado. Los objetos no se duplican.</p>';
const p=V.v4Playability.open?null:document.body.appendChild(document.createElement('div'));if(p){p.id='v4pPanel';p.className='v4p-panel';p.innerHTML='<div class="v4p-head"><strong>'+esc(label)+'</strong><button class="v4p-close">CERRAR</button></div><div class="v4p-body">'+html+'</div>';p.querySelector('.v4p-close').onclick=()=>{p.remove();V.v4Playability.open=null};p.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy,Number(b.dataset.price)));V.v4Playability.open=p;return true}return false}
function patch(){const G=V.v4Playability;if(!G||S.patched||typeof G.interact!=='function')return false;const original=G.interact;G.interact=function(){const s=state();let target=null;if(typeof V.worldInteractionAPI?.nearest==='function')target=V.worldInteractionAPI.nearest();else if(typeof V.engine?.nearest==='function')target=V.engine.nearest();if(target&&(target.type==='shop'||target.type==='bakery'))return open(target);return original.apply(this,arguments)};S.patched=true;S.hook='V.v4Playability.interact';return true}
patch();setTimeout(patch,250);setTimeout(patch,800);S.features=['contextual-shop','bread-purchase','yerba-purchase','money-sync','inventory-sync','mission-sync','save-sync','no-duplicate-items'];
})();
