/* Villa Pelón V73 — runtime de interiores.
   Convierte la entrada de edificios en espacios con identidad, objetos y personas.
   No duplica el mapa exterior: consume el estado de V.buildings71.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const R={version:'V73',active:null,rooms:{
 escuela:{title:'Escuela',subtitle:'Aula y memoria del pueblo',objects:[['archivo','Archivo escolar','Cuadernos, fotos y registros de generaciones.'],['patio','Patio','El lugar donde transcurrieron miles de recreos.']]},
 radio:{title:'Radio Oasis',subtitle:'La voz cotidiana',objects:[['microfono','Micrófono','Un punto de encuentro entre vecinos y territorio.'],['archivo','Archivo de programas','Las voces también construyen memoria.']]},
 almacen:{title:'Almacén',subtitle:'Provisiones y encuentros',objects:[['pan','Mostrador','Pan, yerba y productos de todos los días.'],['libreta','Libreta','Las cuentas y los nombres también cuentan una historia.']]},
 galpon:{title:'Galpón rural',subtitle:'Herramientas y trabajo',objects:[['herramientas','Herramientas','Elementos de trabajo de la chacra.'],['cajones','Cajones','Preparados para cosecha y traslado.']]},
 bodega:{title:'Bodega',subtitle:'Producción y transformación',objects:[['cosecha','Cosecha','El producto del trabajo de la tierra.'],['herramientas','Herramientas','Tecnología y trabajo detrás de la producción.']]},
 casa:{title:'Vivienda',subtitle:'Vida cotidiana',objects:[['mate','Mate','Una pausa sencilla de la vida diaria.'],['mesa','Mesa familiar','Un lugar para conversar, comer y descansar.']]}
}};
function room(){const b=V.buildings71?.getState?.();if(!b)return null;const key=b.type==='school'?'escuela':b.type==='shop'?'almacen':b.type;return R.rooms[key]?{...R.rooms[key],id:key}:null}
function toast(text){if(V.interactions69?.lastMessage!==undefined)V.interactions69.lastMessage=text;let d=document.getElementById('vp73-toast');if(!d){d=document.createElement('div');d.id='vp73-toast';document.body.appendChild(d)}d.textContent=text;d.classList.add('show');clearTimeout(d.__t);d.__t=setTimeout(()=>d.classList.remove('show'),2600)}
function ensure(){let el=document.getElementById('v73-room');if(el)return el;el=document.createElement('div');el.id='v73-room';el.innerHTML='<div class="v73-shell"><div class="v73-kicker">INTERIOR · VILLA PELÓN</div><h2></h2><p class="v73-sub"></p><div class="v73-grid"></div><div class="v73-people"></div><button class="v73-exit" type="button">SALIR · E</button></div>';document.body.appendChild(el);el.querySelector('.v73-exit').onclick=()=>V.buildings71?.exit();return el}
function render(){const r=room(),el=ensure();if(!r){el.classList.remove('active');return}el.querySelector('h2').textContent=r.title;el.querySelector('.v73-sub').textContent=r.subtitle;const grid=el.querySelector('.v73-grid');grid.innerHTML='';r.objects.forEach(o=>{const b=document.createElement('button');b.type='button';b.innerHTML='<strong>'+o[1]+'</strong><span>'+o[2]+'</span>';b.onclick=()=>{if(V.addItem)V.addItem('Registro: '+o[1]);toast(o[2]);if(V.worldEvent)V.worldEvent('object-inspect',{building:r.id,object:o[0]})};grid.appendChild(b)});const people=el.querySelector('.v73-people');people.innerHTML='<b>PERSONAS</b><span>El interior forma parte de la vida del pueblo. Próximamente los vecinos tendrán rutinas y conversaciones propias dentro de este espacio.</span>';el.classList.add('active')}
function style(){if(document.getElementById('v73-style'))return;const s=document.createElement('style');s.id='v73-style';s.textContent='#v73-room{position:fixed;inset:0;z-index:10001;display:none;place-items:center;background:rgba(17,21,18,.96);font-family:system-ui,sans-serif;color:#eee}#v73-room.active{display:grid}.v73-shell{width:min(820px,90vw);min-height:470px;padding:32px;background:linear-gradient(180deg,#75654d,#40382e);border:2px solid rgba(220,205,164,.55);box-shadow:0 24px 80px #000}.v73-kicker{font:12px monospace;letter-spacing:.18em;opacity:.65}.v73-shell h2{font-size:36px;margin:8px 0 2px}.v73-sub{margin:0;opacity:.72}.v73-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:38px 0}.v73-grid button{min-height:105px;text-align:left;padding:18px;background:rgba(20,20,16,.22);border:1px solid rgba(255,255,255,.12);color:#f4ead1;cursor:pointer}.v73-grid button:hover{background:rgba(255,255,255,.10)}.v73-grid strong,.v73-grid span{display:block}.v73-grid span{margin-top:8px;line-height:1.4;opacity:.68;font-size:13px}.v73-people{display:grid;gap:6px;padding:16px 0;border-top:1px solid rgba(255,255,255,.15);font-size:12px;opacity:.78}.v73-people span{line-height:1.5}.v73-exit{padding:12px 18px;border:0;background:#d8c59a;font-weight:800;cursor:pointer}#vp73-toast{position:fixed;left:50%;bottom:35px;transform:translate(-50%,12px);opacity:0;pointer-events:none;padding:12px 16px;max-width:85vw;background:rgba(18,23,18,.96);border:1px solid #b6a77c;color:#f4ead1;font:13px monospace;z-index:10002;transition:.18s}#vp73-toast.show{opacity:1;transform:translate(-50%,0)}@media(max-width:600px){.v73-shell{padding:22px}.v73-shell h2{font-size:28px}.v73-grid{grid-template-columns:1fr;margin:24px 0}.v73-grid button{min-height:90px}}';document.head.appendChild(s)}
function install(){style();window.addEventListener('villa-pelon-world-event',e=>{if(e.detail?.type==='building-enter'||e.detail?.type==='building-exit')setTimeout(render,0)});render()}
R.inspect=(id)=>{const r=room();const o=r?.objects.find(x=>x[0]===id);if(o)toast(o[2])};V.interior73=R;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
