/* Villa Pelón V78.2 — interiores espaciales reales.
   Congela el estado exterior mientras el interior está activo.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const I={version:'V78.2',inside:null,snapshot:null,player:{x:400,y:280},speed:155,input:{up:false,down:false,left:false,right:false},rooms:{
 escuela:{label:'Escuela',type:'school',description:'Aula, patio y memoria de generaciones.',objects:[['archivo','Archivo escolar',120,120],['pupitres','Pupitres',330,155],['mapa','Mapa del territorio',560,110]]},
 radio:{label:'Radio Oasis',type:'radio',description:'La voz cotidiana',objects:[['microfono','Micrófono',210,145],['archivo','Archivo de programas',520,135],['consola','Consola de radio',360,300]]},
 almacen:{label:'Almacén',type:'shop',description:'Provisiones y encuentros de todos los días.',objects:[['mostrador','Mostrador',530,285],['libreta','Libreta de cuentas',600,145],['pan','Pan de campo',180,260]]},
 galpon:{label:'Galpón rural',type:'rural',description:'Herramientas, máquinas y trabajo de chacra.',objects:[['herramientas','Herramientas',170,150],['cajones','Cajones de cosecha',500,180],['banco','Banco de trabajo',340,300]]},
 bodega:{label:'Bodega',type:'rural',description:'Producción, cosecha y transformación del territorio.',objects:[['cosecha','Cosecha',170,180],['herramientas','Herramientas',470,145],['mesa','Mesa de trabajo',360,300]]},
 casa:{label:'Vivienda',type:'home',description:'Una casa también guarda historias familiares.',objects:[['mate','Mate',220,220],['mesa','Mesa familiar',430,220],['foto','Fotografías familiares',600,120]]}
}};
function canvas(){return document.getElementById('world')}
function ctx(){return canvas()?.getContext('2d')}
function player(){return V.gameState||{x:0,y:0}}
function roomFor(b){const key=b?.id||b?.meta?.id||b?.type;if(key&&I.rooms[key])return key;if(b?.meta?.type==='shop')return 'almacen';if(b?.meta?.type==='school')return 'escuela';if(b?.meta?.type==='radio')return 'radio';if(b?.meta?.type==='rural')return b.id==='bodega'?'bodega':'galpon';return 'casa'}
function nearObject(){if(!I.inside)return null;const r=I.rooms[I.inside.id],p=I.player;let best=null,d=Infinity;r.objects.forEach(o=>{const q=Math.hypot(p.x-o[2],p.y-o[3]);if(q<68&&q<d){d=q;best=o}});return best}
function toast(t){if(V.ui67?.toast)return V.ui67.toast(t);const el=document.createElement('div');el.textContent=t;el.style='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:12000;background:#20251f;color:#fff;padding:12px 18px;border:1px solid #d8c59a;font:600 14px system-ui;border-radius:6px';document.body.appendChild(el);setTimeout(()=>el.remove(),1700)}
function enter(b){if(!b||I.inside)return false;const r=roomFor(b),g=player();I.snapshot={x:g.x,y:g.y,minutes:g.minutes,energy:g.energy};I.inside={id:r,buildingId:b.id||r,enteredAt:Date.now()};I.player={x:400,y:285};g.dialogue=true;if(V.buildings71){V.buildings71.inside=I.inside;V.buildings71.snapshot=I.snapshot}if(V.worldEvent)V.worldEvent('spatial-enter',{building:I.inside.buildingId,room:r});return true}
function exit(){if(!I.inside)return false;const old=I.inside,g=player();if(I.snapshot){g.x=I.snapshot.x;g.y=I.snapshot.y;g.minutes=I.snapshot.minutes;g.energy=I.snapshot.energy}I.inside=null;I.player={x:400,y:285};g.dialogue=false;if(V.buildings71){V.buildings71.inside=null;V.buildings71.snapshot=null}if(V.worldEvent)V.worldEvent('spatial-exit',{building:old.buildingId,room:old.id});return true}
function move(dt){const p=I.player;let dx=(I.input.right?1:0)-(I.input.left?1:0),dy=(I.input.down?1:0)-(I.input.up?1:0);if(!dx&&!dy)return;const l=Math.hypot(dx,dy);dx/=l;dy/=l;const nx=p.x+dx*I.speed*dt,ny=p.y+dy*I.speed*dt;if(nx>55&&nx<745)p.x=nx;if(ny>70&&ny<430)p.y=ny;const g=player();g.minutes+=dt*0.18;g.energy=Math.max(0,g.energy-dt*.03)}
function interact(){if(!I.inside)return false;const o=nearObject();if(o){const item='Registro interior: '+o[1];if(typeof V.addItem==='function')V.addItem(item);toast(o[1]+' · registrado');if(V.worldEvent)V.worldEvent('interior-object',{room:I.inside.id,object:o[0]});return true}if(I.player.y<105){exit();return true}return false}
function draw(){if(!I.inside)return;const c=ctx(),cv=canvas();if(!c||!cv)return;const w=cv.clientWidth,h=cv.clientHeight;c.save();c.setTransform(1,0,0,1,0,0);c.fillStyle='#2c2923';c.fillRect(0,0,w,h);const sx=Math.max(24,(w-800)/2),sy=Math.max(54,(h-510)/2),rw=Math.min(800,w-48),rh=Math.min(510,h-90);c.fillStyle='#6f5a43';c.fillRect(sx,sy,rw,rh);c.strokeStyle='#d8c59a';c.lineWidth=4;c.strokeRect(sx,sy,rw,rh);c.fillStyle='#826c50';c.fillRect(sx+18,sy+18,rw-36,rh-36);const scale=Math.min((rw-36)/800,(rh-36)/510),ox=sx+18,oy=sy+18;c.save();c.translate(ox,oy);c.scale(scale,scale);c.fillStyle='#9a8465';c.fillRect(0,0,800,510);c.fillStyle='#65513f';c.fillRect(0,0,800,38);c.fillStyle='#e8dfc9';c.font='bold 20px system-ui';c.fillText(I.rooms[I.inside.id].label,18,26);c.fillStyle='#4c3c2e';c.fillRect(0,472,800,38);c.fillStyle='#d8c59a';c.fillRect(360,0,80,18);c.font='bold 12px system-ui';c.fillStyle='#f3ead3';c.fillText('SALIDA',378,14);I.rooms[I.inside.id].objects.forEach(o=>{c.fillStyle='#3d342a';c.fillRect(o[2]-34,o[3]-24,68,48);c.fillStyle='#c5aa76';c.fillRect(o[2]-27,o[3]-18,54,36);c.fillStyle='#29251f';c.font='11px system-ui';c.textAlign='center';c.fillText(o[1],o[2],o[3]+4)});const p=I.player;c.fillStyle='rgba(20,20,16,.3)';c.beginPath();c.ellipse(p.x,p.y+17,14,5,0,0,Math.PI*2);c.fill();c.fillStyle='#2f5d46';c.fillRect(p.x-11,p.y-9,22,25);c.fillStyle='#d9a27c';c.fillRect(p.x-9,p.y-29,18,18);c.fillStyle='#332923';c.fillRect(p.x-10,p.y-30,20,6);c.restore();c.restore();const o=nearObject();c.save();c.setTransform(1,0,0,1,0,0);c.fillStyle='rgba(20,24,20,.84)';c.fillRect(16,h-70,Math.min(560,w-32),52);c.fillStyle='#fff';c.font='600 13px system-ui';c.fillText(o?'E · '+o[1]:'WASD / flechas · caminar',30,h-48);c.fillText('E · interactuar · E cerca de la puerta superior para salir',30,h-27);c.fillStyle='#d8c59a';c.font='bold 11px system-ui';c.fillText('INTERIOR V78',w-100,26);c.restore()}
function bind(){window.addEventListener('keydown',e=>{if(!I.inside)return;const k=e.key.toLowerCase();if(['arrowup','w'].includes(k)){I.input.up=true;e.preventDefault();e.stopImmediatePropagation()}if(['arrowdown','s'].includes(k)){I.input.down=true;e.preventDefault();e.stopImmediatePropagation()}if(['arrowleft','a'].includes(k)){I.input.left=true;e.preventDefault();e.stopImmediatePropagation()}if(['arrowright','d'].includes(k)){I.input.right=true;e.preventDefault();e.stopImmediatePropagation()}if(k==='e'||k===' '){e.preventDefault();e.stopImmediatePropagation();interact()}},{capture:true});window.addEventListener('keyup',e=>{if(!I.inside)return;const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))I.input.up=false;if(['arrowdown','s'].includes(k))I.input.down=false;if(['arrowleft','a'].includes(k))I.input.left=false;if(['arrowright','d'].includes(k))I.input.right=false},{capture:true});const button=document.getElementById('interact');if(button)button.addEventListener('pointerdown',e=>{if(!I.inside)return;e.preventDefault();e.stopImmediatePropagation();interact()},{capture:true});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{if(!I.inside)return;e.preventDefault();I.input[k]=true},{capture:true});['pointerup','pointercancel','pointerleave','lostpointercapture'].forEach(ev=>b.addEventListener(ev,()=>{if(I.inside)I.input[k]=false},{capture:true})})}
function loop(t){const dt=Math.min(.033,((t-I.last)||16)/1000);I.last=t;if(I.inside)move(dt);draw();requestAnimationFrame(loop)}
function install(){if(V.__v78Installed)return;V.__v78Installed=true;V.spatialInteriors78=I;const B=V.buildings71;if(B){B.enter=enter;B.exit=exit;B.getState=()=>I.inside;B.interact=()=>I.inside?exit():false}bind();I.last=performance.now();requestAnimationFrame(loop)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
