/* Villa Pelón V88 — experiencia de entrada + menú profesional + gráficos. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),S=V.gameState,$=id=>document.getElementById(id);
const KEY='villa_pelon_ux_v88';
let cfg={language:'es',graphics:'high',fullscreen:false,motion:true};
try{cfg={...cfg,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){}
const TEXT={
es:{continue:'CONTINUAR',back:'ATRÁS',enter:'ENTRAR AL MUNDO',menu:'MENÚ',resume:'CONTINUAR',restart:'REINICIAR JUEGO',language:'IDIOMA',graphics:'GRÁFICOS',motion:'EFECTOS DE MOVIMIENTO',fullscreen:'PANTALLA COMPLETA',close:'CERRAR',low:'BAJO',medium:'EQUILIBRADO',high:'ALTO',on:'ACTIVADOS',off:'DESACTIVADOS',confirm:'¿Querés reiniciar la partida? Se perderá el progreso no guardado.',pages:[['ANTES DEL PUEBLO','Antes de las calles, las casas y las bodegas, hubo una tierra atravesada por el viento, el río, las bardas y los cauces. Este mundo comienza allí: en el territorio.'],['EL AGUA CAMBIÓ LA TIERRA','El agua abrió caminos nuevos. Las acequias, las chacras y el trabajo cotidiano transformaron el paisaje y permitieron que aparecieran nuevas formas de vida.'],['UN PUEBLO SE HACE ENTRE TODOS','La historia no vive solamente en fechas. Está en una escuela, una radio, una herramienta, una fotografía, una conversación y en las personas que recuerdan.'],['TU HISTORIA EMPIEZA CAMINANDO','En Villa Pelón vas a poder recorrer el pueblo y la zona rural, entrar a lugares, hablar con vecinos, trabajar, comprar cosas y descubrir pistas. No todo se revela de golpe.'],['UNA HISTORIA PARA DESCUBRIR','Tu objetivo es reconstruir el territorio a través de misiones. Algunas respuestas estarán en los diálogos; otras, en los lugares que recorras. Cuando la historia real se incorpore, deberá estar respaldada por fuentes verificables.']]},
en:{continue:'CONTINUE',back:'BACK',enter:'ENTER WORLD',menu:'MENU',resume:'RESUME',restart:'RESTART GAME',language:'LANGUAGE',graphics:'GRAPHICS',motion:'MOTION EFFECTS',fullscreen:'FULLSCREEN',close:'CLOSE',low:'LOW',medium:'BALANCED',high:'HIGH',on:'ON',off:'OFF',confirm:'Restart the game? Unsaved progress will be lost.',pages:[['BEFORE THE TOWN','Before streets, houses and wineries, there was land shaped by wind, river, cliffs and waterways. This world begins there: in the territory.'],['WATER CHANGED THE LAND','Water opened new paths. Irrigation channels, farms and everyday work transformed the landscape and made new forms of life possible.'],['A TOWN IS BUILT TOGETHER','History lives not only in dates. It lives in a school, a radio, a tool, a photograph, a conversation and in the people who remember.'],['YOUR STORY STARTS BY WALKING','In Villa Pelón you can explore the town and countryside, enter places, talk to neighbors, work, shop and discover clues. Not everything is revealed at once.'],['A STORY TO DISCOVER','Your goal is to reconstruct the territory through missions. Some answers are in dialogue; others are in the places you explore. Real history must be backed by verifiable sources.']]}};
function tr(){return TEXT[cfg.language==='en'?'en':'es']}
function saveCfg(){localStorage.setItem(KEY,JSON.stringify(cfg));document.documentElement.lang=cfg.language==='en'?'en':'es'}
function style(){if($('v88-style'))return;const s=document.createElement('style');s.id='v88-style';s.textContent=`#v88Intro{position:fixed;inset:0;z-index:20000;display:grid;place-items:center;background:radial-gradient(circle at 50% 35%,#4b5f4d 0,#202b25 58%,#121713 100%);color:#f4eedf;font-family:system-ui,sans-serif;padding:22px;box-sizing:border-box}#v88Intro.hidden,#v88Menu.hidden{display:none}#v88Intro .card,#v88Menu .card{width:min(760px,94vw);background:rgba(18,23,19,.88);border:1px solid rgba(226,210,166,.35);box-shadow:0 28px 90px #0008;backdrop-filter:blur(8px);padding:clamp(24px,5vw,54px);box-sizing:border-box}.v88-kicker{font-size:11px;letter-spacing:.24em;opacity:.65}.v88-page{min-height:280px;display:flex;flex-direction:column;justify-content:center}.v88-page h1{font-size:clamp(30px,6vw,58px);line-height:.98;margin:16px 0}.v88-page p{font-size:clamp(16px,2vw,20px);line-height:1.65;max-width:650px;color:#ddd8c9}.v88-progress{display:flex;gap:7px;margin:24px 0}.v88-dot{width:30px;height:3px;background:#665f51}.v88-dot.active{background:#d8c59a}.v88-actions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap}.v88-btn{border:1px solid rgba(216,197,154,.45);background:#d8c59a;color:#1e241f;padding:13px 18px;font-weight:800;cursor:pointer}.v88-btn.alt{background:transparent;color:#f4eedf}.v88-menu{position:fixed;inset:0;z-index:19000;display:grid;place-items:center;background:#0c110dbd;padding:20px}.v88-menu h2{font-size:32px;margin:8px 0 24px}.v88-row{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;border-top:1px solid #ffffff18;padding:15px 0}.v88-row span{font-weight:700}.v88-choice{display:flex;gap:5px;flex-wrap:wrap}.v88-choice button{border:1px solid #ffffff2c;background:#ffffff08;color:#eee;padding:9px 11px;cursor:pointer}.v88-choice button.active{background:#d8c59a;color:#1e241f}.v88-menu-actions{display:grid;gap:9px;margin-top:18px}.v88-menu-actions button{padding:13px;border:1px solid #ffffff2c;background:#ffffff0d;color:#eee;cursor:pointer;text-align:left}.v88-menu-actions button.primary{background:#d8c59a;color:#1e241f;font-weight:800}body.v88-low #world,body.v88-low #vpPlayerOverlay{filter:saturate(.75) contrast(.95)}body.v88-medium #world,body.v88-medium #vpPlayerOverlay{filter:saturate(.9)}body.v88-high #world,body.v88-high #vpPlayerOverlay{filter:none}body.v88-no-motion *{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}`;document.head.appendChild(s)}
function buildIntro(){style();let root=$('v88Intro');if(!root){root=document.createElement('div');root.id='v88Intro';document.body.appendChild(root)}let i=0,pages=tr().pages;function render(){const last=i===pages.length-1;root.innerHTML='<div class="card"><div class="v88-kicker">VILLA PELÓN · '+(i+1)+' / '+pages.length+'</div><div class="v88-page"><h1>'+pages[i][0]+'</h1><p>'+pages[i][1]+'</p></div><div class="v88-progress">'+pages.map((_,n)=>'<span class="v88-dot '+(n<=i?'active':'')+'"></span>').join('')+'</div><div class="v88-actions">'+(i?'<button class="v88-btn alt" data-back>'+tr().back+'</button>':'')+'<button class="v88-btn" data-next>'+ (last?tr().enter:tr().continue) +'</button></div></div>';root.querySelector('[data-back]')?.addEventListener('click',()=>{i--;render()});root.querySelector('[data-next]').addEventListener('click',()=>{if(!last){i++;render()}else{root.classList.add('hidden');startGame()}})}render();return root}
function startGame(){const b=$('startBtn');if(V.__v88OriginalStart)V.__v88OriginalStart.call(b);else{S.started=true;$('start')?.classList.add('hidden');$('game')?.classList.remove('hidden')}setTimeout(()=>{V.persistence72?.load?.();S.started=true;$('start')?.classList.add('hidden');$('game')?.classList.remove('hidden')},0)}
function buildMenu(){style();let m=$('v88Menu');if(!m){m=document.createElement('div');m.id='v88Menu';m.className='hidden v88-menu';document.body.appendChild(m)}function render(){const t=tr();m.innerHTML='<div class="card"><div class="v88-kicker">VILLA PELÓN · CONFIGURACIÓN</div><h2>'+t.menu+'</h2><div class="v88-row"><span>'+t.language+'</span><div class="v88-choice"><button data-lang="es" class="'+(cfg.language==='es'?'active':'')+'">ES</button><button data-lang="en" class="'+(cfg.language==='en'?'active':'')+'">EN</button></div></div><div class="v88-row"><span>'+t.graphics+'</span><div class="v88-choice"><button data-g="low" class="'+(cfg.graphics==='low'?'active':'')+'">'+t.low+'</button><button data-g="medium" class="'+(cfg.graphics==='medium'?'active':'')+'">'+t.medium+'</button><button data-g="high" class="'+(cfg.graphics==='high'?'active':'')+'">'+t.high+'</button></div></div><div class="v88-row"><span>'+t.motion+'</span><div class="v88-choice"><button data-motion="0" class="'+(!cfg.motion?'active':'')+'">'+t.off+'</button><button data-motion="1" class="'+(cfg.motion?'active':'')+'">'+t.on+'</button></div></div><div class="v88-menu-actions"><button class="primary" data-a="resume">'+t.resume+'</button><button data-a="fullscreen">'+t.fullscreen+'</button><button data-a="restart">'+t.restart+'</button><button data-a="close">'+t.close+'</button></div></div>';m.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{cfg.language=b.dataset.lang;saveCfg();render()});m.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{cfg.graphics=b.dataset.g;saveCfg();apply();render()});m.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>{cfg.motion=b.dataset.motion==='1';saveCfg();apply();render()});m.querySelector('[data-a=resume]').onclick=closeMenu;m.querySelector('[data-a=close]').onclick=closeMenu;m.querySelector('[data-a=fullscreen]').onclick=fullscreen;m.querySelector('[data-a=restart]').onclick=()=>{if(confirm(t.confirm))restart()}}
render();return m}
function openMenu(){const m=buildMenu();m.classList.remove('hidden');if(S)S._menuPaused=true;V.deepAudit84?.releaseInput?.()}
function closeMenu(){const m=$('v88Menu');m?.classList.add('hidden');if(S){S._menuPaused=false;S.dialogue=false}V.deepAudit84?.releaseInput?.()}
function toggleMenu(){if($('v88Menu')&&!$('v88Menu').classList.contains('hidden'))closeMenu();else openMenu()}
function fullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.()}
function restart(){Object.assign(S,{started:true,x:960,y:650,speed:205,money:10000,energy:100,minutes:480,day:1,quest:0,dialogue:false,saved:false,inventory:[],walk:0,facing:'down'});localStorage.removeItem('villa_pelon_save');for(let i=1;i<=3;i++)localStorage.removeItem('villa_pelon_save_slot_'+i);closeMenu();$('start')?.classList.add('hidden');$('game')?.classList.remove('hidden');buildIntro().classList.add('hidden');V.persistence72?.save?.()}
function apply(){document.body.classList.remove('v88-low','v88-medium','v88-high','v88-no-motion');document.body.classList.add('v88-'+cfg.graphics);if(!cfg.motion)document.body.classList.add('v88-no-motion');saveCfg()}
function install(){style();apply();const b=$('startBtn');if(b){V.__v88OriginalStart=b.onclick;b.onclick=()=>{};buildIntro().classList.remove('hidden');$('start')?.classList.add('hidden')}const mb=$('vpMenuButton');if(mb)mb.onclick=e=>{e.preventDefault();toggleMenu()};else{const g=$('game');if(g){const x=document.createElement('button');x.id='v88MenuOpen';x.className='v88-btn';x.textContent='☰';x.style.cssText='position:absolute;right:14px;top:54px;z-index:20';x.onclick=toggleMenu;g.appendChild(x)}}V.professionalUX88={version:'88.0.0',openMenu,closeMenu,toggleMenu,restart,apply,cfg};window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m'){e.preventDefault();toggleMenu()}},{capture:false})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
