/* V62 FALLBACK — autoridad de jugabilidad de emergencia. Garantiza movimiento, jugador visible y vida básica. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),C=document.getElementById('world');if(!C)return;const X=C.getContext('2d',{alpha:false});X.imageSmoothingEnabled=false,S=V.gameState||window.__villaPelonState;if(!S)return;
const I={up:false,down:false,left:false,right:false};let W=innerWidth,H=innerHeight,last=performance.now(),camX=0,camY=0;
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,W*d);C.height=Math.max(1,H*d);C.style.width=W+'px';C.style.height=H+'px';X.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize,{passive:true});resize();
function set(k,v){if(k==='up'||k==='down'||k==='left'||k==='right')I[k]=v}
addEventListener('keydown',e=>{const k=e.key.toLowerCase(),m={w:'up',arrowup:'up',s:'down',arrowdown:'down',a:'left',arrowleft:'left',d:'right',arrowright:'right'}[k];if(m){set(m,true);e.preventDefault()}if(k==='e'||k===' '){if(typeof V.interact==='function')V.interact();else if(typeof V.openDialogue==='function')V.openDialogue('VILLA PELÓN',['Acercate a una persona o lugar para interactuar.'])}});
addEventListener('keyup',e=>{const m={w:'up',arrowup:'up',s:'down',arrowdown:'down',a:'left',arrowleft:'left',d:'right',arrowright:'right'}[e.key.toLowerCase()];if(m)set(m,false)});
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();set(k,true);try{b.setPointerCapture(e.pointerId)}catch(_){}});['pointerup','pointercancel','lostpointercapture'].forEach(t=>b.addEventListener(t,()=>set(k,false)))});
addEventListener('blur',()=>Object.keys(I).forEach(k=>I[k]=false));
document.getElementById('startBtn')?.addEventListener('click',()=>{setTimeout(()=>{S.started=true;document.getElementById('start')?.classList.add('hidden');document.getElementById('game')?.classList.remove('hidden');last=performance.now()},20)});
function geom(){return V.worldAuthority?.geometry||V.worldGeometry||{width:3200,height:2000,buildings:[]}}
function blocked(x,y){const g=geom();if(x<35||y<35||x>g.width-35||y>g.height-35)return true;return (g.buildings||[]).some(b=>x>b.x-14&&x<b.x+(b.w||0)+14&&y>b.y-14&&y<b.y+(b.h||0)+14)}
function move(dt){if(!S.started||S.dialogue||S.transport)return;let dx=(I.right?1:0)-(I.left?1:0),dy=(I.down?1:0)-(I.up?1:0);if(!dx&&!dy){S.walk=0;return}const l=Math.hypot(dx,dy);dx/=l;dy/=l;const speed=Number(S.speed)>0?Math.min(Number(S.speed),205):205,nx=S.x+dx*speed*dt,ny=S.y+dy*speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;S.walk=(S.walk||0)+dt*9;S.facing=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');S.energy=Math.max(0,(S.energy||100)-dt*.45);S.minutes=(S.minutes||480)+dt*3.5}
function worldToScreen(x,y){const z=.78;return{x:(x-camX)*z,y:(y-camY)*z}}
function person(x,y,o={}){const p=worldToScreen(x,y),moving=!!o.moving,w=moving?Math.floor((o.walk||0)*2)%2:0;X.fillStyle='rgba(20,20,15,.28)';X.beginPath();X.ellipse(p.x,p.y+17,13,5,0,0,Math.PI*2);X.fill();X.fillStyle=o.player?'#263f34':'#7a5a48';X.fillRect(p.x-10,p.y-2,20,19);X.fillStyle=o.player?'#d9a27c':'#d5a07d';X.fillRect(p.x-8,p.y-20,16,16);X.fillStyle=o.player?'#332923':'#40342e';X.fillRect(p.x-9,p.y-21,18,5);X.fillStyle='#304b67';X.fillRect(p.x-8,p.y+17+w,6,12);X.fillRect(p.x+2,p.y+17-w,6,12)}
function draw(){const g=geom(),z=.78;X.fillStyle='#7d9a68';X.fillRect(0,0,W,H);const r=g.river;if(r){const p=worldToScreen(r.x,r.y);X.fillStyle='#5c9ca4';X.fillRect(p.x,p.y,(r.w||g.width)*z,(r.h||190)*z)}(g.roads||[]).forEach(r=>{const p=worldToScreen(r.x,r.y);X.fillStyle='#8b8170';X.fillRect(p.x,p.y,(r.w||80)*z,(r.h||24)*z)});(g.buildings||[]).forEach(b=>{const p=worldToScreen(b.x,b.y);X.fillStyle='#b99a78';X.fillRect(p.x,p.y,(b.w||100)*z,(b.h||70)*z);X.fillStyle='#704f45';X.fillRect(p.x+8,p.y+8,(b.w||100)*z-16,18);X.fillStyle='#242820';X.fillRect(p.x+(b.w||100)*z*.43,p.y+(b.h||70)*z-28,22,28)});(V.npcs||[]).forEach(n=>person(n.x,n.y,{moving:false,walk:n.walk}));person(S.x,S.y,{player:true,moving:I.up||I.down||I.left||I.right,walk:S.walk});X.fillStyle='rgba(10,15,11,.65)';X.fillRect(8,H-42,220,32);X.fillStyle='#eee3c5';X.font='12px system-ui';X.fillText('V62 · MOVIMIENTO ACTIVO',18,H-22)}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;move(dt);const g=geom(),z=.78;camX=Math.max(0,Math.min((g.width||3200)-W/z,S.x-W/(2*z)));camY=Math.max(0,Math.min((g.height||2000)-H/z,S.y-H/(2*z)));draw();requestAnimationFrame(loop)}
requestAnimationFrame(loop);V.emergencyV62={active:true,movement:true,player:true,npcs:true};console.info('[Villa Pelón] V62 fallback activo');
})();