/* VILLA PELÓN — FUNCTIONAL HEALTHCHECK V106.2 */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
function overlap(a,b,pad=0){return a.x<b.x+b.w+pad&&a.x+a.w>b.x-pad&&a.y<b.y+b.h+pad&&a.y+a.h>b.y-pad}
function missionContract(M){
 const list=Array.isArray(M.list)?M.list:[];
 const ids=list.map(x=>x?.id).filter(Boolean),set=new Set(ids);
 const expected=['welcome','memory_01','name_01','community_01','school_01','water_01','production_01','pelon_01','oral_01','archive_01','dni_01','picada21_memory','founding_01','irrigation_02','school_02','worker_01','map_01','bridges_01','research_01','history_01','free_explore'];
 const nextRefs=list.filter(x=>x?.next!=null&&!set.has(x.next)).map(x=>({id:x.id,next:x.next}));
 const terminal=list.filter(x=>x?.next==null).map(x=>x.id);
 const ordered=expected.length===list.length&&expected.every((id,i)=>ids[i]===id);
 return {ok:list.length===21&&ordered&&new Set(ids).size===21&&nextRefs.length===0&&terminal.length===1&&terminal[0]==='free_explore'&&expected.every(id=>set.has(id)),count:list.length,expectedCount:21,ordered,duplicateIds:ids.filter((id,i)=>ids.indexOf(id)!==i),danglingNext:nextRefs,terminal};
}
function worldContract(G){
 const w=G.worldRules||{},r=G.rendering||{},p=G.pixelArt||{};
 const requiredZones=['urban_core','rural_north','productive_rural','picada21','rural_south'];
 const zones=Array.isArray(G.zones)?G.zones:[];
 return {ok:V.world?.w===8200&&V.world?.h===4200&&w.water?.riverCrossing==='bridge_only'&&w.buildings?.neverOccupyRoads===true&&w.roads?.buildingsForbidden===true&&w.roads?.picada21Required===true&&w.simulation?.npcMovementAuthority==='v90_engine'&&w.simulation?.lifeActivityAuthority==='village_life_v99'&&w.simulation?.ambientDataAuthority==='people_vehicles_v91'&&r.authority==='render_compositor_v93'&&r.pixelArt===true&&r.smoothing===false&&p.hardEdges===true&&p.smoothing===false&&p.grid===1&&requiredZones.every(id=>zones.some(z=>z.id===id)),zones:zones.length,riverCrossing:w.water?.riverCrossing,buildingRoadRule:w.buildings?.neverOccupyRoads,renderAuthority:r.authority,pixelGrid:p.grid};
}
function run(){
 const G=V.worldGeometry||{},S=V.gameState||{},M=V.missions||{},B=Array.isArray(G.buildings)?G.buildings:[],R=Array.isArray(G.roads)?G.roads:[],mission=missionContract(M),worldRules=worldContract(G);const checks=[];
 checks.push(['canvas',!!document.getElementById('world')]);checks.push(['renderOverlay',!!document.getElementById('worldDetail')&&V.renderCompositor?.singleRAF===true]);checks.push(['no_duplicate_detail_layer',!document.getElementById('detailLayer')]);checks.push(['gameState',!!V.gameState&&typeof S.x==='number'&&typeof S.y==='number']);checks.push(['engine',!!V.engine]);checks.push(['world',V.world?.w===8200&&V.world?.h===4200]);checks.push(['npc',Array.isArray(V.npcs)&&V.npcs.length>=7]);checks.push(['vehicles',!!V.peopleVehicles&&V.peopleVehicles.vehicles>=9]);checks.push(['people',!!V.peopleVehicles&&V.peopleVehicles.people>=18]);checks.push(['no_npc_overlay',V.peopleVehicles?.npcOverlay===false]);checks.push(['distinct_buildings',B.some(b=>b.type==='hospital')&&B.some(b=>b.type==='library')&&B.some(b=>b.type==='municipality')&&B.some(b=>b.type==='fire_station')]);checks.push(['missions',mission.ok,mission]);checks.push(['world_laws',worldRules.ok,worldRules]);checks.push(['vergel',!!V.vergel&&typeof V.vergel.harvest==='function'&&typeof V.vergel.inspect==='function']);checks.push(['historical_world',V.historicalWorld?.version==='98.0'&&V.historicalWorld.points?.length>=15]);const stop=G.points?.find?.(p=>p.id==='picada21_stop'),route=G.routes?.find?.(r=>r.id==='picada21_route');checks.push(['picada21',!!stop&&+stop.x===7550&&+stop.y===2350&&!!route&&route.points?.at?.(-1)?.x===7900]);const badBuildings=B.filter(b=>R.some(r=>overlap(b,r,0))).map(b=>b.label);checks.push(['no_building_on_road',badBuildings.length===0,badBuildings]);checks.push(['localStorage',(()=>{try{const k='villa_pelon_healthcheck';localStorage.setItem(k,JSON.stringify({ok:true,t:Date.now()}));const ok=JSON.parse(localStorage.getItem(k)).ok===true;localStorage.removeItem(k);return ok}catch(_){return false}})()]);checks.push(['save_api',typeof V.saveGame==='function']);checks.push(['stability',V.stability?.version==='95.1'&&typeof V.stability?.normalize==='function']);checks.push(['integrity',V.integrity?.version==='97.1'&&Array.isArray(V.integrity?.failed)]);checks.push(['architecture_contract',V.engine?.health?.().singleBuildingRenderer===true&&V.architectureContract?.singleBuildingRenderer===true&&V.architectureContract?.buildingRendererOwner==='render_compositor_v93']);const failed=checks.filter(c=>!c[1]);V.health={version:'106.2',ok:failed.length===0,failed:failed.map(c=>c[0]),checkedAt:Date.now(),details:checks};if(failed.length)console.error('[Villa Pelón HEALTHCHECK]',V.health);else console.info('[Villa Pelón HEALTHCHECK] OK',V.health);window.dispatchEvent(new CustomEvent('villa-pelon-health',{detail:V.health}));return V.health}
window.addEventListener('villa-pelon-engine-ready',()=>setTimeout(run,160),{once:true});setTimeout(()=>{if(V.gameState?.started)run()},2600);V.runHealthcheck=run;
})();
