/* VILLA PELÓN — HISTORICAL CAMPAIGN V98
   Extiende la campaña sin crear otro motor. Agrega acciones de investigación y observación.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),M=V.missions;if(!M)return;
const extra=[
 {id:'territory_artifacts_01',chapter:'PATRIMONIO',title:'Los objetos también hablan',description:'Aprendé a mirar objetos del territorio como pistas, sin confundir una interpretación con una fuente.',objectives:[{id:'photo',type:'action',target:'take_photo',label:'Registrá una imagen del mirador'},{id:'water_obs',type:'inspect',target:'water_observation',label:'Observá el recorrido del agua'},{id:'tools',type:'inspect',target:'rural_tools',label:'Examiná los objetos del trabajo rural'}],reward:6800,next:'source_03'},
 {id:'source_03',chapter:'INVESTIGACIÓN',title:'Comparar antes de afirmar',description:'Una buena investigación no junta datos al azar: compara evidencias y reconoce lo que todavía no sabe.',objectives:[{id:'sources',type:'inspect',target:'source_lab',label:'Abrí la mesa de fuentes'},{id:'compare',type:'action',target:'compare_sources',label:'Compará tres tipos de fuente'},{id:'question',type:'inspect',target:'research_question',label:'Escribí una pregunta verificable'}],reward:7600,next:'rural_memory_02'},
 {id:'rural_memory_02',chapter:'TRABAJO',title:'Las huellas del trabajo',description:'Reconocé herramientas, tareas y memoria como parte del patrimonio cotidiano.',objectives:[{id:'tools_action',type:'action',target:'inspect_tools',label:'Examiná las herramientas con atención'},{id:'rosa',type:'talk',target:'rosa',label:'Hablá con Rosa sobre el trabajo rural'},{id:'worker',type:'inspect',target:'worker_marker',label:'Registrá una pista del trabajo'}],reward:7200,next:'landscape_01'},
 {id:'landscape_01',chapter:'PAISAJE',title:'Mirar también es investigar',description:'Aprendé a observar el paisaje antes de sacar conclusiones: agua, caminos, producción y viviendas forman un sistema.',objectives:[{id:'observe',type:'action',target:'observe_landscape',label:'Observá el paisaje durante unos segundos'},{id:'picada',type:'reach',target:'picada21',label:'Volvé a recorrer el camino hacia Picada 21'},{id:'picada_sign',type:'inspect',target:'picada_sign',label:'Leé el cartel de Picada 21'}],reward:8000,next:'free_explore'}
];
const free=M.list.findIndex(m=>m.id==='free_explore');
if(free>=0){const ids=new Set(M.list.map(m=>m.id));const clean=extra.filter(m=>!ids.has(m.id));if(clean.length)M.list.splice(free,0,...clean);}
const hist=M.list.find(m=>m.id==='history_01');if(hist)hist.next='territory_artifacts_01';
V.historicalCampaign={version:'98.0',missions:extra.map(m=>m.id),actions:['take_photo','compare_sources','inspect_tools','observe_landscape']};
function dist(p,s){return Math.hypot((+s.x||0)-p.x,(+s.y||0)-p.y)}
function say(title,lines){const S=V.gameState;if(!S)return;S.dialogue=true;const d=document.getElementById('dialogue');if(!d)return;d.classList.remove('hidden');d.dataset.lines=JSON.stringify(lines);d.dataset.i='0';const a=document.getElementById('speaker'),b=document.getElementById('dialogueText');if(a)a.textContent=title;if(b)b.textContent=lines[0]||''}
function advance(key){const S=V.gameState,r=M.completeStep?.(S,key);if(!r)return false;if(r.reward){const e=document.getElementById('missionToast');if(e){e.textContent='MISIÓN COMPLETADA · +$'+r.reward;e.classList.add('show');clearTimeout(V.historicalCampaign.toast);V.historicalCampaign.toast=setTimeout(()=>e.classList.remove('show'),2200)}}else{const e=document.getElementById('missionToast');if(e){e.textContent='OBJETIVO COMPLETADO';e.classList.add('show');clearTimeout(V.historicalCampaign.toast);V.historicalCampaign.toast=setTimeout(()=>e.classList.remove('show'),1800)}}window.dispatchEvent(new CustomEvent('villa-pelon-mission',{detail:{mission:M.status(S)}}));return true}
function act(){const S=V.gameState;if(!S||S.dialogue)return false;const o=M.objective(S);if(!o||o.type!=='action')return false;
if(o.target==='take_photo'&&dist({x:6500,y:2080},S)<125){S.inventory=Array.isArray(S.inventory)?S.inventory:[];if(!S.inventory.includes('Foto del territorio'))S.inventory.push('Foto del territorio');S.stats=S.stats||{};S.stats.photos=(+S.stats.photos||0)+1;advance('action:take_photo');say('CUADERNO · FOTOGRAFÍA',['Registraste una imagen del paisaje. Una fotografía muestra un momento y un encuadre: no explica por sí sola todo lo que ocurrió.','Anotá siempre lugar, fecha y contexto cuando una imagen vaya a ser utilizada como fuente.']);return true}
if(o.target==='compare_sources'&&dist({x:2450,y:1400},S)<130){S.flags=S.flags||{};S.flags.comparedSources=true;advance('action:compare_sources');say('LABORATORIO DE FUENTES',['Comparaste una fuente institucional, una cronología periodística y una memoria oral.','No todas responden la misma pregunta. La investigación mejora cuando usás cada una para lo que puede aportar.','Tu cuaderno queda marcado: fuente + fecha + autoría + pregunta + contraste.']);return true}
if(o.target==='inspect_tools'&&dist({x:6250,y:1900},S)<130){S.flags=S.flags||{};S.flags.toolsObserved=true;advance('action:inspect_tools');say('OBJETOS DEL TRABAJO',['Una herramienta no cuenta toda una historia por sí sola. Pero puede abrir preguntas: ¿quién la usaba?, ¿para qué tarea?, ¿en qué época?, ¿dónde se conserva?','El patrimonio cotidiano también merece documentación.']);return true}
if(o.target==='observe_landscape'&&dist({x:6500,y:2080},S)<145){S.flags=S.flags||{};S.flags.landscapeObserved=true;advance('action:observe_landscape');say('OBSERVACIÓN DEL PAISAJE',['Detuviste el personaje unos segundos y miraste antes de avanzar.','Ves camino, vegetación, producción y horizonte. El paisaje es un sistema de relaciones, no un decorado.','En una investigación, observar primero evita inventar explicaciones después.']);return true}
return false}
window.addEventListener('keydown',e=>{if(!['e',' '].includes(String(e.key).toLowerCase())||V.gameState?.dialogue)return;if(act())e.stopImmediatePropagation()},{capture:true});document.getElementById('interact')?.addEventListener('pointerup',e=>{if(V.gameState?.dialogue)return;if(act()){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});
})();
