/* VILLA PELÓN V159 — INTERFAZ CONSOLIDADA
   Menú, mapa, mochila y audio consumen las autoridades existentes.
   No redefine geometría, no crea motor y no crea segundo reloj.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),$=id=>document.getElementById(id),KEY='villa_pelon_ui_v159';
const state=Object.assign({music:true,graphics:'high',language:'es'},JSON.parse(localStorage.getItem(KEY)||'{}'));
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function labels(){return state.language==='en'?{menu:'MENU',map:'MAP',bag:'BACKPACK',close:'CLOSE',music:'MUSIC',graphics:'GRAPHICS',language:'LANGUAGE',restart:'RESTART',save:'SAVE GAME',high:'HIGH',eco:'ECO',on:'ON',off:'OFF',restartAsk:'Restart the game? Unsaved progress will be lost.',world:'WORLD',controls:'CONTROLS',empty:'Your backpack is empty.',context:'CONTEXT',resume:'RESUME',transport:'TRANSPORT',walking:'WALKING',riding:'RIDING'}:{menu:'MENÚ',map:'MAPA',bag:'MOCHILA',close:'CERRAR',music:'MÚSICA',graphics:'GRÁFICOS',language:'IDIOMA',restart:'REINICIAR',save:'GUARDAR PARTIDA',high:'ALTO',eco:'AHORRO',on:'ACTIVADA',off:'APAGADA',restartAsk:'¿Reiniciar el juego? El progreso no guardado se perderá.',world:'MUNDO',controls:'CONTROLES',empty:'Tu mochila está vacía.',context:'CONTEXTO',resume:'CONTINUAR',transport:'TRANSPORTE',walking:'A PIE',riding:'EN VEHÍCULO'}}
function ensure(){if($('vpTopActions'))return;const css=document.createElement('style');css.textContent=`#game{position:relative}#vpTopActions{position:absolute;top:48px;right:10px;z-index:80;display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.vp-action{font:900 10px/1 monospace;letter-spacing:.7px;border:2px solid #d6bd79;background:#17251b;color:#f5ead0;padding:9px 10px;border-radius:3px;box-shadow:3px 3px 0 #0007;cursor:pointer}.vp-action:active{transform:translate(2px,2px)}.vp-overlay{position:absolute;inset:0;z-index:100;display:grid;place-items:center;background:rgba(8,12,9,.72);backdrop-filter:blur(3px)}.vp-overlay.hidden{display:none}.vp-modal{width:min(720px,94vw);max-height:86vh;overflow:auto;border:3px solid #d6bd79;background:#17251b;color:#f5ead0;box-shadow:10px 10px 0 #0008;font-family:system-ui,sans-serif}.vp-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;background:#263b2b;border-bottom:2px solid #5d6249}.vp-head b{font:900 14px monospace;letter-spacing:1px}.vp-x{border:0;background:none;color:#f5ead0;font-size:25px;cursor:pointer}.vp-body{padding:16px}.vp-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.vp-setting{border:1px solid #ffffff20;padding:12px;background:#203126}.vp-setting strong{display:block;font:900 11px monospace;margin-bottom:9px}.vp-setting button,.vp-primary{border:2px solid #c8ae6f;background:#294d38;color:#fff;padding:9px 11px;font:900 10px monospace;cursor:pointer}.vp-setting button.active{background:#8b7040}.vp-wide{grid-column:1/-1}.vp-note{opacity:.75;font-size:12px;line-height:1.45}.vp-map{display:block;width:100%;height:auto;aspect-ratio:8200/4200;background:#a99a70;border:2px solid #c8ae6f;image-rendering:pixelated}.vp-inv{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.vp-item{padding:11px;border:1px solid #ffffff1f;background:#203126;font:700 11px monospace}.vp-status{margin-top:10px;font-size:11px;opacity:.8}@media(max-width:650px){#vpTopActions{top:42px;right:5px;gap:4px}.vp-action{padding:8px 7px;font-size:9px}.vp-grid{grid-template-columns:1fr}}`;document.head.appendChild(css);
const wrap=document.createElement('div');wrap.id='vpTopActions';wrap.innerHTML='<button class="vp-action" id="vpMenuBtn">☰ MENÚ</button><button class="vp-action" id="vpMapBtn">🗺 MAPA</button><button class="vp-action" id="vpBagBtn">🎒 MOCHILA</button>';$('game')?.appendChild(wrap);
const ov=document.createElement('div');ov.id='vpOverlay';ov.className='vp-overlay hidden';ov.innerHTML='<section class="vp-modal" role="dialog" aria-modal="true"><header class="vp-head"><b id="vpTitle">MENÚ</b><button class="vp-x" id="vpClose" aria-label="Cerrar">×</button></header><div class="vp-body" id="vpBody"></div></section>';$('game')?.appendChild(ov);
$('vpClose').onclick=close;$('vpMenuBtn').onclick=openMenu;$('vpMapBtn').onclick=openMap;$('vpBagBtn').onclick=openBag}
function open(title,html){ensure();$('vpTitle').textContent=title;$('vpBody').innerHTML=html;$('vpOverlay').classList.remove('hidden');V.v159Bridge?.pause?.();V.engine?.pause?.()}
function close(){if(!$('vpOverlay'))return;$('vpOverlay').classList.add('hidden');V.v159Bridge?.resume?.();V.engine?.resume?.()}
function drawMap(c){const x=c.getContext('2d');x.imageSmoothingEnabled=false;const G=V.worldGeometry||{},W=V.world||{w:8200,h:4200},sx=c.width/W.w,sy=c.height/W.h;x.fillStyle='#9ca36a';x.fillRect(0,0,c.width,c.height);(G.zones||[]).forEach(z=>{x.fillStyle=z.kind==='urban'?'#b3a476':z.kind==='river'?'#668b8e':z.kind==='route'?'#a89a68':z.kind==='productive'?'#8e9a63':'#9ca36a';x.fillRect(z.x*sx,z.y*sy,z.w*sx,z.h*sy)});x.fillStyle='#c3ac79';(G.roads||[]).forEach(r=>x.fillRect(r.x*sx,r.y*sy,r.w*sx,r.h*sy));if(G.river){x.fillStyle='#668b8e';x.fillRect(G.river.x*sx,G.river.y*sy,G.river.w*sx,G.river.h*sy)}x.fillStyle='#e5d09b';(G.bridges||[]).forEach(b=>x.fillRect(b.x*sx,b.y*sy,b.w*sx,b.h*sy));x.fillStyle='#283d2d';x.font='bold 13px monospace';x.fillText(state.language==='en'?'URBAN':'URBANO',30,30);x.fillText(state.language==='en'?'RURAL':'RURAL',430,30);x.fillText('RÍO',30,Math.max(20,(G.river?.y||2700)*sy-8));x.fillText('PICADA 21',Math.min(c.width-120,(G.zones?.find(z=>z.id==='picada21')?.x||4900)*sx),c.height-15);const s=V.gameState||{x:1380,y:1200};x.fillStyle='#fff';x.fillRect(s.x*sx-4,s.y*sy-4,8,8)}
function openMap(){open(labels().map,'<canvas id="vpMapCanvas" class="vp-map" width="820" height="420"></canvas><p class="vp-note">'+(state.language==='en'?'The map reads the canonical world geometry: urban core → rural/production → river → Picada 21. The river can only be crossed at bridges.':'El mapa lee la geometría canónica: núcleo urbano → rural/producción → río → Picada 21. El río sólo se cruza por puentes.')+'</p>');drawMap($('vpMapCanvas'))}
function openBag(){const inv=V.gameState?.inventory||[],L=labels();open(L.bag,inv.length?'<div class="vp-inv">'+inv.map((i,n)=>'<div class="vp-item">'+String(n+1).padStart(2,'0')+' · '+String(i)+'</div>').join('')+'</div>':'<div class="vp-setting">'+L.empty+'</div>')}
let audio=null,stopMusicLoop=null;function startMusic(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();stopMusic();const notes=[196,247,294,247,220,262,330,262];let i=0;const beat=()=>{if(!state.music)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.018,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.8);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.85)};stopMusicLoop=(V.runtimeRegister||((fn,ms,...args)=>{const id=setInterval(()=>fn(...args),ms);return()=>clearInterval(id)}))(beat,1000)}catch(e){state.music=false;persist()}}
function stopMusic(){if(stopMusicLoop){stopMusicLoop();stopMusicLoop=null}}
function toggleMusic(){state.music=!state.music;persist();if(state.music)startMusic();else stopMusic();openMenu()}
function setGraphics(mode){state.graphics=mode;persist();document.documentElement.dataset.graphics=mode;openMenu()}
function setLanguage(lang){state.language=lang;persist();document.documentElement.lang=lang==='en'?'en':'es-AR';openMenu()}
function restart(){const L=labels();if(!confirm(L.restartAsk))return;try{localStorage.removeItem('villa_pelon_save')}catch(e){}location.reload()}
function openMenu(){const L=labels(),r=S=V.gameState||{};const riding=S.transport?.active;open(L.menu,`<div class="vp-grid"><div class="vp-setting vp-wide"><strong>${L.world}</strong>8200 × 4200 · ${state.language==='en'?'urban + rural + river + Picada 21':'urbano + rural + río + Picada 21'}<div class="vp-status">${L.controls}: WASD / flechas · E interactuar · B subir al colectivo · X bajar · móvil: controles táctiles</div></div><div class="vp-setting"><strong>${L.transport}</strong>${riding?L.riding+': '+String(S.transport.mode||'bus').toUpperCase():L.walking}<div class="vp-status">${V.peopleVehicles?.transport?.busIds?.length||0} colectivo registrado · rutas canónicas conectadas</div></div><div class="vp-setting"><strong>${L.music}</strong><button id="m0" class="${state.music?'active':''}">${state.music?L.on:L.off}</button></div><div class="vp-setting"><strong>${L.graphics}</strong><button id="g1" class="${state.graphics==='high'?'active':''}">${L.high}</button> <button id="g0" class="${state.graphics==='eco'?'active':''}">${L.eco}</button></div><div class="vp-setting"><strong>${L.language}</strong><button id="es" class="${state.language==='es'?'active':''}">ES</button> <button id="en" class="${state.language==='en'?'active':''}">EN</button></div><div class="vp-setting"><strong>${L.context}</strong><button id="ctx">${L.resume}</button></div><div class="vp-setting"><strong>${L.restart}</strong><button id="rst">${L.restart}</button></div><div class="vp-setting vp-wide"><button class="vp-primary" id="sv">${L.save}</button></div></div>`);$('m0').onclick=toggleMusic;$('g1').onclick=()=>setGraphics('high');$('g0').onclick=()=>setGraphics('eco');$('es').onclick=()=>setLanguage('es');$('en').onclick=()=>setLanguage('en');$('rst').onclick=restart;$('sv').onclick=()=>{V.saveGame?.();close()};$('ctx').onclick=()=>{close();document.getElementById('storyIntro')?.classList.remove('hidden')}}
function init(){ensure();document.documentElement.dataset.graphics=state.graphics;V.interface={version:'159.0',authority:'V159_INTERFACE',menu:openMenu,map:openMap,backpack:openBag,settings:()=>openMenu};V.runtimeAudit=Object.assign(V.runtimeAudit||{},{interface159:true,mapUsesCanonicalGeometry:true,musicUsesLogicalRuntime:true,transportUi:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
