(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),$=id=>document.getElementById(id);
const KEY='villa_pelon_ui_v139';
const state=Object.assign({music:true,graphics:'high',language:'es'},JSON.parse(localStorage.getItem(KEY)||'{}'));
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function labels(){return state.language==='en'?{menu:'MENU',map:'MAP',bag:'BACKPACK',close:'CLOSE',music:'MUSIC',graphics:'GRAPHICS',language:'LANGUAGE',restart:'RESTART',save:'SAVE GAME',high:'HIGH',eco:'ECO',on:'ON',off:'OFF',restartAsk:'Restart the game? Unsaved progress will be lost.',world:'WORLD',controls:'CONTROLS',empty:'Your backpack is empty.',context:'CONTEXT',resume:'RESUME'}:{menu:'MENÚ',map:'MAPA',bag:'MOCHILA',close:'CERRAR',music:'MÚSICA',graphics:'GRÁFICOS',language:'IDIOMA',restart:'REINICIAR',save:'GUARDAR PARTIDA',high:'ALTO',eco:'AHORRO',on:'ACTIVADA',off:'APAGADA',restartAsk:'¿Reiniciar el juego? El progreso no guardado se perderá.',world:'MUNDO',controls:'CONTROLES',empty:'Tu mochila está vacía.',context:'CONTEXTO',resume:'CONTINUAR'}}
function ensure(){if($('vpTopActions'))return;const css=document.createElement('style');css.textContent=`#game{position:relative}#vpTopActions{position:absolute;top:48px;right:10px;z-index:80;display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.vp-action{font:900 10px/1 monospace;letter-spacing:.7px;border:2px solid #d6bd79;background:#17251b;color:#f5ead0;padding:9px 10px;border-radius:3px;box-shadow:3px 3px 0 #0007;cursor:pointer}.vp-action:active{transform:translate(2px,2px)}.vp-overlay{position:absolute;inset:0;z-index:100;display:grid;place-items:center;background:rgba(8,12,9,.72);backdrop-filter:blur(3px)}.vp-overlay.hidden{display:none}.vp-modal{width:min(720px,94vw);max-height:86vh;overflow:auto;border:3px solid #d6bd79;background:#17251b;color:#f5ead0;box-shadow:10px 10px 0 #0008;font-family:system-ui,sans-serif}.vp-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;background:#263b2b;border-bottom:2px solid #5d6249}.vp-head b{font:900 14px monospace;letter-spacing:1px}.vp-x{border:0;background:none;color:#f5ead0;font-size:25px;cursor:pointer}.vp-body{padding:16px}.vp-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.vp-setting{border:1px solid #ffffff20;padding:12px;background:#203126}.vp-setting strong{display:block;font:900 11px monospace;margin-bottom:9px}.vp-setting button,.vp-primary{border:2px solid #c8ae6f;background:#294d38;color:#fff;padding:9px 11px;font:900 10px monospace;cursor:pointer}.vp-setting button.active{background:#8b7040}.vp-wide{grid-column:1/-1}.vp-note{opacity:.75;font-size:12px;line-height:1.45}.vp-map{display:block;width:100%;height:auto;aspect-ratio:8200/4200;background:#a99a70;border:2px solid #c8ae6f;image-rendering:pixelated}.vp-inv{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.vp-item{padding:11px;border:1px solid #ffffff1f;background:#203126;font:700 11px monospace}.vp-status{margin-top:10px;font-size:11px;opacity:.8}@media(max-width:650px){#vpTopActions{top:42px;right:5px;gap:4px}.vp-action{padding:8px 7px;font-size:9px}.vp-grid{grid-template-columns:1fr}}`;
 document.head.appendChild(css);
 const wrap=document.createElement('div');wrap.id='vpTopActions';wrap.innerHTML='<button class="vp-action" id="vpMenuBtn">☰ MENÚ</button><button class="vp-action" id="vpMapBtn">🗺 MAPA</button><button class="vp-action" id="vpBagBtn">🎒 MOCHILA</button>';$('game')?.appendChild(wrap);
 const ov=document.createElement('div');ov.id='vpOverlay';ov.className='vp-overlay hidden';ov.innerHTML='<section class="vp-modal" role="dialog" aria-modal="true"><header class="vp-head"><b id="vpTitle">MENÚ</b><button class="vp-x" id="vpClose" aria-label="Cerrar">×</button></header><div class="vp-body" id="vpBody"></div></section>';$('game')?.appendChild(ov);
 $('vpClose').onclick=close;$('vpMenuBtn').onclick=openMenu;$('vpMapBtn').onclick=openMap;$('vpBagBtn').onclick=openBag;
}
function open(title,html){ensure();$('vpTitle').textContent=title;$('vpBody').innerHTML=html;$('vpOverlay').classList.remove('hidden');V.engine?.pause?.()}
function close(){if(!$('vpOverlay'))return;$('vpOverlay').classList.add('hidden');V.engine?.resume?.()}
function drawMap(c){const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#9ca36a';x.fillRect(0,0,820,420);x.fillStyle='#b3a476';x.fillRect(0,0,300,270);x.fillStyle='#8e9a63';x.fillRect(300,0,520,270);x.fillStyle='#668b8e';x.fillRect(25,270,760,10);x.fillStyle='#c3ac79';x.fillRect(0,260,820,30);x.fillStyle='#76583f';const route=V.worldGeometry?.routes?.find(r=>r.id==='picada21_route');if(route?.points?.length){x.lineWidth=4;x.beginPath();route.points.forEach((p,i)=>{const px=p.x/10,py=p.y/10;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}x.fillStyle='#283d2d';x.font='bold 13px monospace';x.fillText(state.language==='en'?'URBAN':'URBANO',30,30);x.fillText(state.language==='en'?'RURAL':'RURAL',390,30);x.fillText('RÍO',40,255);x.fillText('PICADA 21',665,405);const s=V.gameState||{x:1380,y:1200};x.fillStyle='#fff';x.fillRect(s.x/10-4,s.y/10-4,8,8)}
function openMap(){open(labels().map,'<canvas id="vpMapCanvas" class="vp-map" width="820" height="420"></canvas><p class="vp-note">'+(state.language==='en'?'Canonical territory: compact urban core → rural/production → distant river → remote Picada 21. Cross the river only at bridges.':'Territorio canónico: núcleo urbano compacto → rural/producción → río lejano → Picada 21 remota. El río se cruza únicamente por los puentes.')+'</p>');drawMap($('vpMapCanvas'))}
function openBag(){const inv=V.gameState?.inventory||[];const L=labels();open(L.bag,inv.length?'<div class="vp-inv">'+inv.map((i,n)=>'<div class="vp-item">'+String(n+1).padStart(2,'0')+' · '+String(i)+'</div>').join('')+'</div>':'<div class="vp-setting">'+L.empty+'</div>')}
function toggleMusic(){state.music=!state.music;persist();if(state.music)startMusic();else stopMusic();openMenu()}
let audio=null,timer=null;function startMusic(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();stopMusic();const notes=[196,247,294,247,220,262,330,262];let i=0;timer=setInterval(()=>{if(!state.music)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.018,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.8);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.85)},1000)}catch(e){state.music=false;persist()}}
function stopMusic(){if(timer){clearInterval(timer);timer=null}}
function setGraphics(mode){state.graphics=mode;persist();document.documentElement.dataset.graphics=mode;openMenu()}
function setLanguage(lang){state.language=lang;persist();document.documentElement.lang=lang==='en'?'en':'es-AR';openMenu()}
function restart(){const L=labels();if(!confirm(L.restartAsk))return;try{localStorage.removeItem('villa_pelon_save')}catch(e){}location.reload()}
function openMenu(){const L=labels();open(L.menu,`<div class="vp-grid"><div class="vp-setting vp-wide"><strong>${L.world}</strong>8200 × 4200 · ${state.language==='en'?'urban core + rural + river + Picada 21':'núcleo urbano + rural + río + Picada 21'}<div class="vp-status">${L.controls}: WASD / flechas · E interactuar · móvil: controles táctiles</div></div><div class="vp-setting"><strong>${L.music}</strong><button id="m0" class="${state.music?'active':''}">${state.music?L.on:L.off}</button></div><div class="vp-setting"><strong>${L.graphics}</strong><button id="g1" class="${state.graphics==='high'?'active':''}">${L.high}</button> <button id="g0" class="${state.graphics==='eco'?'active':''}">${L.eco}</button></div><div class="vp-setting"><strong>${L.language}</strong><button id="es" class="${state.language==='es'?'active':''}">ES</button> <button id="en" class="${state.language==='en'?'active':''}">EN</button></div><div class="vp-setting"><strong>${L.context}</strong><button id="ctx">${L.resume}</button></div><div class="vp-setting"><strong>${L.restart}</strong><button id="rst">${L.restart}</button></div><div class="vp-setting vp-wide"><button class="vp-primary" id="sv">${L.save}</button></div></div>`);$('m0').onclick=toggleMusic;$('g1').onclick=()=>setGraphics('high');$('g0').onclick=()=>setGraphics('eco');$('es').onclick=()=>setLanguage('es');$('en').onclick=()=>setLanguage('en');$('rst').onclick=restart;$('sv').onclick=()=>{V.saveGame?.();close()};$('ctx').onclick=()=>{close();document.getElementById('storyIntro')?.classList.remove('hidden')};}
function init(){ensure();document.documentElement.dataset.graphics=state.graphics;if(state.music&&localStorage.getItem(KEY)){}V.interface={version:'139.0',menu:openMenu,map:openMap,backpack:openBag,settings:()=>openMenu};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
