/* VILLA PELÓN V159 — RUNTIME DE MISIÓN CONSOLIDADO */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),S=V.gameState||(V.gameState={}),M=V.missions;if(!M)return;M.ensure?.(S);const G=V.worldGeometry||{};
function zone(id,f){const z=(G.zones||[]).find(x=>x.id===id||x.kind===id);return z?{x:+z.x,y:+z.y,w:+z.w,h:+z.h}:f}
const R={version:'159.0',geometryAuthority:'V138',regions:{rural:zone('rural',{x:3000,y:300,w:4900,h:2350}),productive:zone('productive',{x:4900,y:300,w:3000,h:2050}),winery:zone('productive',{x:5500,y:300,w:1900,h:1800}),urban:zone('urban',{x:300,y:300,w:2700,h:1900}),plaza:zone('plaza',{x:300,y:300,w:2700,h:1900}),river:{x:250,y:2700,w:7600,h:100},picada21:{x:4300,y:3180,w:3500,h:850}},points:{dni:{x:1280,y:470},picada21:{x:7600,y:3600},memory:{x:7600,y:3600},archive:{x:2080,y:520},name_marker:{x:1500,y:470},school_archive:{x:430,y:520},irrigation_marker:{x:5000,y:910},pelon_marker:{x:5900,y:1460},founding_marker:{x:2050,y:470},irrigation_timeline:{x:5100,y:1030},school_archive_2:{x:430,y:570},worker_marker:{x:1500,y:1080},territory_map:{x:2450,y:1460},source_lab:{x:2450,y:1400},research_question:{x:2500,y:1510},archive_final:{x:2080,y:520}}};V.missionRuntime=R;
const dist=p=>Math.hypot((+S.x||0)-p.x,(+S.y||0)-p.y),toast=t=>{const e=document.getElementById('missionToast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(R.toastTimer);R.toastTimer=setTimeout(()=>e.classList.remove('show'),2200)},say=(t,l)=>{S.dialogue=true;const d=document.getElementById('dialogue');if(!d)return;d.classList.remove('hidden');d.dataset.lines=JSON.stringify(l);d.dataset.i='0';document.getElementById('speaker').textContent=t;document.getElementById('dialogueText').textContent=l[0]||''},advance=k=>{const r=M.completeStep?.(S,k);if(!r)return false;if(r.reward)toast('MISIÓN COMPLETADA · +$'+r.reward);else toast('OBJETIVO COMPLETADO');window.dispatchEvent(new CustomEvent('villa-pelon-mission',{detail:{mission:M.status(S)}}));return true},fact=(t,l,k)=>{if(!R.points[k]||dist(R.points[k])>=130)return false;advance('inspect:'+k);say(t,l);return true};
function specialInteract(){if(S.dialogue)return false;const o=M.objective(S);if(!o)return false;
if(o.type==='reach'&&o.target==='bridge'){const bs=Array.isArray(G.bridges)?G.bridges:[];if(bs.some(b=>dist({x:+b.x+(+b.w||0)/2,y:+b.y+(+b.h||0)/2})<130)){advance('reach:bridge');say('PUENTE',['Llegaste a un puente. El agua también organiza caminos, producción y vida cotidiana.']);return true}}
if(o.type==='collect'&&o.target==='lost_dni'&&dist(R.points.dni)<105){S.inventory=Array.isArray(S.inventory)?S.inventory:[];if(!S.inventory.includes('DNI extraviado'))S.inventory.push('DNI extraviado');S.flags=S.flags||{};S.flags.lostDni=true;advance('collect:lost_dni');say('PUNTO DE ENCUENTRO',['Encontraste un DNI extraviado. No es tuyo: devolverlo es la misión.','Ahora seguí el camino rural hacia Picada 21.']);return true}
if(o.type==='deliver'&&o.target==='dni_picada21'&&dist(R.points.picada21)<125){if(!S.inventory?.includes('DNI extraviado')){say('MISIÓN',['Primero tenés que encontrar el DNI extraviado.']);return true}S.inventory=S.inventory.filter(x=>x!=='DNI extraviado');S.flags=S.flags||{};S.flags.dniReturned=true;advance('deliver:dni_picada21');say('PICADA 21 · UN ENCUENTRO',['—¿Vos encontraste mi DNI? —pregunta una mujer que venía mirando el camino.','Cuando se lo entregás, se le ilumina la cara.','La escena es narrativa y ficticia; su enseñanza sobre memoria, encuentro y territorio es parte del juego.']);return true}
if(o.type==='inspect'&&o.target==='picada21_memory'&&dist(R.points.memory)<125){advance('inspect:picada21_memory');say('MEMORIA DE PICADA 21',['La memoria oral puede abrir una investigación, pero una investigación responsable debe contrastar sus datos.','Villa Pelón se aprende caminándolo, escuchando y preguntando.']);return true}
if(o.type==='inspect'&&o.target==='name_marker')return fact('TOPÓNIMO · UNA PISTA',['El nombre San Patricio se vincula con San Patricio, patrono de Campofilone, localidad italiana asociada a la familia Gasparri. «Chañar» remite al nombre histórico del paraje y al árbol conocido como chañar.','Fuente: reseña histórica municipal.'],'name_marker');
if(o.type==='inspect'&&o.target==='school_archive')return fact('ESCUELA 273 · FICHA 01',['La cronología consultada registra que la Escuela Nº 273 comenzó a funcionar el 1 de marzo de 1975 y la identifica como la primera escuela de la localidad.','Fuente: cronología de San Patricio del Chañar publicada por Más Neuquén.','Julia es ficticia.'],'school_archive');
if(o.type==='inspect'&&o.target==='irrigation_marker')return fact('RIEGO · FICHA 01',['La cronología local registra una primera bocatoma en Picada 13 en 1971 y una segunda en 1972.','Fuente: cronología local de Más Neuquén.'],'irrigation_marker');
if(o.type==='inspect'&&o.target==='pelon_marker')return fact('PELÓN · FICHA 01',['La primera Fiesta Provincial del Pelón se realizó el 1 de marzo de 1985. Con el tiempo se incorporó un homenaje al trabajador rural.','Fuente: cronología local de San Patricio del Chañar.'],'pelon_marker');
if(o.type==='inspect'&&o.target==='founding_marker')return fact('FUNDACIÓN · FICHA 01',['La localidad fue creada el 21 de mayo de 1973 mediante el Decreto Provincial 1339.','Fuentes: Municipalidad de San Patricio del Chañar y documentación provincial.'],'founding_marker');
if(o.type==='inspect'&&o.target==='irrigation_timeline')return fact('RIEGO · SECUENCIA',['1971 → primera bocatoma en Picada 13.','1972 → segunda bocatoma.','La pregunta es qué cambió después: cruzá agua, tierra, producción y población.'],'irrigation_timeline');
if(o.type==='inspect'&&o.target==='school_archive_2')return fact('ESCUELA · FICHA 02',['Una escuela conserva documentos, fotografías, actos y recuerdos. Un recuerdo no reemplaza automáticamente a un documento.'],'school_archive_2');
if(o.type==='inspect'&&o.target==='worker_marker')return fact('TRABAJO RURAL · FICHA',['Desde 1999 se incorporó la Fiesta del Trabajador Rural a la celebración del Pelón.','La producción cambia; la memoria del trabajo también merece documentación.'],'worker_marker');
if(o.type==='inspect'&&o.target==='territory_map')return fact('MAPA · LEER EL TERRITORIO',['Un mapa muestra relaciones: agua, caminos, puentes, producción, viviendas y memoria.','Antes de usarlo como evidencia preguntá qué representa, qué fecha tiene y quién lo produjo.'],'territory_map');
if(o.type==='inspect'&&o.target==='source_lab')return fact('LABORATORIO DE FUENTES',['INSTITUCIONAL: decretos y reseñas.','PERIODÍSTICA: cronología y contexto.','ORAL: experiencias y preguntas; requiere contraste cuando afirma hechos históricos.'],'source_lab');
if(o.type==='inspect'&&o.target==='research_question')return fact('PREGUNTA DE INVESTIGACIÓN',['¿Qué relación existe entre agua, producción y crecimiento comunitario?','Regla de trabajo: AFIRMACIÓN → FUENTE → CONTRASTE → CONCLUSIÓN.'],'research_question');
if(o.type==='inspect'&&(o.target==='archive'||o.target==='archive_final')){const k=o.target;if(dist(R.points[k])>=130)return false;advance('inspect:'+k);say('CUADERNO DE INVESTIGACIÓN',['Tu ficha queda cerrada con cuatro campos: afirmación, fuente, contraste y lo que todavía no sabés.','No conviertas un recuerdo o una leyenda en falsa certeza.']);return true}return false}
R.specialInteract=specialInteract;window.addEventListener('keydown',e=>{if(!['e',' '].includes(String(e.key).toLowerCase())||S.dialogue)return;if(specialInteract())e.stopImmediatePropagation()},{capture:true});document.getElementById('interact')?.addEventListener('pointerup',e=>{if(S.dialogue)return;if(specialInteract()){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});
})();