/* VILLA PELÓN — MISSION CATALOG 97.0
   Campaña educativa RPG: el jugador aprende territorio, memoria, fuentes,
   riego, fundación, escuela, producción, trabajo rural y patrimonio mediante acciones.
   Los hechos históricos se presentan con fuente; los personajes y escenas del juego son ficticios.
*/
(()=>{'use strict';
 const V=window.VillaPelon||(window.VillaPelon={}),M=V.missions=V.missions||{};M.version='97.0';
 M.list=[
 {id:'welcome',chapter:'PUEBLO',title:'Conocé Villa Pelón',description:'Empezá a recorrer el pueblo, reconocé su plaza y escuchá una voz local.',objectives:[{id:'talk_marta',type:'talk',target:'marta',label:'Hablá con Marta'},{id:'plaza',type:'reach',target:'plaza',label:'Recorré la plaza'}],reward:500,next:'memory_01'},
 {id:'memory_01',chapter:'MEMORIA',title:'Una pista del pueblo',description:'Aprendé que investigar un pueblo también significa guardar y contrastar fuentes.',objectives:[{id:'clue',type:'collect',target:'historic_clue',label:'Encontrá la pista histórica'}],reward:2500,next:'name_01'},
 {id:'name_01',chapter:'IDENTIDAD',title:'¿Por qué se llama así?',description:'Descubrí que un nombre puede reunir geografía, migraciones y memoria.',objectives:[{id:'talk_celso',type:'talk',target:'celso',label:'Hablá con Celso sobre el nombre del lugar'},{id:'inspect_name',type:'inspect',target:'name_marker',label:'Consultá la ficha del topónimo'}],reward:2800,next:'community_01'},
 {id:'community_01',chapter:'COMUNIDAD',title:'Las voces del pueblo',description:'Conocé dos miradas distintas de la comunidad.',objectives:[{id:'talk_nico',type:'talk',target:'nico',label:'Hablá con Nico'},{id:'talk_lucia',type:'talk',target:'lucia',label:'Hablá con Lucía'}],reward:1800,next:'school_01'},
 {id:'school_01',chapter:'EDUCACIÓN',title:'La primera escuela',description:'La escuela permite estudiar cómo una comunidad construye memoria.',objectives:[{id:'talk_julia',type:'talk',target:'julia',label:'Hablá con Julia'},{id:'inspect_school',type:'inspect',target:'school_archive',label:'Consultá la ficha de la Escuela 273'}],reward:3200,next:'water_01'},
 {id:'water_01',chapter:'TERRITORIO',title:'El agua hace al valle',description:'Recorré el sector rural y descubrí cómo el riego transforma el paisaje.',objectives:[{id:'reach_rural',type:'reach',target:'rural',label:'Llegá al sector rural'},{id:'talk_mateo',type:'talk',target:'mateo',label:'Hablá con Mateo'},{id:'inspect_water',type:'inspect',target:'irrigation_marker',label:'Leé la ficha de riego'}],reward:4200,next:'production_01'},
 {id:'production_01',chapter:'PRODUCCIÓN',title:'Del fruto a la identidad',description:'Conocé el paisaje productivo y la relación entre trabajo, fruta, vino y territorio.',objectives:[{id:'winery',type:'reach',target:'winery',label:'Llegá al área de producción'},{id:'talk_tomas',type:'talk',target:'tomas',label:'Hablá con Tomás'}],reward:3000,next:'pelon_01'},
 {id:'pelon_01',chapter:'PRODUCCIÓN',title:'La memoria del pelón',description:'Seguí una pista sobre una celebración productiva y el trabajo rural.',objectives:[{id:'talk_rosa',type:'talk',target:'rosa',label:'Hablá con Rosa'},{id:'inspect_pelon',type:'inspect',target:'pelon_marker',label:'Consultá la ficha de la Fiesta del Pelón'}],reward:4500,next:'oral_01'},
 {id:'oral_01',chapter:'MEMORIA',title:'Una historia se escucha',description:'Usá la radio como punto de encuentro y aprendé a distinguir relato oral y fuente documental.',objectives:[{id:'talk_raul',type:'talk',target:'raul',label:'Hablá con Raúl'},{id:'talk_nico_2',type:'talk',target:'nico',label:'Volvé a hablar con Nico'}],reward:3200,next:'archive_01'},
 {id:'archive_01',chapter:'INVESTIGACIÓN',title:'El laboratorio de las fuentes',description:'Aprendé a separar memoria, fotografía, prensa, cronología y documento oficial.',objectives:[{id:'talk_amalia',type:'talk',target:'amalia',label:'Hablá con Amalia'},{id:'inspect_archive',type:'inspect',target:'archive',label:'Armá tu primera ficha de fuente'}],reward:5200,next:'dni_01'},
 {id:'dni_01',chapter:'COMUNIDAD',title:'El DNI perdido',description:'Un objeto extraviado te lleva por el camino rural hasta una pequeña historia de encuentro humano.',objectives:[{id:'dni',type:'collect',target:'lost_dni',label:'Levantá el DNI extraviado'},{id:'picada',type:'reach',target:'picada21',label:'Viajá por el camino rural hasta Picada 21'},{id:'deliver',type:'deliver',target:'dni_picada21',label:'Devolvé el DNI en Picada 21'}],reward:6500,next:'picada21_memory'},
 {id:'picada21_memory',chapter:'MEMORIA',title:'Lo que queda en el camino',description:'Después de devolver el DNI, una conversación te enseña a escuchar un territorio sin confundir relato y documento.',objectives:[{id:'listen',type:'inspect',target:'picada21_memory',label:'Escuchá la historia en Picada 21'}],reward:5000,next:'founding_01'},
 {id:'founding_01',chapter:'HISTORIA',title:'Un pueblo no aparece de la nada',description:'Reconstruí una cronología básica de la creación de San Patricio del Chañar y aprendé a verificar fechas.',objectives:[{id:'inspect_founding',type:'inspect',target:'founding_marker',label:'Consultá la ficha de fundación'},{id:'talk_celso_2',type:'talk',target:'celso',label:'Volvé con Celso y explicá qué fuente encontraste'}],reward:5600,next:'irrigation_02'},
 {id:'irrigation_02',chapter:'TERRITORIO',title:'Dos bocatomas, una transformación',description:'Relacioná fechas, agua y territorio en una pequeña investigación sobre el riego.',objectives:[{id:'inspect_water_2',type:'inspect',target:'irrigation_timeline',label:'Ordená la secuencia del riego'},{id:'talk_mateo_2',type:'talk',target:'mateo',label:'Contrastá la información con Mateo'}],reward:6200,next:'school_02'},
 {id:'school_02',chapter:'MEMORIA',title:'La escuela como archivo',description:'Comprendé por qué una escuela también conserva memoria comunitaria.',objectives:[{id:'inspect_school_2',type:'inspect',target:'school_archive_2',label:'Revisá la segunda ficha escolar'},{id:'talk_julia_2',type:'talk',target:'julia',label:'Preguntale a Julia cómo se verifica un recuerdo'}],reward:5200,next:'worker_01'},
 {id:'worker_01',chapter:'TRABAJO',title:'El trabajo también cuenta',description:'Reconocé el aporte del trabajo rural a la identidad productiva y social.',objectives:[{id:'talk_rosa_2',type:'talk',target:'rosa',label:'Escuchá a Rosa'},{id:'inspect_worker',type:'inspect',target:'worker_marker',label:'Consultá la ficha del trabajador rural'}],reward:5800,next:'map_01'},
 {id:'map_01',chapter:'CARTOGRAFÍA',title:'Leer el territorio',description:'Usá el mapa como una fuente: caminos, agua, producción y lugares de memoria forman una red.',objectives:[{id:'inspect_map',type:'inspect',target:'territory_map',label:'Consultá el mapa territorial'},{id:'reach_picada_map',type:'reach',target:'picada21',label:'Volvé a recorrer el camino hacia Picada 21'}],reward:6000,next:'bridges_01'},
 {id:'bridges_01',chapter:'TERRITORIO',title:'El río y los puentes',description:'Observá cómo los caminos se encuentran con el agua sin romper la continuidad del viaje.',objectives:[{id:'bridge',type:'reach',target:'bridge',label:'Llegá a un puente del mundo'}],reward:3800,next:'research_01'},
 {id:'research_01',chapter:'INVESTIGACIÓN',title:'Tres fuentes, una pregunta',description:'Combiná memoria oral, cronología y fuente institucional para resolver una pregunta histórica.',objectives:[{id:'inspect_sources',type:'inspect',target:'source_lab',label:'Compará tres tipos de fuente'},{id:'inspect_question',type:'inspect',target:'research_question',label:'Resolvé la pregunta del cuaderno'}],reward:7000,next:'history_01'},
 {id:'history_01',chapter:'INVESTIGACIÓN',title:'No alcanza con creer',description:'Convertí una curiosidad en una investigación: afirmación, fuente, contraste y conclusión.',objectives:[{id:'archive',type:'inspect',target:'archive_final',label:'Cerrá tu primera ficha de investigación'}],reward:7500,next:'free_explore'},
 {id:'free_explore',chapter:'EXPLORACIÓN',title:'Villa Pelón abierta',description:'Completaste el primer ciclo histórico. El mapa queda abierto para nuevas historias, fuentes, personajes y misiones.',objectives:[],reward:0,next:null}
 ];
 M.ensure=s=>{s.missionId=s.missionId||'welcome';s.missionStep=Number.isFinite(+s.missionStep)?Math.max(0,+s.missionStep):0;s.missionFlags=s.missionFlags&&typeof s.missionFlags==='object'?s.missionFlags:{};s.missionHistory=Array.isArray(s.missionHistory)?s.missionHistory:[]};
 M.current=s=>{M.ensure(s);return M.list.find(x=>x.id===s.missionId)||M.list[0]};M.objective=s=>M.current(s).objectives[s.missionStep]||null;
 M.completeStep=(s,key)=>{M.ensure(s);const m=M.current(s),o=M.objective(s);if(!o||o.type+':'+o.target!==key)return false;s.missionStep++;if(s.missionStep>=m.objectives.length){s.money=(+s.money||0)+(+m.reward||0);s.missionFlags[m.id]=true;s.missionHistory.push({id:m.id,title:m.title,chapter:m.chapter,day:s.day||1,reward:m.reward||0});const next=m.next;s.missionId=next||m.id;s.missionStep=0;return{complete:true,reward:m.reward||0,mission:m.title,next}}return{complete:false}};
 M.status=s=>{const m=M.current(s),o=M.objective(s);return{id:m.id,chapter:m.chapter,title:m.title,description:m.description,step:s.missionStep,total:m.objectives.length,objective:o?.label||'Exploración libre',reward:m.reward||0,history:s.missionHistory.length}};
 M.progress=(s)=>({completed:M.ensure(s),current:M.status(s),history:s.missionHistory||[]});
})();
