/* VILLA PELÓN — MISSION CATALOG 96.0
   Campaña educativa RPG: cada misión agrega una capa de conocimiento sobre territorio,
   memoria, comunidad, producción y patrimonio. Los hechos históricos se presentan con
   fuente o como narrativa explícitamente ficticia.
*/
(()=>{'use strict';
 const V=window.VillaPelon||(window.VillaPelon={}),M=V.missions=V.missions||{};M.version='96.0';
 M.list=[
 {id:'welcome',chapter:'PUEBLO',title:'Conocé Villa Pelón',description:'Empezá a recorrer el pueblo, reconocé su plaza y escuchá una voz local.',objectives:[{id:'talk_marta',type:'talk',target:'marta',label:'Hablá con Marta'},{id:'plaza',type:'reach',target:'plaza',label:'Recorré la plaza'}],reward:500,next:'memory_01'},
 {id:'memory_01',chapter:'MEMORIA',title:'Una pista del pueblo',description:'Encontrá una primera pista y aprendé que investigar un pueblo también significa guardar fuentes.',objectives:[{id:'clue',type:'collect',target:'historic_clue',label:'Encontrá la pista histórica'}],reward:2500,next:'community_01'},
 {id:'community_01',chapter:'COMUNIDAD',title:'Las voces del pueblo',description:'Conocé dos miradas distintas de la comunidad.',objectives:[{id:'talk_nico',type:'talk',target:'nico',label:'Hablá con Nico'},{id:'talk_lucia',type:'talk',target:'lucia',label:'Hablá con Lucía'}],reward:1800,next:'water_01'},
 {id:'water_01',chapter:'TERRITORIO',title:'El agua hace al valle',description:'Recorré el sector rural y aprendé por qué el riego transforma el paisaje.',objectives:[{id:'rural',type:'reach',target:'rural',label:'Llegá al sector rural'},{id:'talk_elena',type:'talk',target:'elena',label:'Hablá con Elena'}],reward:2200,next:'production_01'},
 {id:'production_01',chapter:'PRODUCCIÓN',title:'Del fruto a la identidad',description:'Conocé el paisaje productivo y descubrí la relación entre trabajo, fruta y territorio.',objectives:[{id:'winery',type:'reach',target:'winery',label:'Llegá al área de producción'},{id:'talk_tomas',type:'talk',target:'tomas',label:'Hablá con Tomás'}],reward:3000,next:'oral_01'},
 {id:'oral_01',chapter:'MEMORIA',title:'Una historia se escucha',description:'Usá la radio como punto de encuentro y aprendé a distinguir un relato oral de una fuente documental.',objectives:[{id:'talk_raul',type:'talk',target:'raul',label:'Hablá con Raúl'},{id:'talk_nico_2',type:'talk',target:'nico',label:'Volvé a hablar con Nico'}],reward:3200,next:'dni_01'},
 {id:'dni_01',chapter:'COMUNIDAD',title:'El DNI perdido',description:'Encontraste un DNI extraviado. La misión parece sencilla: devolverlo. Pero el camino hasta Picada 21 guarda una pequeña historia.',objectives:[{id:'dni',type:'collect',target:'lost_dni',label:'Levantá el DNI extraviado'},{id:'picada',type:'reach',target:'picada21',label:'Viajá por el camino rural hasta Picada 21'},{id:'deliver',type:'deliver',target:'dni_picada21',label:'Devolvé el DNI en Picada 21'}],reward:6500,next:'picada21_memory'},
 {id:'picada21_memory',chapter:'MEMORIA',title:'Lo que queda en el camino',description:'Después de devolver el DNI, una conversación inesperada te enseña que un territorio también se conoce por sus recuerdos.',objectives:[{id:'listen',type:'inspect',target:'picada21_memory',label:'Escuchá la historia en Picada 21'}],reward:5000,next:'bridges_01'},
 {id:'bridges_01',chapter:'TERRITORIO',title:'El río y los puentes',description:'Observá cómo los caminos deben encontrarse con el agua sin romper la continuidad del viaje.',objectives:[{id:'bridge',type:'reach',target:'bridge',label:'Llegá a un puente del mundo'}],reward:3800,next:'history_01'},
 {id:'history_01',chapter:'INVESTIGACIÓN',title:'No alcanza con creer',description:'Aprendé una regla fundamental: separar memoria, relato y dato documentado.',objectives:[{id:'archive',type:'inspect',target:'archive',label:'Consultá el punto de archivo'}],reward:4500,next:'free_explore'},
 {id:'free_explore',chapter:'EXPLORACIÓN',title:'Villa Pelón abierta',description:'Terminaste el primer recorrido educativo. Ahora el mapa queda abierto para seguir descubriendo personas, territorio e historias.',objectives:[],reward:0,next:null}
 ];
 M.ensure=s=>{s.missionId=s.missionId||'welcome';s.missionStep=Number.isFinite(+s.missionStep)?Math.max(0,+s.missionStep):0;s.missionFlags=s.missionFlags&&typeof s.missionFlags==='object'?s.missionFlags:{};s.missionHistory=Array.isArray(s.missionHistory)?s.missionHistory:[]};
 M.current=s=>{M.ensure(s);return M.list.find(x=>x.id===s.missionId)||M.list[0]};M.objective=s=>M.current(s).objectives[s.missionStep]||null;
 M.completeStep=(s,key)=>{M.ensure(s);const m=M.current(s),o=M.objective(s);if(!o||o.type+':'+o.target!==key)return false;s.missionStep++;if(s.missionStep>=m.objectives.length){s.money=(+s.money||0)+(+m.reward||0);s.missionFlags[m.id]=true;s.missionHistory.push({id:m.id,title:m.title,day:s.day||1,reward:m.reward||0});const next=m.next;s.missionId=next||m.id;s.missionStep=0;return{complete:true,reward:m.reward||0,mission:m.title,next}}return{complete:false}};
 M.status=s=>{const m=M.current(s),o=M.objective(s);return{id:m.id,chapter:m.chapter,title:m.title,description:m.description,step:s.missionStep,total:m.objectives.length,objective:o?.label||'Exploración libre',reward:m.reward||0,history:s.missionHistory.length}};
})();
