/* Villa Pelón CORE PROFESSIONAL v1.1
   UX principal, mochila, mapa, contexto educativo e integración móvil.
   No crea autoridad propia de movimiento ni de estado.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const state=()=>V.gameState||{};
const SETTINGS='villa_pelon_settings';
let settings={language:'es',music:true,sfx:true,graphics:'auto',scale:'auto'};
try{settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS)||'{}')}}catch(_){ }
const I={es:{menu:'MENÚ',back:'VOLVER',inventory:'MOCHILA',map:'MAPA',settings:'AJUSTES',save:'GUARDAR',load:'CARGAR',restart:'REINICIAR',language:'IDIOMA',graphics:'GRÁFICOS',sound:'SONIDO',music:'MÚSICA',sfx:'EFECTOS',on:'ACTIVADO',off:'DESACTIVADO',auto:'AUTO',low:'BAJO',medium:'MEDIO',high:'ALTO',mapInfo:'Mapa territorial',empty:'La mochila está vacía.',world:'MUNDO',rules:'El mundo continúa viviendo aunque no estés mirando.',close:'CERRAR'},en:{menu:'MENU',back:'BACK',inventory:'BAG',map:'MAP',settings:'SETTINGS',save:'SAVE',load:'LOAD',restart:'RESTART',language:'LANGUAGE',graphics:'GRAPHICS',sound:'SOUND',music:'MUSIC',sfx:'SFX',on:'ON',off:'OFF',auto:'AUTO',low:'LOW',medium:'MEDIUM',high:'HIGH',mapInfo:'Territorial map',empty:'Your bag is empty.',world:'WORLD',rules:'The world keeps living even when you are not watching.',close:'CLOSE'},pt:{menu:'MENU',back:'VOLTAR',inventory:'MOCHILA',map:'MAPA',settings:'AJUSTES',save:'SALVAR',load:'CARREGAR',restart:'REINICIAR',language:'IDIOMA',graphics:'GRÁFICOS',sound:'SOM',music:'MÚSICA',sfx:'EFEITOS',on:'ATIVADO',off:'DESATIVADO',auto:'AUTO',low:'BAIXO',medium:'MÉDIO',high:'ALTO',mapInfo:'Mapa territorial',empty:'A mochila está vazia.',world:'MUNDO',rules:'O mundo continua vivendo mesmo quando você não está olhando.',close:'FECHAR'}};
const tr=k=>(I[settings.language]||I.es)[k]||k;
function persist(){localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function panel(title,body,kind='default'){const old=document.querySelector('.vp-pro-panel');if(old)old.remove();const p=document.createElement('div');p.className='vp-pro-panel '+(kind==='map'?'vp-map-panel':'');p.innerHTML=`<div class="vp-pro-head"><b>${esc(title)}</b><button data-pro-close aria-label="Cerrar">×</button></div><div class="vp-pro-body">${body}</div>`;document.getElementById('game')?.appendChild(p);p.querySelector('[data-pro-close]').onclick=()=>p.remove();return p}
function inventory(){const s=state(),items=Array.isArray(s.inventory)?s.inventory:[];const rows=items.length?items.map((x,i)=>`<div class="vp-item"><span>${i+1}</span><b>${esc(x)}</b></div>`).join(''):`<div class="vp-empty">${tr('empty')}</div>`;panel(tr('inventory'),`<div class="vp-bag-summary"><b>${items.length}</b> descubrimiento${items.length===1?'':'s'}</div><div class="vp-item-list">${rows}</div><p class="vp-muted">Las pistas, objetos y documentos encontrados forman parte de tu recorrido educativo.</p>`)}
function map(){const s=state(),g=V.worldGeometry||{},buildings=Array.isArray(g.buildings)?g.buildings:[];const territory=V.territory?.zones||{pueblo:{x:120,y:180,w:1680,h:650},rural:{x:1800,y:830,w:1080,h:1000},river:{x:2880,y:120,w:320,h:1710}};const W=360,H=225;const px=Math.max(2,Math.min(W-4,(+s.x/3200)*W)),py=Math.max(2,Math.min(H-4,(+s.y/2000)*H));const rects=Object.entries(territory).map(([k,z])=>{const x=z.x/3200*W,y=z.y/2000*H,w=z.w/3200*W,h=z.h/2000*H;return `<div class="vp-map-zone vp-${esc(k)}" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px">${esc(k.toUpperCase())}</div>`}).join('');const places=buildings.map(b=>`<div class="vp-map-place" title="${esc(b.label||b.type||'Lugar')}" style="left:${(b.x+b.w/2)/3200*W}px;top:${(b.y+b.h/2)/2000*H}px">◆</div>`).join('');panel(tr('map'),`<div class="vp-map"><div class="vp-map-land"></div>${rects}${places}<div class="vp-map-player" style="left:${px}px;top:${py}px">●</div></div><div class="vp-map-legend"><span>● Vos</span><span>◆ Lugares</span></div><p class="vp-muted">${tr('mapInfo')} · posición ${Math.round(s.x)}, ${Math.round(s.y)}. Explorá el territorio y usá las misiones para descubrir qué significa cada lugar.</p>`,'map')}
function settingsPanel(){const s=settings;panel(tr('settings'),`<div class="vp-setting"><b>${tr('language')}</b><button data-pro-lang>${s.language.toUpperCase()}</button></div><div class="vp-setting"><b>${tr('graphics')}</b><button data-pro-graphics>${tr(s.graphics)}</button></div><div class="vp-setting"><b>${tr('music')}</b><button data-pro-music>${s.music?tr('on'):tr('off')}</button></div><div class="vp-setting"><b>${tr('sfx')}</b><button data-pro-sfx>${s.sfx?tr('on'):tr('off')}</button></div>`);const p=document.querySelector('.vp-pro-panel:last-child');p.querySelector('[data-pro-lang]').onclick=()=>{s.language=s.language==='es'?'en':s.language==='en'?'pt':'es';persist();document.documentElement.lang=s.language==='es'?'es-AR':s.language;window.dispatchEvent(new CustomEvent('villa-pelon-language',{detail:s.language}));p.remove();settingsPanel()};p.querySelector('[data-pro-graphics]').onclick=()=>{s.graphics=s.graphics==='auto'?'low':s.graphics==='low'?'medium':s.graphics==='medium'?'high':'auto';persist();applyGraphics();p.remove();settingsPanel()};p.querySelector('[data-pro-music]').onclick=()=>{s.music=!s.music;persist();V.ui?.toggleMusic?.();p.remove();settingsPanel()};p.querySelector('[data-pro-sfx]').onclick=()=>{s.sfx=!s.sfx;persist();p.remove();settingsPanel()}}
function applyGraphics(){const g=settings.graphics;document.documentElement.dataset.graphics=g;V.graphics={quality:g,adaptive:g==='auto',pixelated:true}}
function bindMainTools(){document.querySelectorAll('[data-main-tool]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const a=b.dataset.mainTool;if(a==='inventory')inventory();if(a==='map')map()})})}
function augmentMenu(){const m=document.getElementById('vpMenu'),p=m?.querySelector('.vp-panel');if(!p||p.dataset.pro)return;p.dataset.pro='1';const group=document.createElement('div');group.className='vp-pro-tools';group.innerHTML=`<button data-pro="inventory">🎒 ${tr('inventory')}</button><button data-pro="map">🗺️ ${tr('map')}</button><button data-pro="settings">⚙️ ${tr('settings')}</button>`;p.insertBefore(group,p.querySelector('[data-a="restart"]')||p.lastElementChild);group.onclick=e=>{const b=e.target.closest('[data-pro]');if(!b)return;const a=b.dataset.pro;if(a==='inventory')inventory();if(a==='map')map();if(a==='settings')settingsPanel()}}
function intro(){const start=document.getElementById('start');if(!start||start.dataset.pro)return;start.dataset.pro='1';start.querySelectorAll('[data-intro-tab]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.introTab;start.querySelectorAll('[data-intro-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.introPanel!==key));start.querySelectorAll('[data-intro-tab]').forEach(b=>b.classList.toggle('active',b===btn))}));}
function worldRules(){V.worldRules={...(V.worldRules||{}),version:'1.1.0',singleWorldAuthority:true,singleStateAuthority:true,singleInteractionAuthority:true,mobileFirst:true,onlineLinkPlay:true,noInstall:true,freeExploration:true,educationalHistory:true,historicalSourcesRequired:true,fictionMustBeMarked:true,dayNight:true,npcLife:true,persistence:true,interactionPriority:['npc','door','mission','object','shop','work'],zones:['pueblo','rural','river']};if(V.life)V.life.worldRules=V.worldRules}
function boot(){applyGraphics();worldRules();bindMainTools();augmentMenu();intro();window.addEventListener('villa-pelon-mobile-ready',worldRules);window.addEventListener('click',e=>{if(e.target.closest('#vpMenuButton'))setTimeout(augmentMenu,0)})}
V.professionalRuntime={version:'1.1.0',settings,inventory,map,settingsPanel,applyGraphics,worldRules};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
