/* Villa Pelón CORE PROFESSIONAL v1.3
   UX principal, mochila, mapa, contexto educativo e integración móvil.
   La interfaz consume la autoridad territorial sin crear otra.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const state=()=>V.gameState||{};const SETTINGS='villa_pelon_settings';
let settings={language:'es',music:true,sfx:true,graphics:'auto',scale:'auto'};try{settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS)||'{}')}}catch(_){ }
const I={es:{menu:'MENÚ',back:'VOLVER',inventory:'MOCHILA',map:'MAPA',settings:'AJUSTES',save:'GUARDAR',load:'CARGAR',restart:'REINICIAR',language:'IDIOMA',graphics:'GRÁFICOS',music:'MÚSICA',sfx:'EFECTOS',on:'ACTIVADO',off:'DESACTIVADO',auto:'AUTO',low:'BAJO',medium:'MEDIO',high:'ALTO',mapInfo:'Mapa territorial',empty:'La mochila está vacía.'},en:{menu:'MENU',back:'BACK',inventory:'BAG',map:'MAP',settings:'SETTINGS',save:'SAVE',load:'LOAD',restart:'RESTART',language:'LANGUAGE',graphics:'GRAPHICS',music:'MUSIC',sfx:'SFX',on:'ON',off:'OFF',auto:'AUTO',low:'LOW',medium:'MEDIUM',high:'HIGH',mapInfo:'Territorial map',empty:'Your bag is empty.'},pt:{menu:'MENU',back:'VOLTAR',inventory:'MOCHILA',map:'MAPA',settings:'AJUSTES',language:'IDIOMA',graphics:'GRÁFICOS',music:'MÚSICA',sfx:'EFEITOS',on:'ATIVADO',off:'DESATIVADO',auto:'AUTO',low:'BAIXO',medium:'MÉDIO',high:'ALTO',mapInfo:'Mapa territorial',empty:'A mochila está vazia.'}};
const tr=k=>(I[settings.language]||I.es)[k]||k;const persist=()=>localStorage.setItem(SETTINGS,JSON.stringify(settings));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function panel(title,body,kind='default'){document.querySelector('.vp-pro-panel')?.remove();const p=document.createElement('div');p.className='vp-pro-panel '+(kind==='map'?'vp-map-panel':'');p.innerHTML=`<div class="vp-pro-head"><b>${esc(title)}</b><button data-pro-close aria-label="Cerrar">×</button></div><div class="vp-pro-body">${body}</div>`;document.getElementById('game')?.appendChild(p);p.querySelector('[data-pro-close]').onclick=()=>p.remove();return p}
function inventory(){if(V.educationJournal?.panel){V.educationJournal.panel();return}const items=Array.isArray(state().inventory)?state().inventory:[];const rows=items.length?items.map((x,i)=>`<div class="vp-item"><span>${i+1}</span><b>${esc(x)}</b></div>`).join(''):`<div class="vp-empty">${tr('empty')}</div>`;panel(tr('inventory'),`<div class="vp-bag-summary"><b>${items.length}</b> objetos y descubrimientos</div><div class="vp-item-list">${rows}</div>`)}
function map(){const s=state(),g=V.worldAuthority?.geometry||V.worldGeometry||{},zones=Array.isArray(g.zones)?g.zones:[],roads=Array.isArray(g.roads)?g.roads:[],buildings=Array.isArray(g.buildings)?g.buildings:[],sites=Array.isArray(g.sites)?g.sites:[];const W=360,H=225,scaleX=W/(g.width||3200),scaleY=H/(g.height||2000),px=Math.max(2,Math.min(W-4,(+s.x/(g.width||3200))*W)),py=Math.max(2,Math.min(H-4,(+s.y/(g.height||2000))*H));const rects=zones.map(z=>`<div class="vp-map-zone vp-${esc(z.id)}" style="left:${z.x*scaleX}px;top:${z.y*scaleY}px;width:${z.w*scaleX}px;height:${z.h*scaleY}px">${esc(z.name.toUpperCase())}</div>`).join('');const rds=roads.map(r=>`<div class="vp-map-road" title="${esc(r.name)}" style="left:${r.x*scaleX}px;top:${r.y*scaleY}px;width:${r.w*scaleX}px;height:${r.h*scaleY}px"></div>`).join('');const places=[...buildings.map(b=>({x:b.x+b.w/2,y:b.y+b.h/2,label:b.label})),...sites.map(p=>({x:p.x,y:p.y,label:p.name}))];const marks=places.map(p=>`<div class="vp-map-place" title="${esc(p.label)}" style="left:${p.x*scaleX}px;top:${p.y*scaleY}px">◆</div>`).join('');const river=g.river?`<div class="vp-map-river" style="left:${g.river.x*scaleX}px;top:${g.river.y*scaleY}px;width:${g.river.w*scaleX}px;height:${g.river.h*scaleY}px"></div>`:'';panel(tr('map'),`<div class="vp-map"><div class="vp-map-land"></div>${river}${rects}${rds}${marks}<div class="vp-map-player" style="left:${px}px;top:${py}px">●</div></div><div class="vp-map-legend"><span>● Vos</span><span>◆ Lugar</span><span>━ Ruta</span></div><p class="vp-muted">${tr('mapInfo')} · Centro · Barrio · Rural · Río · Bodega · Meseta. Las rutas son corredores de circulación y no alojan viviendas.</p>`,'map')}
function settingsPanel(){panel(tr('settings'),`<div class="vp-setting"><b>${tr('language')}</b><button data-pro-lang>${settings.language.toUpperCase()}</button></div><div class="vp-setting"><b>${tr('graphics')}</b><button data-pro-graphics>${tr(settings.graphics)}</button></div><div class="vp-setting"><b>${tr('music')}</b><button data-pro-music>${settings.music?tr('on'):tr('off')}</button></div><div class="vp-setting"><b>${tr('sfx')}</b><button data-pro-sfx>${settings.sfx?tr('on'):tr('off')}</button></div>`);const p=document.querySelector('.vp-pro-panel:last-child');p.querySelector('[data-pro-lang]').onclick=()=>{settings.language=settings.language==='es'?'en':settings.language==='en'?'pt':'es';persist();document.documentElement.lang=settings.language==='es'?'es-AR':settings.language;window.dispatchEvent(new CustomEvent('villa-pelon-language',{detail:settings.language}));p.remove();settingsPanel()};p.querySelector('[data-pro-graphics]').onclick=()=>{settings.graphics=settings.graphics==='auto'?'low':settings.graphics==='low'?'medium':settings.graphics==='medium'?'high':'auto';persist();applyGraphics();p.remove();settingsPanel()};p.querySelector('[data-pro-music]').onclick=()=>{settings.music=!settings.music;persist();V.ui?.toggleMusic?.();p.remove();settingsPanel()};p.querySelector('[data-pro-sfx]').onclick=()=>{settings.sfx=!settings.sfx;persist();p.remove();settingsPanel()}}
function applyGraphics(){const g=settings.graphics;document.documentElement.dataset.graphics=g;V.graphics={quality:g,adaptive:g==='auto',pixelated:true}}
function bindMainTools(){document.querySelectorAll('[data-main-tool]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>b.dataset.mainTool==='inventory'?inventory():map())})}
function augmentMenu(){const m=document.getElementById('vpMenu'),p=m?.querySelector('.vp-panel');if(!p||p.dataset.pro)return;p.dataset.pro='1';const group=document.createElement('div');group.className='vp-pro-tools';group.innerHTML=`<button data-pro="inventory">🎒 ${tr('inventory')}</button><button data-pro="map">🗺️ ${tr('map')}</button><button data-pro="settings">⚙️ ${tr('settings')}</button>`;p.insertBefore(group,p.querySelector('[data-a="restart"]')||p.lastElementChild);group.onclick=e=>{const b=e.target.closest('[data-pro]');if(!b)return;const a=b.dataset.pro;if(a==='inventory')inventory();if(a==='map')map();if(a==='settings')settingsPanel()}}
function worldRules(){V.worldRules={...(V.worldRules||{}),version:'1.3.0',singleWorldAuthority:true,singleStateAuthority:true,singleInteractionAuthority:true,mobileFirst:true,onlineLinkPlay:true,noInstall:true,whatsappReady:true,freeExploration:true,educationalHistory:true,historicalSourcesRequired:true,fictionMustBeMarked:true,dayNight:true,npcLife:true,persistence:true,territorialRules:true,interactionPriority:['npc','door','mission','object','shop','work']};if(V.life)V.life.worldRules=V.worldRules}
function boot(){applyGraphics();worldRules();bindMainTools();augmentMenu();window.addEventListener('villa-pelon-mobile-ready',worldRules);window.addEventListener('click',e=>{if(e.target.closest('#vpMenuButton'))setTimeout(augmentMenu,0)})}
V.professionalRuntime={version:'1.3.0',settings,inventory,map,settingsPanel,applyGraphics,worldRules};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
