/* VILLA PELÓN V159 — ENTRADA ÚNICA Y PRÓLOGO CONSOLIDADO
   Única autoridad para la primera pantalla + intro interactiva.
   Mientras esta capa está activa: el mundo NO recibe controles, interacción, guardado ni movimiento.
   Al finalizar: libera el mundo una sola vez y queda bloqueada contra reaperturas accidentales.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),UI=V.ui=V.ui||{};
const entry=UI.entry=UI.entry||{version:'159.0',authority:'CORE_INTRO_ENTRY',phase:'presentation',locked:true,released:false};
UI.intro=UI.intro||{active:false};
const P={es:[['UN PUEBLO PARA MIRAR DE CERCA','Antes de entrar, conocé cuatro referencias del territorio: la plaza, el campo, el río y el camino hacia Picada 21.'],['LA PLAZA','Es el corazón del núcleo urbano. Desde acá comienza la exploración del pueblo y sus historias cotidianas.'],['EL CAMPO','Al salir del centro, el paisaje se abre. Chacras, producción, animales, herramientas y trabajo rural forman otra zona del pueblo.'],['EL RÍO','Está lejos del núcleo urbano. El agua funciona como límite territorial y los puentes concentran los cruces.'],['PICADA 21','Más allá del río comienza un territorio todavía más abierto. Es el destino lejano de la primera gran exploración.'],['AHORA TE TOCA A VOS','Ahora sí: el prólogo termina y empieza la exploración. Caminá, hablá, observá y relacioná lo que encuentres.']],en:[['A VILLAGE TO LOOK AT CLOSELY','Before entering, learn four territorial references: the plaza, countryside, river and road to Picada 21.'],['THE PLAZA','It is the heart of the urban core. Exploration of the village and its everyday stories begins here.'],['THE COUNTRYSIDE','Leaving the center opens the landscape. Farms, production, animals, tools and rural work form another zone of the village.'],['THE RIVER','It is far from the urban core. Water acts as a territorial boundary and bridges concentrate crossings.'],['PICADA 21','Beyond the river the territory becomes even more open. It is the distant destination of the first major exploration.'],['NOW IT IS YOUR TURN','Now the prologue ends and exploration begins. Walk, talk, observe and connect what you find.']]};
function injectStyle(){if(document.getElementById('vp-v159-entry-style'))return;const s=document.createElement('style');s.id='vp-v159-entry-style';s.textContent=`#start.vp-entry-active,#storyIntro.vp-entry-active{position:fixed!important;inset:0!important;z-index:99990!important;pointer-events:auto!important}#game.vp-world-locked{pointer-events:none!important;user-select:none!important;touch-action:none!important;visibility:hidden!important}#start.vp-entry-active~#storyIntro.vp-entry-active{display:block!important}.story-scene{cursor:default;image-rendering:pixelated}.story-scene:before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,rgba(230,213,159,.06),transparent 45%,rgba(0,0,0,.18));pointer-events:none;z-index:1}.intro-hotspots{position:absolute;inset:0;z-index:5;pointer-events:none}.intro-hotspots .hotspot{position:absolute;pointer-events:auto;min-height:28px;padding:5px 8px;border:2px solid rgba(238,227,197,.65);background:rgba(16,23,18,.84);color:#f2e5bf;font:800 8px monospace;letter-spacing:1px;box-shadow:3px 3px 0 rgba(0,0,0,.3);cursor:pointer}.intro-hotspots .plaza{left:12%;bottom:34%}.intro-hotspots .rural{right:14%;bottom:43%}.intro-hotspots .river{left:15%;bottom:19%}.intro-hotspots .picada{right:9%;bottom:10%}.story-intro[data-scene=player] .intro-hotspots{opacity:.35}.story-tools{display:flex;gap:8px;margin-top:10px}.story-tools button{flex:1;min-height:38px;border:1px solid rgba(225,211,164,.35);background:#18271d;color:#d9cda7;font:800 10px monospace;cursor:pointer}@media(max-width:700px){.intro-hotspots .hotspot{font-size:7px;min-height:25px;padding:4px 6px}.story-tools button{min-height:36px;font-size:9px}}`;document.head.appendChild(s)}
function worldLocked(){entry.locked=true;entry.phase=entry.phase==='released'?'released':entry.phase;document.getElementById('game')?.classList.add('vp-world-locked');const S=V.gameState=V.gameState||{};S.intro=true;S.entryLocked=true;S.entryPhase=entry.phase}
function releaseWorld(){if(entry.released)return;entry.released=true;entry.locked=false;entry.phase='released';const S=V.gameState=V.gameState||{};S.intro=false;S.entryLocked=false;S.entryPhase='world';document.getElementById('game')?.classList.remove('vp-world-locked');window.dispatchEvent(new CustomEvent('villa-pelon-world-entry-released',{detail:{version:'159.0',authority:'CORE_INTRO_ENTRY'}}));}
function boot(){const presentation=document.getElementById('start'),story=document.getElementById('storyIntro');if(!presentation||!story||story.dataset.v159)return;story.dataset.v159='1';injectStyle();entry.phase='presentation';entry.released=false;entry.locked=true;worldLocked();const title=story.querySelector('[data-intro-title]'),text=story.querySelector('[data-intro-text]'),nextBtn=story.querySelector('[data-intro-next]'),step=story.querySelector('#storyStep'),dots=[...story.querySelectorAll('.story-dot')];let scene=story.querySelector('.story-scene'),tools=story.querySelector('.story-tools');if(!tools){tools=document.createElement('div');tools.className='story-tools';tools.innerHTML='<button type="button" data-intro-back>ATRÁS</button><button type="button" data-intro-skip>SALTAR</button>';story.querySelector('.story-copy')?.appendChild(tools)}const back=tools.querySelector('[data-intro-back]'),skip=tools.querySelector('[data-intro-skip]');let lang='es',i=0,lock=false;
function paint(){const a=P[lang][i];if(title)title.textContent=a[0];if(text)text.textContent=a[1];if(step)step.textContent=String(i+1).padStart(2,'0')+' / 06';if(nextBtn)nextBtn.textContent=i===5?(lang==='en'?'ENTER WORLD':'ENTRAR AL MUNDO'):(lang==='en'?'CONTINUE':'CONTINUAR');if(back)back.textContent=lang==='en'?'BACK':'ATRÁS';if(skip)skip.textContent=lang==='en'?'SKIP':'SALTAR';dots.forEach((d,n)=>d.classList.toggle('active',n===i));story.dataset.page=String(i+1);story.dataset.scene=['town','plaza','rural','river','picada','player'][i]||'town'}
function open(){if(entry.released)return;entry.phase='intro';entry.locked=true;worldLocked();lang=document.documentElement.lang==='en'?'en':'es';i=0;UI.intro.active=true;presentation.classList.remove('hidden');presentation.classList.remove('vp-entry-active');story.classList.add('vp-entry-active');story.classList.remove('hidden');story.setAttribute('aria-hidden','false');presentation.setAttribute('aria-hidden','true');paint()}
function startIntro(){if(entry.released)return;entry.phase='intro';entry.locked=true;worldLocked();UI.intro.active=true;presentation.classList.add('hidden');story.classList.add('vp-entry-active');story.classList.remove('hidden');story.setAttribute('aria-hidden','false');paint()}
function finish(){if(entry.released)return;UI.intro.active=false;story.classList.remove('vp-entry-active');story.classList.add('hidden');story.setAttribute('aria-hidden','true');presentation.classList.add('hidden');releaseWorld();window.dispatchEvent(new CustomEvent('villa-pelon-intro-finished',{detail:{version:'159.0',entryReleased:true}}))}
function advance(){if(lock||!UI.intro.active)return;lock=true;if(i<5){i++;paint()}else finish();setTimeout(()=>lock=false,140)}function previous(){if(lock||!UI.intro.active)return;lock=true;if(i>0){i--;paint()}setTimeout(()=>lock=false,140)}
function handle(e){if(!UI.intro.active)return;const t=e.target.closest?.('[data-intro-next],[data-intro-back],[data-intro-skip],[data-intro-hotspot]');if(!t||!story.contains(t))return;e.preventDefault();e.stopPropagation();if(t===nextBtn)advance();else if(t===back)previous();else if(t===skip)finish();else{const n=Number(t.dataset.introHotspot);if(Number.isFinite(n)){i=Math.max(0,Math.min(5,n));paint()}}}
story.addEventListener('click',handle,true);story.addEventListener('pointerup',handle,true);if(scene){const hot=document.createElement('div');hot.className='intro-hotspots';hot.innerHTML='<button data-intro-hotspot="1" class="hotspot plaza" aria-label="Plaza">PLAZA</button><button data-intro-hotspot="2" class="hotspot rural" aria-label="Campo">CAMPO</button><button data-intro-hotspot="3" class="hotspot river" aria-label="Río">RÍO</button><button data-intro-hotspot="4" class="hotspot picada" aria-label="Picada 21">PICADA 21</button>';scene.appendChild(hot)}
document.addEventListener('keydown',e=>{if(!UI.intro.active)return;if(e.key==='Enter'||e.key===' '||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();advance()}else if(e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();previous()}else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();finish()}},true);document.getElementById('presentationStart')?.addEventListener('click',startIntro,true);window.addEventListener('villa-pelon-open-intro',open);presentation.classList.remove('hidden');presentation.classList.add('vp-entry-active');presentation.setAttribute('aria-hidden','false');story.classList.remove('vp-entry-active');story.classList.add('hidden');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120));else setTimeout(boot,120);
})();
