/* VILLA PELÓN V160.2 — ENTRADA ÚNICA Y PRÓLOGO INTERACTIVO
   Mantiene la autoridad estructural V159: portada -> prólogo -> mundo.
   Esta capa no crea motor, renderer, geometría ni loop.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),UI=V.ui=V.ui||{};
const entry=UI.entry=UI.entry||{version:'159.0',authority:'CORE_INTRO_ENTRY',phase:'presentation',locked:true,released:false};
UI.intro=UI.intro||{active:false};
const P={es:[
['ACOMPAÑÁ A LUNA','Luna es una nueva habitante de Villa Pelón. Llegó con ganas de conocer el lugar donde va a vivir. Acompañala a descubrir su historia, sus caminos y a las personas que hacen que este pueblo sea lo que es.'],
['PRIMERA MIRADA · LA PLAZA','Luna comienza por el corazón del pueblo. La plaza no es solamente un lugar: es un punto de encuentro, de conversaciones, de recuerdos y de pequeñas historias que se cruzan todos los días.'],
['MÁS ALLÁ · EL CAMPO','Después del núcleo urbano, Luna encuentra chacras, caminos, animales, herramientas y trabajo. El campo no es un decorado: tiene sus propios ritmos, personas y decisiones.'],
['EL LÍMITE · EL RÍO','Más lejos aparece el río. Está separado del pueblo por distancia y paisaje. Para cruzarlo hay que encontrar los puentes. El territorio empieza a sentirse más grande.'],
['EL CAMINO · PICADA 21','Del otro lado, el camino continúa hacia Picada 21, el asentamiento más lejano. Luna todavía no conoce todo lo que hay allí. Parte de la historia tendrá que descubrirla caminando.'],
['AHORA TE TOCA A VOS','Luna ya tiene una primera idea de Villa Pelón. Ahora empieza su verdadera historia: caminar, hablar con la gente, trabajar, descubrir lugares, tomar decisiones y construir su propia vida en el pueblo.']
],en:[
['FOLLOW LUNA','Luna is a new resident of Villa Pelón. She arrived wanting to discover the place where she will live. Follow her as she discovers its history, roads and people.'],
['FIRST LOOK · THE PLAZA','Luna begins at the heart of the village. The plaza is a meeting place filled with conversations, memories and small everyday stories.'],
['BEYOND · THE COUNTRYSIDE','Beyond the urban core Luna finds farms, roads, animals, tools and work. The countryside has its own rhythms, people and choices.'],
['THE BORDER · THE RIVER','Farther away, Luna reaches the river. It is separated from the village by distance and landscape. Bridges are the places where it can be crossed.'],
['THE ROAD · PICADA 21','Beyond the river the road continues toward Picada 21, the most distant settlement. Luna does not know everything that is there yet. She will have to discover it by walking.'],
['NOW IT IS YOUR TURN','Luna has her first idea of Villa Pelón. Now her real story begins: walk, talk, work, discover places, make choices and build a life in the village.']
]};
function injectStyle(){if(document.getElementById('vp-v159-entry-style'))return;const s=document.createElement('style');s.id='vp-v159-entry-style';s.textContent=`#start.vp-entry-active,#storyIntro.vp-entry-active{position:fixed!important;inset:0!important;z-index:99990!important;pointer-events:auto!important}#game.vp-world-locked{pointer-events:none!important;user-select:none!important;touch-action:none!important;visibility:hidden!important}.story-scene{cursor:default;image-rendering:pixelated}.story-scene:before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,rgba(230,213,159,.06),transparent 45%,rgba(0,0,0,.18));pointer-events:none;z-index:1}.intro-hotspots{position:absolute;inset:0;z-index:5;pointer-events:none}.intro-hotspots .hotspot{position:absolute;pointer-events:auto;min-height:28px;padding:5px 8px;border:2px solid rgba(238,227,197,.65);background:rgba(16,23,18,.84);color:#f2e5bf;font:800 8px monospace;letter-spacing:1px;box-shadow:3px 3px 0 rgba(0,0,0,.3);cursor:pointer}.intro-hotspots .plaza{left:12%;bottom:34%}.intro-hotspots .rural{right:14%;bottom:43%}.intro-hotspots .river{left:15%;bottom:19%}.intro-hotspots .picada{right:9%;bottom:10%}.story-intro[data-scene=player] .intro-hotspots{opacity:.35}.story-tools{display:flex;gap:8px;margin-top:10px}.story-tools button{flex:1;min-height:38px;border:1px solid rgba(225,211,164,.35);background:#18271d;color:#d9cda7;font:800 10px monospace;cursor:pointer}.story-tools .world-entry{flex:2;background:#294d38;border:2px solid #e6d59f;color:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.3)}.story-tools button:disabled,.story-copy [data-intro-next]:disabled{opacity:.55;cursor:wait}@media(max-width:700px){.intro-hotspots .hotspot{font-size:7px;min-height:25px;padding:4px 6px}.story-tools button{min-height:36px;font-size:9px}}`;document.head.appendChild(s)}
function worldLocked(){entry.locked=true;document.getElementById('game')?.classList.add('vp-world-locked');const S=V.gameState=V.gameState||{};S.intro=true;S.entryLocked=true;S.entryPhase=entry.phase}
function releaseWorld(){if(entry.released)return false;entry.released=true;entry.locked=false;entry.phase='released';const S=V.gameState=V.gameState||{};S.intro=false;S.entryLocked=false;S.entryPhase='world';document.getElementById('game')?.classList.remove('vp-world-locked');window.dispatchEvent(new CustomEvent('villa-pelon-world-entry-released',{detail:{version:'160.2',authority:'CORE_INTRO_ENTRY'}}));return true}
function boot(){const presentation=document.getElementById('start'),story=document.getElementById('storyIntro');if(!presentation||!story||story.dataset.v159)return;story.dataset.v159='1';injectStyle();entry.phase='presentation';entry.released=false;entry.locked=true;worldLocked();const title=story.querySelector('[data-intro-title]'),text=story.querySelector('[data-intro-text]'),nextBtn=story.querySelector('[data-intro-next]'),step=story.querySelector('#storyStep'),dots=[...story.querySelectorAll('.story-dot')];const scene=story.querySelector('.story-scene');let tools=story.querySelector('.story-tools');if(!tools){tools=document.createElement('div');tools.className='story-tools';tools.innerHTML='<button type="button" data-intro-back>ATRÁS</button><button type="button" data-intro-skip>SALTAR INTRO</button>';story.querySelector('.story-copy')?.appendChild(tools)}const back=tools.querySelector('[data-intro-back]'),skip=tools.querySelector('[data-intro-skip]');let lang='es',i=0,lock=false;
function paint(){const a=P[lang][i];if(title)title.textContent=a[0];if(text)text.textContent=a[1];if(step)step.textContent=String(i+1).padStart(2,'0')+' / 06';if(nextBtn){nextBtn.textContent=i===5?(lang==='en'?'ENTER WORLD':'ENTRAR AL MUNDO'):(lang==='en'?'CONTINUE':'CONTINUAR');nextBtn.classList.toggle('world-entry',i===5);nextBtn.setAttribute('aria-label',i===5?(lang==='en'?'Enter the world':'Entrar al mundo'):(lang==='en'?'Continue':'Continuar'))}if(back)back.textContent=lang==='en'?'BACK':'ATRÁS';if(skip)skip.textContent=lang==='en'?'SKIP INTRO':'SALTAR INTRO';dots.forEach((d,n)=>d.classList.toggle('active',n===i));story.dataset.page=String(i+1);story.dataset.scene=['town','plaza','rural','river','picada','luna'][i]||'town'}
function showIntro(){if(entry.released)return;entry.phase='intro';entry.locked=true;worldLocked();lang=document.documentElement.lang==='en'?'en':'es';i=0;UI.intro.active=true;presentation.classList.add('hidden');presentation.classList.remove('vp-entry-active');story.classList.add('vp-entry-active');story.classList.remove('hidden');story.setAttribute('aria-hidden','false');presentation.setAttribute('aria-hidden','true');paint();window.dispatchEvent(new CustomEvent('villa-pelon-intro-started',{detail:{version:'160.2',character:'Luna'}}))}
function finish(){if(lock||entry.released)return;lock=true;UI.intro.active=false;if(nextBtn)nextBtn.disabled=true;if(skip)skip.disabled=true;if(back)back.disabled=true;story.classList.remove('vp-entry-active');story.classList.add('hidden');story.setAttribute('aria-hidden','true');presentation.classList.add('hidden');const released=releaseWorld();if(released)window.dispatchEvent(new CustomEvent('villa-pelon-intro-finished',{detail:{version:'160.2',entryReleased:true,character:'Luna'}}));setTimeout(()=>{lock=false},220)}
function advance(){if(lock||!UI.intro.active)return;lock=true;if(i<5){i++;paint();setTimeout(()=>{lock=false},180)}else{lock=false;finish()}}
function previous(){if(lock||!UI.intro.active)return;lock=true;if(i>0)i--;paint();setTimeout(()=>{lock=false},180)}
function hotspot(n){if(lock||!UI.intro.active)return;if(!Number.isFinite(n))return;lock=true;i=Math.max(0,Math.min(5,n));paint();setTimeout(()=>{lock=false},180)}
function handleClick(e){if(!UI.intro.active)return;const t=e.target.closest?.('[data-intro-next],[data-intro-back],[data-intro-skip],[data-intro-hotspot]');if(!t||!story.contains(t))return;e.preventDefault();e.stopPropagation();if(t===nextBtn)advance();else if(t===back)previous();else if(t===skip)finish();else hotspot(Number(t.dataset.introHotspot))}
story.addEventListener('click',handleClick,true);
if(scene){const hot=document.createElement('div');hot.className='intro-hotspots';hot.innerHTML='<button type="button" data-intro-hotspot="1" class="hotspot plaza" aria-label="Ir a la plaza">PLAZA</button><button type="button" data-intro-hotspot="2" class="hotspot rural" aria-label="Ir al campo">CAMPO</button><button type="button" data-intro-hotspot="3" class="hotspot river" aria-label="Ir al río">RÍO</button><button type="button" data-intro-hotspot="4" class="hotspot picada" aria-label="Ir a Picada 21">PICADA 21</button>';scene.appendChild(hot)}
document.addEventListener('keydown',e=>{if(!UI.intro.active)return;if(e.key==='Enter'||e.key===' '||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();advance()}else if(e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();previous()}else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();finish()}},true);
document.getElementById('presentationStart')?.addEventListener('click',showIntro,true);window.addEventListener('villa-pelon-open-intro',showIntro);window.addEventListener('villa-pelon-world-entry-released',()=>{entry.released=true;entry.locked=false;entry.phase='released';UI.intro.active=false},{once:true});presentation.classList.remove('hidden');presentation.classList.add('vp-entry-active');presentation.setAttribute('aria-hidden','false');story.classList.remove('vp-entry-active');story.classList.add('hidden');story.setAttribute('aria-hidden','true');paint()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120));else setTimeout(boot,120);
})();
