/* VILLA PELÓN V133 — CONSOLIDACIÓN TOTAL
   Una historia, un sistema de acciones, una vida, una movilidad.
   No crea ni modifica geometría canónica.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),S=V.gameState||(V.gameState={}),G=V.worldGeometry||{},M=V.missions,P=V.peopleVehicles,L=V.villageLife,A=V.visualAuthority;
const U=V.gameUnification={version:'V133',principle:'one world · one life · one action language · one story'};
U.actionDefs={talk:'escuchar',reach:'recorrer',inspect:'investigar',collect:'observar y conservar',deliver:'resolver',work:'comprender el trabajo',observe:'reconocer el territorio'};
U.action=(type,target,meta={})=>{const e={type,target,verb:U.actionDefs[type]||'actuar',day:+S.day||1,minutes:+S.minutes||0,mission:M?.current?.(S)?.id||null,...meta};S.actionHistory=Array.isArray(S.actionHistory)?S.actionHistory:[];S.actionHistory.push(e);if(S.actionHistory.length>250)S.actionHistory.shift();window.dispatchEvent(new CustomEvent('villa-pelon-action',{detail:e}));return e};
U.knowledgeCatalog={welcome:['identidad','territorio'],memory_01:['fuentes','memoria'],name_01:['toponimia','identidad'],community_01:['comunidad'],school_01:['escuela','memoria'],water_01:['riego','territorio'],production_01:['produccion','trabajo'],pelon_01:['pelon','produccion'],oral_01:['memoria_oral'],archive_01:['fuentes','investigacion'],dni_01:['convivencia','picada21'],picada21_memory:['memoria_oral','picada21'],founding_01:['fundacion','cronologia'],irrigation_02:['riego','cronologia'],school_02:['escuela','fuentes'],worker_01:['trabajo_rural'],map_01:['cartografia','territorio'],bridges_01:['rio','puentes'],research_01:['fuentes','contraste'],history_01:['investigacion','metodo']};
function learn(id){S.knowledge=S.knowledge&&typeof S.knowledge==='object'?S.knowledge:{};const tags=U.knowledgeCatalog[id]||[];tags.forEach(t=>S.knowledge[t]=true);S.knowledgeHistory=Array.isArray(S.knowledgeHistory)?S.knowledgeHistory:[];if(!S.knowledgeHistory.some(x=>x.id===id))S.knowledgeHistory.push({id,tags,day:+S.day||1})}
if(M?.completeStep){const old=M.completeStep;M.completeStep=function(s,key){const r=old(s,key);if(r){const id=r.complete?(r.next||s.missionId):s.missionId;if(r.complete)learn(id);const q=String(key).split(':');U.action(q[0],q.slice(1).join(':'),{result:r.complete?'mission_complete':'objective_complete'})}return r}}
if(V.missionRuntime){const R=V.missionRuntime,z=G.zones||[],zone=id=>z.find(x=>x.id===id),node=id=>(G.routeNetwork?.nodes||[]).find(x=>x.id===id),pl=G.plaza||{x:1080,y:690,w:480,h:220},pic=zone('picada21')||{x:4300,y:3180,w:3500,h:850},rur=zone('transition_rural')||{x:3000,y:300,w:4900,h:2350},win=(G.buildings||[]).find(b=>b.type==='winery')||{x:4100,y:430,w:430,h:260};R.version='133.0';R.regions={urban:zone('urban_core'),rural:rur,picada21:pic,river:zone('river_buffer')};R.points={plaza:{x:pl.x+pl.w/2,y:pl.y+pl.h/2},rural:{x:node('rural')?.x||4300,y:node('rural')?.y||865},winery:{x:win.x+win.w/2,y:win.y+win.h/2},dni:{x:1250,y:1320},picada21:{x:node('picada21')?.x||6000,y:node('picada21')?.y||3250},memory:{x:node('picada21')?.x||6000,y:node('picada21')?.y||3250},archive:{x:1140,y:650},name_marker:{x:1260,y:620},school_archive:{x:630,y:600},irrigation_marker:{x:3500,y:760},pelon_marker:{x:5100,y:1760},founding_marker:{x:1100,y:620},irrigation_timeline:{x:4200,y:760},school_archive_2:{x:630,y:620},worker_marker:{x:900,y:1320},territory_map:{x:1500,y:1320},source_lab:{x:1650,y:1320},research_question:{x:1800,y:1320},archive_final:{x:1140,y:650}}}
if(P){const roads=G.roads||[],road=id=>roads.find(r=>r.id===id),lanes=['urban_north','urban_mid','urban_south','rural_north','rural_middle','rural_south'].map(road).filter(Boolean);(P.vehicleData||[]).forEach((v,i)=>{const r=lanes[i%lanes.length];if(!r)return;v.routeId=r.id;v.route={...r,minX:r.x,maxX:r.x+r.w,laneY:r.y+r.h/2};v.y=v.route.laneY;v.visualFamily=v.type==='tractor'?'productive':v.type==='pickup'?'rural':'urban'});(P.animals||[]).forEach(a=>{a.zoneId='transition_rural';a.behavior='bounded-graze';a.visualFamily='natural';a.bounds={minX:3150,maxX:7750,minY:450,maxY:2200}});U.mobility={version:'133.0',vehicleAuthority:'worldGeometry.roads',animalAuthority:'transition_rural',riverCrossing:'bridge_only',vehicleFreeRoam:false}}
U.audit=()=>({ok:!!(G.version&&A?.version&&L?.singleTick&&M?.list),geometry:G.version,visual:A?.version,life:L?.version,missions:M?.list?.length||0,vehicles:P?.vehicleData?.length||0,animals:P?.animals?.length||0,knowledge:Object.keys(S.knowledge||{}).length,actions:(S.actionHistory||[]).length});
window.dispatchEvent(new CustomEvent('villa-pelon-unification-ready',{detail:U.audit()}));
})();
