/* VILLA PELÓN V134.2 — MUNDO VIVO CONSOLIDADO
   Detalles cotidianos derivados sobre la geografía ya bloqueada.
   No crea edificios, rutas, río ni zonas. No modifica G.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),G=V.worldGeometry||{},P=V.visualAuthority?.contract?.palette||{},S=V.gameState||{};
const fixed=[
{id:'plaza-flower-01',x:1100,y:1335,w:24,h:8,type:'planter',zone:'urban_core',use:'ornamento',action:'observe'},{id:'plaza-flower-02',x:1370,y:1350,w:24,h:8,type:'planter',zone:'urban_core',use:'ornamento',action:'observe'},{id:'plaza-bike-01',x:1450,y:1460,w:22,h:10,type:'bike',zone:'urban_core',use:'movilidad_local',action:'observe'},{id:'plaza-bin-01',x:1040,y:1450,w:12,h:14,type:'bin',zone:'urban_core',use:'limpieza',action:'observe'},{id:'plaza-notice-01',x:1500,y:1280,w:40,h:12,type:'notice',zone:'urban_core',use:'informacion',action:'read'},{id:'plaza-light-01',x:1000,y:1250,w:7,h:16,type:'streetlight',zone:'urban_core',use:'iluminacion',action:'observe'},{id:'urban-water-01',x:1430,y:1240,w:12,h:13,type:'waterpoint',zone:'urban_core',use:'agua_publica',action:'observe'},
{id:'rural-crate-01',x:3900,y:1180,w:18,h:13,type:'crate',zone:'transition_rural',use:'acopio',action:'work'},{id:'rural-barrel-01',x:4200,y:1320,w:14,h:15,type:'barrel',zone:'transition_rural',use:'produccion',action:'work'},{id:'rural-hay-01',x:4550,y:1180,w:18,h:12,type:'hay',zone:'transition_rural',use:'forraje',action:'observe'},{id:'rural-hay-02',x:4620,y:1210,w:18,h:12,type:'hay',zone:'transition_rural',use:'forraje',action:'observe'},{id:'rural-mailbox-01',x:4750,y:1480,w:12,h:16,type:'mailbox',zone:'transition_rural',use:'correo',action:'observe'},{id:'rural-bucket-01',x:3820,y:1510,w:11,h:8,type:'bucket',zone:'transition_rural',use:'agua_trabajo',action:'work'},{id:'rural-crate-02',x:5200,y:1450,w:18,h:13,type:'crate',zone:'transition_rural',use:'acopio',action:'work'},{id:'rural-wheelbarrow-01',x:5350,y:1370,w:25,h:15,type:'wheelbarrow',zone:'transition_rural',use:'trabajo_rural',action:'work'},{id:'rural-fence-01',x:5750,y:1250,w:34,h:11,type:'fence',zone:'transition_rural',use:'limite_productivo',action:'observe'},{id:'rural-post-01',x:5900,y:1280,w:4,h:18,type:'post',zone:'transition_rural',use:'referencia',action:'observe'},{id:'rural-watertrough-01',x:6250,y:1420,w:28,h:10,type:'watertrough',zone:'transition_rural',use:'agua_animal',action:'observe'},{id:'rural-sack-01',x:6500,y:1540,w:13,h:15,type:'sack',zone:'transition_rural',use:'cosecha',action:'work'},{id:'rural-toolbox-01',x:4300,y:1510,w:20,h:10,type:'toolbox',zone:'transition_rural',use:'herramientas',action:'work'},{id:'rural-cart-01',x:4700,y:1650,w:26,h:12,type:'cart',zone:'transition_rural',use:'transporte_carga',action:'observe'},
{id:'river-lookout-01',x:5500,y:2520,w:30,h:9,type:'bench',zone:'river_buffer',use:'mirador',action:'observe'},{id:'river-warning-01',x:5750,y:2570,w:44,h:12,type:'warning',zone:'river_buffer',use:'seguridad',action:'read'},{id:'river-reed-01',x:5850,y:2650,w:10,h:18,type:'reed',zone:'river_buffer',use:'vegetacion_ribera',action:'observe'},{id:'river-reed-02',x:6000,y:2700,w:10,h:18,type:'reed',zone:'river_buffer',use:'vegetacion_ribera',action:'observe'},{id:'river-post-01',x:6150,y:2580,w:4,h:18,type:'post',zone:'river_buffer',use:'referencia',action:'observe'},
{id:'picada-woodpile-01',x:7250,y:3020,w:23,h:12,type:'woodpile',zone:'picada21',use:'leña',action:'work'},{id:'picada-bucket-01',x:7380,y:3060,w:11,h:8,type:'bucket',zone:'picada21',use:'agua_trabajo',action:'work'},{id:'picada-crate-01',x:7650,y:2990,w:18,h:13,type:'crate',zone:'picada21',use:'acopio',action:'work'},{id:'picada-mailbox-01',x:7750,y:3090,w:12,h:16,type:'mailbox',zone:'picada21',use:'correo',action:'observe'},{id:'picada-fence-01',x:7900,y:3000,w:34,h:11,type:'fence',zone:'picada21',use:'limite',action:'observe'},{id:'picada-water-01',x:7480,y:3160,w:12,h:13,type:'waterpoint',zone:'picada21',use:'agua',action:'observe'}
];
const overlap=(a,b,p=0)=>a.x-p<b.x+b.w+p&&a.x+a.w+p>b.x-p&&a.y-p<b.y+b.h+p&&a.y+a.h+p>b.y-p;
const validZone=o=>Array.isArray(G.zones)&&G.zones.some(z=>z.id===o.zone&&o.x>=z.x&&o.y>=z.y&&o.x+o.w<=z.x+z.w&&o.y+o.h<=z.y+z.h);
const roads=G.roads||[],buildings=G.buildings||[],river=G.river||null,rejected=[],details=[];
for(const o of fixed){const e=[];if(!validZone(o))e.push('outside-canonical-zone');if(roads.some(r=>overlap(o,r,4)))e.push('road-conflict');if(river&&overlap(o,river,4))e.push('river-conflict');if(buildings.some(b=>overlap(o,b,5)))e.push('building-conflict');if(e.length)rejected.push({id:o.id,errors:e});else details.push(Object.freeze(o));}
function box(ctx,x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.max(1,Math.round(w)),Math.max(1,Math.round(h)))}
function draw(o,ctx){const x=o.x,y=o.y;switch(o.type){case'planter':box(ctx,x,y,24,8,P.woodDark);box(ctx,x+3,y-5,18,6,P.leaf);box(ctx,x+8,y-9,3,5,P.leafLight);break;case'bike':ctx.strokeStyle=P.metal;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+4,y+6,4,0,Math.PI*2);ctx.arc(x+18,y+6,4,0,Math.PI*2);ctx.stroke();box(ctx,x+9,y-5,2,10,P.metalLight);break;case'bin':box(ctx,x,y,12,14,P.metalDark);box(ctx,x+2,y-2,8,3,P.metalLight);break;case'notice':box(ctx,x,y,40,12,P.signDark);box(ctx,x+2,y+2,36,7,P.sign);break;case'streetlight':box(ctx,x,y,3,16,P.metalDark);box(ctx,x-2,y,7,3,P.sign);break;case'waterpoint':box(ctx,x,y,12,13,P.metalDark);box(ctx,x+2,y+2,8,4,P.waterLight);box(ctx,x+4,y+6,4,7,P.metalLight);break;case'crate':box(ctx,x,y,18,13,P.woodDark);box(ctx,x+2,y+2,14,8,P.woodLight);box(ctx,x+8,y+2,2,8,P.woodDark);break;case'barrel':box(ctx,x,y,14,15,P.woodDark);box(ctx,x+2,y+3,10,2,P.metal);box(ctx,x+2,y+10,10,2,P.metal);break;case'hay':box(ctx,x,y,18,12,P.signDark);box(ctx,x+2,y+2,14,8,P.sign);break;case'mailbox':box(ctx,x,y,12,8,P.metalDark);box(ctx,x+2,y-2,8,4,P.metalLight);box(ctx,x+5,y+8,2,8,P.woodDark);break;case'bucket':box(ctx,x,y,11,8,P.metalDark);box(ctx,x+2,y+2,7,4,P.metalLight);break;case'wheelbarrow':box(ctx,x+2,y,20,7,P.woodDark);box(ctx,x+4,y+2,14,5,P.woodLight);box(ctx,x+20,y+2,5,5,P.metalDark);box(ctx,x+4,y+7,2,8,P.woodDark);break;case'fence':box(ctx,x,y,34,3,P.woodDark);for(let i=0;i<35;i+=12)box(ctx,x+i,y-4,3,11,P.wood);break;case'post':box(ctx,x,y,4,18,P.woodDark);box(ctx,x+1,y,2,5,P.woodLight);break;case'watertrough':box(ctx,x,y,28,10,P.woodDark);box(ctx,x+3,y+3,22,4,P.waterLight);break;case'sack':box(ctx,x,y,13,15,P.woodLight);box(ctx,x+3,y-2,7,3,P.sign);break;case'toolbox':box(ctx,x,y,20,10,P.woodDark);box(ctx,x+2,y-3,16,4,P.woodLight);box(ctx,x+8,y+3,4,2,P.metalLight);break;case'cart':box(ctx,x,y,26,8,P.woodDark);box(ctx,x+3,y-3,20,5,P.woodLight);ctx.strokeStyle=P.metalDark;ctx.beginPath();ctx.arc(x+5,y+9,4,0,Math.PI*2);ctx.arc(x+21,y+9,4,0,Math.PI*2);ctx.stroke();break;case'bench':box(ctx,x,y,30,5,P.woodDark);box(ctx,x+2,y-5,26,4,P.woodLight);break;case'warning':box(ctx,x,y,44,12,P.signDark);box(ctx,x+2,y+2,40,7,P.sign);break;case'reed':box(ctx,x,y,2,18,P.leafDark);box(ctx,x+4,y-4,2,22,P.leaf);box(ctx,x+8,y+1,2,17,P.leafLight);break;case'woodpile':for(let i=0;i<4;i++)box(ctx,x+i*5,y-i*2,18,4,i%2?P.wood:P.woodLight);break}}
function drawLivingDetails(ctx){const h=((+S.minutes||0)/60)%24,weather=V.atmosphere?.weather?.type||'despejado';for(const o of details)draw(o,ctx);if(h>=7&&h<20&&weather!=='lluvia'){for(let i=0;i<3;i++){const x=1280+i*38+Math.sin(performance.now()/900+i)*5,y=1180+Math.sin(performance.now()/700+i)*5;box(ctx,x,y,3,2,P.ink)}}if(weather==='lluvia'){for(const o of details.filter(x=>x.type==='hay'))box(ctx,o.x-2,o.y-2,22,2,P.waterDark)}if(h>=18||h<6){for(const o of details.filter(x=>['streetlight','mailbox'].includes(x.type)))box(ctx,o.x-1,o.y-1,14,2,P.sign)}}
const previous=V.visualAuthority?.drawContent;if(previous&&!V.visualAuthority.__v134Wrapped){V.visualAuthority.__v134Base=previous;V.visualAuthority.drawContent=function(ctx,meta){previous(ctx,meta);drawLivingDetails(ctx)};V.visualAuthority.__v134Wrapped=true;}
V.livingWorld={version:'V134.2',details,drawObject:draw,weatherReactive:true,scheduleReactive:true,geometryUntouched:true,functionalActions:[...new Set(details.map(x=>x.action))],audit:{ok:rejected.length===0,accepted:details.length,rejected,geometryUntouched:true,principle:'detalles funcionales expanden; geografia no cambia'}};
window.dispatchEvent(new CustomEvent('villa-pelon-living-world-ready',{detail:V.livingWorld.audit}));
})();
