/* VILLA PELÓN V135 — INTEGRIDAD Y CONSOLIDACIÓN
   Unifica las últimas capas sin mover la geografía.
   Autoridades: mapa -> vida -> contenido -> visual -> interacción.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),G=V.worldGeometry||{},A=V.visualAuthority,L=V.villageLife,P=V.gameState||{};
const palette=A?.contract?.palette||{};
const legacyMap={'#40332e':palette.roofDark||palette.roof,'#493b34':palette.roof||palette.roofLight,'#3c302a':palette.outline,'#654b3b':palette.wood,'#513f36':palette.roof,'#71858a':palette.glass,'#3e4a49':palette.outline,'#d7c77e':palette.sign,'#8d7770':palette.wallDark,'#b13d3d':palette.signDark,'#e8e1cf':palette.wallLight,'#d0c7b3':palette.wall,'#cbb78e':palette.wall,'#806746':palette.wood,'#76583f':palette.wood,'#5c4639':palette.woodDark,'#6a3029':palette.roof,'#b25d4d':palette.wallDark,'#753a35':palette.roof,'#49383a':palette.outline,'#d2b56f':palette.sign,'#46513f':palette.leafDark,'#c8b486':palette.wallLight,'#70583f':palette.wood,'#70553f':palette.wood,'#4d6048':palette.leafDark,'#d0b37d':palette.wall,'#526a50':palette.leafDark,'#75563f':palette.wood,'#6b5149':palette.roof,'#b99b71':palette.wall,'#76563f':palette.wood,'#654839':palette.woodDark,'#714d47':palette.roof,'#d6bf94':palette.wallLight,'#745040':palette.woodDark,'#6b4a45':palette.roof,'#5d4439':palette.roof,'#c6a477':palette.wall,'#876649':palette.wallDark,'#27343a':palette.outline,'#202326':palette.ink,'#211d1b':palette.ink,'#302824':palette.outline,'#e1d8c5':palette.wallLight,'#5b4b3c':palette.woodDark,'#3b332b':palette.outline,'#8b5c3c':palette.wood,'#70472f':palette.woodDark,'#493326':palette.outline,'#e2d5b8':palette.wallLight,'#bd4d3e':palette.signDark,'#554236':palette.outline};
const integrity=V.systemIntegrity={version:'V135',principle:'one authority per system',authorities:{geometry:'worldGeometry',life:'villageLife',content:'worldContent + livingWorld',visual:'visualAuthority',frame:'renderCompositor',actions:'gameUnification'},rules:['geometry-read-only','river-crossing-bridge-only','vehicles-road-only','animals-rural-bounds','pixel-grid','canonical-palette','y-depth-order','single-life-tick','single-visual-loop']};
if(typeof CanvasRenderingContext2D!=='undefined'&&!CanvasRenderingContext2D.prototype.__vp135){const proto=CanvasRenderingContext2D.prototype,fd=Object.getOwnPropertyDescriptor(proto,'fillStyle'),sd=Object.getOwnPropertyDescriptor(proto,'strokeStyle');if(fd?.get&&fd?.set){Object.defineProperty(proto,'fillStyle',{configurable:true,get:fd.get,set(v){fd.set.call(this,legacyMap[String(v).toLowerCase()]||v)}})}if(sd?.get&&sd?.set){Object.defineProperty(proto,'strokeStyle',{configurable:true,get:sd.get,set(v){sd.set.call(this,legacyMap[String(v).toLowerCase()]||v)}})}Object.defineProperty(proto,'__vp135',{value:true});}
if(A){const base=A.__v134Base||A.drawContent;const detail=V.livingWorld;A.drawContent=function(ctx){const items=[];const baseItems=Array.isArray(V.worldContent?.elements)?V.worldContent.elements:[];for(const o of baseItems)items.push({y:(o.y||0)+(o.h||0),fn:()=>A.drawObject(ctx,o)});if(detail?.details&&detail.drawObject)for(const o of detail.details)items.push({y:(o.y||0)+(o.h||0),fn:()=>detail.drawObject(o,ctx)});items.sort((a,b)=>a.y-b.y);items.forEach(i=>i.fn());};A.depthAuthority='V135-y-sort';A.livingDetailsIntegrated=true;A.visualLegacyAdapter='V135-palette-adapter';}
if(L){L.geometryAuthority='worldGeometry';L.vehicleMovementAuthority='vehicle.route';L.animalMovementAuthority='animal.bounds';L.functionalDetailAuthority='V.livingWorld';}
const audit=()=>{const zones=G.zones||[],badDetails=(V.livingWorld?.audit?.rejected||[]).length;const geo=!!G.version,visual=A?.version==='V132',life=!!L?.singleTick;return{ok:geo&&visual&&life&&badDetails===0,geometry:geo,visual,life,details:V.livingWorld?.details?.length||0,rejectedDetails:badDetails,depth:A?.depthAuthority||null,paletteAdapter:A?.visualLegacyAdapter||null,principle:integrity.principle}};
integrity.audit=audit();V.engine=V.engine||{};V.engine.health=V.engine.health||function(){return{ok:true}};V.engine.health.integrity=audit();window.dispatchEvent(new CustomEvent('villa-pelon-integrity-ready',{detail:integrity.audit}));
})();
