/* VILLA PELÓN V142 — VIDA REACTIVA + MOVIMIENTO NPC + MICRODETALLE
   Capa no estructural. Respeta el sello V138: no cambia mundo, geometría, rutas ni edificios.
   V150 registra el reloj único; este módulo conserva la autoridad de vida reactiva.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const S=V.gameState||(V.gameState={});
const P=V.peopleVehicles||(V.peopleVehicles={});
const R=V.reactiveLife=V.reactiveLife||{};
R.version='142.1';R.active=true;R.geometry='SEALED_V138';R.actorSpeed=42;R.arrive=34;R.stateKey='v142';
const profiles=['marta','celso','nico','lucia','julia','mateo','tomas','rosa','raul','amalia'];
const nodes={plaza:[1120,690],escuela:[520,690],radio:[830,1010],comercio:[1500,690],barrio:[2150,1050],taller:[2750,1180],riego:[4950,900],rural:[5900,1500],bodega:[6500,1500],picada:[7350,2150],puente:[6500,2165]};
const schedules={marta:{morning:'comercio',midday:'plaza',evening:'barrio',night:'barrio'},celso:{morning:'plaza',midday:'plaza',evening:'plaza',night:'barrio'},nico:{morning:'escuela',midday:'plaza',evening:'taller',night:'barrio'},lucia:{morning:'comercio',midday:'comercio',evening:'plaza',night:'barrio'},julia:{morning:'escuela',midday:'escuela',evening:'plaza',night:'barrio'},mateo:{morning:'riego',midday:'rural',evening:'rural',night:'barrio'},tomas:{morning:'rural',midday:'bodega',evening:'rural',night:'barrio'},rosa:{morning:'rural',midday:'rural',evening:'plaza',night:'barrio'},raul:{morning:'radio',midday:'radio',evening:'plaza',night:'barrio'},amalia:{morning:'radio',midday:'plaza',evening:'radio',night:'barrio'}};
function hour(){return((Number(S.minutes)||480)/60)%24}function period(){const h=hour();return h<11?'morning':h<16?'midday':h<20?'evening':'night'}function dist(a,b){return Math.hypot(a.x-b[0],a.y-b[1])}function seed(i){return(Math.sin(i*91.17)*43758.5453)%1}
function ensureActors(){const A=Array.isArray(P.ambient)?P.ambient:[];if(!A.length)return[];if(!Array.isArray(V.npcs))V.npcs=[];A.forEach((a,i)=>{const id=a.id||profiles[i%profiles.length]||('villager_'+i);a.id=id;a.n=a.n||id.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());a.reactive=true;a.moving=!!a.moving;a.lifeState=a.lifeState||'quieto';a.target=a.target||null;a.v142=a.v142||{};if(i<profiles.length){a.role=a.role||profiles[i];a.contentAuthority=a.contentAuthority||'V141'}if(!V.npcs.includes(a))V.npcs.push(a)});return A}
function chooseTarget(a,i){const id=a.id||profiles[i%profiles.length],slot=(schedules[id]||{} )[period()]||['plaza','barrio','rural'][i%3],n=nodes[slot]||nodes.plaza;return[n[0]+(seed(i+Math.floor(Number(S.day)||1)*3)-.5)*70,n[1]+(seed(i+17)-.5)*46]}
function setRoutine(a,i){const p=period(),target=chooseTarget(a,i),night=p==='night';if(night&&dist(a,[2150,1050])<100){a.moving=false;a.lifeState='descansando';a.target=null;return}if(!a.target||dist(a,a.target)<R.arrive||a.v142.period!==p||a.v142.day!==Number(S.day)||a.v142.retarget){a.target=target;a.v142.period=p;a.v142.day=Number(S.day)||1;a.v142.retarget=false}a.moving=dist(a,a.target)>R.arrive;a.lifeState=a.moving?'caminando':'haciendo su tarea';a.lifeHour=Math.floor(hour());a.lifePeriod=p}
function moveActor(a,dt){if(!a.target||!a.moving)return;const dx=a.target[0]-a.x,dy=a.target[1]-a.y,d=Math.hypot(dx,dy)||1,speed=(Number(a.walkSpeed)||R.actorSpeed)*(V.atmosphere?.weather?.type==='lluvia'?.7:1);a.x+=dx/d*speed*dt;a.y+=dy/d*speed*dt;if(Math.abs(dx)>Math.abs(dy))a.dir=dx>0?'right':'left';else a.dir=dy>0?'down':'up';a.walk=(Number(a.walk)||0)+dt*6;if(d<R.arrive){a.x=a.target[0];a.y=a.target[1];a.moving=false;a.lifeState='haciendo su tarea';a.v142.retarget=true}}
function moveActors(dt){const A=ensureActors();A.forEach((a,i)=>{setRoutine(a,i);moveActor(a,dt)});R.actorCount=A.length}
function reactiveConsequence(){const h=hour();R.worldMood=h<7?'silencio':h<11?'inicio':h<16?'actividad':h<20?'regreso':'quietud';S.lifeState=S.lifeState||{};S.lifeState.reactiveMood=R.worldMood;S.lifeState.reactiveActors=R.actorCount||0}
function detailSeed(x,y){return Math.abs(Math.sin(x*12.9898+y*78.233)*43758.5453)%1}function blocked(x,y){const bs=V.worldGeometry?.buildings||[];return bs.some(b=>x>b.x-18&&x<b.x+b.w+18&&y>b.y-18&&y<b.y+b.h+18)}
function microDetails(ctx){const g=V.worldGeometry;if(!g)return;const bounds={x:300,y:300,w:7600,h:3900},s=V.gameState||{},cam=.82,vw=innerWidth,vh=innerHeight,screen=(x,y)=>({x:(x-(+s.x||0))*cam+vw/2,y:(y-(+s.y||0))*cam+vh/2}),minX=+s.x-vw/(2*cam)-80,maxX=+s.x+vw/(2*cam)+80,minY=+s.y-vh/(2*cam)-80,maxY=+s.y+vh/(2*cam)+80;ctx.save();for(let x=Math.floor(minX/70)*70;x<maxX;x+=70)for(let y=Math.floor(minY/70)*70;y<maxY;y+=70){if(x<bounds.x||x>bounds.x+bounds.w||y<bounds.y||y>bounds.y+bounds.h||blocked(x,y))continue;const q=detailSeed(x,y);if(q>.55)continue;const p=screen(x+(q-.5)*35,y+(detailSeed(y,x)-.5)*35);ctx.fillStyle=q>.27?'#6d7a51':'#7f8758';ctx.fillRect(Math.round(p.x),Math.round(p.y),2,4);if(q>.4)ctx.fillRect(Math.round(p.x+3),Math.round(p.y-2),2,3)}ctx.restore()}
R.drawDetails=microDetails;let last=performance.now();function tick(){const now=performance.now(),dt=Math.min(.12,(now-last)/1000);last=now;if(!S.started)return;try{moveActors(dt);reactiveConsequence()}catch(e){console.error('[VillaPelon][reactive-142]',e)}}
const register=V.runtimeRegister||((fn,ms)=>window.setInterval(fn,ms));R.clockRegistration=register(tick,80);tick();window.dispatchEvent(new CustomEvent('villa-pelon-reactive-ready',{detail:{version:R.version,geometryLocked:true,clock:'V150'}}));
})();
