/* VILLA PELÓN V154 — DIRECTOR DE CAMPAÑA Y ATLAS VIVO
   Autoridad integradora: misión -> conocimiento -> personaje -> capítulo -> continuidad.
   No modifica geometría ni crea un segundo motor de misiones.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}), M=V.missions;if(!M)return;
const S=V.gameState||(V.gameState={}), A=V.knowledgeAtlas||{entries:[]};
const D={version:'154.0',sealed:true,authority:'CAMPAIGN_CONTENT_V154',geometryAuthority:'V138',runtimeAuthority:'V150',missionAuthority:'V97',atlasAuthority:'V152',storyAuthority:'V153'};
D.unlocks={welcome:['welcome'],memory_01:['sources'],name_01:['community'],community_01:['community'],school_01:['school'],water_01:['water'],production_01:['production'],pelon_01:['production','work'],oral_01:['fiction'],archive_01:['sources','research'],dni_01:['picada21'],picada21_memory:['fiction','research'],founding_01:['research'],irrigation_02:['water'],school_02:['school','sources'],worker_01:['work'],map_01:['river','picada21'],bridges_01:['river'],research_01:['sources','research'],history_01:['research'],free_explore:['open']};
D.missionLessons={welcome:'Orientación: el pueblo se comprende recorriéndolo.',memory_01:'Método: una pista abre una investigación.',name_01:'Identidad: los nombres contienen capas de memoria.',community_01:'Comunidad: las voces son parciales y valiosas.',school_01:'Instituciones: la escuela conserva rastros de generaciones.',water_01:'Territorio: el riego conecta agua, tierra y producción.',production_01:'Producción: el trabajo transforma paisaje e identidad.',pelon_01:'Memoria social: una celebración también puede conservar trabajo y cultura.',oral_01:'Relato: una historia oral puede abrir preguntas sin convertirse automáticamente en prueba.',archive_01:'Fuentes: cada tipo de evidencia responde preguntas distintas.',dni_01:'Territorio humano: el camino también conecta encuentros y responsabilidades.',picada21_memory:'Contraste: escuchar primero y verificar después.',founding_01:'Cronología: crear, organizar y crecer son procesos diferentes.',irrigation_02:'Relación: agua, producción y población deben estudiarse juntas.',school_02:'Memoria institucional: recordar exige contextualizar.',worker_01:'Trabajo: las personas que producen también forman memoria.',map_01:'Cartografía: un mapa es una fuente que necesita contexto.',bridges_01:'Espacio: el río organiza recorridos y relaciones.',research_01:'Investigación: afirmación → fuente → contraste → conclusión.',history_01:'Rigor: reconocer lo que todavía no sabemos también es conocimiento.',free_explore:'Autonomía: terminar una campaña abre nuevas preguntas.'};
function ensure(){S.knowledge=Array.isArray(S.knowledge)?S.knowledge:[];S.knowledgeSeen=Array.isArray(S.knowledgeSeen)?S.knowledgeSeen:[];S.chapterState=S.chapterState&&typeof S.chapterState==='object'?S.chapterState:{};S.npcArcs=S.npcArcs&&typeof S.npcArcs==='object'?S.npcArcs:{};S.campaign=S.campaign&&typeof S.campaign==='object'?S.campaign:{};S.campaign.version='154.0'}
function entry(id){return A.entries.find(e=>e.id===id)||null}
function unlock(ids,mission){ensure();let added=[];(ids||[]).forEach(id=>{if(!S.knowledge.includes(id)){S.knowledge.push(id);added.push(id)}if(!S.knowledgeSeen.includes(id))S.knowledgeSeen.push(id)});if(added.length){S.campaign.lastUnlocks=added;window.dispatchEvent(new CustomEvent('villa-pelon-knowledge-unlocked',{detail:{ids:added,mission}}))}return added}
function setChapter(m){ensure();const a=m?.chapter||'EXPLORACIÓN';S.chapterState[a]=(S.chapterState[a]||0)+1;S.campaign.currentAct=m?.id==='free_explore'?'futuro':({PUEBLO:'llegada',MEMORIA:'huellas',IDENTIDAD:'huellas',COMUNIDAD:'huellas',EDUCACIÓN:'huellas',TERRITORIO:'territorio',PRODUCCIÓN:'territorio',TRABAJO:'territorio',CARTOGRAFÍA:'territorio',INVESTIGACIÓN:'memoria',HISTORIA:'memoria',EXPLORACIÓN:'futuro'}[a]||'territorio')}
function updateNpc(m){ensure();(m?.objectives||[]).forEach(o=>{if(o.type==='talk'&&o.target){const id=o.target.replace(/_\d+$/,'');S.npcArcs[id]=(S.npcArcs[id]||0)+1}})}
const baseComplete=M.completeStep;
M.completeStep=function(state,key){const before=this.current(state),result=baseComplete.call(this,state,key);if(!result)return result;if(result.complete){ensure();const added=unlock(D.unlocks[before.id]||[],before.id);setChapter(before);updateNpc(before);state.campaign.lastMission=before.id;state.campaign.lastLesson=D.missionLessons[before.id]||'';state.campaign.completedCount=(+state.campaign.completedCount||0)+1;result.knowledge=added;result.lesson=state.campaign.lastLesson;result.act=state.campaign.currentAct;window.dispatchEvent(new CustomEvent('villa-pelon-campaign-progress',{detail:{mission:before.id,knowledge:added,lesson:result.lesson,act:result.act}}))}return result};
function buildAtlas(){if(document.getElementById('knowledgeAtlasPanel'))return;const p=document.createElement('aside');p.id='knowledgeAtlasPanel';p.className='knowledge-atlas hidden';p.innerHTML='<div class="ka-head"><div><small>VILLA PELÓN · CUADERNO</small><h2>Atlas de conocimiento</h2></div><button id="kaClose" type="button">×</button></div><div class="ka-summary" id="kaSummary"></div><div class="ka-list" id="kaList"></div>';document.body.appendChild(p);document.getElementById('kaClose')?.addEventListener('click',()=>p.classList.add('hidden'));window.addEventListener('keydown',e=>{if(String(e.key).toLowerCase()==='i'&&!S.dialogue){p.classList.toggle('hidden');renderAtlas();e.preventDefault()}});window.addEventListener('villa-pelon-knowledge-unlocked',renderAtlas);renderAtlas()}
function renderAtlas(){ensure();const p=document.getElementById('knowledgeAtlasPanel');if(!p)return;const l=document.getElementById('kaList'),s=document.getElementById('kaSummary'),known=S.knowledge||[];if(s)s.textContent=`${known.length}/${A.entries.length} conocimientos desbloqueados · ${S.campaign.completedCount||0} misiones completadas`;if(l)l.innerHTML=A.entries.map(e=>{const ok=known.includes(e.id);return `<article class="ka-entry ${ok?'unlocked':'locked'}"><div class="ka-badge">${ok?'✓':'?'}</div><div><small>${e.act}</small><h3>${ok?e.title:'Conocimiento pendiente'}</h3><p>${ok?e.body:'Completá misiones para desbloquear esta entrada.'}</p>${ok&&e.source?`<span class="ka-source">${e.source}${e.fiction?' · FICCIÓN':''}</span>`:''}</div></article>`}).join('')}
function bind(){window.addEventListener('villa-pelon-campaign-progress',e=>{const d=e.detail||{};if(d.knowledge?.length){const n=d.knowledge.map(id=>entry(id)?.title).filter(Boolean),t=document.getElementById('missionToast');if(t&&n.length){t.textContent='CONOCIMIENTO DESBLOQUEADO · '+n.join(' · ');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}}renderAtlas()})}
ensure();V.campaignDirector=D;V.knowledgeState={unlock,entry,render:renderAtlas};V.runtimeAudit=Object.assign(V.runtimeAudit||{},{campaignDirector:true,campaignDirectorVersion:'154.0',atlasMissionLink:true,geometryLocked:true});window.addEventListener('DOMContentLoaded',()=>{buildAtlas();bind()});if(document.readyState!=='loading'){buildAtlas();bind()}
})();
