/* VILLA PELÓN V155.2 — CAMPAÑA PROFUNDA CONSOLIDADA
   Unifica el catálogo, elimina ramas huérfanas y corrige objetivos sin runtime.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),M=V.missions;if(!M)return;
const orphan=['territory_artifacts_01','source_03','rural_memory_02','landscape_01'];
M.list=M.list.filter(m=>!orphan.includes(m.id));
const repair=M.list.find(m=>m.id==='memory_01');if(repair)repair.objectives=[{id:'archive_clue',type:'inspect',target:'archive',label:'Encontrá la primera pista en el archivo'}];
const deep=[
['camp21','HUELLAS','Volver a mirar','Regresá al núcleo y comprobá cuánto cambió tu mirada después de conocer el territorio.',[['marta21','talk','marta','Volvé a hablar con Marta'],['plaza21','reach','plaza','Volvé a la plaza']],4200,'camp22'],
['camp22','HUELLAS','Celso y los nombres','Contrastá una memoria del lugar con la pregunta que dejó abierta el topónimo.',[['celso22','talk','celso','Preguntale a Celso qué recuerda'],['name22','inspect','name_marker','Revisá nuevamente la ficha del nombre']],4400,'camp23'],
['camp23','HUELLAS','Preguntar mejor','Nico plantea una duda; tu tarea ya no es responder rápido sino formular una buena pregunta.',[['nico23','talk','nico','Escuchá la pregunta de Nico'],['map23','inspect','territory_map','Buscá pistas en el mapa']],4500,'camp24'],
['camp24','HUELLAS','Una red de personas','Lucía conecta dos recuerdos y te obliga a mirar la comunidad como una red.',[['lucia24','talk','lucia','Hablá con Lucía'],['nico24','talk','nico','Contrastá la historia con Nico']],4600,'camp25'],
['camp25','HUELLAS','La escuela vuelve a hablar','Volvé a la escuela con una pregunta concreta en vez de buscar solamente una fecha.',[['julia25','talk','julia','Consultá a Julia'],['school25','inspect','school_archive_2','Revisá la ficha escolar']],4800,'camp26'],
['camp26','TERRITORIO','Mateo y el agua','Relacioná lo aprendido sobre riego con la experiencia cotidiana de quien trabaja el territorio.',[['mateo26','talk','mateo','Escuchá a Mateo'],['water26','inspect','irrigation_timeline','Revisá la secuencia del riego']],5000,'camp27'],
['camp27','TERRITORIO','La producción se ve','Tomás te ayuda a leer el paisaje productivo como resultado de decisiones y trabajo.',[['tomas27','talk','tomas','Hablá con Tomás'],['winery27','reach','winery','Recorré nuevamente el área productiva']],5200,'camp28'],
['camp28','TERRITORIO','Rosa recuerda el trabajo','La memoria productiva se amplía hacia las personas que hicieron posible ese paisaje.',[['rosa28','talk','rosa','Escuchá a Rosa'],['worker28','inspect','worker_marker','Revisá la ficha del trabajo rural']],5400,'camp29'],
['camp29','MEMORIA','Contar también es elegir','Raúl muestra que comunicar una historia exige decidir qué se dice y qué se deja como pregunta.',[['raul29','talk','raul','Hablá con Raúl'],['source29','inspect','source_lab','Compará las fuentes']],5600,'camp30'],
['camp30','MEMORIA','El archivo responde','Amalia convierte tus notas dispersas en una investigación ordenada.',[['amalia30','talk','amalia','Consultá a Amalia'],['archive30','inspect','archive','Ordená tu ficha']],5800,'camp31'],
['camp31','TERRITORIO','Volver al camino','El conocimiento cambia el significado del recorrido hacia el borde rural.',[['rural31','reach','rural','Atravesá la transición rural'],['mateo31','talk','mateo','Buscá nuevamente a Mateo']],6000,'camp32'],
['camp32','TERRITORIO','El río desde otra mirada','Llegá al agua sin convertirla en decoración: observá cómo organiza el viaje.',[['bridge32','reach','bridge','Llegá a un puente'],['map32','inspect','territory_map','Relacioná el puente con el mapa']],6200,'camp33'],
['camp33','TERRITORIO','Picada 21, sin apuro','El camino rural pide otra velocidad. Observá antes de buscar una recompensa.',[['picada33','reach','picada21','Llegá a Picada 21'],['memory33','inspect','picada21_memory','Releé la memoria del camino']],6400,'camp34'],
['camp34','MEMORIA','Lo oral abre la puerta','Separá una frase recordada de la afirmación histórica que podría investigarse.',[['rosa34','talk','rosa','Pedile a Rosa un recuerdo'],['sources34','inspect','source_lab','Elegí qué fuente podría contrastarlo']],6600,'camp35'],
['camp35','MEMORIA','Una fecha necesita contexto','La cronología deja de ser una lista: ahora tenés que explicar qué significa cada fecha.',[['celso35','talk','celso','Contrastá una fecha con Celso'],['found35','inspect','founding_marker','Revisá la ficha de fundación']],6800,'camp36'],
['camp36','INVESTIGACIÓN','El agua como evidencia','Volvé al riego con una pregunta más precisa: qué cambió y qué evidencia lo demuestra.',[['water36','inspect','irrigation_marker','Revisá la evidencia del riego'],['mateo36','talk','mateo','Contrastá con Mateo']],7000,'camp37'],
['camp37','INVESTIGACIÓN','La escuela como contraste','Usá la memoria escolar para practicar la diferencia entre recordar y documentar.',[['julia37','talk','julia','Consultá a Julia'],['school37','inspect','school_archive','Volvé a la ficha de la escuela']],7200,'camp38'],
['camp38','INVESTIGACIÓN','El territorio completo','Uní personas, agua, caminos, producción y memoria en una sola lectura.',[['map38','inspect','territory_map','Armá la lectura territorial'],['bridge38','reach','bridge','Comprobá la relación con el río']],7400,'camp39'],
['camp39','FUTURO','Contar sin inventar','Prepará una síntesis que distinga hechos documentados, testimonios y ficción narrativa.',[['raul39','talk','raul','Consultá a Raúl sobre cómo comunicar'],['research39','inspect','research_question','Revisá tu método de investigación']],7600,'camp40'],
['camp40','FUTURO','Villa Pelón queda abierta','Cerrá la campaña profunda: no con una respuesta definitiva, sino con herramientas para seguir investigando.',[['amalia40','talk','amalia','Presentá tu investigación a Amalia'],['archive40','inspect','archive_final','Cerrá el archivo de campaña']],10000,'free_explore']
].map(x=>({id:x[0],chapter:x[1],title:x[2],description:x[3],objectives:x[4].map(o=>({id:o[0],type:o[1],target:o[2],label:o[3]})),reward:x[5],next:x[6]}));
const oldEnd=M.list.find(m=>m.id==='history_01');if(oldEnd)oldEnd.next='camp21';
M.list=M.list.filter(m=>m.id!=='free_explore'&&!deep.some(d=>d.id===m.id)).concat(deep,M.list.filter(m=>m.id==='free_explore'));
const D=V.campaignDirector||(V.campaignDirector={});D.version='155.2';D.sealed=true;D.deepCampaign=true;D.campaignLength=M.list.length;D.finalMission='camp40';D.authority='CAMPAIGN_CONTENT_V155';D.removedParallelMissions=orphan;
D.missionLessons=Object.assign(D.missionLessons||{},Object.fromEntries(deep.map((m,i)=>[m.id,`Campaña profunda ${i+21}: ${m.description}`])));
D.unlocks=Object.assign(D.unlocks||{},Object.fromEntries(deep.map((m,i)=>[m.id,[['community','school','water','production','work','river','picada21','sources','research','open'][i%10]]])));
function audit(){const issues=[],list=M.list||[],set=new Set(list.map(m=>m.id));list.forEach(m=>{if(m.next&&!set.has(m.next))issues.push('broken-next:'+m.id+'>'+m.next);(m.objectives||[]).forEach(o=>{if(!o.id||!o.type||!o.target)issues.push('bad-objective:'+m.id);if(o.type==='inspect'&&!V.missionRuntime?.points?.[o.target])issues.push('missing-point:'+m.id+':'+o.target);if(o.type==='reach'&&!V.missionRuntime?.regions?.[o.target]&&o.target!=='bridge')issues.push('missing-region:'+m.id+':'+o.target)})});return{ok:issues.length===0,issues,total:list.length,deep:deep.length,removedParallel:orphan.length,first:'welcome',last:'free_explore',geometryAuthority:'V138'} }
V.campaignAudit=audit();V.runtimeAudit=Object.assign(V.runtimeAudit||{},{deepCampaign:true,deepCampaignVersion:'155.2',campaignAudit:V.campaignAudit,geometryLocked:true,parallelMissionAuthorityRemoved:true,orphanObjectivesRepaired:true});window.dispatchEvent(new CustomEvent('villa-pelon-deep-campaign-ready',{detail:V.campaignAudit}));
})();