/* VILLA PELÓN V155 — CAMPAÑA PROFUNDA
   Autoridad única: mission_system + V154 + V155.
   Consolida la cadena y desconecta el catálogo histórico paralelo para evitar misiones huérfanas.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),M=V.missions;if(!M)return;
const orphan=['territory_artifacts_01','source_03','rural_memory_02','landscape_01'];
M.list=M.list.filter(m=>!orphan.includes(m.id));
const deep=[
{id:'camp21',chapter:'HUELLAS',title:'Volver a mirar',description:'Regresá al núcleo y comprobá cuánto cambió tu mirada después de conocer el territorio.',objectives:[{id:'marta21',type:'talk',target:'marta',label:'Volvé a hablar con Marta'},{id:'plaza21',type:'reach',target:'plaza',label:'Volvé a la plaza'}],reward:4200,next:'camp22'},
{id:'camp22',chapter:'HUELLAS',title:'Celso y los nombres',description:'Contrastá una memoria del lugar con la pregunta que dejó abierta el topónimo.',objectives:[{id:'celso22',type:'talk',target:'celso',label:'Preguntale a Celso qué recuerda'},{id:'name22',type:'inspect',target:'name_marker',label:'Revisá nuevamente la ficha del nombre'}],reward:4400,next:'camp23'},
{id:'camp23',chapter:'HUELLAS',title:'Preguntar mejor',description:'Nico plantea una duda; tu tarea ya no es responder rápido sino formular una buena pregunta.',objectives:[{id:'nico23',type:'talk',target:'nico',label:'Escuchá la pregunta de Nico'},{id:'map23',type:'inspect',target:'territory_map',label:'Buscá pistas en el mapa'}],reward:4500,next:'camp24'},
{id:'camp24',chapter:'HUELLAS',title:'Una red de personas',description:'Lucía conecta dos recuerdos y te obliga a mirar la comunidad como una red.',objectives:[{id:'lucia24',type:'talk',target:'lucia',label:'Hablá con Lucía'},{id:'nico24',type:'talk',target:'nico',label:'Contrastá la historia con Nico'}],reward:4600,next:'camp25'},
{id:'camp25',chapter:'HUELLAS',title:'La escuela vuelve a hablar',description:'Volvé a la escuela con una pregunta concreta en vez de buscar solamente una fecha.',objectives:[{id:'julia25',type:'talk',target:'julia',label:'Consultá a Julia'},{id:'school25',type:'inspect',target:'school_archive_2',label:'Revisá la ficha escolar'}],reward:4800,next:'camp26'},
{id:'camp26',chapter:'TERRITORIO',title:'Mateo y el agua',description:'Relacioná lo aprendido sobre riego con la experiencia cotidiana de quien trabaja el territorio.',objectives:[{id:'mateo26',type:'talk',target:'mateo',label:'Escuchá a Mateo'},{id:'water26',type:'inspect',target:'irrigation_timeline',label:'Revisá la secuencia del riego'}],reward:5000,next:'camp27'},
{id:'camp27',chapter:'TERRITORIO',title:'La producción se ve',description:'Tomás te ayuda a leer el paisaje productivo como resultado de decisiones y trabajo.',objectives:[{id:'tomas27',type:'talk',target:'tomas',label:'Hablá con Tomás'},{id:'winery27',type:'reach',target:'winery',label:'Recorré nuevamente el área productiva'}],reward:5200,next:'camp28'},
{id:'camp28',chapter:'TERRITORIO',title:'Rosa recuerda el trabajo',description:'La memoria productiva se amplía hacia las personas que hicieron posible ese paisaje.',objectives:[{id:'rosa28',type:'talk',target:'rosa',label:'Escuchá a Rosa'},{id:'worker28',type:'inspect',target:'worker_marker',label:'Revisá la ficha del trabajo rural'}],reward:5400,next:'camp29'},
{id:'camp29',chapter:'MEMORIA',title:'Contar también es elegir',description:'Raúl muestra que comunicar una historia exige decidir qué se dice y qué se deja como pregunta.',objectives:[{id:'raul29',type:'talk',target:'raul',label:'Hablá con Raúl'},{id:'source29',type:'inspect',target:'source_lab',label:'Compará las fuentes'}],reward:5600,next:'camp30'},
{id:'camp30',chapter:'MEMORIA',title:'El archivo responde',description:'Amalia convierte tus notas dispersas en una investigación ordenada.',objectives:[{id:'amalia30',type:'talk',target:'amalia',label:'Consultá a Amalia'},{id:'archive30',type:'inspect',target:'archive',label:'Ordená tu ficha'}],reward:5800,next:'camp31'},
{id:'camp31',chapter:'TERRITORIO',title:'Volver al camino',description:'El conocimiento cambia el significado del recorrido hacia el borde rural.',objectives:[{id:'rural31',type:'reach',target:'rural',label:'Atravesá la transición rural'},{id:'mateo31',type:'talk',target:'mateo',label:'Buscá nuevamente a Mateo'}],reward:6000,next:'camp32'},
{id:'camp32',chapter:'TERRITORIO',title:'El río desde otra mirada',description:'Llegá al agua sin convertirla en decoración: observá cómo organiza el viaje.',objectives:[{id:'bridge32',type:'reach',target:'bridge',label:'Llegá a un puente'},{id:'map32',type:'inspect',target:'territory_map',label:'Relacioná el puente con el mapa'}],reward:6200,next:'camp33'},
{id:'camp33',chapter:'TERRITORIO',title:'Picada 21, sin apuro',description:'El camino rural pide otra velocidad. Observá antes de buscar una recompensa.',objectives:[{id:'picada33',type:'reach',target:'picada21',label:'Llegá a Picada 21'},{id:'memory33',type:'inspect',target:'picada21_memory',label:'Releé la memoria del camino'}],reward:6400,next:'camp34'},
{id:'camp34',chapter:'MEMORIA',title:'Lo oral abre la puerta',description:'Separá una frase recordada de la afirmación histórica que podría investigarse.',objectives:[{id:'rosa34',type:'talk',target:'rosa',label:'Pedile a Rosa un recuerdo'},{id:'sources34',type:'inspect',target:'source_lab',label:'Elegí qué fuente podría contrastarlo'}],reward:6600,next:'camp35'},
{id:'camp35',chapter:'MEMORIA',title:'Una fecha necesita contexto',description:'La cronología deja de ser una lista: ahora tenés que explicar qué significa cada fecha.',objectives:[{id:'celso35',type:'talk',target:'celso',label:'Contrastá una fecha con Celso'},{id:'found35',type:'inspect',target:'founding_marker',label:'Revisá la ficha de fundación'}],reward:6800,next:'camp36'},
{id:'camp36',chapter:'INVESTIGACIÓN',title:'El agua como evidencia',description:'Volvé al riego con una pregunta más precisa: qué cambió y qué evidencia lo demuestra.',objectives:[{id:'water36',type:'inspect',target:'irrigation_marker',label:'Revisá la evidencia del riego'},{id:'mateo36',type:'talk',target:'mateo',label:'Contrastá con Mateo'}],reward:7000,next:'camp37'},
{id:'camp37',chapter:'INVESTIGACIÓN',title:'La escuela como contraste',description:'Usá la memoria escolar para practicar la diferencia entre recordar y documentar.',objectives:[{id:'julia37',type:'talk',target:'julia',label:'Consultá a Julia'},{id:'school37',type:'inspect',target:'school_archive',label:'Volvé a la ficha de la escuela'}],reward:7200,next:'camp38'},
{id:'camp38',chapter:'INVESTIGACIÓN',title:'El territorio completo',description:'Uní personas, agua, caminos, producción y memoria en una sola lectura.',objectives:[{id:'map38',type:'inspect',target:'territory_map',label:'Armá la lectura territorial'},{id:'bridge38',type:'reach',target:'bridge',label:'Comprobá la relación con el río'}],reward:7400,next:'camp39'},
{id:'camp39',chapter:'FUTURO',title:'Contar sin inventar',description:'Prepará una síntesis que distinga hechos documentados, testimonios y ficción narrativa.',objectives:[{id:'raul39',type:'talk',target:'raul',label:'Consultá a Raúl sobre cómo comunicar'},{id:'research39',type:'inspect',target:'research_question',label:'Revisá tu método de investigación'}],reward:7600,next:'camp40'},
{id:'camp40',chapter:'FUTURO',title:'Villa Pelón queda abierta',description:'Cerrá la campaña profunda: no con una respuesta definitiva, sino con herramientas para seguir investigando.',objectives:[{id:'amalia40',type:'talk',target:'amalia',label:'Presentá tu investigación a Amalia'},{id:'archive40',type:'inspect',target:'archive_final',label:'Cerrá el archivo de campaña'}],reward:10000,next:'free_explore'}
];
const oldEnd=M.list.find(m=>m.id==='history_01');if(oldEnd)oldEnd.next='camp21';
M.list=M.list.filter(m=>m.id!=='free_explore'&&!deep.some(d=>d.id===m.id)).concat(deep,M.list.filter(m=>m.id==='free_explore'));
const D=V.campaignDirector||(V.campaignDirector={});D.version='155.1';D.sealed=true;D.deepCampaign=true;D.campaignLength=M.list.length;D.finalMission='camp40';D.authority='CAMPAIGN_CONTENT_V155';D.removedParallelMissions=orphan;
D.missionLessons=Object.assign(D.missionLessons||{},Object.fromEntries(deep.map((m,i)=>[m.id,`Campaña profunda ${i+21}: ${m.description}`])));
D.unlocks=Object.assign(D.unlocks||{},Object.fromEntries(deep.map((m,i)=>[m.id,[['community','school','water','production','work','river','picada21','sources','research','open'][i%10]]])));
function audit(){const issues=[],list=M.list||[],set=new Set(list.map(m=>m.id));list.forEach(m=>{if(m.next&&!set.has(m.next))issues.push('broken-next:'+m.id+'>'+m.next);(m.objectives||[]).forEach(o=>{if(!o.id||!o.type||!o.target)issues.push('bad-objective:'+m.id);if(o.type==='inspect'&&!V.missionRuntime?.points?.[o.target])issues.push('missing-point:'+m.id+':'+o.target);if(o.type==='reach'&&!V.missionRuntime?.regions?.[o.target]&&o.target!=='bridge')issues.push('missing-region:'+m.id+':'+o.target)})});return{ok:issues.length===0,issues,total:list.length,deep:deep.length,removedParallel:orphan.length,first:'welcome',last:'free_explore',geometryAuthority:'V138'} }
V.campaignAudit=audit();V.runtimeAudit=Object.assign(V.runtimeAudit||{},{deepCampaign:true,deepCampaignVersion:'155.1',campaignAudit:V.campaignAudit,geometryLocked:true,parallelMissionAuthorityRemoved:true});window.dispatchEvent(new CustomEvent('villa-pelon-deep-campaign-ready',{detail:V.campaignAudit}));
})();