/* VILLA PELÓN V156 — AUDITORÍA VISUAL QUIRÚRGICA
   No mueve geometría. Unifica capas visuales, detecta duplicados de UI y fija contratos de presentación.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const A={version:'156.0',sealed:true,geometryAuthority:'V138',visualAuthority:'V131/V143/V144',frameAuthority:'V150',principles:['one-world-frame','single-pixel-language','no-ui-duplication','no-world-overlay-duplication','no-random-decoration']};
function css(){if(document.getElementById('v156VisualContract'))return;const s=document.createElement('style');s.id='v156VisualContract';s.textContent=`#game{position:relative;overflow:hidden}#world,#worldDetail,#worldAmbient{position:absolute;inset:0;width:100%;height:100%;display:block}#world{z-index:1}#worldDetail{z-index:2;pointer-events:none}#worldAmbient{z-index:0;pointer-events:none}#worldAtmosphere{position:absolute;inset:0;z-index:3;pointer-events:none}.hud{position:absolute;z-index:20}.quest{position:absolute;z-index:21}.dialogue{position:absolute;z-index:40}.touch{position:absolute;z-index:45}.save{position:absolute;z-index:46}.missionToast{position:fixed;z-index:1200;pointer-events:none}.knowledge-atlas{z-index:1100}`;document.head.appendChild(s)}
function audit(){const issues=[],warnings=[],ids=[...document.querySelectorAll('[id]')].map(e=>e.id),dups=ids.filter((id,i,a)=>a.indexOf(id)!==i);if(dups.length)issues.push(...[...new Set(dups)].map(id=>'duplicate-dom-id:'+id));const required=['world','worldDetail','worldAtmosphere','questText','questProgress','dialogue','speaker','dialogueText','missionToast','interact','save'];required.forEach(id=>{if(!document.getElementById(id))issues.push('missing-ui:'+id)});if(V.visualAuthority?.version!=='V132')warnings.push('visual-authority-version');if(V.renderCompositor?.singleRAF!==true)warnings.push('compositor-contract-not-confirmed');const c=['world','worldDetail','worldAmbient'].map(id=>document.getElementById(id)).filter(Boolean);if(c.some(x=>x.width&&x.height&&x.width!==c[0].width&&x.height!==c[0].height))warnings.push('canvas-size-mismatch');return{ok:issues.length===0,issues,warnings,duplicateIds:[...new Set(dups)],requiredUI:required.length,canvasLayers:c.map(x=>x.id),singleFrame:V.renderCompositor?.singleRAF===true}}
function run(){css();V.visualSurgicalAudit=audit();V.visualContract=A;V.runtimeAudit=Object.assign(V.runtimeAudit||{},{visualSurgicalAudit:true,visualSurgicalAuditVersion:'156.0',geometryLocked:true,uiDuplicationCheck:V.visualSurgicalAudit.issues.length===0});document.documentElement.dataset.visualAudit='156';window.dispatchEvent(new CustomEvent('villa-pelon-visual-surgical-audit',{detail:V.visualSurgicalAudit}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();