/* VILLA PELÓN V159 — PUENTE DE CARGA Y AUDITORÍA VISUAL */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const ids=['world','worldDetail','worldAtmosphere','questText','questProgress','dialogue','speaker','dialogueText','missionToast','interact','save'];const seen=new Set(),dupes=[];document.querySelectorAll('[id]').forEach(e=>{if(seen.has(e.id))dupes.push(e.id);seen.add(e.id)});const terrain=document.getElementById('world'),detail=document.getElementById('worldDetail'),ambient=document.getElementById('worldAmbient');
const audit={version:'159.0',geometry:'V138_LOCKED',frame:'SINGLE_RAF_V90',terrainAuthority:'V158_ENGINE',actorAuthority:'V158_COMPOSITOR',playerAuthority:'V158_COMPOSITOR',gameplayAuthority:'V159_INTEGRATION_FLOOR',pixelLanguage:'PIXEL_RURAL_PATAGONICO',checks:{uniqueDomIds:dupes.length===0,requiredUi:ids.every(id=>document.getElementById(id)),singleFrame:!!V.engine&&!!V.renderCompositor&&V.renderCompositor.singleRAF,terrainActorSeparation:!!V.renderCompositor&&!V.renderCompositor.ownsTerrain,playerCentralized:!!V.renderCompositor?.ownsPlayer,detailCanvas:!!detail,ambientCanvasDisabled:ambient?.style.display==='none',geometryLocked:!!V.worldLock||!!V.worldSeal,visualAuthority:!!V.renderCompositor&&V.renderCompositor.version==='158.0',movementMissionBridge:!!V.engine?.gameplayBridge,reachObjectives:!!V.engine?.health?.().reachBridge};audit.duplicateIds=dupes;audit.ok=Object.values(audit.checks).every(Boolean)&&dupes.length===0;V.visualWorldAudit=audit;V.visualPresentationSeal={version:'159.0',sealed:true,geometry:'V138',frame:'V90_SINGLE_RAF',render:'V158',player:'CENTRALIZED',gameplay:'V159_CONNECTED',intro:'INTERACTIVE',style:'PIXEL_RURAL_PATAGONICO',status:audit.ok?'CONSOLIDATED':'NEEDS_REVIEW'};V.runtimeAudit=Object.assign(V.runtimeAudit||{},{visualWorldAudit:audit.ok,singleVisualFrame:audit.checks.singleFrame,terrainActorSeparation:audit.checks.terrainActorSeparation,playerCentralized:audit.checks.playerCentralized,movementMissionBridge:audit.checks.movementMissionBridge,reachObjectives:audit.checks.reachObjectives,interactiveIntro:true,visualPresentationSeal:true});window.dispatchEvent(new CustomEvent('villa-pelon-visual-world-audit-ready',{detail:audit}));
function load159(){if(document.querySelector('script[data-v159-bridge]'))return;const s=document.createElement('script');s.src='./v159_integration_bridge.js?v=159.0';s.defer=false;s.dataset.v159Bridge='1';s.onload=()=>loadActions();document.head.appendChild(s)}
function loadActions(){if(document.querySelector('script[data-v159-actions]'))return;const s=document.createElement('script');s.src='./v159_action_transport_runtime.js?v=159.0';s.defer=false;s.dataset.v159Actions='1';s.onload=()=>loadRepair();document.head.appendChild(s)}
function loadRepair(){if(document.querySelector('script[data-v159-repair]'))return;const s=document.createElement('script');s.src='./v159_repair_guard.js?v=159.0';s.defer=false;s.dataset.v159Repair='1';s.onload=()=>loadSeal();document.head.appendChild(s)}
function loadSeal(){if(document.querySelector('script[data-v159-seal]'))return;const s=document.createElement('script');s.src='./v159_system_seal.js?v=159.0';s.defer=false;s.dataset.v159Seal='1';s.onload=()=>window.dispatchEvent(new CustomEvent('villa-pelon-v159-actions-ready'));document.head.appendChild(s)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load159,{once:true});else load159();
})();
