/* VILLA PELÓN V159 — SYSTEM FLOOR / CERTIFICACIÓN FINAL
   V138 = geometría cerrada | V150 = runtime lógico | V155 = campaña | V158 = render | V159 = integración.
   V159 agrega una prueba explícita de espacio público para impedir que una calle o edificio vuelva a ocupar la plaza.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),G=V.worldGeometry||{},S=V.gameState||{},issues=[],warnings=[];const fail=(ok,msg)=>{if(!ok)issues.push(msg)},warn=(ok,msg)=>{if(!ok)warnings.push(msg)},rect=(a,b)=>!!a&&!!b&&['x','y','w','h'].every(k=>Math.round(+a[k])===Math.round(+b[k]));
const canonical={world:[8200,4200],urban:{x:300,y:300,w:2700,h:1900},rural:{x:3000,y:300,w:4900,h:2350},river:{x:250,y:2700,w:7600,h:100},picada21:{x:4300,y:3180,w:3500,h:850}};
const B=G.buildings||[],R=G.roads||[],BR=G.bridges||[],Z=G.zones||[],missions=V.missions?.list||[],P=V.peopleVehicles||{},A=V.atmosphere||{},I=V.interface||{};
const overlaps=(a,b,p=0)=>!!a&&!!b&&a.x-p<b.x+b.w+p&&a.x+a.w+p>b.x-p&&a.y-p<b.y+b.h+p&&a.y+a.h+p>b.y-p;
/* 1. GEOMETRÍA */
fail(+V.world?.w===8200&&+V.world?.h===4200,'WORLD_SIZE');fail(!!V.worldSeal&&V.worldSeal.version==='V138','V138_SEAL');fail(!!V.geometryFloorLock?.locked,'GEOMETRY_LOCK');fail(!!V.worldMaster?.locked,'WORLD_MASTER_LOCK');fail(rect(G.river,canonical.river),'RIVER_CANONICAL');fail(Z.some(z=>rect(z,canonical.urban)),'URBAN_CANONICAL');fail(Z.some(z=>rect(z,canonical.rural)),'RURAL_CANONICAL');fail(Z.some(z=>rect(z,canonical.picada21)),'PICADA21_CANONICAL');fail(B.length>0,'BUILDINGS_EMPTY');fail(R.length>0,'ROADS_EMPTY');fail(BR.length===2,'BRIDGES_NOT_TWO');
const geoAudit=Array.isArray(G.geometryContract?.audit)?G.geometryContract.audit:[];fail(geoAudit.length===0,'GEOMETRY_AUDIT');
for(let i=0;i<B.length;i++)for(let j=i+1;j<B.length;j++){const a=B[i],b=B[j];if(overlaps(a,b,0))fail(false,'BUILDING_OVERLAP:'+a.id+'>'+b.id)}
/* 2. RUTAS / PLAZA — el espacio público tiene contrato propio */
const nodes=G.routeNetwork?.nodes||[],edges=G.routeNetwork?.edges||[],plaza=G.plaza;fail(nodes.length>=8&&edges.length>=7,'ROUTE_NETWORK');fail(nodes.some(n=>n.id==='plaza')&&nodes.some(n=>n.id==='picada21'),'ROUTE_KEY_NODES');fail(!!plaza?.landmark&&!!plaza?.interactive&&plaza?.open===true,'PLAZA');
fail(!!G.geometryContract?.noBuildingOnPlaza&&!!G.geometryContract?.noRoadThroughPlaza,'PLAZA_GEOMETRY_CONTRACT');
if(plaza){B.forEach(b=>fail(!overlaps(b,plaza,18),'BUILDING_ON_PLAZA:'+b.id));R.forEach(r=>fail(!overlaps(r,plaza,0),'ROAD_THROUGH_PLAZA:'+r.id));fail(plaza.x>=canonical.urban.x&&plaza.y>=canonical.urban.y&&plaza.x+plaza.w<=canonical.urban.x+canonical.urban.w&&plaza.y+plaza.h<=canonical.urban.y+canonical.urban.h,'PLAZA_OUTSIDE_URBAN');}
/* 3. MOTOR + RENDER */
fail(V.engine?.singleVisualFrame===true&&V.engine?.singleTerrainRenderer===true,'ENGINE_SINGLE_FRAME');fail(V.engine?.version==='159.0','ENGINE_V159');fail(V.renderCompositor?.singleRAF===true&&V.renderCompositor?.ownsPlayer===true&&!V.renderCompositor?.ownsTerrain,'COMPOSITOR_CONTRACT');fail(V.visualAuthority?.singleVisualLoop===true,'VISUAL_LOOP');fail(V.visualAuthority?.version==='V132','VISUAL_CANON');
/* 4. CAMPAÑA / MISIONES */
fail(missions.length>0,'MISSION_CATALOG');const mids=new Set(missions.map(m=>m.id));missions.forEach(m=>{if(m.next)fail(mids.has(m.next),'MISSION_NEXT:'+m.id);(m.objectives||[]).forEach(o=>fail(!!o.id&&!!o.type&&!!o.target,'OBJECTIVE:'+m.id))});fail(!!V.campaignDirector?.deepCampaign,'DEEP_CAMPAIGN');fail(V.campaignDirector?.finalMission==='camp40','FINAL_MISSION');fail(V.missionRuntime?.version==='159.0','MISSION_RUNTIME');['urban','rural','picada21'].forEach(k=>fail(rect(V.missionRuntime?.regions?.[k],canonical[k]),'MISSION_REGION:'+k));
const targets=missions.flatMap(m=>m.objectives||[]);targets.filter(o=>['inspect','reach'].includes(o.type)&&o.target!=='bridge').forEach(o=>fail(!!V.missionRuntime?.points?.[o.target]||!!V.missionRuntime?.regions?.[o.target],'TARGET:'+o.target));
/* 5. PERSONAJES / VIDA / TRANSPORTE */
fail(Array.isArray(V.npcs),'NPC_REGISTRY');fail(V.villageLife?.singleTick===true,'LIFE_SINGLE_TICK');fail(V.villageLife?.saveAuthority==='gameState','LIFE_SAVE_AUTHORITY');fail(Array.isArray(P.vehicleData)&&Array.isArray(P.animals),'LIFE_REGISTRIES');fail(P.vehicleData?.every(v=>v.id&&v.route?.routeId),'VEHICLE_IDS_ROUTES');fail(P.vehicleData?.some(v=>v.type==='bus'),'BUS_REGISTRY');fail(P.transport?.busIds?.length>0,'BUS_TRANSPORT_REGISTRY');
/* 6. ACCIONES / PUENTES V159 */
fail(V.v159Bridge?.version==='159.0'&&V.v159Bridge?.sealedContract===true,'INTEGRATION_BRIDGE');fail(V.actionRuntime?.version==='159.0'&&V.actionRuntime?.singleLoop===true,'ACTION_RUNTIME');fail(typeof V.actionRuntime?.tick==='function','ACTION_TICK');fail(typeof V.transport?.board==='function'&&typeof V.transport?.disembark==='function','TRANSPORT_API');fail(typeof V.missionActions?.do==='function','ACTION_API');fail(typeof V.engine?.pause==='function'&&typeof V.engine?.resume==='function','PAUSE_RESUME');
/* 7. INTERFAZ / INTRO / AUDIO */
fail(I.version==='159.0'&&typeof I.menu==='function'&&typeof I.map==='function'&&typeof I.backpack==='function','INTERFACE');fail(!!V.ui?.intro,'INTRO_REGISTRY');fail(document.getElementById('presentationStart')&&document.getElementById('storyIntro'),'INTRO_DOM');warn(typeof window.AudioContext==='function'||typeof window.webkitAudioContext==='function','WEB_AUDIO');
/* 8. UI / DOM / DUPLICADOS */
const required=['world','worldDetail','worldAtmosphere','questText','questProgress','dialogue','speaker','dialogueText','missionToast','interact','save'];required.forEach(id=>fail(!!document.getElementById(id),'UI:'+id));const domIds=[...document.querySelectorAll('[id]')].map(e=>e.id);fail(domIds.length===new Set(domIds).size,'DUPLICATE_DOM_ID');fail(document.getElementById('worldAmbient')?.style.display==='none','AMBIENT_DISABLED');
/* 9. RELOJ / CLIMA / ESTACIONES */
fail(A.rules?.timeAuthority==='gameState.minutes','TIME_AUTHORITY');fail(A.rules?.calendarAuthority==='atmosphere.calendar','CALENDAR_AUTHORITY');fail(A.rules?.weatherAuthority==='atmosphere.weather','WEATHER_AUTHORITY');fail(A.rules?.dayNightAuthority==='atmosphere.phase','DAYNIGHT_AUTHORITY');fail(Array.isArray(A.rules?.seasons)&&A.rules.seasons.length===4,'SEASONS');fail(typeof A.apply==='function','ATMOSPHERE_APPLY');
/* 10. SEGURIDAD DE VERSIONES */
fail(V.runtimeAudit?.singleVisualFrame!==false,'RUNTIME_FRAME');fail(V.v159Bridge?.authority==='INTEGRATION_BRIDGE','BRIDGE_AUTHORITY');fail(V.actionRuntime?.authority==='V159_BRIDGE','ACTION_AUTHORITY');
const audit={version:'159.0',status:issues.length?'BLOCKED':'SEALED',issues,warnings,authorities:{geometry:'V138',runtime:'V150',render:'V158',visual:'V132',campaign:'V155.2',missionRuntime:'V159',integration:'V159',interface:'V159',transport:'V159',actions:'V159'},survey:{world:canonical,plaza:plaza?{id:plaza.id,x:plaza.x,y:plaza.y,w:plaza.w,h:plaza.h,open:plaza.open}:null,buildings:B.length,roads:R.length,bridges:BR.length,routeNodes:nodes.length,routeEdges:edges.length,npcs:Array.isArray(V.npcs)?V.npcs.length:0,vehicles:P.vehicleData?.length||0,animals:P.animals?.length||0,bus:P.vehicleData?.filter(v=>v.type==='bus').length||0,missions:missions.length,deepCampaign:!!V.campaignDirector?.deepCampaign,finalMission:V.campaignDirector?.finalMission||null,intro:!!V.ui?.intro,interface159:I.version==='159.0',actionRuntime159:V.actionRuntime?.version==='159.0',transport159:typeof V.transport?.board==='function'},checks:{geometry:!issues.some(x=>/WORLD|V138|GEOMETRY|RIVER|URBAN|RURAL|PICADA|PLAZA_|BUILDING_ON_PLAZA|ROAD_THROUGH_PLAZA/.test(x)),routes:!issues.some(x=>/ROUTE|PLAZA/.test(x)),render:!issues.some(x=>/ENGINE|COMPOSITOR|VISUAL_LOOP|VISUAL_CANON/.test(x)),missions:!issues.some(x=>/MISSION|OBJECTIVE|TARGET|CAMPAIGN|FINAL/.test(x)),life:!issues.some(x=>/NPC|LIFE|VEHICLE|BUS/.test(x)),integration:!issues.some(x=>/BRIDGE|ACTION|TRANSPORT|PAUSE/.test(x)),interface:!issues.some(x=>/INTERFACE|INTRO|UI:/.test(x)),worldClock:!issues.some(x=>/TIME|CALENDAR|DAYNIGHT|SEASONS|ATMOSPHERE/.test(x)),duplicates:!issues.includes('DUPLICATE_DOM_ID')},nextMutableLayer:issues.length?'REPAIR_BLOCKERS':'CONTENT_PRESENTATION_GAMEPLAY',rule:'NO_NEW_AUTHORITY_WITHOUT_CONSOLIDATION'};
V.v159=audit;V.systemFloor={version:'159.0',sealed:issues.length===0,authority:'INTEGRATION_FLOOR_V159',geometry:'V138_LOCKED',runtime:'SINGLE_LOGICAL_RUNTIME',campaign:'V155.2',missionRuntime:'V159',visual:'CANONICAL_PIXEL',status:audit.status,nextMutableLayer:audit.nextMutableLayer};V.runtimeAudit=Object.assign(V.runtimeAudit||{},{v159:true,v159Status:audit.status,v159Issues:issues.length,v159Warnings:warnings.length,systemSurvey:audit.survey,systemChecks:audit.checks,actionRuntime159:V.actionRuntime?.version==='159.0',transportRuntime159:typeof V.transport?.board==='function',interface159:I.version==='159.0'});window.dispatchEvent(new CustomEvent('villa-pelon-v159-audit-ready',{detail:audit}));
})();
