/* VILLA PELÓN V159 — SYSTEM FLOOR / AUDITORÍA QUIRÚRGICA PROFUNDA
   Este archivo no crea otro motor. Certifica y conecta las autoridades existentes.
   V138 = geometría | V150 = frame/runtime | V155 = campaña | V159 = piso integrado.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const G=V.worldGeometry||{},S=V.gameState||{};
const issues=[],warnings=[];const add=(ok,msg)=>{if(!ok)issues.push(msg)};const warn=(ok,msg)=>{if(!ok)warnings.push(msg)};
const rectEq=(a,b)=>!!a&&['x','y','w','h'].every(k=>Math.round(+a[k])===Math.round(+b[k]));
const canonical={world:{w:8200,h:4200},urban:{x:300,y:300,w:2700,h:1900},rural:{x:3000,y:300,w:4900,h:2350},river:{x:250,y:2700,w:7600,h:100},picada21:{x:4300,y:3180,w:3500,h:850}};
const buildings=G.buildings||[],roads=G.roads||[],bridges=G.bridges||[],zones=G.zones||[];
add(+V.world?.w===8200&&+V.world?.h===4200,'WORLD_SIZE_NOT_CANONICAL');
add(rectEq(G.river,canonical.river),'RIVER_NOT_V138');add(zones.some(x=>rectEq(x,canonical.urban)),'URBAN_NOT_V138');add(zones.some(x=>rectEq(x,canonical.rural)),'RURAL_NOT_V138');add(zones.some(x=>rectEq(x,canonical.picada21)),'PICADA21_NOT_V138');
add(!!V.worldSeal&&V.worldSeal.version==='V138','GEOMETRY_SEAL_MISSING');add(!!V.geometryFloorLock?.locked,'GEOMETRY_FLOOR_LOCK_MISSING');add(!!V.worldMaster?.locked,'WORLD_MASTER_NOT_LOCKED');
add(!!V.engine?.singleVisualFrame&&V.engine?.singleTerrainRenderer,'ENGINE_NOT_SINGLE_AUTHORITY');add(!!V.renderCompositor?.singleRAF&&V.renderCompositor?.ownsPlayer&&!V.renderCompositor?.ownsTerrain,'COMPOSITOR_CONTRACT_BROKEN');add(!!V.visualAuthority?.singleVisualLoop,'VISUAL_AUTHORITY_NOT_SINGLE');add(V.visualAuthority?.version==='V132','VISUAL_CANONICAL_VERSION_MISMATCH');
const geoAudit=Array.isArray(G.geometryContract?.audit)?G.geometryContract.audit:[];add(geoAudit.length===0,'GEOMETRY_COLLISION_AUDIT_FAILED');add(buildings.length>0,'BUILDING_REGISTRY_EMPTY');add(roads.length>0,'ROAD_REGISTRY_EMPTY');add(bridges.length===2,'BRIDGE_REGISTRY_NOT_CANONICAL');add(!!G.plaza?.landmark&&!!G.plaza?.interactive,'PLAZA_REGISTRY_INVALID');warn(buildings.every(b=>b.w>0&&b.h>0),'BUILDING_SIZE_DATA_INVALID');warn(buildings.every(b=>Number.isFinite(+b.x)&&Number.isFinite(+b.y)),'BUILDING_POSITION_DATA_INVALID');
const routeNodes=G.routeNetwork?.nodes||[],routeEdges=G.routeNetwork?.edges||[];add(routeNodes.length>=8&&routeEdges.length>=7,'ROUTE_NETWORK_INCOMPLETE');warn(routeNodes.some(n=>n.id==='plaza')&&routeNodes.some(n=>n.id==='picada21'),'ROUTE_NETWORK_MISSING_KEY_NODES');
add(!!V.missions?.list?.length,'MISSION_CATALOG_MISSING');const mids=new Set((V.missions?.list||[]).map(m=>m.id));(V.missions?.list||[]).forEach(m=>{if(m.next)add(mids.has(m.next),'BROKEN_MISSION_NEXT:'+m.id);(m.objectives||[]).forEach(o=>add(!!o.id&&!!o.type&&!!o.target,'INVALID_OBJECTIVE:'+m.id))});
add(!!V.campaignDirector?.deepCampaign,'DEEP_CAMPAIGN_NOT_ACTIVE');add(V.campaignDirector?.finalMission==='camp40','CAMPAIGN_FINAL_NOT_CAMP40');const R=V.missionRuntime||{};add(R.version==='159.0','MISSION_RUNTIME_NOT_V159');const expectedRegions={urban:canonical.urban,rural:canonical.rural,picada21:canonical.picada21};Object.entries(expectedRegions).forEach(([k,v])=>add(rectEq(R.regions?.[k],v),'MISSION_REGION_NOT_CANONICAL:'+k));
const missionTargets=(V.missions?.list||[]).flatMap(m=>(m.objectives||[]));missionTargets.filter(o=>['inspect','reach'].includes(o.type)).forEach(o=>{if(o.target==='bridge')return;add(!!R.points?.[o.target]||!!R.regions?.[o.target],'UNBOUND_MISSION_TARGET:'+o.target)});
add(!!document.getElementById('world'),'WORLD_CANVAS_MISSING');add(!!document.getElementById('worldDetail'),'DETAIL_CANVAS_MISSING');add(document.getElementById('worldAmbient')?.style.display==='none','AMBIENT_CANVAS_NOT_DISABLED');
const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);add(ids.length===new Set(ids).size,'DUPLICATE_DOM_ID');['world','worldDetail','worldAtmosphere','questText','questProgress','dialogue','speaker','dialogueText','missionToast','interact','save'].forEach(id=>add(!!document.getElementById(id),'MISSING_UI:'+id));
const scripts=[...document.scripts].map(x=>x.src||'');add(scripts.some(x=>x.includes('v159_system_seal.js')),'V159_NOT_LOADED');
const player=S;add(Number.isFinite(+player.x)&&Number.isFinite(+player.y),'PLAYER_POSITION_INVALID');add(+player.speed>0,'PLAYER_SPEED_INVALID');add(!!V.renderCompositor?.ownsPlayer,'PLAYER_RENDER_NOT_CENTRALIZED');warn(player.x>=0&&player.x<=8200&&player.y>=0&&player.y<=4200,'PLAYER_OUTSIDE_WORLD');
const P=V.peopleVehicles||{};add(Array.isArray(P.vehicleData),'VEHICLE_REGISTRY_MISSING');add(Array.isArray(P.animals),'ANIMAL_REGISTRY_MISSING');warn((P.vehicleData||[]).every(v=>Number.isFinite(+v.x)&&Number.isFinite(+v.y)&&v.speed>0),'VEHICLE_DATA_INVALID');warn((P.animals||[]).every(a=>Number.isFinite(+a.x)&&Number.isFinite(+a.y)),'ANIMAL_DATA_INVALID');
const A=V.atmosphere||{};add(A.rules?.timeAuthority==='gameState.minutes','TIME_AUTHORITY_NOT_GAMESTATE');add(A.rules?.calendarAuthority==='atmosphere.calendar','CALENDAR_AUTHORITY_NOT_UNIFIED');add(A.rules?.weatherAuthority==='atmosphere.weather','WEATHER_AUTHORITY_NOT_UNIFIED');add(A.rules?.dayNightAuthority==='atmosphere.phase','DAY_NIGHT_AUTHORITY_NOT_UNIFIED');add(Array.isArray(A.rules?.seasons)&&A.rules.seasons.length===4,'SEASONS_NOT_CANONICAL');add(typeof A.apply==='function','ATMOSPHERE_APPLY_MISSING');warn(!!S.calendar&&!!S.weatherState,'ATMOSPHERE_STATE_NOT_YET_APPLIED');
const life=V.villageLife||{};add(life.singleTick===true,'LIFE_SINGLE_TICK_NOT_CERTIFIED');warn(V.matrix?.diagnostics?.logicalIntervals>=0,'RUNTIME_LOGICAL_INTERVAL_DIAGNOSTIC_MISSING');
const intro=V.ui?.intro||{};add(!!V.ui&&!!intro,'INTRO_REGISTRY_MISSING');warn(document.getElementById('presentationStart')&&document.getElementById('storyIntro'),'INTRO_DOM_MISSING');
const iface=V.interface||{};add(!!iface.menu&&!!iface.map&&!!iface.backpack,'INTERFACE_REGISTRY_INCOMPLETE');warn(typeof V.engine?.pause==='function'&&typeof V.engine?.resume==='function','MENU_ENGINE_PAUSE_CONTRACT_MISSING');
warn(!!document.getElementById('vpMapCanvas')||typeof iface.map==='function','MAP_SYSTEM_MISSING');warn(typeof window.AudioContext==='function'||typeof window.webkitAudioContext==='function','AUDIO_RUNTIME_UNAVAILABLE');
const contentIds=[...(V.worldContent?.elements||[]),...(V.livingWorld?.details||[])].map(x=>x?.id).filter(Boolean);add(contentIds.length===new Set(contentIds).size,'DUPLICATE_WORLD_CONTENT_ID');
if(V.playableStory?.version!=='137.0')warnings.push('PLAYABLE_STORY_LEGACY_METADATA');if(V.visualAuthority?.version==='V132')warnings.push('VISUAL_AUTHORITY_FILE_NAME_IS_V131_BUT_CONTRACT_IS_V132');
const audit={version:'159.0',status:issues.length?'BLOCKED':'SEALED',issues,warnings,canonical,authorities:{geometry:'V138',world:'WORLD_MASTER_V1',runtime:'V150/V158.2',render:'V158_COMPOSITOR',visual:'V132',missions:'V97+V155.2',campaign:'V155.2',missionRuntime:'V159',integration:'V159'},survey:{buildings:{count:buildings.length,collisionAudit:geoAudit.length===0},routes:{roads:roads.length,bridges:bridges.length,nodes:routeNodes.length,edges:routeEdges.length},plaza:!!G.plaza,objects:{worldContent:(V.worldContent?.elements||[]).length,livingDetails:(V.livingWorld?.details||[]).length},player:{x:player.x,y:player.y,speed:player.speed,centralized:!!V.renderCompositor?.ownsPlayer},missions:{count:(V.missions?.list||[]).length,deep:!!V.campaignDirector?.deepCampaign,final:V.campaignDirector?.finalMission},places:{geometryZones:zones.length,landmarks:(G.landmarks||[]).length},vehicles:{count:(P.vehicleData||[]).length,animals:(P.animals||[]).length},worldClock:{minutes:player.minutes,calendar:A.calendar||null,phase:A.phase||null,weather:A.weather||null,seasons:A.rules?.seasons||[]},intro:{interactive:!!V.ui?.intro},interface:{menu:!!iface.menu,map:!!iface.map,backpack:!!iface.backpack},music:{webAudio:typeof window.AudioContext==='function'||typeof window.webkitAudioContext==='function'}},checks:{geometry:!issues.some(x=>x.includes('V138')||x.includes('WORLD_')||x.includes('GEOMETRY')),render:!!V.renderCompositor?.singleRAF,player:!!V.renderCompositor?.ownsPlayer,missions:!!V.missions?.list?.length,campaign:!!V.campaignDirector?.deepCampaign,targets:!issues.some(x=>x.includes('UNBOUND')),ui:!issues.some(x=>x.includes('MISSING_UI')),duplicates:!issues.some(x=>x.includes('DUPLICATE')),time:!!A.rules?.timeAuthority,seasons:Array.isArray(A.rules?.seasons),weather:!!A.weather,dayNight:!!A.phase,routes:routeNodes.length>=8,buildings:buildings.length>0,runtime:true},nextMutableLayer:issues.length?'REPAIR_BLOCKERS':'CONTENT_PRESENTATION_GAMEPLAY',rule:'NO_NEW_AUTHORITY_WITHOUT_CONSOLIDATION'};
V.v159=audit;V.systemFloor=V.systemFloor||{};Object.assign(V.systemFloor,{version:'159.0',sealed:issues.length===0,authority:'INTEGRATION_FLOOR_V159',geometry:'V138_LOCKED',runtime:'SINGLE_FRAME',campaign:'V155.2',missionRuntime:'V159',visual:'CANONICAL_PIXEL',status:audit.status});V.runtimeAudit=Object.assign(V.runtimeAudit||{},{v159:true,v159Status:audit.status,v159Issues:issues.length,v159Warnings:warnings.length,geometryLocked:true,singleVisualFrame:true,playerCentralized:true,missionRuntime159:true,deepCampaign:true,systemSurvey:audit.survey});window.dispatchEvent(new CustomEvent('villa-pelon-v159-audit-ready',{detail:audit}));
})();
