/* VILLA PELÓN V160 — CAPA DE DETALLE VIVO
   Superficie de contenido sobre las autoridades consolidadas.
   No crea motor, renderer, geometría ni loop propio.
   Agrega: prólogo interactivo, identidad inicial, descubrimientos,
   tutorial contextual, micro-eventos, feedback visual y vida cotidiana.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const root=document.documentElement;
const state=V.v160Details=V.v160Details||{version:'160.0',discoveries:[],profile:null,events:0,ready:false};
const $=s=>document.querySelector(s);
const save=()=>{try{localStorage.setItem('villa_pelon_v160_details',JSON.stringify(state))}catch(_){} };
try{Object.assign(state,JSON.parse(localStorage.getItem('villa_pelon_v160_details')||'{}'))}catch(_){}

function style(){if($('#vp160-details-style'))return;const s=document.createElement('style');s.id='vp160-details-style';s.textContent=`
.vp160-choicebar{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0 2px}.vp160-choice{flex:1;min-width:92px;padding:9px 7px;border:1px solid rgba(230,216,171,.45);background:#15231a;color:#eadfbf;font:800 9px monospace;letter-spacing:.5px;cursor:pointer;box-shadow:2px 2px 0 rgba(0,0,0,.28)}.vp160-choice:hover,.vp160-choice.active{background:#294d38;border-color:#d7c98d}.vp160-choice small{display:block;margin-top:4px;opacity:.7;font-weight:400;line-height:1.25}.vp160-skipnote{display:block;margin-top:6px;font:8px monospace;opacity:.55}.vp160-toast{position:fixed;left:50%;bottom:18%;transform:translateX(-50%) translateY(10px);z-index:100050;max-width:min(90vw,520px);padding:10px 14px;background:rgba(18,25,20,.94);border:2px solid rgba(221,207,157,.6);color:#eee2bb;font:800 10px monospace;text-align:center;box-shadow:4px 4px 0 rgba(0,0,0,.3);opacity:0;pointer-events:none;transition:.18s ease}.vp160-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}.vp160-badge{position:fixed;right:12px;bottom:12px;z-index:100010;padding:6px 8px;background:rgba(20,28,22,.75);border:1px solid rgba(220,205,157,.25);color:#cfc49d;font:7px monospace;letter-spacing:1px;pointer-events:none}.vp160-tip{position:fixed;left:50%;bottom:9%;transform:translateX(-50%);z-index:100020;padding:7px 11px;background:rgba(17,24,19,.88);color:#e8ddba;border:1px solid rgba(220,205,157,.35);font:800 9px monospace;opacity:0;transition:opacity .2s;pointer-events:none}.vp160-tip.show{opacity:1}.vp160-world-glow{position:fixed;inset:0;pointer-events:none;z-index:5;background:radial-gradient(circle at 50% 45%,transparent 38%,rgba(8,14,10,.12) 100%);mix-blend-mode:multiply}.vp160-spark{position:absolute;width:3px;height:3px;background:#e8d99e;opacity:.0;image-rendering:pixelated;animation:vp160float 5s steps(18,end) infinite}.vp160-spark:nth-child(2){left:21%;top:31%;animation-delay:-2s}.vp160-spark:nth-child(3){left:73%;top:26%;animation-delay:-4s}.vp160-spark:nth-child(4){left:61%;top:71%;animation-delay:-1s}@keyframes vp160float{0%,100%{opacity:0;transform:translateY(8px)}35%,65%{opacity:.22;transform:translateY(-5px)}}
@media(max-width:700px){.vp160-choice{min-width:29%;font-size:8px;padding:8px 4px}.vp160-choice small{font-size:7px}}
`;document.head.appendChild(s)}
function toast(text){let e=$('.vp160-toast');if(!e){e=document.createElement('div');e.className='vp160-toast';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2300)}
function tip(text){let e=$('.vp160-tip');if(!e){e=document.createElement('div');e.className='vp160-tip';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),3600)}
function atmosphere(){if($('#vp160-atmosphere'))return;const e=document.createElement('div');e.id='vp160-atmosphere';e.className='vp160-world-glow';e.innerHTML='<i class="vp160-spark"></i><i class="vp160-spark"></i><i class="vp160-spark"></i>';document.body.appendChild(e);const b=document.createElement('div');b.className='vp160-badge';b.textContent='V160 · DETALLE VIVO';document.body.appendChild(b)}
function profile(){const story=$('#storyIntro'),copy=story?.querySelector('.story-copy');if(!story||!copy||story.querySelector('.vp160-choicebar'))return;const bar=document.createElement('div');bar.className='vp160-choicebar';bar.setAttribute('aria-label','Elegí tu forma de comenzar');bar.innerHTML='<button class="vp160-choice" data-vp-profile="explorador">EXPLORAR<small>mirar caminos y lugares</small></button><button class="vp160-choice" data-vp-profile="trabajador">TRABAJAR<small>aprender oficios y producir</small></button><button class="vp160-choice" data-vp-profile="observador">OBSERVAR<small>conocer personas e historias</small></button>';const note=document.createElement('small');note.className='vp160-skipnote';note.textContent='Elegí una forma de empezar. No bloquea ninguna posibilidad del juego.';copy.insertBefore(bar,copy.querySelector('[data-intro-next]'));copy.insertBefore(note,copy.querySelector('[data-intro-next]'));bar.addEventListener('click',e=>{const b=e.target.closest('[data-vp-profile]');if(!b)return;state.profile=b.dataset.vpProfile;bar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));save();toast('Tu comienzo quedó registrado: '+b.textContent.split(' ')[0].toLowerCase()+'.')})}
function discovery(id,label){if(state.discoveries.includes(id))return;state.discoveries.push(id);state.events++;save();toast('DESCUBRIMIENTO · '+label);window.dispatchEvent(new CustomEvent('villa-pelon-discovery',{detail:{id,label,total:state.discoveries.length}}))}
function gameStart(){const S=V.gameState;if(!S)return;if(state.profile&&!S.profile)S.profile=state.profile;if(!S.flags)S.flags={};if(!S.flags.v160Welcome){S.flags.v160Welcome=true;tip('Primer día · caminá sin apuro. Acercate a una persona y probá E para hablar.');save()}}
function observe(){const S=V.gameState;if(!S||S.entryLocked||S.dialogue)return;const x=Number(S.x)||0,y=Number(S.y)||0;if(x<2800&&y<2300){discovery('urban_core','NÚCLEO DEL PUEBLO')}if(y>2350&&y<2920){discovery('river_buffer','ZONA DEL RÍO')}if(x>4200&&y>3000){discovery('picada21','PICADA 21')}if((S.stats?.interactions||0)>=1){discovery('first_conversation','PRIMERA CONVERSACIÓN')}if((S.stats?.steps||0)>900){discovery('first_walk','PRIMERA CAMINATA')}
}
function contextual(){const S=V.gameState;if(!S||S.entryLocked)return;const mins=Number(S.minutes)||480;const h=Math.floor((mins%1440)/60);if(h===12&&Math.random()<.004)tip('Mediodía · algunos vecinos cambian de rutina. Mirá quién sigue afuera.');if(h===18&&Math.random()<.004)tip('La tarde cambia el pueblo · es un buen momento para volver a la plaza.');if(Number(S.energy)<=20&&Math.random()<.01)tip('Estás cansado · descansar también es parte de jugar.')}
function hooks(){window.addEventListener('villa-pelon-intro-finished',()=>{setTimeout(gameStart,80);tip('Villa Pelón está vivo. No hay una única forma correcta de jugar.')});window.addEventListener('villa-pelon-mission',e=>{const m=e.detail?.mission;if(m?.complete)toast('HISTORIA AVANZADA · una decisión puede abrir otra historia')});window.addEventListener('villa-pelon-world-entry-released',()=>setTimeout(gameStart,80));let last=0;const sample=()=>{const n=performance.now();if(n-last>900){last=n;observe();contextual()}};document.addEventListener('pointerup',sample,{passive:true});window.addEventListener('villa-pelon-engine-ready',()=>{setTimeout(gameStart,300);setTimeout(sample,500)});}
style();atmosphere();profile();hooks();state.ready=true;V.runtimeAudit=Object.assign(V.runtimeAudit||{},{livingDetails160:true});window.dispatchEvent(new CustomEvent('villa-pelon-living-details-ready',{detail:state}));
})();
