/* VILLA PELÓN — ENGINE V86
   Motor integrado: mundo, cámara, colisiones, interacción, ciclo diario, guardado y controles.
*/
(()=>{'use strict';
 const V=window.VillaPelon||(window.VillaPelon={});
 const canvas=document.getElementById('world'),ctx=canvas.getContext('2d',{alpha:false});
 const W=V.world||{w:8200,h:4200}; W.w=8200;W.h=4200;V.world=W;
 const G=V.worldGeometry||{}; const buildings=G.buildings||[]; const bridges=G.bridges||[];
 const state=V.gameState||(V.gameState={}); Object.assign(state,{started:true,x:Number(state.x)||1180,y:Number(state.y)||650,speed:205,money:Number(state.money)||10000,energy:Number(state.energy)||100,minutes:Number(state.minutes)||480,day:Number(state.day)||1,quest:Number(state.quest)||0,dialogue:false,saved:false,inventory:Array.isArray(state.inventory)?state.inventory:[],facing:state.facing||'down',walk:0});
 V.gameState=state; window.__villaPelonState=state;
 const input={up:false,down:false,left:false,right:false}; let vw=innerWidth,vh=innerHeight,camX=0,camY=0,last=performance.now(),near=null;
 const Z=.78;
 const npcs=[
  {x:650,y:570,name:'Marta',color:'#b95e4e',lines:['Buen día. Soy Marta. En un pueblo chico siempre hay alguien para ayudar.','El almacén es un buen lugar para enterarse de lo que pasa.']},
  {x:1730,y:600,name:'Raúl',color:'#557ca8',lines:['Trabajo en una chacra. Las temporadas marcan el ritmo de muchas familias.','En el sector rural siempre hay algo por aprender.']},
  {x:520,y:1040,name:'Lucía',color:'#a55e8f',lines:['La escuela guarda recuerdos que pueden ayudarnos a reconstruir la historia local.','Una fotografía también puede ser una pista.']},
  {x:1850,y:1040,name:'Pedro',color:'#bd8249',lines:['En la chacra siempre aparece algo para hacer.','El trabajo rural también es parte de la vida cotidiana.']},
  {x:1190,y:390,name:'Nico',color:'#5d8d59',lines:['La plaza es el corazón del pueblo.','Una radio puede conectar a toda una comunidad.']},
  {x:5200,y:760,name:'Elena',color:'#9b6c45',lines:['Las chacras tienen sus propios ritmos.','El agua y las estaciones son parte de esta historia.']},
  {x:6200,y:920,name:'Tomás',color:'#5f789d',lines:['Las bodegas forman parte del paisaje productivo del valle.','Acá la tierra y el trabajo se encuentran.']}
 ]; V.npcs=npcs;
 const clue={x:2040,y:430},jobSpot={x:2200,y:700}; V.worldGeometry.clue=clue;V.worldGeometry.jobSpot=jobSpot;
 function resize(){vw=innerWidth;vh=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(vw*d);canvas.height=Math.floor(vh*d);canvas.style.width=vw+'px';canvas.style.height=vh+'px';ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false} addEventListener('resize',resize,{passive:true});resize();
 function bind(){addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowup'||k==='w')input.up=true;if(k==='arrowdown'||k==='s')input.down=true;if(k==='arrowleft'||k==='a')input.left=true;if(k==='arrowright'||k==='d')input.right=true;if(k==='e'||k===' '){e.preventDefault();interact()}});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='arrowup'||k==='w')input.up=false;if(k==='arrowdown'||k==='s')input.down=false;if(k==='arrowleft'||k==='a')input.left=false;if(k==='arrowright'||k==='d')input.right=false});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();input[k]=true});['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,()=>input[k]=false))});document.getElementById('interact')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});document.getElementById('save')?.addEventListener('click',save)} bind();
 function blocked(x,y){if(x<50||y<120||x>W.w-50||y>W.h-50)return true;return buildings.some(b=>x>b.x-16&&x<b.x+b.w+16&&y>b.y-16&&y<b.y+b.h+16)}
 function load(){try{const s=JSON.parse(localStorage.getItem('villa_pelon_save'));if(s)Object.assign(state,s)}catch(_){}state.started=true;state.dialogue=false;if(!['up','down','left','right'].includes(state.facing))state.facing='down'}
 function save(){localStorage.setItem('villa_pelon_save',JSON.stringify({...state,dialogue:false,saved:false}));state.saved=true;ui();setTimeout(()=>{state.saved=false},1400)} V.saveGame=save;load();
 function dialogue(title,lines){state.dialogue=true;const b=document.getElementById('dialogue');b.classList.remove('hidden');b.dataset.lines=JSON.stringify(lines);b.dataset.index='0';document.getElementById('speaker').textContent=title;document.getElementById('dialogueText').textContent=lines[0]}
 function nextDialogue(){const b=document.getElementById('dialogue');let a=[];try{a=JSON.parse(b.dataset.lines||'[]')}catch(_){}const i=Number(b.dataset.index||0)+1;if(i<a.length){b.dataset.index=i;document.getElementById('dialogueText').textContent=a[i]}else{state.dialogue=false;b.classList.add('hidden')}} document.getElementById('dialogueNext')?.addEventListener('click',nextDialogue);
 function nearby(){let best=null,bd=Infinity;[...npcs,clue,jobSpot,...buildings].forEach(o=>{const ox=o.x+(o.w?o.w/2:0),oy=o.y+(o.h?o.h+30:0),d=Math.hypot(state.x-ox,state.y-oy);if(d<(o.w?115:100)&&d<bd){best=o;bd=d}});return best}
 function interact(){if(state.dialogue){nextDialogue();return}const n=near;if(!n)return;if(n===clue){state.quest=Math.max(state.quest,2);if(!state.inventory.includes('Pista histórica')){state.inventory.push('Pista histórica');state.money+=2500;dialogue('ARCHIVO DE MEMORIA',['Encontraste una pista histórica.','Las futuras misiones incorporarán datos reales con fuentes verificables.','Recompensa: $2.500.'])}else dialogue('ARCHIVO DE MEMORIA',['Esta pista ya fue descubierta.']);return}if(n===jobSpot){if(state.energy<20){dialogue('CHANGA RURAL',['Estás cansado. Descansá y volvé después.']);return}state.energy-=18;state.money+=850;dialogue('CHANGA RURAL',['Ayudaste con una tarea rural.','Cobraste $850 y conociste otra parte de la vida productiva.']);return}if(n.name){if(state.quest===0)state.quest=1;dialogue(n.name,n.lines);return}if(n.type==='home'){state.energy=Math.min(100,state.energy+30);state.minutes+=30;dialogue('CASA',['Descansaste un rato y recuperaste energía.']);return}dialogue(n.label||'EDIFICIO',['Podés seguir explorando este lugar.','Cada edificio podrá recibir contenido propio en próximas misiones.'])} V.interact=interact;V.getNearby=()=>near;
 function update(dt){if(!state.started||state.dialogue)return;let dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0),moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;if(Math.abs(dx)>Math.abs(dy))state.facing=dx<0?'left':'right';else state.facing=dy<0?'up':'down';const nx=state.x+dx*state.speed*dt,ny=state.y+dy*state.speed*dt;if(!blocked(nx,state.y))state.x=nx;if(!blocked(state.x,ny))state.y=ny;state.energy=Math.max(0,state.energy-dt*.55);state.walk+=dt*10}else state.walk=0;state.minutes+=dt*(moving?3.5:.05);if(state.minutes>=1440){state.minutes-=1440;state.day++;state.energy=100}near=nearby();camX=Math.max(0,Math.min(W.w-vw/Z,state.x-vw/(2*Z)));camY=Math.max(0,Math.min(W.h-vh/Z,state.y-vh/(2*Z)));ui()}
 function ui(){const h=Math.floor(state.minutes/60)%24,m=Math.floor(state.minutes%60);document.getElementById('clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');document.getElementById('day').textContent=state.day;document.getElementById('money').textContent=Math.round(state.money);document.getElementById('energy').textContent=Math.round(state.energy);document.getElementById('weather').textContent=state.minutes>1080?'Atardecer':state.minutes>1320?'Noche':'Despejado';document.getElementById('questText').textContent=state.quest===0?'Conocé a un vecino.':state.quest===1?'Recorré el pueblo y buscá una pista.':'Primer descubrimiento completado.'}
 function r(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)} function shadow(x,y,w){ctx.fillStyle='rgba(30,25,20,.22)';ctx.beginPath();ctx.ellipse(x,y,w||25,7,0,0,Math.PI*2);ctx.fill()}
 function building(b){shadow(b.x+b.w/2,b.y+b.h+12,b.w*.42);const pal={school:['#e0c99b','#76523b'],shop:['#d3ad72','#784735'],civic:['#c8b08c','#625345'],culture:['#bfa27e','#654b3b'],health:['#d8d2b4','#61706a'],service:['#aa8d6c','#5e4938'],community:['#c9a27b','#6d493a'],radio:['#b47f6e','#624137'],rural:['#a78059','#5e4939'],winery:['#a77d61','#543d38'],home:['#c7a784','#765443']}[b.type]||['#c5a27e','#6b4b3a'];r(b.x-10,b.y-8,b.w+20,b.h+18,pal[1]);r(b.x,b.y,b.w,b.h,pal[0]);ctx.fillStyle=pal[1];ctx.beginPath();ctx.moveTo(b.x-18,b.y);ctx.lineTo(b.x+b.w/2,b.y-54);ctx.lineTo(b.x+b.w+18,b.y);ctx.closePath();ctx.fill();r(b.x+b.w*.44,b.y+b.h*.55,b.w*.12,b.h*.45,'#634333');r(b.x+28,b.y+34,50,34,'#7898a1');r(b.x+b.w-78,b.y+34,50,34,'#7898a1');ctx.fillStyle='#302822';ctx.font='bold 18px monospace';ctx.textAlign='center';ctx.fillText(b.label,b.x+b.w/2,b.y-66);if(b.type==='winery'){r(b.x+50,b.y+b.h-48,b.w-100,25,'#734b3d');ctx.fillStyle='#f4e2b7';ctx.font='bold 11px monospace';ctx.fillText('BODEGA · VALLE',b.x+b.w/2,b.y+b.h-30)}}
 function tree(x,y,s=1){shadow(x,y+30*s,18*s);r(x-5*s,y+7*s,10*s,25*s,'#6b5039');ctx.fillStyle='#4f7049';ctx.beginPath();ctx.arc(x,y,23*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#698855';ctx.beginPath();ctx.arc(x-12*s,y-8*s,13*s,0,Math.PI*2);ctx.arc(x+13*s,y-6*s,14*s,0,Math.PI*2);ctx.fill()}
 function terrain(){r(0,0,W.w,W.h,'#aa9b71');for(let i=0;i<520;i++){const x=(i*173+41)%W.w,y=(i*113+87)%W.h,s=5+(i%5)*4;r(x,y,s,s/2,i%3?'rgba(75,67,48,.09)':'rgba(230,210,160,.11)')}r(4900,0,3300,4200,'#9ca36a');r(0,820,W.w,28,'#66888c');r(0,848,W.w,4,'#a8b5a6')}
 function roads(){r(0,600,4900,190,'#c6b17e');r(0,880,4900,110,'#c1aa76');r(1070,0,190,1900,'#c6b17e');r(0,1040,4900,110,'#c1aa76');r(4700,0,120,4200,'#bca273');r(0,2120,8200,130,'#b99e69');ctx.strokeStyle='#e1d2a2';ctx.lineWidth=4;ctx.setLineDash([28,20]);[[0,694,4900,694],[1165,0,1165,1900],[0,2185,8200,2185]].forEach(q=>{ctx.beginPath();ctx.moveTo(q[0],q[1]);ctx.lineTo(q[2],q[3]);ctx.stroke()});ctx.setLineDash([])}
 function fields(){for(let i=0;i<5;i++){const x=5050+i*600;r(x,2700,480,620,'#7f9458');ctx.strokeStyle='#b5a45e';ctx.lineWidth=3;for(let xx=x+25;xx<x+460;xx+=42){ctx.beginPath();ctx.moveTo(xx,2730);ctx.lineTo(xx+10,3290);ctx.stroke()}}for(let i=0;i<70;i++){const x=5000+(i*97)%3000,y=2700+(i*151)%1150;tree(x,y,.55)}}
 function bridge(b){r(b.x,b.y,b.w,b.h,'#76583f');for(let x=b.x+10;x<b.x+b.w;x+=35)r(x,b.y+8,22,b.h-16,'#a17b53');ctx.fillStyle='#3f342c';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText(b.label,b.x+b.w/2,b.y-8)}
 function character(x,y,o={}){const c=o.color||'#2f5d46';shadow(x,y+31,18);r(x-9,y+8,8,20,'#304b67');r(x+1,y+8,8,20,'#304b67');r(x-10,y+26,10,5,'#352c29');r(x+1,y+26,10,5,'#352c29');r(x-14,y-8,28,19,c);r(x-9,y-27,18,17,'#d9a27c');r(x-10,y-29,20,6,'#332923');if(o.name){ctx.fillStyle='rgba(20,27,21,.9)';ctx.fillRect(x-35,y-49,70,16);ctx.fillStyle='#f5edcf';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText(o.name.toUpperCase(),x,y-37)}}
 function draw(){ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(vw/2,vh/2);ctx.scale(Z,Z);ctx.translate(-camX-vw/(2*Z)+state.x,-camY-vh/(2*Z)+state.y);terrain();roads();fields();for(let i=0;i<70;i++){const x=(i*311+600)%4700,y=(i*173+180)%1900;if(y>1150)tree(x,y,.7)}buildings.forEach(building);bridges.forEach(bridge);npcs.forEach(n=>character(n.x,n.y,n));character(state.x,state.y,{color:'#2f5d46',name:'VOS'});if(near&&!state.dialogue){ctx.fillStyle='rgba(20,27,21,.9)';ctx.fillRect(state.x-74,state.y-66,148,28);ctx.fillStyle='#fff';ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.fillText('E · INTERACTUAR',state.x,state.y-47)}ctx.restore();
  const hour=state.minutes/60; if(hour<6||hour>20){ctx.fillStyle='rgba(20,30,55,.30)';ctx.fillRect(0,0,vw,vh)}else if(hour>18){ctx.fillStyle='rgba(190,125,70,.12)';ctx.fillRect(0,0,vw,vh)} }
 function loop(now){const dt=Math.min((now-last)/1000,.05);last=now;update(dt);draw();requestAnimationFrame(loop)}
 V.engine=V.engine||{};V.engine.version='86.0.0';V.engine.state='running';V.engine.health=()=>({version:'86.0.0',world:[W.w,W.h],buildings:buildings.length,npcs:npcs.length,canvas:!!canvas,save:typeof V.saveGame==='function'});requestAnimationFrame(loop);window.dispatchEvent(new CustomEvent('villa-pelon-engine-ready'));
})();
