(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),C=document.getElementById('world'),X=C.getContext('2d',{alpha:false});
const W=V.world||{w:8200,h:4200},G=V.worldGeometry||{},B=G.buildings||[],BR=G.bridges||[];
const S=V.gameState||{};V.gameState=S;Object.assign(S,{started:true,x:Number(S.x)||1180,y:Number(S.y)||650,speed:205,money:Number(S.money)||10000,energy:Number(S.energy)||100,minutes:Number(S.minutes)||480,day:Number(S.day)||1,quest:Number(S.quest)||0,dialogue:false,inventory:Array.isArray(S.inventory)?S.inventory:[],facing:S.facing||'down',walk:0});
let vw=innerWidth,vh=innerHeight,last=performance.now(),near=null;const I={up:0,down:0,left:0,right:0},Z=.78;
function resize(){vw=innerWidth;vh=innerHeight;let d=Math.min(devicePixelRatio||1,2);C.width=vw*d;C.height=vh*d;C.style.width=vw+'px';C.style.height=vh+'px';X.setTransform(d,0,0,d,0,0);X.imageSmoothingEnabled=false}resize();addEventListener('resize',resize);
function keys(k,v){if(k==='w'||k==='arrowup')I.up=v;if(k==='s'||k==='arrowdown')I.down=v;if(k==='a'||k==='arrowleft')I.left=v;if(k==='d'||k==='arrowright')I.right=v}addEventListener('keydown',e=>{keys(e.key.toLowerCase(),1);if(['e',' '].includes(e.key.toLowerCase())){e.preventDefault();interact()}});addEventListener('keyup',e=>keys(e.key.toLowerCase(),0));document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();I[b.dataset.key]=1});['pointerup','pointercancel','pointerleave'].forEach(q=>b.addEventListener(q,()=>I[b.dataset.key]=0))});document.getElementById('interact')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});
function save(){localStorage.setItem('villa_pelon_save',JSON.stringify({...S,dialogue:false}));S.saved=true}V.saveGame=save;document.getElementById('save')?.addEventListener('click',save);try{Object.assign(S,JSON.parse(localStorage.getItem('villa_pelon_save')||'{}'))}catch(_){}S.started=true;
const NPC=[{x:650,y:570,n:'Marta',c:'#b95e4e',t:['En un pueblo chico siempre hay alguien para ayudar.','El almacén es un buen lugar para enterarse de lo que pasa.']},{x:1730,y:600,n:'Raúl',c:'#557ca8',t:['Las temporadas marcan el ritmo de muchas familias.','El sector rural también cuenta la historia del pueblo.']},{x:520,y:1040,n:'Lucía',c:'#a55e8f',t:['La escuela guarda recuerdos.','Una fotografía puede ser una pista.']},{x:1850,y:1040,n:'Pedro',c:'#bd8249',t:['En la chacra siempre aparece algo por hacer.','El trabajo rural es parte de la vida cotidiana.']},{x:1190,y:390,n:'Nico',c:'#5d8d59',t:['La plaza es el corazón del pueblo.','La radio conecta a la comunidad.']},{x:5200,y:760,n:'Elena',c:'#9b6c45',t:['Las chacras tienen sus propios ritmos.','El agua y las estaciones son parte de esta historia.']},{x:6200,y:920,n:'Tomás',c:'#5f789d',t:['Las bodegas forman parte del paisaje productivo.','Acá la tierra y el trabajo se encuentran.']}];V.npcs=NPC;
const clue={x:2040,y:430,label:'PISTA'},job={x:2200,y:700,label:'CHANGA'};G.clue=clue;G.jobSpot=job;
function blocked(x,y){return x<50||y<120||x>W.w-50||y>W.h-50||B.some(b=>x>b.x-14&&x<b.x+b.w+14&&y>b.y-14&&y<b.y+b.h+14)}
function dlg(title,lines){S.dialogue=true;let d=document.getElementById('dialogue');d.classList.remove('hidden');d.dataset.l=JSON.stringify(lines);d.dataset.i=0;document.getElementById('speaker').textContent=title;document.getElementById('dialogueText').textContent=lines[0]}
function next(){let d=document.getElementById('dialogue'),a=JSON.parse(d.dataset.l||'[]'),i=+d.dataset.i+1;if(i<a.length){d.dataset.i=i;document.getElementById('dialogueText').textContent=a[i]}else{S.dialogue=false;d.classList.add('hidden')}}document.getElementById('dialogueNext')?.addEventListener('click',next);
function interact(){if(S.dialogue)return next();let n=near;if(!n)return;if(n===clue){S.quest=2;if(!S.inventory.includes('Pista histórica')){S.inventory.push('Pista histórica');S.money+=2500;dlg('ARCHIVO DE MEMORIA',['Encontraste una pista histórica.','Las futuras misiones educativas incorporarán fuentes verificables.','Recompensa: $2.500.'])}else dlg('ARCHIVO',['Esta pista ya fue descubierta.']);return}if(n===job){S.money+=850;S.energy=Math.max(0,S.energy-18);dlg('CHANGA RURAL',['Ayudaste con una tarea rural.','Cobraste $850.']);return}if(n.n){S.quest=Math.max(S.quest,1);dlg(n.n,n.t);return}dlg(n.label||'EDIFICIO',['Este lugar forma parte de Villa Pelón.','Próximamente tendrá una actividad propia.'])}V.interact=interact;
function ui(){let h=Math.floor(S.minutes/60)%24,m=Math.floor(S.minutes%60);document.getElementById('clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');document.getElementById('day').textContent=S.day;document.getElementById('money').textContent=Math.round(S.money);document.getElementById('energy').textContent=Math.round(S.energy);document.getElementById('weather').textContent=h>=19?'Atardecer':h<7?'Noche':'Despejado';document.getElementById('questText').textContent=S.quest===0?'Conocé a un vecino.':S.quest===1?'Recorré el pueblo y buscá una pista.':'Primer descubrimiento completado.'}
function rect(x,y,w,h,c){X.fillStyle=c;X.fillRect(x,y,w,h)}function sh(x,y,w){X.fillStyle='rgba(20,20,15,.2)';X.beginPath();X.ellipse(x,y,w||20,6,0,0,7);X.fill()}
function house(b){let p={school:['#dfc79a','#74513d'],shop:['#d4ae73','#754536'],civic:['#c9b18c','#5d5148'],culture:['#bda17d','#624a3d'],health:['#d8d3b7','#617069'],service:['#aa8d6d','#5d493a'],community:['#c9a07a','#68483b'],radio:['#b57f6e','#5e4037'],rural:['#a78058','#5b4839'],winery:['#a77c60','#533d37'],home:['#c8a783','#755342']}[b.type]||['#c5a17d','#684a3a'];sh(b.x+b.w/2,b.y+b.h+10,b.w*.42);rect(b.x-9,b.y-7,b.w+18,b.h+16,p[1]);rect(b.x,b.y,b.w,b.h,p[0]);X.fillStyle=p[1];X.beginPath();X.moveTo(b.x-15,b.y);X.lineTo(b.x+b.w/2,b.y-48);X.lineTo(b.x+b.w+15,b.y);X.fill();rect(b.x+b.w*.44,b.y+b.h*.55,b.w*.12,b.h*.45,'#624232');rect(b.x+25,b.y+30,52,34,'#7897a0');rect(b.x+b.w-77,b.y+30,52,34,'#7897a0');X.fillStyle='#302721';X.font='bold 16px monospace';X.textAlign='center';X.fillText(b.label,b.x+b.w/2,b.y-60);if(b.type==='winery'){rect(b.x+40,b.y+b.h-42,b.w-80,23,'#71483c');X.fillStyle='#f2dfb5';X.font='bold 10px monospace';X.fillText('BODEGA · VALLE',b.x+b.w/2,b.y+b.h-26)}}
function tree(x,y,s=.7){sh(x,y+25*s,16*s);rect(x-4*s,y+6*s,8*s,22*s,'#6b5039');X.fillStyle='#4f7049';X.beginPath();X.arc(x,y,22*s,0,7);X.fill();X.fillStyle='#6a8856';X.beginPath();X.arc(x-11*s,y-7*s,12*s,0,7);X.arc(x+12*s,y-5*s,13*s,0,7);X.fill()}
function world(){rect(0,0,W.w,W.h,'#aa9b71');rect(4900,0,3300,4200,'#9ca36a');rect(0,820,W.w,28,'#67898c');rect(0,848,W.w,4,'#a9b6a5');rect(0,600,4900,190,'#c6b17e');rect(0,880,4900,110,'#c0a875');rect(1070,0,190,1900,'#c6b17e');rect(0,1040,4900,110,'#c0a875');rect(4700,0,120,4200,'#bca273');rect(0,2120,8200,130,'#b99e69');X.strokeStyle='#e0d09e';X.lineWidth=4;X.setLineDash([26,20]);[[0,694,4900,694],[1165,0,1165,1900],[0,2185,8200,2185]].forEach(a=>{X.beginPath();X.moveTo(a[0],a[1]);X.lineTo(a[2],a[3]);X.stroke()});X.setLineDash([]);for(let i=0;i<100;i++){tree((i*191+140)%4700,(i*137+180)%1900,.55)}for(let i=0;i<5;i++){let x=5050+i*600;rect(x,2700,480,620,'#80945a');X.strokeStyle='#b5a45e';for(let q=x+20;q<x+470;q+=42){X.beginPath();X.moveTo(q,2730);X.lineTo(q+10,3290);X.stroke()}}B.forEach(house);BR.forEach(b=>{rect(b.x,b.y,b.w,b.h,'#76583f');for(let x=b.x+10;x<b.x+b.w;x+=35)rect(x,b.y+8,22,b.h-16,'#a17b53');X.fillStyle='#43362e';X.font='10px monospace';X.fillText(b.label,b.x+b.w/2,b.y-8)});NPC.forEach(n=>{sh(n.x,n.y+28,17);rect(n.x-12,n.y-8,24,19,n.c);rect(n.x-8,n.y-27,16,18,'#d9a27c');rect(n.x-9,n.y-29,18,6,'#332923');X.fillStyle='#f5edcf';X.font='10px monospace';X.textAlign='center';X.fillText(n.n,n.x,n.y-39)});sh(S.x,S.y+29,18);rect(S.x-13,S.y-8,26,20,'#2f5d46');rect(S.x-9,S.y-27,18,18,'#d9a27c');rect(S.x-10,S.y-29,20,6,'#332923')}
function draw(){X.clearRect(0,0,vw,vh);X.save();X.translate(vw/2,vh/2);X.scale(Z,Z);X.translate(-S.x,-S.y);world();if(near&&!S.dialogue){rect(S.x-70,S.y-63,140,27,'rgba(20,27,21,.92)');X.fillStyle='#fff';X.font='bold 11px monospace';X.textAlign='center';X.fillText('E · INTERACTUAR',S.x,S.y-45)}X.restore();let h=S.minutes/60;if(h<6||h>20){rect(0,0,vw,vh,'rgba(18,28,55,.28)')}else if(h>18){rect(0,0,vw,vh,'rgba(190,125,70,.12)')}}
function loop(t){let dt=Math.min((t-last)/1000,.05);last=t;if(S.started&&!S.dialogue){let dx=I.right-I.left,dy=I.down-I.up;if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;let nx=S.x+dx*S.speed*dt,ny=S.y+dy*S.speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;S.energy=Math.max(0,S.energy-dt*.55);S.walk+=dt*10}else S.walk=0;S.minutes+=dt*(dx||dy?3.5:.05);if(S.minutes>=1440){S.minutes-=1440;S.day++;S.energy=100}near=[...NPC,clue,job,...B].sort((a,b)=>Math.hypot(S.x-(a.x+(a.w||0)/2),S.y-(a.y+(a.h||0)/2))-Math.hypot(S.x-(b.x+(b.w||0)/2),S.y-(b.y+(b.h||0)/2)))[0];ui()}draw();requestAnimationFrame(loop)}
V.engine={version:'86.1.0',state:'running',health:()=>({version:'86.1.0',world:[W.w,W.h],buildings:B.length,npcs:NPC.length,canvas:!!C,save:true})};requestAnimationFrame(loop);window.dispatchEvent(new CustomEvent('villa-pelon-engine-ready'));
})();
