/* V87.11 — cartel de misión compacto, reactivo y sin temporizadores paralelos. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});const root=document.getElementById('game');if(!root)return;
document.querySelector('.quest')?.remove();
const wrap=document.createElement('aside');wrap.id='vpMission';wrap.innerHTML='<button id="vpMissionHead" type="button" aria-expanded="false"><span>🎯 MISIÓN</span><b id="vpMissionShort">Explorá el territorio</b><i>⌄</i></button><div id="vpMissionBody" hidden><div id="vpMissionTitle"></div><p id="vpMissionBrief"></p><small id="vpMissionHint"></small><button id="vpMissionRoadmap" type="button">VER LAS 10 MISIONES</button></div>';root.appendChild(wrap);
const style=document.createElement('style');style.textContent=`#vpMission{position:fixed;left:50%;transform:translateX(-50%);bottom:92px;width:min(430px,calc(100vw - 20px));z-index:24;font-family:monospace;pointer-events:none}#vpMissionHead,#vpMissionBody{pointer-events:auto}#vpMissionHead{width:100%;display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;text-align:left;border:1px solid rgba(51,64,58,.55);border-radius:11px;background:rgba(255,247,233,.91);color:#33403a;padding:8px 10px;box-shadow:0 3px 12px rgba(20,30,25,.12);font:700 10px monospace}#vpMissionHead b{font-size:10px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#vpMissionHead i{font-style:normal;font-size:15px}#vpMissionBody{margin-top:5px;padding:11px 12px;border:1px solid rgba(51,64,58,.45);border-radius:12px;background:rgba(255,247,233,.97);box-shadow:0 8px 25px rgba(20,30,25,.18);max-height:30vh;overflow:auto}#vpMissionTitle{font-weight:900;font-size:13px}#vpMissionBrief{font-size:11px;line-height:1.4;margin:6px 0}#vpMissionHint{display:block;opacity:.72;font-size:10px;line-height:1.4}#vpMissionRoadmap{margin-top:9px;border:1px solid #718078;border-radius:8px;background:#e9f0e6;padding:7px 9px;font:800 10px monospace;color:#26332e}@media(max-width:600px){#vpMission{bottom:max(88px,calc(78px + env(safe-area-inset-bottom)));width:calc(100vw - 14px)}}@media(min-width:900px){#vpMission{bottom:20px;left:auto;right:18px;transform:none;width:330px}}`;
document.head.appendChild(style);
const head=wrap.querySelector('#vpMissionHead'),body=wrap.querySelector('#vpMissionBody');head.addEventListener('click',()=>{body.hidden=!body.hidden;head.setAttribute('aria-expanded',String(!body.hidden));head.querySelector('i').textContent=body.hidden?'⌄':'⌃'});
wrap.querySelector('#vpMissionRoadmap').addEventListener('click',()=>{const lessons=V.getCampaignLessons?.()||[];const lines=lessons.map((m,i)=>`${i+1}. ${m.title} · ${m.topic}`);V.openDialogue?.('CAMPAÑA · 10 MISIONES',lines)});
function refresh(){const lessons=V.getCampaignLessons?.()||[],completed=V.gameState?.campaign?.completed||[],m=V.getCampaignCurrent?.(),next=lessons.find(x=>!completed.includes(x.id));const short=wrap.querySelector('#vpMissionShort');if(!short)return;short.textContent=m?m.title:(next?next.title:'Campaña completada');wrap.querySelector('#vpMissionTitle').textContent=m?m.title:'Próxima misión';wrap.querySelector('#vpMissionBrief').textContent=m?m.brief:(next?.brief||'Exploración libre.');wrap.querySelector('#vpMissionHint').textContent=m?`Tema: ${m.topic}. Cumplila recorriendo el territorio.`:'Las diez misiones forman una clase caminable sobre Villa Pelón.'}
refresh();V.missionUI={version:'V87.11.0',compact:true,noFullscreenCover:true,refresh};
})();