/* V87.9 — puente final: conecta misiones secundarias con el motor, móvil y guardado. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const S=()=>V.gameState;
function persist(){const s=S();if(!s)return;try{s.sideMissions=Object.fromEntries(Object.entries(V.sideMissions||{}).map(([k,m])=>[k,{id:m.id,title:m.title,status:m.status,reward:m.reward}]));localStorage.setItem('villa_pelon_save',JSON.stringify(s))}catch(_){} }
function restore(){const s=S();if(!s||!V.sideMissions)return;Object.entries(s.sideMissions||{}).forEach(([k,v])=>{if(V.sideMissions[k])Object.assign(V.sideMissions[k],v)})}
const engineSave=V.saveGame;V.saveGame=()=>{persist();engineSave?.()};
function bindSave(){document.getElementById('save')?.addEventListener('click',()=>setTimeout(persist,20))}
function action(name){if(V.sideActions){V.sideActions(name);setTimeout(persist,20)}}
function mission(id){if(V.startSideMission){V.startSideMission(id);setTimeout(persist,20)}}
function mount(){if(document.getElementById('vpActions'))return;const root=document.getElementById('game');if(!root)return;const wrap=document.createElement('div');wrap.id='vpActions';wrap.setAttribute('aria-label','Acciones y misiones');wrap.innerHTML='<button id="vpActionsToggle" type="button">ACCIONES</button><div id="vpActionsPanel" hidden><div class="vp-actions-title">VIDA COTIDIANA</div><div class="vp-actions-grid"><button data-vp-action="mate">🧉 Mate</button><button data-vp-action="rest">🛏 Descansar</button><button data-vp-action="photo">📷 Foto</button><button data-vp-action="water">💧 Agua</button><button data-vp-action="radio">📻 Radio</button></div><div class="vp-actions-title">MISIONES</div><div class="vp-actions-grid"><button data-vp-mission="q06">Q6 · Agua</button><button data-vp-mission="q07">Q7 · Chacra</button><button data-vp-mission="q08">Q8 · Memoria</button></div></div>';
root.appendChild(wrap);const toggle=wrap.querySelector('#vpActionsToggle'),panel=wrap.querySelector('#vpActionsPanel');toggle.addEventListener('click',()=>{panel.hidden=!panel.hidden;toggle.textContent=panel.hidden?'ACCIONES':'CERRAR'});wrap.querySelectorAll('[data-vp-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.vpAction)));wrap.querySelectorAll('[data-vp-mission]').forEach(b=>b.addEventListener('click',()=>mission(b.dataset.vpMission)))}
const style=document.createElement('style');style.textContent='#vpActions{position:fixed;right:12px;bottom:18px;z-index:30;font-family:monospace}#vpActionsToggle{border:2px solid #33403a;background:#fff7e9;color:#33403a;border-radius:12px;padding:10px 13px;font-weight:800;box-shadow:0 4px 0 rgba(40,50,45,.2)}#vpActionsPanel{margin-bottom:8px;width:min(330px,calc(100vw - 24px));padding:10px;background:rgba(255,247,233,.97);border:2px solid #33403a;border-radius:14px;box-shadow:0 8px 24px rgba(20,30,25,.2)}.vp-actions-title{font-size:11px;font-weight:900;letter-spacing:.08em;margin:4px 0 7px}.vp-actions-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:10px}.vp-actions-grid button{min-height:42px;border:1px solid #718078;background:#e9f0e6;color:#26332e;border-radius:9px;font:700 11px monospace;padding:6px}@media(min-width:800px){#vpActions{right:18px;bottom:18px}}';document.head.appendChild(style);
const start=document.getElementById('startBtn');start?.addEventListener('click',()=>setTimeout(()=>{restore();mount();bindSave();},40));
if(document.getElementById('game')&&!document.getElementById('game').classList.contains('hidden')){restore();mount();bindSave()}
V.auditBridge={version:'V87.9.0',singleSave:true,mobileActions:true,persistentSideMissions:true};console.info('[Villa Pelón] V87.9 puente de integridad activo');
})();