/* V87.8 — misiones secundarias, acciones cotidianas y diálogos. */
(()=>{'use strict';const V=window.VillaPelon||(window.VillaPelon={});const S=()=>V.gameState;const say=(t,a)=>V.openDialogue?.(t,a);const add=i=>V.addItem?.(i);const save=()=>V.saveGame?.();
const q={q06:{id:'q06',title:'El agua no espera',status:'available',reward:900},q07:{id:'q07',title:'La voz de la chacra',status:'available',reward:1100},q08:{id:'q08',title:'Una foto para la memoria',status:'available',reward:750}};V.sideMissions=q;
const oldInteract=V.interact;V.interact=function(){const s=S();if(!s)return oldInteract?.();const n=V.getNearby?.();
 if(n?.name==='Rosa'&&q.q06.status==='available'){q.q06.status='active';add('Cuaderno de agua');say('ROSA · MISIÓN',['Necesito que recorras el borde del canal y mires si encontrás el antiguo punto de compuerta.','No hace falta correr: prestá atención al paisaje.','Cuando vuelvas, contame qué viste.']);return true}
 if(n?.name==='Julio'&&q.q07.status==='available'){q.q07.status='active';add('Grabador de campo');say('JULIO · MISIÓN',['En la chacra hay historias que casi nunca quedan escritas.','Escuchá a dos personas que trabajen por acá y llevá sus voces a la radio.','La misión se completa conversando, no peleando.']);return true}
 if(n?.name==='Lucía'&&q.q08.status==='available'){q.q08.status='active';say('LUCÍA · MISIÓN',['La escuela necesita una imagen del territorio para su archivo.','Recorré la ribera, las chacras o las bardas y elegí un lugar que quieras recordar.','Volvé después con una fotografía simbólica en tu mochila.']);return true}
 return oldInteract?.()};
function action(name){const s=S();if(!s)return;if(name==='mate'){s.energy=Math.min(100,s.energy+10);s.minutes+=8;add('Mate');say('MATE',['Unos minutos tranquilos.','No todo avance tiene que ser apurado.'])}if(name==='rest'){s.energy=Math.min(100,s.energy+35);s.minutes+=30;say('DESCANSO',['Te sentaste un rato. Recuperaste energía.'])}if(name==='photo'){add('Fotografía del territorio');s.minutes+=4;if(q.q08.status==='active'){q.q08.status='completed';s.money+=q.q08.reward;s.quest=Math.max(s.quest,3);say('ARCHIVO ESCOLAR',['La fotografía quedó guardada para la memoria local.','Recompensa: $750.'])}else say('FOTOGRAFÍA',['Guardaste una fotografía simbólica del territorio.'])}if(name==='water'){add('Muestra de agua');s.minutes+=6;if(q.q06.status==='active'){q.q06.status='completed';s.money+=q.q06.reward;add('Ficha del canal');say('AGUA QUE TRANSFORMA',['Encontraste el punto indicado y registraste el recorrido del agua.','Recompensa: $900.'])}else say('CANAL',['Observaste el recorrido del agua.'])}if(name==='radio'){if(q.q07.status==='active'){q.q07.status='completed';s.money+=q.q07.reward;remove('Grabador de campo');say('RADIO OASIS',['Llevaste las voces de la chacra a la radio.','Recompensa: $1.100.','Una comunidad también se cuenta a través de sus voces.'])}else say('RADIO OASIS',['El micrófono está listo. Quizás alguien tenga algo que contar.'])}save?.()}
function remove(i){const s=S();const n=s?.inventory?.indexOf(i);if(n>=0)s.inventory.splice(n,1)}
addEventListener('keydown',e=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='m')action('mate');if(k==='r')action('rest');if(k==='p')action('photo');if(k==='f')action('water');if(k==='o')action('radio')});
V.sideActions=action;V.missionDialogueVersion='87.8';console.info('[Villa Pelón] V87.8 misiones y vida cotidiana activas')})();
