/* Villa Pelón V87.9 — motor único, vida integrada, misiones persistentes y transporte sin loop paralelo. */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),C=document.getElementById('world');if(!C)return;
const X=C.getContext('2d',{alpha:false});X.imageSmoothingEnabled=false;
const G=()=>V.worldAuthority?.geometry||V.worldGeometry||{width:8000,height:5200,roads:[],buildings:[],fields:[],sites:[],bridges:[],river:{x:0,y:120,w:8000,h:190}};let g=G();
const S={started:false,x:960,y:650,speed:205,money:10000,energy:100,minutes:480,day:1,year:1,quest:0,dialogue:false,saved:false,inventory:[],walk:0,facing:'down',transport:null,missions:{}};
V.gameState=S;window.__villaPelonState=S;
V.territoryMissions=V.territoryMissions||{};V.territoryMissions.q05=V.territoryMissions.q05||{id:'q05',title:'El DNI perdido',status:'available',step:0,reward:1200};
const I={up:false,down:false,left:false,right:false};let W=innerWidth,H=innerHeight,cx=0,cy=0,last=performance.now(),near=null;
const P={grass:'#a9c995',grass2:'#bfd9a7',soil:'#c8aa83',water:'#91cbd0',water2:'#b9e0df',road:'#8e938d',road2:'#b9beb6',wall:'#ead8ba',roof:'#b58b7b',wood:'#9d7b61',leaf:'#6f9b69',leaf2:'#91b77b',skin:'#e7b28f',hair:'#68554b',shirt:'#86a99a',pants:'#7189a2',outline:'#33403a',glass:'#9ecbd0',yellow:'#e2c56c',red:'#c8796b'};
const PEOPLE=[['Marta',650,570,'neighbor','En el almacén siempre se cruza información del pueblo.'],['Raúl',1720,590,'farmer','Las chacras tienen su propio ritmo. Hay días de trabajo y días de espera.'],['Lucía',530,1010,'teacher','La escuela guarda recuerdos que pueden ayudarnos a reconstruir el territorio.'],['Pedro',1810,1010,'farmer','Cuando cambia la temporada cambia también el trabajo.'],['Nico',1190,390,'neighbor','La radio conecta voces que de otro modo quedarían lejos.'],['Rosa',900,760,'neighbor','El agua organiza buena parte de las chacras.'],['Julio',1500,1180,'farmer','No todo camino lleva al centro. Algunos llevan directo al trabajo.'],['Ana',2500,900,'teacher','Si encontrás una pista, anotala. La memoria también necesita método.'],['Beto',3100,1600,'farmer','En época de cosecha el pueblo empieza temprano.'],['Sonia',5600,900,'neighbor','La periferia creció con familias, comercios y nuevos caminos.'],['Omar',6100,1500,'farmer','Por acá el campo queda más cerca que el centro.'],['Clara',7000,1700,'neighbor','La Picada 21 parece lejos, pero también forma parte del territorio.'],['Don Félix',7600,4450,'elder','Acá se aprende a medir las distancias de otra manera.'],['Mabel',7800,4700,'neighbor','El colectivo hace que este lugar no quede aislado.'],['Tomás',5400,2100,'child','Me gusta caminar hasta donde termina el camino.'],['Elena',6800,2200,'neighbor','Las bardas cambian el paisaje y también la forma de moverse.']];
const N=PEOPLE.map((p,i)=>({id:'npc-'+i,name:p[0],x:p[1],y:p[2],role:p[3],line:p[4],phase:i*.63}));V.npcs=N;
const special={clue:{id:'clue',x:2040,y:430},job:{id:'jobSpot',x:2200,y:700},bus:{id:'terminal-local',x:7160,y:705},home21:{id:'picada21-casa-01',x:7565,y:4625}};
const buildings=()=>Array.isArray(g.buildings)?g.buildings:[];
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,W*d);C.height=Math.max(1,H*d);C.style.width=W+'px';C.style.height=H+'px';X.setTransform(d,0,0,d,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize,{passive:true});resize();
function key(k,v){if(['arrowup','w'].includes(k))I.up=v;if(['arrowdown','s'].includes(k))I.down=v;if(['arrowleft','a'].includes(k))I.left=v;if(['arrowright','d'].includes(k))I.right=v}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();key(k,true);if(k==='e'||k===' ')interact();if('wasd'.includes(k)||k.startsWith('arrow'))e.preventDefault()});
addEventListener('keyup',e=>key(e.key.toLowerCase(),false));
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();I[k]=true});['pointerup','pointercancel','pointerleave'].forEach(q=>b.addEventListener(q,e=>{e.preventDefault();I[k]=false}))});
document.getElementById('interact')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});
document.getElementById('startBtn')?.addEventListener('click',()=>startGame());
document.getElementById('save')?.addEventListener('click',save);
document.getElementById('dialogueNext')?.addEventListener('click',nextDialogue);
function startGame(){if(S.started)return;S.started=true;document.getElementById('start')?.classList.add('hidden');document.getElementById('game')?.classList.remove('hidden');load();S.started=true;last=performance.now();ui();V.gameStart?.()}
function inside(o,x,y,p=0){return x>=o.x-p&&x<=o.x+(o.w||0)+p&&y>=o.y-p&&y<=o.y+(o.h||0)+p}function river(x,y){return inside(g.river||{x:0,y:120,w:g.width,h:190},x,y)}function bridge(x,y){return (g.bridges||[]).some(b=>inside(b,x,y))}
function blocked(x,y){if(x<30||y<30||x>g.width-30||y>g.height-30)return true;if(river(x,y)&&!bridge(x,y))return true;return buildings().some(b=>inside(b,x,y,18))}
function nearby(){let a=null,d0=Infinity;[...N,...buildings(),special.clue,special.job,special.bus,special.home21].forEach(o=>{const d=Math.hypot(S.x-(o.x+(o.w||0)/2),S.y-(o.y+(o.h||0)/2));if(d<(o.name?105:125)&&d<d0){a=o;d0=d}});return a}
function say(title,lines){S.dialogue=true;const b=document.getElementById('dialogue');if(!b)return;b.classList.remove('hidden');b.dataset.lines=JSON.stringify(lines);b.dataset.index='0';document.getElementById('speaker').textContent=title;document.getElementById('dialogueText').textContent=lines[0]}
function nextDialogue(){const b=document.getElementById('dialogue');if(!S.dialogue)return;let a=[];try{a=JSON.parse(b.dataset.lines||'[]')}catch(_){}const i=Number(b.dataset.index||0)+1;if(i<a.length){b.dataset.index=i;document.getElementById('dialogueText').textContent=a[i]}else{S.dialogue=false;b.classList.add('hidden');ui()}}
function item(i){if(!Array.isArray(S.inventory))S.inventory=[];if(!S.inventory.includes(i))S.inventory.push(i);ui()}function remove(i){const n=S.inventory.indexOf(i);if(n>=0)S.inventory.splice(n,1);ui()}
function syncMission(){const q=V.territoryMissions.q05;if(q)S.missions.q05={id:q.id,title:q.title,status:q.status,step:q.step,reward:q.reward}}
function restoreMission(){const q=S.missions?.q05;if(q)Object.assign(V.territoryMissions.q05,q)}
function quest(){const q=V.territoryMissions.q05;if(q?.status==='completed')return '✓ DNI entregado en Picada 21 · explorá libremente.';if(q?.status==='traveling')return '🚌 En viaje hacia Picada 21.';if(S.quest>=5)return 'El DNI perdido · entregalo en la casa marcada.';if(S.quest>=2)return 'Explorá: agua, chacras, caminos y bardas esconden historias.';if(S.quest===1)return 'Buscá la primera pista histórica.';return 'Conocé a un vecino y empezá a descubrir el territorio.'}
function interact(){if(!S.started)return;if(S.transport)return;if(S.dialogue){nextDialogue();return}const o=near();if(!o){say('TERRITORIO',['No hay nadie cerca. Caminá y observá.','Probá acercarte a una casa, comercio, vecino, parada o lugar señalado.']);return}if(o===special.clue){if(S.quest<2){S.quest=2;item('Pista histórica');S.money+=2500;say('ARCHIVO DE MEMORIA',['Encontraste una pista.','La historia documental del juego se construirá con fuentes verificables.','Recompensa: $2.500.'])}else say('ARCHIVO DE MEMORIA',['Ya registraste esta pista.']);return}if(o===special.job){if(S.energy<20){say('CHANGA RURAL',['Estás cansado. Descansá y volvé más tarde.']);return}S.energy-=18;S.money+=850;item('Cajón de cosecha');say('CHANGA RURAL',['Ayudaste con una carga de cosecha.','Cobraste $850.']);return}if(o===special.bus){busAction();return}if(o===special.home21){deliver();return}if(o.name){S.quest=Math.max(1,S.quest);say(o.name,[o.line,'Cada persona conoce una parte distinta del territorio.','Podés volver a hablar con ellos en otro momento.']);return}if(o.type==='shop'){if(S.money<450){say('ALMACÉN',['No alcanza para pan de campo.']);return}S.money-=450;item('Pan de campo');S.energy=Math.min(100,S.energy+8);S.minutes+=5;say('ALMACÉN',['Compraste pan de campo.','Guardalo en la mochila o compartilo en una futura misión.']);return}if(o.type==='home'){S.energy=Math.min(100,S.energy+35);S.minutes+=30;say('CASA',['Descansaste. Recuperaste energía.']);return}if(o.type==='radio'){say('RADIO OASIS',['La radio acompaña la vida cotidiana.','Acá pueden aparecer futuras pistas, voces y misiones.']);return}say((o.label||o.name||'LUGAR'),['Este lugar forma parte del territorio.','Observá los detalles y buscá nuevas historias.'])}
function busAction(){const q=V.territoryMissions.q05;if(!q)return;if(q.status==='traveling'){return}if(!S.inventory.includes('DNI perdido')){item('DNI perdido');S.quest=5;q.step=1;q.status='active';syncMission();save();say('ENCARGO · DNI PERDIDO',['Encontraron un DNI y hay que llevarlo a una familia de Picada 21.','Volvé a interactuar para subir al colectivo.']);return}if(q.step>=4){say('PARADA REGIONAL',['Ya llegaste a Picada 21. Buscá la casa marcada.']);return}if(Math.hypot(S.x-special.bus.x,S.y-special.bus.y)>180){say('PARADA REGIONAL',['Acercate a la parada para subir.']);return}q.status='traveling';q.step=2;S.transport={progress:0,minutesStart:S.minutes,energyStart:S.energy,points:[{x:7160,y:705},{x:7350,y:705},{x:7350,y:2450},{x:7350,y:4920},{x:7240,y:4840}],elapsed:0,duration:34};S.dialogue=false;document.getElementById('dialogue')?.classList.add('hidden');S.speed=0;syncMission();save()}
function updateTransport(dt){const tr=S.transport;if(!tr)return;tr.elapsed=Math.min(tr.duration,tr.elapsed+dt);const t=tr.elapsed/tr.duration;let total=0,seg=[];for(let i=1;i<tr.points.length;i++){const d=Math.hypot(tr.points[i].x-tr.points[i-1].x,tr.points[i].y-tr.points[i-1].y);seg.push(d);total+=d}let d=t*total,p=tr.points[tr.points.length-1];for(let i=1;i<tr.points.length;i++){if(d<=seg[i-1]){const a=tr.points[i-1],b=tr.points[i],u=d/seg[i-1];p={x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u};break}d-=seg[i-1]}S.x=p.x;S.y=p.y;S.minutes=tr.minutesStart+34*t;S.energy=Math.max(0,tr.energyStart-6*t);if(t>=1){S.x=7240;S.y=4840;S.speed=205;S.transport=null;const q=V.territoryMissions.q05;q.step=4;q.status='active';syncMission();save();say('PICADA 21',['Llegaste en colectivo.','Ahora seguí la señal hasta la casa marcada y entregá el DNI.'])}}
function deliver(){const q=V.territoryMissions.q05;if(!q||q.step<4||!S.inventory.includes('DNI perdido')){say('PICADA 21',['Todavía no hay nada para entregar.']);return}if(Math.hypot(S.x-7565,S.y-4625)>170){say('PICADA 21',['Acercate a la casa marcada.']);return}remove('DNI perdido');S.money+=1200;q.step=5;q.status='completed';S.quest=6;syncMission();save();say('MISIÓN COMPLETADA',['El DNI llegó a destino.','Recompensa: $1.200.','La distancia también cuenta una historia: el transporte conecta territorio y comunidad.'])}
function save(){try{syncMission();localStorage.setItem('villa_pelon_save',JSON.stringify(S));S.saved=true;ui();setTimeout(()=>{S.saved=false;ui()},1600)}catch(err){console.warn('[Villa Pelón] No se pudo guardar',err)}}
function load(){try{const a=JSON.parse(localStorage.getItem('villa_pelon_save'));if(a)Object.assign(S,a)}catch(err){console.warn('[Villa Pelón] Partida inválida, se inicia limpia',err)}if(!Array.isArray(S.inventory))S.inventory=[];S.transport=null;restoreMission();S.dialogue=false}
function ui(){const h=Math.floor(S.minutes/60)%24,m=Math.floor(S.minutes%60),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('clock',String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'));set('day',S.day);set('year',S.year||1);set('money',Math.round(S.money));set('energy',Math.round(S.energy));set('questText',S.saved?'Partida guardada ✓':quest());set('discoveryCount',S.inventory.length);set('weather',V.life?(V.life.weather||'Despejado').replace(/^./,x=>x.toUpperCase()):'Despejado')}
function screen(x,y){return{x:(x-cx)*.78,y:(y-cy)*.78}}
function drawTree(x,y,sc=1){const p=screen(x,y),z=.78*sc;X.fillStyle=P.wood;X.fillRect(p.x-4*z,p.y+5*z,8*z,24*z);X.fillStyle=P.leaf;X.beginPath();X.arc(p.x,p.y,22*z,0,7);X.fill();X.fillStyle=P.leaf2;X.beginPath();X.arc(p.x-11*z,p.y-8*z,12*z,0,7);X.arc(p.x+11*z,p.y-6*z,13*z,0,7);X.fill()}
function drawWorld(){X.fillStyle=P.grass;X.fillRect(0,0,W,H);const r=g.river;if(r){const p=screen(r.x,r.y);X.fillStyle=P.water;X.fillRect(p.x,p.y,r.w*.78,r.h*.78);for(let x=0;x<g.width;x+=60){const q=screen(x,r.y+38);X.fillStyle=P.water2;X.fillRect(q.x,q.y,28,3)}}(g.roads||[]).forEach(r=>{const p=screen(r.x,r.y);X.fillStyle=P.road;X.fillRect(p.x,p.y,r.w*.78,r.h*.78);X.fillStyle=P.road2;if(r.w>r.h)X.fillRect(p.x,p.y+r.h*.39,r.w*.78,3);else X.fillRect(p.x+r.w*.39,p.y,3,r.h*.78)});(g.fields||[]).forEach((f,i)=>{const p=screen(f.x,f.y);X.fillStyle=i%2?P.grass2:P.soil;X.fillRect(p.x,p.y,f.w*.78,f.h*.78)});for(let x=450;x<g.width;x+=280)drawTree(x,430,.7);for(let x=3800;x<5400;x+=90)drawTree(x,720,.85);for(let x=2500;x<4000;x+=130)drawTree(x,3000,.6)}
function drawBuildings(){buildings().forEach(b=>{const p=screen(b.x,b.y),w=b.w*.78,h=b.h*.78;X.fillStyle=P.outline;X.fillRect(p.x-4,p.y-4,w+8,h+8);X.fillStyle=b.type==='rural'?P.soil:P.wall;X.fillRect(p.x,p.y,w,h);X.fillStyle=b.type==='rural'?P.wood:P.roof;X.beginPath();X.moveTo(p.x-8,p.y);X.lineTo(p.x+w/2,p.y-30);X.lineTo(p.x+w+8,p.y);X.fill();X.fillStyle=P.glass;X.fillRect(p.x+w*.1,p.y+h*.22,w*.14,h*.16);X.fillRect(p.x+w*.76,p.y+h*.22,w*.14,h*.16);X.fillStyle=P.wood;X.fillRect(p.x+w*.43,p.y+h*.58,w*.14,h*.42);X.font='bold 10px monospace';X.textAlign='center';X.fillStyle=P.outline;X.fillText((b.label||b.name||'').toUpperCase(),p.x+w/2,p.y-35)})}
function drawPerson(n){const p=screen(n.x,n.y);X.fillStyle='rgba(35,40,35,.18)';X.beginPath();X.ellipse(p.x,p.y+29,13,5,0,0,7);X.fill();X.fillStyle=P.outline;X.fillRect(p.x-10,p.y-30,20,18);X.fillStyle=P.skin;X.fillRect(p.x-8,p.y-28,16,14);X.fillStyle=P.hair;X.fillRect(p.x-11,p.y-34,22,7);X.fillStyle=n.role==='farmer'?'#668d80':n.role==='teacher'?'#a5a6c3':n.role==='child'?'#d1a06d':P.shirt;X.fillRect(p.x-9,p.y-10,18,25);X.fillStyle=P.pants;X.fillRect(p.x-8,p.y+15,7,13);X.fillRect(p.x+1,p.y+15,7,13);if(Math.hypot(S.x-n.x,S.y-n.y)<100){X.font='bold 10px monospace';X.textAlign='center';X.fillStyle=P.outline;X.fillText(n.name.toUpperCase(),p.x,p.y-43)}}
function drawPlayer(){const p=screen(S.x,S.y),bob=S.walk?Math.sin(S.walk*1.7)*2:0;X.fillStyle='rgba(35,40,35,.22)';X.beginPath();X.ellipse(p.x,p.y+31,15,5,0,0,7);X.fill();X.fillStyle=P.outline;X.fillRect(p.x-11,p.y-30+bob,22,18);X.fillStyle=P.skin;X.fillRect(p.x-9,p.y-28+bob,18,15);X.fillStyle=P.hair;X.fillRect(p.x-11,p.y-34+bob,22,7);X.fillStyle=P.shirt;X.fillRect(p.x-10,p.y-9+bob,20,25);X.fillStyle=P.pants;X.fillRect(p.x-8,p.y+16+bob,7,14);X.fillRect(p.x+1,p.y+16+bob,7,14);if(near&&!S.dialogue&&!S.transport){X.fillStyle='rgba(30,40,34,.92)';X.fillRect(p.x-58,p.y-63,116,22);X.fillStyle='#fff7e9';X.font='bold 10px monospace';X.textAlign='center';X.fillText('E · INTERACTUAR',p.x,p.y-48)}}
function drawTransport(){if(!S.transport)return;const p=screen(S.x,S.y);X.fillStyle='rgba(35,40,35,.18)';X.fillRect(p.x-25,p.y+18,50,7);X.fillStyle='#d8bd68';X.fillRect(p.x-30,p.y-18,60,34);X.fillStyle='#6e8f91';X.fillRect(p.x-21,p.y-12,16,12);X.fillRect(p.x+5,p.y-12,16,12);X.fillStyle=P.outline;X.fillRect(p.x-22,p.y+10,10,7);X.fillRect(p.x+12,p.y+10,10,7);X.fillStyle=P.outline;X.font='bold 9px monospace';X.textAlign='center';X.fillText('PICADA 21',p.x,p.y-25)}
function drawSpecial(){const q=V.territoryMissions.q05;if(q&&q.status!=='completed'){const p=screen(special.bus.x,special.bus.y);X.fillStyle=P.yellow;X.fillRect(p.x-9,p.y-9,18,18);X.fillStyle=P.outline;X.font='bold 9px monospace';X.textAlign='center';X.fillText('BUS',p.x,p.y-13)}if(q?.step>=4){const p=screen(special.home21.x,special.home21.y);X.fillStyle=P.red;X.fillRect(p.x-8,p.y-8,16,16);X.fillStyle='#fff7e9';X.font='bold 12px monospace';X.fillText('!',p.x,p.y+4)}const p=screen(special.clue.x,special.clue.y);X.fillStyle=P.yellow;X.fillRect(p.x-10,p.y-10,20,20);X.fillStyle=P.outline;X.font='bold 16px monospace';X.fillText('?',p.x,p.y+6)}
function render(){g=G();X.clearRect(0,0,W,H);drawWorld();drawBuildings();if(V.life?.drawWorld){X.save();X.translate(-cx*.78,-cy*.78);X.scale(.78,.78);V.life.drawWorld(X);X.restore()}N.forEach(drawPerson);drawSpecial();drawTransport();drawPlayer();if(V.life?.drawOverlay)V.life.drawOverlay(X,W,H);const h=Math.floor(S.minutes/60);if(h<6||h>=21){X.fillStyle='rgba(25,36,48,.22)';X.fillRect(0,0,W,H)}else if(h>=18){X.fillStyle='rgba(224,177,117,.08)';X.fillRect(0,0,W,H)}}
function update(dt){if(!S.started)return;if(S.transport){updateTransport(dt);near=null;ui();return}if(S.dialogue){V.life?.update?.(dt,S.minutes);ui();return}let dx=(I.right?1:0)-(I.left?1:0),dy=(I.down?1:0)-(I.up?1:0),moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;S.facing=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');const nx=S.x+dx*S.speed*dt,ny=S.y+dy*S.speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;S.energy=Math.max(0,S.energy-dt*.62);S.walk+=dt*9}else S.walk=0;S.minutes+=dt*(moving?3.5:.05);if(S.minutes>=1440){S.minutes-=1440;S.day++;S.energy=100;V.life?.nextWeather?.()}V.life?.update?.(dt,S.minutes);near=nearby();cx=Math.max(0,Math.min(g.width-W/.78,S.x-W/(1.56)));cy=Math.max(0,Math.min(g.height-H/.78,S.y-H/(1.56)));ui()}
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.05);last=now;update(dt);render()}requestAnimationFrame(loop);
V.openDialogue=say;V.addItem=item;V.removeItem=remove;V.saveGame=save;V.getNearby=nearby;V.interact=interact;V.engine={version:'V87.9.0',singleLoop:true,canonicalWorld:true,canvas:C,draw:render,update};V.worldGeometry=g;console.info('[Villa Pelón] V87.9 motor consolidado: un loop, transporte integrado, vida y persistencia activas');
})();