/* VILLA PELÓN V157 — MOTOR DE TERRENO CONSOLIDADO
   V138 mantiene la geometría. Este motor dibuja SOLO terreno, caminos, río y puentes.
   Actores/fachadas/contenido pertenecen al compositor V157.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),canvas=document.getElementById('world');if(!canvas)return;const ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;const W=V.world||{w:8200,h:4200},G=V.worldGeometry||{},B=G.buildings||[],BR=G.bridges||[],roads=G.roads||[],RIVER=G.river;if(!V.worldMaster?.locked||!RIVER)throw new Error('WORLD_MASTER_V1 no disponible');
const S=V.gameState=V.gameState||{};Object.assign(S,{started:true,x:Number(S.x)||1380,y:Number(S.y)||1200,speed:205,money:Number(S.money)||10000,energy:Number(S.energy)||100,minutes:Number(S.minutes)||480,day:Number(S.day)||1,inventory:Array.isArray(S.inventory)?S.inventory:[],facing:S.facing||'down',walk:0,missionId:S.missionId||'welcome',missionStep:Number(S.missionStep)||0,missionFlags:S.missionFlags||{},missionHistory:Array.isArray(S.missionHistory)?S.missionHistory:[],flags:S.flags||{},stats:S.stats||{steps:0,interactions:0,harvests:0}});
let vw=innerWidth,vh=innerHeight,last=performance.now(),near=null;const I={up:false,down:false,left:false,right:false},Z=.82;
const C={grass:'#8d9667',grassDark:'#66794e',urban:'#a89a72',urbanDark:'#8e815e',rural:'#9a9b65',productive:'#8b8b59',road:'#b8a174',roadEdge:'#806b51',river:'#668d91',river2:'#7ea3a0',riverDark:'#456e76',wood:'#6a503b',bridge:'#76583f',bridgeLight:'#a17b53'};
function resize(){vw=innerWidth;vh=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,vw*d);canvas.height=Math.max(1,vh*d);canvas.style.width=vw+'px';canvas.style.height=vh+'px';canvas.style.position='absolute';canvas.style.inset='0';canvas.style.zIndex='1';ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize,{passive:true});resize();
function inRect(x,y,r,p=0){return x>=r.x-p&&x<=r.x+r.w+p&&y>=r.y-p&&y<=r.y+r.h+p}function bridgeAt(x,y){return BR.find(b=>inRect(x,y,b,22))}function blocked(x,y){if(x<45||y<105||x>W.w-45||y>W.h-45)return true;if(inRect(x,y,RIVER)&&!bridgeAt(x,y))return true;return B.some(b=>inRect(x,y,b,18))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function addItem(x){if(!S.inventory.includes(x))S.inventory.push(x)}
function key(k,v){k=k.toLowerCase();if(k==='w'||k==='arrowup')I.up=v;if(k==='s'||k==='arrowdown')I.down=v;if(k==='a'||k==='arrowleft')I.left=v;if(k==='d'||k==='arrowright')I.right=v}addEventListener('keydown',e=>{key(e.key,true);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>key(e.key,false));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();I[k]=true});['pointerup','pointercancel','pointerleave'].forEach(q=>b.addEventListener(q,()=>I[k]=false))});
function save(){localStorage.setItem('villa_pelon_save',JSON.stringify({...S,dialogue:false,savedAt:Date.now()}));S.saved=true;setTimeout(()=>S.saved=false,1600)}document.getElementById('save')?.addEventListener('click',save);
function dialogue(title,lines){S.dialogue=true;const d=document.getElementById('dialogue');if(!d)return;d.classList.remove('hidden');d.dataset.lines=JSON.stringify(lines);d.dataset.i='0';document.getElementById('speaker').textContent=title;document.getElementById('dialogueText').textContent=lines[0]}function nextDialogue(){const d=document.getElementById('dialogue');if(!S.dialogue||!d)return;let a=[];try{a=JSON.parse(d.dataset.lines||'[]')}catch(_){}const i=Number(d.dataset.i||0)+1;if(i<a.length){d.dataset.i=i;document.getElementById('dialogueText').textContent=a[i]}else{S.dialogue=false;d.classList.add('hidden')}}document.getElementById('dialogueNext')?.addEventListener('click',nextDialogue);
function interact(){if(S.dialogue){nextDialogue();return}S.stats.interactions++;let best=null,bd=Infinity;(V.npcs||[]).forEach(n=>{const d=dist(S,n);if(d<95&&d<bd){best=n;bd=d}});B.forEach(b=>{const p={x:b.x+b.w/2,y:b.y+b.h+35},d=dist(S,p);if(d<105&&d<bd){best=b;bd=d}});if(!best)return;if(best.id&&best.lines){if(V.missions?.completeStep)V.missions.completeStep(S,'talk:'+best.id);dialogue(best.n,best.lines);return}if(best.type==='home'){S.energy=Math.min(100,S.energy+30);S.minutes+=35;dialogue(best.label||'CASA',['Descansaste. Recuperaste energía.']);return}dialogue(best.label||best.type,['Este lugar forma parte del mundo de Villa Pelón.'])}document.getElementById('interact')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});
function update(dt){if(S.dialogue)return;let dx=(I.right?1:0)-(I.left?1:0),dy=(I.down?1:0)-(I.up?1:0),moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;const nx=S.x+dx*S.speed*dt,ny=S.y+dy*S.speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;S.facing=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');S.walk=(S.walk||0)+dt*9;S.minutes+=dt*3.2;S.energy=Math.max(0,S.energy-dt*.58)}}
function road(r){ctx.fillStyle=C.roadEdge;ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle=C.road;ctx.fillRect(r.x+4,r.y+4,Math.max(1,r.w-8),Math.max(1,r.h-8));if(r.w>=r.h){ctx.fillStyle='#9d8968';ctx.fillRect(r.x+18,r.y+r.h/2-1,r.w-36,2)}else{ctx.fillStyle='#9d8968';ctx.fillRect(r.x+r.w/2-1,r.y+18,2,r.h-36)}}
function cluster(x,y,c){ctx.fillStyle=c;ctx.fillRect(x,y,4,3);ctx.fillRect(x-3,y+3,4,4);ctx.fillRect(x+4,y+4,4,3)}
function terrain(){ctx.fillStyle=C.grass;ctx.fillRect(0,0,W.w,W.h);
 (G.zones||[]).forEach(z=>{ctx.fillStyle=z.kind==='urban'?C.urban:(z.kind==='productive'?C.productive:(z.kind==='rural'?C.rural:C.grass));ctx.fillRect(z.x,z.y,z.w,z.h);});
 // Deterministic vegetation texture: sparse clusters, never over the road network.
 for(let i=0;i<180;i++){const x=90+(i*347)%7950,y=140+(i*211)%2380;if((roads||[]).some(r=>inRect(x,y,r,24)))continue;let c=i%4===0?C.grassDark:'#74845a';cluster(x,y,c)}
 // Urban paving rhythm: restrained blocks instead of a flat rectangle.
 const U=G.zones?.find(z=>z.kind==='urban');if(U){ctx.fillStyle=C.urbanDark;for(let x=U.x+80;x<U.x+U.w;x+=96)ctx.fillRect(x,U.y+12,2,Math.min(U.h-24,8));for(let y=U.y+90;y<U.y+U.h;y+=96)ctx.fillRect(U.x+12,y,Math.min(U.w-24,8),2)}
 roads.forEach(road);
 // Rural parcel rhythm: rows follow the productive landscape without crossing buildings.
 for(let row=0;row<9;row++){const y=1280+row*54;for(let x=5200;x<7350;x+=72){ctx.fillStyle=row%2?C.grassDark:'#81885c';ctx.fillRect(x,y,22,2);ctx.fillRect(x+7,y-3,3,2)}}
 // River bank: dark edge + light water bands, geometry unchanged.
 ctx.fillStyle=C.riverDark;ctx.fillRect(RIVER.x,RIVER.y,RIVER.w,RIVER.h);ctx.fillStyle=C.river;ctx.fillRect(RIVER.x,RIVER.y+5,RIVER.w,Math.max(1,RIVER.h-10));for(let x=RIVER.x+30;x<RIVER.x+RIVER.w-20;x+=92){ctx.fillStyle=C.river2;ctx.fillRect(x,RIVER.y+25,28,2);ctx.fillRect(x+13,RIVER.y+61,20,2)}
 BR.forEach(b=>{ctx.fillStyle=C.bridge;ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle=C.bridgeLight;for(let x=b.x+10;x<b.x+b.w;x+=34)ctx.fillRect(x,b.y+7,22,Math.max(1,b.h-14));ctx.fillStyle='#513d31';ctx.fillRect(b.x,b.y,b.w,3);ctx.fillRect(b.x,b.y+b.h-3,b.w,3)})
}
function render(){ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(vw/2,vh/2);ctx.scale(Z,Z);ctx.translate(-S.x,-S.y);terrain();near=null;ctx.restore();if(V.renderCompositor?.renderNow)V.renderCompositor.renderNow()}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}
V.engine={version:'157.0',state:'running',health:()=>({version:'157.0',world:[W.w,W.h],buildings:B.length,npcs:(V.npcs||[]).length,save:true,missionSystem:!!V.missions,singleTerrainRenderer:true,npcNavigation:'bridge-aware',riverRule:'bridge_only',worldMaster:V.worldMaster.version,river:{...RIVER},renderAuthority:'V157-terrain',actorAuthority:'V157-compositor',frameAuthority:'single-v90'}) ,worldMaster:'WORLD_MASTER_V1',singleTerrainRenderer:true,terrainAuthority:'core/v90_engine.js',renderAuthority:'V157-terrain',frameAuthority:'single-RAF'};window.dispatchEvent(new CustomEvent('villa-pelon-engine-ready'));requestAnimationFrame(loop);
})();
