/* VILLA PELÓN V112 — MOTOR DE JUEGO ALINEADO A LA GEOMETRÍA FINAL
   Una sola fuente territorial: V.worldGeometry.
   Terreno, rutas, río y puentes: este motor.
   Fachadas y actores ambientales: render_compositor_v93.js.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const canvas=document.getElementById('world');if(!canvas)return;const ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
const W=V.world||{w:8200,h:4200};const G=V.worldGeometry||{};const B=G.buildings||[];const BR=G.bridges||[];const roads=G.roads||[];const RIVER=G.river||{x:5000,y:3070,w:3200,h:90};
const S=V.gameState=V.gameState||{};Object.assign(S,{started:true,x:Number(S.x)||1340,y:Number(S.y)||770,speed:205,money:Number(S.money)||10000,energy:Number(S.energy)||100,minutes:Number(S.minutes)||480,day:Number(S.day)||1,inventory:Array.isArray(S.inventory)?S.inventory:[],facing:S.facing||'down',walk:0,missionId:S.missionId||'welcome',missionStep:Number(S.missionStep)||0,missionFlags:S.missionFlags||{},missionHistory:Array.isArray(S.missionHistory)?S.missionHistory:[],flags:S.flags||{},stats:S.stats||{steps:0,interactions:0,harvests:0}});
let vw=innerWidth,vh=innerHeight,last=performance.now(),near=null,toastTimer=0,weather='despejado',weatherTimer=0;const I={up:false,down:false,left:false,right:false};const Z=.82;
const colors={grass:'#8d9667',grass2:'#7f895d',urban:'#a89a72',road:'#b8a174',road2:'#8d7857',river:'#668d91',river2:'#7ea3a0',wood:'#6a503b',roof:'#62463b',wall:'#c5a57b',dark:'#283128',gold:'#d0b36c',skin:'#d8a27e'};
const NPC=[
{x:650,y:570,n:'Marta',id:'marta',c:'#b95e4e',role:'comercio',home:[820,1290],work:[1730,750],lines:['El almacén es donde muchas historias empiezan.','Si escuchás con atención, siempre aparece un dato nuevo.']},
{x:1730,y:750,n:'Raúl',id:'raul',c:'#557ca8',role:'rural',home:[1660,1290],work:[5450,1250],lines:['La chacra tiene otro ritmo. Hay que mirar el agua, la tierra y las estaciones.','Cuando termina la cosecha, el pueblo también cambia.']},
{x:520,y:1040,n:'Lucía',id:'lucia',c:'#a55e8f',role:'escuela',home:[980,1290],work:[730,745],lines:['Una escuela también guarda memoria.','Las fotos, cuadernos y relatos pueden convertirse en pistas.']},
{x:1850,y:1040,n:'Pedro',id:'pedro',c:'#bd8249',role:'rural',home:[1960,1290],work:[6100,1280],lines:['En el campo siempre hay una tarea distinta.','El trabajo cotidiano también cuenta la historia del lugar.']},
{x:1190,y:770,n:'Nico',id:'nico',c:'#5d8d59',role:'radio',home:[1360,1290],work:[820,1760],lines:['La radio conecta voces que a veces no se cruzan en la calle.','Un pueblo se entiende mejor cuando escuchás a su gente.']},
{x:5200,y:760,n:'Elena',id:'elena',c:'#9b6b4e',role:'bodega',home:[6750,1950],work:[5960,720],lines:['El sector rural empieza cuando dejás atrás el núcleo urbano.','Acá el paisaje cambia: chacras, acequias, galpones y caminos.']},
{x:6200,y:920,n:'Tomás',id:'tomas',c:'#596f8f',role:'bodega',home:[6750,1950],work:[5960,720],lines:['Las bodegas son parte del paisaje productivo.','La producción también puede contar historias del territorio.']},
{x:2450,y:1400,n:'Amalia',id:'amalia',c:'#8a6b9c',role:'archivo',home:[2500,1290],work:[2450,1400],lines:['Un archivo no es solamente un cuarto lleno de papeles.','Para investigar una fecha, primero anotá qué fuente la respalda.'],source:'Archivo educativo ficticio inspirado en prácticas de documentación local.'},
{x:5100,y:1250,n:'Mateo',id:'mateo',c:'#647e58',role:'riego',home:[5200,1450],work:[5100,1250],lines:['El agua cambia el paisaje cuando existe una red de riego.','Una cronología local registra una primera bocatoma en Picada 13 en 1971 y una segunda en 1972. Contrastá siempre la fecha con la fuente.'],source:'Cronología de San Patricio del Chañar, Más Neuquén.'},
{x:6200,y:1500,n:'Rosa',id:'rosa',c:'#a96d58',role:'trabajadora_rural',home:[6750,1950],work:[6200,1500],lines:['El trabajo rural también es memoria.','La Fiesta Provincial del Pelón comenzó en 1985 y con el tiempo incorporó un homenaje al trabajador rural.'],source:'Cronología local y prensa regional.'},
{x:430,y:745,n:'Julia',id:'julia',c:'#6b7fa0',role:'docente',home:[700,1290],work:[730,745],lines:['La Escuela 273 empezó a funcionar en 1975 y fue la primera escuela de la localidad según la cronología histórica consultada.','Cuando encuentres un dato, fijate de dónde salió antes de repetirlo.'],source:'Cronología de San Patricio del Chañar, Más Neuquén.'},
{x:1550,y:1150,n:'Celso',id:'celso',c:'#806b53',role:'memoria',home:[1600,1290],work:[1550,1150],lines:['El nombre de un lugar también puede contar una historia.','La identidad del Chañar reúne capas: territorio, población, producción, memoria y documentos.'],source:'Municipalidad de San Patricio del Chañar.'}
];V.npcs=NPC;
const points={plaza:{x:1340,y:770},rural:{x:5200,y:1125},winery:{x:5960,y:720},clue:{x:2040,y:560},job:{x:2820,y:1450},picada:{x:6600,y:3725},stop:{x:6200,y:3380}};G.points=G.points||[];G.clue=points.clue;G.jobSpot=points.job;
function resize(){vw=innerWidth;vh=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,vw*d);canvas.height=Math.max(1,vh*d);canvas.style.width=vw+'px';canvas.style.height=vh+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize,{passive:true});resize();
function key(k,v){k=k.toLowerCase();if(k==='w'||k==='arrowup')I.up=v;if(k==='s'||k==='arrowdown')I.down=v;if(k==='a'||k==='arrowleft')I.left=v;if(k==='d'||k==='arrowright')I.right=v;if(v&&['e',' '].includes(k)){try{interact()}catch(e){console.error(e)}}if(v&&k==='f')save()}addEventListener('keydown',e=>{key(e.key,true);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>key(e.key,false));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();I[k]=true});['pointerup','pointercancel','pointerleave'].forEach(q=>b.addEventListener(q,()=>I[k]=false))});document.getElementById('interact')?.addEventListener('pointerdown',e=>{e.preventDefault();interact()});document.getElementById('save')?.addEventListener('click',save);
function save(){localStorage.setItem('villa_pelon_save',JSON.stringify({...S,dialogue:false,savedAt:Date.now()}));S.saved=true;toast('PARTIDA GUARDADA');setTimeout(()=>S.saved=false,1600)}try{const old=JSON.parse(localStorage.getItem('villa_pelon_save')||'null');if(old&&typeof old==='object')Object.assign(S,old)}catch(_){ }S.started=true;
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function inRect(x,y,r,pad=0){return x>=r.x-pad&&x<=r.x+r.w+pad&&y>=r.y-pad&&y<=r.y+r.h+pad}
function bridgeAt(x,y){return BR.find(b=>inRect(x,y,b,22))}
function riverBlocked(x,y){if(!inRect(x,y,RIVER,0))return false;return !bridgeAt(x,y)}
function blocked(x,y){if(x<45||y<105||x>W.w-45||y>W.h-45)return true;if(riverBlocked(x,y))return true;return B.some(b=>inRect(x,y,b,18))}
function inside(p,r=100){return Math.hypot(S.x-p.x,S.y-p.y)<r}function timeHour(){return(S.minutes/60)%24}function isNight(){const h=timeHour();return h<6.5||h>=21}function addItem(x){if(!S.inventory.includes(x))S.inventory.push(x)}
function dialogue(title,lines){S.dialogue=true;const d=document.getElementById('dialogue');if(!d)return;d.classList.remove('hidden');d.dataset.lines=JSON.stringify(lines);d.dataset.i='0';document.getElementById('speaker').textContent=title;document.getElementById('dialogueText').textContent=lines[0]}
function nextDialogue(){const d=document.getElementById('dialogue');if(!S.dialogue||!d)return;let a=[];try{a=JSON.parse(d.dataset.lines||'[]')}catch(_){}const i=Number(d.dataset.i||0)+1;if(i<a.length){d.dataset.i=i;document.getElementById('dialogueText').textContent=a[i]}else{S.dialogue=false;d.classList.add('hidden')}}document.getElementById('dialogueNext')?.addEventListener('click',nextDialogue);
function toast(t){const e=document.getElementById('missionToast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1900)}function mission(key){if(!V.missions?.completeStep)return;const r=V.missions.completeStep(S,key);if(r){if(r.reward)toast('MISIÓN COMPLETADA · +$'+r.reward);else toast('OBJETIVO COMPLETADO');window.dispatchEvent(new CustomEvent('villa-pelon-mission',{detail:{mission:V.missions.status(S)}}))}}
function interact(){if(S.dialogue){nextDialogue();return}S.stats.interactions++;let best=null,bd=Infinity;NPC.forEach(n=>{const d=dist(S,n);if(d<95&&d<bd){best=n;bd=d}});B.forEach(b=>{const p={x:b.x+b.w/2,y:b.y+b.h+35},d=dist(S,p);if(d<105&&d<bd){best=b;bd=d}});if(dist(S,points.clue)<100&&dist(S,points.clue)<bd){best={kind:'clue'};bd=dist(S,points.clue)}if(dist(S,points.job)<105&&dist(S,points.job)<bd){best={kind:'job'};bd=dist(S,points.job)}if(!best)return;if(best.kind==='clue'){if(!S.flags.clue){S.flags.clue=true;addItem('Pista histórica');S.money+=2500;mission('collect:historic_clue');dialogue('ARCHIVO DE MEMORIA',['Encontraste una pista para una futura investigación local.','Regla del mundo: ningún dato histórico se presenta como real sin una fuente verificable.','Recompensa: $2.500.'])}else dialogue('ARCHIVO',['Esta pista ya forma parte de tu cuaderno.']);return}if(best.kind==='job'){if(S.energy<20){dialogue('CHANGA RURAL',['Estás demasiado cansado. Descansá antes de trabajar.']);return}S.energy-=18;S.money+=850;S.stats.harvests++;addItem('Cajón de cosecha');dialogue('CHANGA RURAL',['Ayudaste con una tarea de carga y cosecha.','Cobraste $850. El trabajo rural requiere energía y tiempo.']);return}if(best.id){mission('talk:'+best.id);dialogue(best.n,best.lines);return}if(best.type==='home'){S.energy=Math.min(100,S.energy+30);S.minutes+=35;dialogue(best.label||'CASA',['Descansaste. Recuperaste energía.','El descanso consume tiempo, pero evita trabajar agotado.']);return}if(best.type==='shop'){shop(best);return}if(best.type==='radio'){dialogue(best.label,['La radio funciona como punto de encuentro comunitario.','Podés volver durante el día para encontrar nuevas conversaciones.']);return}if(best.type==='school'){dialogue(best.label,['Este lugar guarda memoria, aprendizaje y vínculos comunitarios.','Más adelante se podrán incorporar archivos y fotografías con fuentes.']);return}dialogue(best.label||best.type,['Este edificio forma parte del mundo de Villa Pelón.','Cada zona tendrá actividades propias a medida que el mundo crezca.'])}
function shop(b){const items=[['Pan',120],['Yerba',900],['Agua',100],['Herramienta',1800]],p=items[(S.stats.interactions+S.day)%items.length];if(S.money<p[1]){dialogue(b.label,['No te alcanza para '+p[0]+'.']);return}S.money-=p[1];addItem(p[0]);if(p[0]==='Pan')S.energy=Math.min(100,S.energy+12);dialogue(b.label,['Compraste '+p[0]+' por $'+p[1]+'.','Las compras quedan registradas en tu inventario.'])}
function scheduleNPC(n){const h=timeHour();if(isNight())return n.home;if(n.role==='comercio'&&h>=9&&h<20)return n.work;if(n.role==='escuela'&&h>=8&&h<16)return n.work;if(n.role==='docente'&&h>=8&&h<16)return n.work;if(n.role==='radio'&&h>=10&&h<18)return n.work;if(n.role==='rural'&&h>=7&&h<18)return n.work;if(n.role==='bodega'&&h>=8&&h<18)return n.work;if(n.role==='archivo'&&h>=9&&h<17)return n.work;if(n.role==='riego'&&h>=7&&h<18)return n.work;if(n.role==='trabajadora_rural'&&h>=7&&h<18)return n.work;if(n.role==='memoria'&&h>=9&&h<19)return n.work;return points.plaza}
function npcRoute(n,final){const ry=RIVER.y+RIVER.h/2,from=n.y<ry?'north':'south',to=final[1]<ry?'north':'south';if(from===to)return[final];let bridge=BR.reduce((best,b)=>{const cx=b.x+b.w/2;return!best||Math.abs(cx-(n.x+final[0])/2)<Math.abs((best.x+best.w/2)-(n.x+final[0])/2)?b:best},null);if(!bridge)return[final];const cx=bridge.x+bridge.w/2,nearY=RIVER.y-35,farY=RIVER.y+RIVER.h+35;return from==='north'&&to==='south'?[[cx,nearY],[cx,farY],final]:[[cx,farY],[cx,nearY],final]}
function updateNPC(dt){NPC.forEach(n=>{n.t=n.t||0;n.t-=dt;const final=scheduleNPC(n),fk=final[0]+':'+final[1];if(n.routeFinal!==fk){n.routeFinal=fk;n.route=npcRoute(n,final);n.routeIndex=0;n.t=0}if(n.t<=0)n.t=2+Math.random()*4;const route=n.route||[final];let target=route[Math.min(n.routeIndex||0,route.length-1)];const dx=target[0]-n.x,dy=target[1]-n.y,d=Math.hypot(dx,dy);if(d<=14){if((n.routeIndex||0)<route.length-1){n.routeIndex=(n.routeIndex||0)+1;target=route[n.routeIndex]}else{n.route=[final];n.routeIndex=0;target=final}}const tx=target[0]-n.x,ty=target[1]-n.y,td=Math.hypot(tx,ty)||1,v=n.role==='rural'||n.role==='bodega'||n.role==='riego'||n.role==='trabajadora_rural'?27:23,step=v*dt,nx=n.x+tx/td*Math.min(step,td),ny=n.y+ty/td*Math.min(step,td);if(!blocked(nx,n.y))n.x=nx;if(!blocked(n.x,ny))n.y=ny;n.walk=(n.walk||0)+dt*8;n.dir=Math.abs(tx)>Math.abs(ty)?(tx<0?'left':'right'):(ty<0?'up':'down');n.navigation={target:[target[0],target[1]],routeIndex:n.routeIndex||0,routeLength:route.length,crossing:route.length>1,bridgeAware:true}})}
function updateTime(dt,moving){S.minutes+=dt*(moving?3.2:.035);if(S.minutes>=1440){S.minutes-=1440;S.day++;S.energy=100;S.flags={};toast('NUEVO DÍA · ENERGÍA RESTAURADA')}if(moving){S.energy=Math.max(0,S.energy-dt*.58);S.stats.steps+=Math.ceil(dt*2)}if(S.energy<=0)S.speed=105;else if(S.energy<25)S.speed=160;else S.speed=205}function updateWeather(dt){weatherTimer+=dt;if(weatherTimer<28)return;weatherTimer=0;const h=timeHour(),pool=h<7?['nublado','viento','despejado']:['despejado','nublado','viento','lluvia'];weather=pool[(S.day+Math.floor(performance.now()/30000))%pool.length]}
function update(dt){if(!S.started||S.dialogue)return;let dx=(I.right?1:0)-(I.left?1:0),dy=(I.down?1:0)-(I.up?1:0),moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;const nx=S.x+dx*S.speed*dt,ny=S.y+dy*S.speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;S.facing=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');S.walk+=dt*9}else S.walk=0;updateTime(dt,moving);updateWeather(dt);updateNPC(dt);missionAuto();ui()}
function missionAuto(){if(inside(points.plaza,120))mission('reach:plaza');if(S.x>4900&&S.y<2600)mission('reach:rural');if(S.x>5400&&S.y<1100)mission('reach:winery');if(S.y>3300)mission('reach:picada21');if(inside(points.stop,100))mission('inspect:picada21_stop')}
function ui(){const h=Math.floor(timeHour()),m=Math.floor((timeHour()-h)*60),set=(id,t)=>{const e=document.getElementById(id);if(e)e.textContent=t};set('clock',String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'));set('day',S.day);set('money',Math.round(S.money));set('energy',Math.round(S.energy));set('weather',weather[0].toUpperCase()+weather.slice(1));if(V.missions?.status){const q=V.missions.status(S);set('questText',q.objective);set('questProgress',q.total?'Paso '+(q.step+1)+' de '+q.total+' · Recompensa $'+q.reward:'Exploración libre')}else set('questText','Explorá Villa Pelón.')}
function road(r){ctx.fillStyle=colors.road2;ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle=colors.road;ctx.fillRect(r.x,r.y+8,r.w,Math.max(4,r.h-16));ctx.fillStyle='rgba(230,211,166,.32)';if(r.w>=r.h)ctx.fillRect(r.x+8,r.y+r.h/2-1,r.w-16,2);else ctx.fillRect(r.x+r.w/2-1,r.y+8,2,r.h-16)}
function terrain(){ctx.fillStyle=colors.grass;ctx.fillRect(0,0,W.w,W.h);(G.zones||[]).forEach(z=>{ctx.fillStyle=z.kind==='urban'?'#9b916b':z.kind==='transition'?'#aaa37c':z.kind==='productive'?'#8d996a':z.kind==='river'?'#a69b72':'#929b6c';ctx.fillRect(z.x,z.y,z.w,z.h)});roads.forEach(road);ctx.fillStyle=colors.river;ctx.fillRect(RIVER.x,RIVER.y,RIVER.w,RIVER.h);ctx.fillStyle=colors.river2;ctx.fillRect(RIVER.x,RIVER.y+25,RIVER.w,4);for(let x=RIVER.x+15;x<RIVER.x+RIVER.w;x+=55){ctx.fillStyle='rgba(210,229,210,.35)';ctx.fillRect(x,RIVER.y+9,22,2)}BR.forEach(b=>{ctx.fillStyle='#76583f';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#a17b53';for(let x=b.x+10;x<b.x+b.w;x+=34)ctx.fillRect(x,b.y+8,22,b.h-16)});for(let i=0;i<90;i++){const x=(i*191+137)%4700,y=(i*137+170)%1900;if(y<420||y>2350)continue;ctx.fillStyle='#55754c';ctx.fillRect(x,y,7,5);ctx.fillRect(x+3,y-5,3,6)} }
function drawObjects(){const marks=[{x:2040,y:560,t:'ARCHIVO'},{x:5100,y:1080,t:'RIEGO'},{x:6200,y:1500,t:'PELÓN'},{x:1500,y:1080,t:'MEMORIA'}];marks.forEach(m=>{ctx.fillStyle='#3e5140';ctx.fillRect(m.x-42,m.y-13,84,26);ctx.fillStyle='#ead9a9';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText(m.t,m.x,m.y+4)})}
function humanoid(o,player=false){const x=Math.round(o.x),y=Math.round(o.y);ctx.fillStyle='rgba(25,25,20,.30)';ctx.beginPath();ctx.ellipse(x,y+29,15,4,0,0,7);ctx.fill();const phase=Math.sin((S.walk||0)*1.4+(o.seed||0))*3,skin=player?'#d8a27e':(o.skin||colors.skin),shirt=player?'#315b47':o.c||'#65764a',hair=o.hair||'#332923';ctx.fillStyle='#252a29';ctx.fillRect(x-8,y+8+phase,6,17);ctx.fillRect(x+2,y+8-phase,6,17);ctx.fillStyle='#202326';ctx.fillRect(x-9,y+24+phase,9,4);ctx.fillRect(x+1,y+24-phase,9,4);ctx.fillStyle=shirt;ctx.fillRect(x-12,y-9,24,19);ctx.fillStyle=skin;ctx.fillRect(x-9,y-27,18,18);ctx.fillStyle=hair;ctx.fillRect(x-10,y-30,20,6);ctx.fillStyle='#1e211e';ctx.fillRect(x-6,y-21,2,2);ctx.fillRect(x+4,y-21,2,2);ctx.fillStyle='#f4ead2';ctx.font='bold 9px monospace';ctx.textAlign='center';ctx.fillText(player?'TÚ':o.n,x,y-40)}
function drawNPC(n){humanoid(n)}function drawPlayer(){humanoid({x:S.x,y:S.y,c:'#315b47',seed:2},true)}
function nearby(){let best=null,bd=Infinity;NPC.forEach(n=>{const d=dist(S,n);if(d<100&&d<bd){best=n;bd=d}});B.forEach(b=>{const p={x:b.x+b.w/2,y:b.y+b.h+38},d=dist(S,p);if(d<110&&d<bd){best=b;bd=d}});return best}
function render(){ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(vw/2,vh/2);ctx.scale(Z,Z);ctx.translate(-S.x,-S.y);terrain();drawObjects();NPC.forEach(drawNPC);drawPlayer();near=nearby();if(near&&!S.dialogue){ctx.fillStyle='rgba(25,30,24,.92)';ctx.fillRect(S.x-85,S.y-68,170,27);ctx.fillStyle='#fff';ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.fillText('E · '+(near.n||near.label||'INTERACTUAR'),S.x,S.y-50)}ctx.restore();const h=timeHour();if(weather==='nublado'){ctx.fillStyle='rgba(90,100,110,.15)';ctx.fillRect(0,0,vw,vh)}if(weather==='lluvia'){ctx.strokeStyle='rgba(210,230,240,.5)';for(let i=0;i<100;i++){const x=(i*83+performance.now()*.18)%vw,y=(i*47+performance.now()*.28)%vh;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y+18);ctx.stroke()}}if(h<6.5||h>=21){ctx.fillStyle='rgba(10,18,35,.45)';ctx.fillRect(0,0,vw,vh)}else if(h>=18){ctx.fillStyle='rgba(190,125,70,.12)';ctx.fillRect(0,0,vw,vh)}}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}
function engineHealth(){return{version:'112.0',world:[W.w,W.h],buildings:B.length,npcs:NPC.length,save:true,missionSystem:!!V.missions,singleBuildingRenderer:true,pixelArtPlayer:true,npcNavigation:'bridge-aware',riverRule:'bridge_only',navigationTelemetry:NPC.filter(n=>n.navigation).map(n=>({id:n.id,bridgeAware:n.navigation.bridgeAware,crossing:n.navigation.crossing,routeIndex:n.navigation.routeIndex,routeLength:n.navigation.routeLength,target:n.navigation.target})),renderAuthority:'engine_terrain_compositor_facades'} }
V.engine={version:'112.0',state:'running',health:engineHealth,singleBuildingRenderer:true,npcNavigation:'bridge-aware',worldRules:'bridge-only',renderAuthority:'split-by-responsibility'};window.dispatchEvent(new CustomEvent('villa-pelon-engine-ready'));requestAnimationFrame(loop);
})();
