/* VILLA PELÓN V136 — VIDA DEL PUEBLO CONSOLIDADA */
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),S=V.gameState;if(!S)return;const L=V.villageLife=V.villageLife||{};L.version='136.0';L.active=true;L.singleTick=true;L.saveAuthority='gameState';L.events=L.events||{};L.history=Array.isArray(L.history)?L.history:[];L.encounters=L.encounters||{};S.lifeState=S.lifeState&&typeof S.lifeState==='object'?S.lifeState:{};L.placeState=S.lifeState.placeState&&typeof S.lifeState.placeState==='object'?S.lifeState.placeState:{};if(S.lifeState.events)L.events=S.lifeState.events;if(Array.isArray(S.lifeState.history))L.history=S.lifeState.history;if(S.lifeState.encounters)L.encounters=S.lifeState.encounters;
const day=()=>Number(S.day)||1,hour=()=>((Number(S.minutes)||0)/60)%24,key=id=>day()+':'+id,near=(x,y,r)=>Math.hypot((+S.x||0)-x,(+S.y||0)-y)<r;
function toast(t){const e=document.getElementById('missionToast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(L.toastTimer);L.toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}function dialogue(speaker,lines){const d=document.getElementById('dialogue');if(!d)return;S.dialogue=true;d.classList.remove('hidden');d.dataset.lines=JSON.stringify(lines);d.dataset.i='0';const sp=document.getElementById('speaker'),tx=document.getElementById('dialogueText');if(sp)sp.textContent=speaker;if(tx)tx.textContent=lines[0]||''}
function remember(id,label,extra={}){L.history.push({day:day(),id,label,time:Number(S.minutes)||0,...extra});if(L.history.length>200)L.history.shift()}function once(id){const k=key(id);if(L.events[k])return false;L.events[k]=true;return true}function worldEvent(id,label,lines,extra){if(!once(id))return false;remember(id,label,extra);toast('VIDA DEL PUEBLO · '+label);if(lines)setTimeout(()=>{if(!S.dialogue)dialogue(label,lines)},220);return true}function sync(){S.lifeState={version:L.version,events:L.events,history:L.history,encounters:L.encounters,placeState:L.placeState}}
function setPlace(id,label,active,extra={}){const p=L.placeState[id]||{id,label,visits:0,activityCount:0};p.label=label;p.active=!!active;p.hour=Math.floor(hour());p.day=day();Object.assign(p,extra);L.placeState[id]=p}
function placeActivity(){const h=hour(),w=V.atmosphere?.weather?.type||'despejado',rain=w==='lluvia',wind=w==='viento',heat=w==='calido';setPlace('plaza','Plaza',h>=7&&h<22,{density:h>=17&&h<21?'alta':h>=9?'media':'baja',weather:w});setPlace('school','Escuela',h>=8&&h<16,{students:h>=8&&h<13,weather:w});setPlace('radio','Radio',h>=10&&h<18,{broadcast:h>=10&&h<12,weather:w});setPlace('irrigation','Riego',h>=7&&h<18&&!rain,{waterFlow:h>=7&&h<17&&!rain,weather:w});setPlace('winery','Bodegas',h>=8&&h<18,{production:h>=9&&h<17,weather:w});setPlace('rural','Sector rural',h>=6&&h<20,{work:h>=7&&h<18&&!rain,weather:w});setPlace('picada21','Picada 21',h>=6&&h<22,{bus:h>=17&&h<19&&!rain,weather:w});L.environmentNote=rain?'lluvia reduce actividad exterior':wind?'viento modifica ritmo exterior':heat&&h>=12&&h<16?'calor reduce ritmo de trabajo al mediodia':'actividad normal'}
function routeFor(v,i){const roads=V.worldGeometry?.roads||[],ids=['urban_north','urban_mid','urban_south','rural_north','rural_middle','rural_south'],r=roads.find(x=>x.id===v.routeId)||roads.find(x=>x.id===ids[i%ids.length]);return r?{...r,minX:r.x,maxX:r.x+r.w,laneY:r.y+r.h/2}:null}
function moveAmbient(dt){const P=V.peopleVehicles;if(!P)return;const w=V.atmosphere?.weather?.type||'despejado',f=w==='lluvia'?.55:w==='viento'?.78:w==='calido'&&hour()>=12&&hour()<16?.7:1;(P.vehicleData||[]).forEach((v,i)=>{const r=routeFor(v,i);if(!r)return;v.route=r;v.x+=(+v.speed||40)*dt*(v.dir||1)*f;if(v.x>r.maxX)v.x=r.minX;if(v.x<r.minX)v.x=r.maxX;v.y=r.laneY});(P.animals||[]).forEach(a=>{const b=a.bounds||{minX:3150,maxX:7750,minY:450,maxY:2200};const af=w==='lluvia'?.45:w==='viento'?.7:1;a.x+=(+a.vx||0)*dt*af;a.y+=(+a.vy||0)*dt*af;if(a.x<b.minX||a.x>b.maxX){a.vx=-a.vx;a.x=Math.max(b.minX,Math.min(b.maxX,a.x))}if(a.y<b.minY||a.y>b.maxY){a.vy=-a.vy;a.y=Math.max(b.minY,Math.min(b.maxY,a.y))}})}
function targetAction(n,h){const w=V.atmosphere?.weather?.type||'despejado',rain=w==='lluvia',heat=w==='calido'&&h>=12&&h<16;if(h<6.5||h>=21)return'descansando';if(n.role==='comercio'&&h>=9&&h<20)return'atendiendo el comercio';if((n.role==='escuela'||n.role==='docente')&&h>=8&&h<16)return'en la escuela';if(n.role==='radio'&&h>=10&&h<18)return'haciendo radio';if(['rural','bodega','riego','trabajadora_rural'].includes(n.role)&&h>=7&&h<18)return rain?'trabajo exterior reducido por lluvia':heat?'trabajo lento por calor':'trabajando en el sector rural';if(n.role==='archivo'&&h>=9&&h<17)return'consultando archivos';if(n.role==='memoria'&&h>=9&&h<19)return'reuniendo recuerdos';return'en la plaza'}
function updateActions(){const ns=Array.isArray(V.npcs)?V.npcs:[],h=hour(),w=V.atmosphere?.weather?.type||'despejado';ns.forEach(n=>{n.lifeAction=targetAction(n,h);n.lifeHour=Math.floor(h);n.lifeWeather=w;n.lifeActive=n.lifeAction!=='descansando'})}
function encounterPair(){const ns=Array.isArray(V.npcs)?V.npcs:[];for(let i=0;i<ns.length;i++)for(let j=i+1;j<ns.length;j++){const a=ns[i],b=ns[j];if(!a||!b||Math.hypot(a.x-b.x,a.y-b.y)>125||Math.hypot(S.x-(a.x+b.x)/2,S.y-(a.y+b.y)/2)>180)continue;const id=[a.id,b.id].sort().join('_'),stamp=key('encounter:'+id);if(L.encounters[stamp])continue;L.encounters[stamp]=true;remember('encounter:'+id,a.n+' y '+b.n+' se cruzan',{people:[a.id,b.id]});toast('ENCUENTRO · '+a.n+' + '+b.n);dialogue(a.n+' y '+b.n,[a.n+': '+b.n+', ¿cómo viene el día?',b.n+': Bien. Estoy '+(b.lifeAction||'siguiendo mi rutina')+'.',a.n+': Yo estoy '+(a.lifeAction||'siguiendo mi rutina')+'.','Escuchaste una conversación cotidiana.']);return}}
function contextualEvents(){const h=hour(),p=V.missionRuntime?.points||{},pl=p.plaza||{x:1160,y:390},sc=p.school_archive||{x:530,y:560},ra=p.name_marker||{x:1300,y:1230},ru=p.irrigation_marker||{x:3500,y:760},wi=p.winery||{x:5850,y:560},pi=p.picada21||{x:7550,y:2350};if(h>=7.5&&h<8.5&&near(pl.x,pl.y,220))worldEvent('morning_plaza','La plaza despierta',['PLAZA','Empieza otro día.']);if(h>=9&&h<11&&near(sc.x,sc.y,170))worldEvent('school_start','Entrada a la escuela',['ESCUELA','La mañana escolar modifica el ritmo de esta zona.']);if(h>=10&&h<12&&near(ra.x,ra.y,190))worldEvent('radio_broadcast','Radio del pueblo',['RADIO','Las voces, el clima, los caminos y el trabajo también forman parte de la vida cotidiana.']);if(h>=12&&h<15&&near(ru.x,ru.y,260))worldEvent('irrigation_midday','Movimiento de riego',['RIEGO','El agua organiza buena parte del territorio productivo.']);if(h>=15&&h<18&&near(wi.x,wi.y,260))worldEvent('winery_afternoon','Actividad productiva',['BODEGAS','La producción genera trabajos, recorridos y conversaciones.']);if(h>=17&&h<19&&near(pi.x,pi.y,260))worldEvent('picada_bus','Llega el colectivo a Picada 21',['PARADA RURAL','El camino conecta pequeñas historias con el núcleo del pueblo.']);if(h>=20&&h<21&&near(pl.x,pl.y,260))worldEvent('evening_plaza','La plaza cambia de ritmo',['PLAZA','Al caer el sol el pueblo cambia, no desaparece.'])}
function tick(){const now=performance.now(),dt=Math.min(.1,Math.max(0,(now-(L.last||now))/1000));L.last=now;if(!S.started)return;try{moveAmbient(dt);updateActions();placeActivity();contextualEvents();if(!S.dialogue)encounterPair();sync();if(V.atmosphere?.apply)V.atmosphere.apply()}catch(e){console.error('[VillaPelon][life-136]',e)}}L.tick=tick;setInterval(tick,100);tick();V.engine=V.engine||{};V.engine.health=V.engine.health||function(){return{ok:true}};V.engine.health.villageLife='136.0';
})();