/* Villa Pelón CORE WORLD LIFE EXPANSION v1.0
   Amplía recorridos, puntos de interés, clima y conversaciones sin crear otra autoridad de movimiento.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const state=()=>V.gameState||{};
const conversations={
Marta:['Buen día, ¿cómo andás?','Acá siempre aparece alguien que viene a buscar pan, yerba o simplemente a conversar.','¿Viste cómo cambió el pueblo? Antes uno conocía prácticamente a todo el mundo.','Cuando hace frío, el almacén se llena temprano. Nadie quiere quedarse afuera mucho rato.','Si vas para las chacras, llevá agua. El sol engaña bastante por acá.','A la tarde suele venir gente a comprar algo para el mate.','Las noticias vuelan en los pueblos. A veces llegan antes por una charla que por la radio.','Bueno, seguí tranquilo. El pueblo se conoce caminándolo.'],
Raúl:['¿Qué hacés por acá?','Yo arranco temprano. En la chacra el día empieza antes que en el pueblo.','Hay días de poda, días de riego y días de cargar cajones hasta quedar con la espalda dura.','Cuando corre viento fuerte hay que asegurar todo. El campo no perdona descuidos.','El agua es parte de la vida de acá. Sin riego, esta tierra sería otra cosa.','En época de cosecha cambia el ritmo: camionetas, cajones, gente entrando y saliendo.','Si querés conocer el pueblo de verdad, caminá por los caminos rurales.','Nos vemos. Si escuchás un tractor, probablemente haya alguien trabajando.'],
Lucía:['Hola. ¿Ya conociste la escuela?','Acá siempre hay una foto vieja, una historia de una familia o alguien que recuerda cómo era antes.','Los chicos escuchan historias de sus abuelos y después las cuentan de otra manera.','A veces una fecha en un papel sirve para empezar una investigación enorme.','No todo lo que se cuenta es necesariamente cierto. Hay que buscar documentos y comparar.','Cuando llueve, el patio cambia completamente y todos buscan dónde resguardarse.','El pueblo también se aprende escuchando a la gente.','Después pasá por la plaza. Siempre hay alguien.'],
Pedro:['¿Todo tranquilo?','Estoy llevando unas cosas para el galpón.','En el campo nunca falta algo: una herramienta, una bomba, un alambrado, una rueda.','Hay días tranquilos y otros en que no parás ni para tomar mate.','Cuando baja el sol se siente enseguida el cambio de temperatura.','Los caminos de tierra tienen su propio ritmo. Después de una lluvia aparecen charcos por todos lados.','A mí me gusta esta vida. Es cansadora, pero uno sabe para qué trabaja.','Bueno, sigo. Todavía queda bastante por hacer.'],
Nico:['Pasá, la radio está prendida.','En un pueblo la radio no es solamente música. También sirve para avisar, acompañar y juntar voces.','Hay gente que escucha mientras trabaja en la chacra, maneja o prepara el mate.','Cuando se corta la luz, lo primero que pregunta la gente es si la radio sigue al aire.','Las historias locales aparecen en cualquier charla. Después hay que investigarlas.','A veces un vecino llama por una cosa y termina contando otra historia.','Si encontrás una fotografía vieja, guardala. Puede tener información que hoy nadie recuerda.','Nos cruzamos después. El pueblo siempre termina juntando a la misma gente.'],
Rosa:['¿Ya pasaste por la plaza?','A esta hora todavía está tranquila. Más tarde aparecen chicos, vecinos y gente que sale a caminar.','Acá uno se cruza con conocidos aunque salga solamente a comprar pan.','Cuando hace calor, la sombra de los árboles vale oro.','Después de la lluvia el aire queda distinto y se siente el olor de la tierra.','Hay días en que parece que no pasa nada. Y sin embargo siempre pasa algo.','Eso es lo lindo de los pueblos: hay que aprender a mirar despacio.','Bueno, te dejo seguir caminando.'],
Tomás:['Estoy haciendo una recorrida por los servicios.','Cuando algo falla en un pueblo, se nota rápido porque todos dependen de lo mismo.','Agua, caminos, electricidad, comunicaciones: parecen cosas invisibles hasta que faltan.','El clima también obliga a estar atentos. Una tormenta puede cambiar una jornada entera.','Los caminos rurales necesitan mantenimiento constante.','La vida urbana y la rural están mucho más conectadas de lo que parece.','Por eso el territorio importa tanto.','Nos vemos más adelante.'],
Elena:['¿Venís de las chacras?','Por acá pasan trabajadores, productores, vecinos y gente que solamente está dando una vuelta.','La bodega tiene otro ritmo. Hay momentos de mucha actividad y otros mucho más tranquilos.','La vid necesita trabajo durante todo el año, no solamente cuando se cosecha.','Cuando cae la tarde, los viñedos quedan muy lindos con la luz baja.','Hay visitantes que vienen por el vino y terminan descubriendo toda la historia productiva del lugar.','Pero una cosa es el paisaje y otra la historia: para contarla bien hay que documentarla.','Que tengas buen camino.']};
function enrichNPCs(){(V.npcs||[]).forEach(n=>{if(conversations[n.name])n.lines=conversations[n.name]});if(V.life?.ambient){const extras=[{name:'Don Julio',x:460,y:760,color:'#78604d',speed:16,role:'plaza',home:[430,820],work:[620,620]},{name:'Norma',x:1180,y:820,color:'#9b6671',speed:17,role:'comercio',home:[1120,1060],work:[790,430]},{name:'Sergio',x:1960,y:650,color:'#63704f',speed:18,role:'chacra',home:[1850,1000],work:[2040,1180]},{name:'Mabel',x:2520,y:1050,color:'#856a55',speed:15,role:'rural',home:[2400,1250],work:[2470,1170]}];extras.forEach(p=>V.life.ambient.push({...p,target:[p.x,p.y],destination:'plaza',wait:2+Math.random()*4,active:true,moving:false,direction:'down',walk:Math.random()*4,sheltered:false})}}
const sites=V.worldAuthority?.geometry?.sites||[];
function nearestSite(){const s=state();let best=null,dmin=115;sites.forEach(p=>{const d=Math.hypot(s.x-p.x,s.y-p.y);if(d<dmin){best=p;dmin=d}});return best}
function siteDialogue(p){const texts={
'plaza':['PLAZA DEL PUEBLO','Acá se cruzan muchas de las historias cotidianas de Villa Pelón.'],
'chacras':['LAS CHACRAS','Hileras de frutales, canales, caminos y trabajo. Esta zona explica buena parte de la vida productiva del valle.'],
'vinedos':['LOS VIÑEDOS','El paisaje cambia: aparecen las hileras de vid y los caminos de producción.'],
'canal':['CANAL DE RIEGO','El agua no está acá por casualidad. Los sistemas de riego transformaron tierras áridas en superficies productivas.'],
'canal-viejo':['CANAL VIEJO','Un lugar para investigar cómo el riego fue modificando el territorio y la vida cotidiana.'],
'ribera':['RIBERA DEL RÍO','Llegaste al río. El agua es una presencia fundamental del territorio. Podés recorrer la ribera sin entrar al cauce.'],
'fossils':['SITIO DE FÓSILES','Este punto representa una zona de investigación paleontológica. Un hallazgo real debe estar respaldado por documentación científica.'],
'mirador':['MIRADOR DE LA MESETA','Desde acá se entiende mejor el contraste entre el ambiente seco, el área irrigada y el río.'],
};const t=texts[p.id];if(t)V.openDialogue(t[0],[t[1],'Seguí recorriendo: todavía quedan lugares por descubrir.'])}
function bindSites(){document.addEventListener('pointerdown',e=>{if(!e.target.closest('#interact'))return;const p=nearestSite();if(p){setTimeout(()=>siteDialogue(p),0)}});document.addEventListener('keydown',e=>{if(!['e',' '].includes(e.key.toLowerCase()))return;const p=nearestSite();if(p)setTimeout(()=>siteDialogue(p),0)})}
function climate(){const l=V.life;if(!l)return;l.climate={temperature:l.temperature,weather:l.weather,season:l.season,isNight:l.isNight,description:l.weather==='lluvia'?'lluvia sobre caminos y techos':l.weather==='viento'?'viento seco y ráfagas':l.weather==='nublado'?'cielo cubierto y luz suave':'cielo despejado y amplitud térmica'};if(!l.nextWeather._expanded){const old=l.nextWeather;l.nextWeather=()=>{const w=old();l.climate.weather=w;l.climate.temperature=l.temperature;l.climate.description=l.climate.description;return w};l.nextWeather._expanded=true}}
function boot(){enrichNPCs();climate();bindSites();V.worldLifeExpansion={version:'1.0.0',accessibleTerritory:true,expandedDialogues:true,climate:true,sites:true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();