/* VILLA PELÓN — WORLD DETAIL V89.1
   Capa visual independiente: textura, profundidad, infraestructura, vehículos y humanoides.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
function install(){
 const canvas=document.getElementById('worldDetail');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
 function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0)}
 addEventListener('resize',resize);resize();
 const P={grass:'#879064',grass2:'#7d855b',dirt:'#9a8157',road:'#8c7655',roadEdge:'#69583f',fence:'#67533a',wood:'#73573e',metal:'#6c7370',skin:'#d7a17d',shirt:'#416a54',shadow:'#302c27'};
 const project=(x,y)=>{const S=V.gameState||{x:1180,y:650};const scale=Math.min(innerWidth/900,innerHeight/620)*.92;return [innerWidth/2+(x-S.x)*scale,innerHeight/2+(y-S.y)*scale,scale]};
 const path=(pts,color,width)=>{ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();pts.forEach((p,i)=>{const q=project(p.x,p.y);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.stroke();ctx.restore()};
 function ruralRoad(){const r=V.worldGeometry?.routes?.find(x=>x.id==='picada21_route');if(!r)return;path(r.points,P.roadEdge,42);path(r.points,P.road,32);path(r.points,P.dirt,25);for(let i=0;i<r.points.length-1;i++){const a=r.points[i],b=r.points[i+1];for(let j=1;j<3;j++){const t=j/3,q=project(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);ctx.fillStyle=P.grass2;ctx.fillRect(q[0]-2,q[1]-1,4,2)}}}
 function crops(){(V.worldGeometry?.crops||[]).forEach(c=>{const q=project(c.x,c.y),w=c.w*q[2],h=c.h*q[2];ctx.fillStyle='#68734d';ctx.fillRect(q[0],q[1],w,h);ctx.fillStyle='#a0a66b';for(let y=q[1]+8*q[2];y<q[1]+h;y+=12*q[2])for(let x=q[0]+5*q[2];x<q[0]+w;x+=18*q[2]){ctx.fillRect(x,y,2*q[2],5*q[2]);ctx.fillRect(x+3*q[2],y+2*q[2],2*q[2],4*q[2])}})}
 function fences(){(V.worldGeometry?.fences||[]).forEach(f=>{const q=project(f.x,f.y),w=f.w*q[2],h=Math.max(5,f.h*q[2]);ctx.strokeStyle=P.fence;ctx.lineWidth=Math.max(2,3*q[2]);ctx.beginPath();ctx.moveTo(q[0],q[1]);ctx.lineTo(q[0]+w,q[1]+h);ctx.stroke();for(let x=q[0];x<=q[0]+w;x+=30*q[2])ctx.fillRect(x,q[1]-10*q[2],3*q[2],20*q[2])})}
 function poles(){(V.worldGeometry?.utilityPoles||[]).forEach(p=>{const q=project(p.x,p.y),s=q[2];ctx.fillStyle=P.wood;ctx.fillRect(q[0]-2*s,q[1]-34*s,4*s,34*s);ctx.fillStyle=P.metal;ctx.fillRect(q[0]-13*s,q[1]-34*s,26*s,3*s)})}
 function sign(){const p=V.worldGeometry?.points?.find(x=>x.id==='picada21_sign');if(!p)return;const q=project(p.x,p.y),s=q[2];ctx.fillStyle=P.wood;ctx.fillRect(q[0]-2*s,q[1]-30*s,4*s,30*s);ctx.fillStyle='#d5b86d';ctx.fillRect(q[0]-34*s,q[1]-43*s,68*s,17*s);ctx.fillStyle='#24382a';ctx.font=`bold ${Math.max(7,10*s)}px monospace`;ctx.textAlign='center';ctx.fillText('PICA. 21 →',q[0],q[1]-31*s)}
 function stop(){const p=V.worldGeometry?.points?.find(x=>x.id==='picada21_stop');if(!p)return;const q=project(p.x,p.y),s=q[2];ctx.fillStyle='rgba(30,25,20,.25)';ctx.fillRect(q[0]-19*s,q[1]+2*s,38*s,5*s);ctx.fillStyle='#e8dfc9';ctx.fillRect(q[0]-3*s,q[1]-38*s,6*s,38*s);ctx.fillStyle='#506d77';ctx.fillRect(q[0]-20*s,q[1]-46*s,40*s,10*s);ctx.fillStyle='#d7b86e';ctx.fillRect(q[0]-16*s,q[1]-42*s,32*s,2*s);ctx.fillStyle='#f4ead2';ctx.font=`bold ${Math.max(7,9*s)}px monospace`;ctx.textAlign='center';ctx.fillText('PARADA',q[0],q[1]-53*s)}
 function vehicle(v,t){let x=v.x,y=v.y;if(v.route&&v.speed){const r=V.worldGeometry?.routes?.find(z=>z.id===v.route);if(r){const progress=(t/1000*v.speed/100)%Math.max(1,r.points.length-1),idx=Math.floor(progress),f=progress-idx,a=r.points[idx],b=r.points[Math.min(idx+1,r.points.length-1)];x=a.x+(b.x-a.x)*f;y=a.y+(b.y-a.y)*f}}const q=project(x,y),s=q[2];ctx.save();ctx.translate(q[0],q[1]);ctx.fillStyle=P.shadow;ctx.beginPath();ctx.ellipse(0,9*s,24*s,7*s,0,0,7);ctx.fill();if(v.type==='tractor'){ctx.fillStyle='#8b713e';ctx.fillRect(-22*s,-12*s,44*s,22*s);ctx.fillStyle='#303b36';ctx.fillRect(-12*s,-20*s,24*s,10*s);ctx.fillStyle='#222';ctx.beginPath();ctx.arc(-15*s,13*s,7*s,0,7);ctx.arc(15*s,13*s,7*s,0,7);ctx.fill()}else if(v.type==='bus'){ctx.fillStyle='#d0b873';ctx.fillRect(-28*s,-15*s,56*s,26*s);ctx.fillStyle='#435c67';ctx.fillRect(-21*s,-10*s,15*s,9*s);ctx.fillRect(5*s,-10*s,15*s,9*s);ctx.fillStyle='#292d2b';ctx.fillRect(-21*s,8*s,9*s,7*s);ctx.fillRect(12*s,8*s,9*s,7*s)}else{ctx.fillStyle='#566e59';ctx.fillRect(-24*s,-12*s,48*s,21*s);ctx.fillStyle='#7b8d7e';ctx.fillRect(-8*s,-19*s,22*s,9*s);ctx.fillStyle='#252725';ctx.fillRect(-18*s,8*s,10*s,7*s);ctx.fillRect(10*s,8*s,10*s,7*s)}ctx.restore()}
 function humanoid(n,t,player=false){const q=project(n.x,n.y),s=q[2],moving=player?true:true,phase=moving?Math.sin(t/95+(n.seed||0)):Math.sin(t/500+(n.seed||0))*.2,leg=phase*5*s;ctx.save();ctx.translate(q[0],q[1]);ctx.fillStyle=P.shadow;ctx.beginPath();ctx.ellipse(0,16*s,11*s,4*s,0,0,7);ctx.fill();ctx.strokeStyle='#3b3430';ctx.lineWidth=Math.max(2,4*s);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-4*s,7*s);ctx.lineTo(-7*s+leg,20*s);ctx.moveTo(4*s,7*s);ctx.lineTo(7*s-leg,20*s);ctx.stroke();ctx.strokeStyle=n.skin||P.skin;ctx.lineWidth=Math.max(2,3*s);ctx.beginPath();ctx.moveTo(-10*s,-2*s);ctx.lineTo(-16*s+leg*.35,8*s);ctx.moveTo(10*s,-2*s);ctx.lineTo(16*s-leg*.35,8*s);ctx.stroke();ctx.fillStyle=n.shirt||P.shirt;ctx.fillRect(-10*s,-12*s,20*s,20*s);ctx.fillStyle=n.skin||P.skin;ctx.beginPath();ctx.arc(0,-21*s,9*s,0,7);ctx.fill();ctx.fillStyle=n.hair||'#3b2d28';ctx.fillRect(-9*s,-29*s,18*s,7*s);ctx.fillStyle='#f4ead2';ctx.font=`bold ${Math.max(7,9*s)}px monospace`;ctx.textAlign='center';ctx.fillText(player?'TÚ':(n.n||''),0,-36*s);ctx.restore()}
 function loop(t){ctx.clearRect(0,0,innerWidth,innerHeight);ruralRoad();crops();fences();poles();sign();stop();(V.worldGeometry?.vehicles||[]).forEach(v=>vehicle(v,t));(V.npcs||[]).forEach((n,i)=>humanoid({...n,seed:i},t));const s=V.gameState;if(s)humanoid({x:s.x,y:s.y,shirt:'#315b47'},t,true);requestAnimationFrame(loop)}
 requestAnimationFrame(loop);V.worldDetail={version:'89.1',layer:'visual',style:'pixel-art'};
}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',install);else install();
})();