/* VILLA PELÓN V129 — LEYES CONSOLIDADAS DEL MUNDO
   Capa normativa: no crea geografía y no mueve objetos canónicos.
   Su función es que todo contenido nuevo tenga una única gramática de mundo.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={});
const L=V.worldLaws=V.worldLaws||{};
L.version='V129';
L.principle='Todo elemento nuevo se adapta al mundo existente; nunca al revés.';
L.geometry={authority:'worldGeometry',immutable:true,world:{x:0,y:0,w:8200,h:4200},zones:['urban_core','transition_rural','river_buffer','picada21'],riverCrossing:'bridge-only',roadsProtected:true,buildingRoadConflict:'reject',buildingRiverConflict:'reject'};
L.hierarchy=['MAPA','ZONA','SUBZONA','ESTRUCTURA','ELEMENTO','ACTOR','ACTIVIDAD','ACCION','MISION'];
L.scale={units:'world-pixels',referencePerson:{w:18,h:42},ranges:{person:[14,24,34,48],animal:[20,80],element:[8,180],vehicle:[45,110],house:[90,300],institution:[160,520]},law:'visual scale must remain coherent with function and zone'};
L.appearance={families:{urban:{ground:'town',materials:['stucco','brick','metal','wood'],density:'compact'},residential:{materials:['stucco','wood','brick','tile'],density:'low'},institutional:{materials:['stucco','stone','painted_metal'],density:'medium'},commercial:{materials:['stucco','glass','metal','wood'],density:'medium'},rural:{ground:'dry-earth',materials:['wood','wire','corrugated_metal','stone'],density:'open'},productive:{ground:'earth',materials:['wood','metal','concrete','wooden_posts'],density:'open'},historical:{materials:['weathered_wood','stone','aged_metal'],condition:'aged-but-readable'},natural:{materials:['soil','vegetation','water','rock'],density:'organic'},infrastructure:{materials:['painted_metal','wood','concrete','signage'],density:'functional'}},palette:{earth:'#9b7b59',sand:'#c8aa78',wood:'#76523a',roof:'#4c433d',metal:'#59615e',vegetation:'#66734b',water:'#5f8290',stone:'#777064',sign:'#c6a96f',light:'#d8c37c',shadow:'rgba(25,24,20,.28)'},textureLaw:'textures communicate material and use; no random decorative noise'};
L.actions={allowed:['observe','read','talk','rest','enter','work','trade','research','mission','use','feed','care','wait'],requirements:{observe:'visible object',read:'readable sign/document',talk:'actor nearby',rest:'rest point',enter:'enterable structure or vehicle',work:'declared workplace + schedule + role',trade:'commercial actor/place + open schedule',research:'archive/source/field reference',mission:'active mission condition',use:'usable object + declared use',feed:'animal + feeding permission',care:'animal/crop + care action',wait:'time passes'},forbidden:'an action may not invent geography'};
L.labor={principles:['trabajo has place, role, tool, schedule and purpose','workers do not work at arbitrary times','closed workplace blocks work/trade actions','weather may slow or alter work but never move geography','fatigue and time are state, not decoration'],shifts:{morning:[6,12],midday:[12,16],afternoon:[16,20],night:[20,24]},roles:{comercio:{work:[9,20],places:['urban_core'],tasks:['atender','ordenar','vender']},escuela:{work:[8,16],places:['urban_core'],tasks:['enseñar','aprender','recreo']},radio:{work:[10,18],places:['urban_core'],tasks:['emitir','preparar','entrevistar']},riego:{work:[7,18],places:['transition_rural'],tasks:['abrir_agua','revisar_canales','recorrer']},rural:{work:[6,20],places:['transition_rural'],tasks:['cuidar','reparar','cosechar','transportar']},bodega:{work:[8,18],places:['transition_rural'],tasks:['elaborar','ordenar','cargar','limpiar']},archivo:{work:[9,17],places:['urban_core'],tasks:['consultar','clasificar','registrar']}},law:'role + schedule + place must agree before an activity is active'};
L.activities={daily:['levantarse','desplazarse','abrir_lugar','trabajar','estudiar','comer','hacer_compras','regar','cuidar_animales','circular','descansar','cerrar_lugar'],weekly:['dia_laboral','fin_de_semana'],seasonal:['siembra','crecimiento','cosecha','mantenimiento'],social:['encuentro','charla','radio','plaza','evento_comunitario'],rural:['riego','trabajo_de_bodega','cuidado_de_animales','reparaciones','recorridos'],environmental:['sombra','viento','lluvia','frio','calor','niebla'],law:'activities change state and animation; they do not rewrite geography'};
L.weatherEffects={despejado:{visibility:1,work:'normal'},seco:{visibility:.95,work:'normal'},calido:{visibility:.95,work:'slower_midday'},frio:{visibility:.9,work:'slower_morning'},nublado:{visibility:.9,work:'normal'},lluvia:{visibility:.72,work:'reduced',outdoor:'reduced'},viento:{visibility:.88,work:'reduced',looseObjects:'move'}};
L.structureSchema=['id','zone','subzone','type','family','x','y','w','h','orientation','appearance','collision','access','action','use','schedule','workRole','state'];
L.validation=['world bounds','canonical zone','subzone','road conflict','river conflict','building conflict','content overlap','scale','visual family','declared action','declared use','schedule','labor role'];
L.integrity={invalidPlacement:'reject',autoMove:false,autoResize:false,geometryWrite:false,duplicateAuthority:false};
V.worldLawLock={version:'V129',locked:true,readOnly:true,principle:'laws are stable; states evolve'};
window.dispatchEvent(new CustomEvent('villa-pelon-world-laws-ready',{detail:{version:'V129',locked:true}}));
})();
