/* VILLA PELÓN V127.1 — LEYES DE MUNDO VIVO
   Simulación ambiental única: reloj, calendario, estaciones, clima y luz.
   No crea ni modifica geometría ni abre otro ciclo de simulación.
*/
(()=>{'use strict';
const V=window.VillaPelon||(window.VillaPelon={}),S=V.gameState;if(!S)return;
const A=V.atmosphere=V.atmosphere||{};A.version='127.1';
A.rules={immutableGeography:true,timeAuthority:'gameState.minutes',calendarAuthority:'atmosphere.calendar',weatherAuthority:'atmosphere.weather',dayNightAuthority:'atmosphere.phase',climateModel:'deterministic-seasonal',worldClockScale:3.2,hoursPerDay:24,daysPerYear:365,seasons:[{id:'verano',from:355,to:59,label:'VERANO'},{id:'otoño',from:60,to:151,label:'OTOÑO'},{id:'invierno',from:152,to:243,label:'INVIERNO'},{id:'primavera',from:244,to:354,label:'PRIMAVERA'}]};
const pad=n=>String(n).padStart(2,'0');
function normalizeDay(){while(Number(S.minutes)>=1440){S.minutes-=1440;S.day=(Number(S.day)||1)+1}while(Number(S.minutes)<0){S.minutes+=1440;S.day=Math.max(1,(Number(S.day)||1)-1)}}
function calendar(){const minute=((Number(S.minutes)||480)%1440+1440)%1440,day=Math.max(1,Number(S.day)||1),year=Math.floor((day-1)/365)+1,doy=((day-1)%365)+1,season=A.rules.seasons.find(x=>x.from<=x.to?(doy>=x.from&&doy<=x.to):(doy>=x.from||doy<=x.to))||A.rules.seasons[0],h=minute/60;let phase='night';if(h>=6&&h<8)phase='dawn';else if(h>=8&&h<18)phase='day';else if(h>=18&&h<20)phase='dusk';return{year,dayOfYear:doy,day,clock:`${pad(Math.floor(minute/60))}:${pad(Math.floor(minute%60))}`,hour:h,season:season.id,seasonLabel:season.label,phase}}
function weatherFor(c){const seed=(c.dayOfYear*37+Math.floor(c.hour/6)*11+c.year*7)%100,p=c.season==='verano'?['despejado','seco','calido','nublado']:c.season==='invierno'?['despejado','frio','nublado','lluvia']:c.season==='otoño'?['nublado','despejado','lluvia','viento']:['despejado','viento','nublado','lluvia'];return{type:p[seed%p.length],seed,season:c.season}}
function apply(){normalizeDay();const c=calendar(),w=weatherFor(c);A.calendar=c;A.weather=w;A.phase=c.phase;S.calendar={...c};S.weatherState={...w};const intensity=c.phase==='night'?.16:c.phase==='dawn'?.42:c.phase==='day'?1:.48;A.light={intensity,sky:c.phase,visibility:c.phase==='night'?.78:1};document.documentElement.style.setProperty('--vp-light',String(intensity));document.documentElement.style.setProperty('--vp-weather',w.type);const overlay=document.getElementById('worldAtmosphere');if(overlay){overlay.dataset.phase=c.phase;overlay.dataset.weather=w.type;overlay.dataset.season=c.season}const clock=document.getElementById('clock');if(clock)clock.textContent=c.clock;const weather=document.getElementById('weather');if(weather)weather.textContent=w.type.charAt(0).toUpperCase()+w.type.slice(1);const day=document.getElementById('day');if(day)day.textContent=c.day;const year=document.getElementById('year');if(year)year.textContent=c.year;window.dispatchEvent(new CustomEvent('villa-pelon-atmosphere',{detail:{calendar:c,weather:w,light:A.light}}))}
const oldTick=V.villageLife?.tick;if(typeof oldTick==='function')V.villageLife.tick=function(){oldTick();apply()};
apply();
V.worldLaws={version:'127.1',rules:['El reloj es continuo: las acciones consumen tiempo.','El día termina a las 24:00 y comienza el siguiente.','El calendario avanza 365 días por año y cambia de estación.','La luz cambia según amanecer, día, atardecer y noche.','El clima pertenece al estado del mundo y afecta la atmósfera, no la geografía.','La geografía canónica no cambia por clima, estación, horario ni evento.','Los sistemas de vida consumen este estado; no crean relojes paralelos.'],lockedBase:true};
})();